(function(){
'use strict';var rJ,uJ,wJ,zJ,AJ,xJ,pJ,tJ,sJ,yJ,vJ,CJ,qJ;$APP.oJ=function(){return new $APP.O(null,1,5,$APP.P,[new $APP.l(null,2,[$APP.jq,function(){$APP.fr(new $APP.O(null,1,5,$APP.P,[$APP.my],null));return $APP.fr(new $APP.O(null,1,5,$APP.P,[$APP.qz],null))},$APP.tA,$APP.ki],null)],null)};
rJ=function(){function a(b){return $APP.fr(new $APP.O(null,2,5,$APP.P,[pJ,$APP.$l.o(b)],null))}return function(){var b=$APP.Uf($APP.$r(new $APP.O(null,1,5,$APP.P,[qJ],null)));b=$APP.G(b,0,null);return new $APP.O(null,5,5,$APP.P,[$APP.gC,$APP.bG.Root,new $APP.l(null,4,[$APP.U,"Token Type",$APP.nz,"Staked",$APP.Jy,b,$APP.rB,a],null),new $APP.O(null,5,5,$APP.P,[$APP.gC,$APP.bG.Trigger,new $APP.l(null,2,[$APP.Cp,"cs1 ce2 rs1 re2 justify-self-start text-xl text-center pl-14 pr-10 py-0.5 rounded relative fb",
$APP.mu,new $APP.l(null,1,[$APP.su,"rgba(129, 198, 221, 0.2)"],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.gC,$APP.bG.Value,$APP.B.j(b,$APP.$B)?"Staked":"Unstaked"],null),new $APP.O(null,3,5,$APP.P,[$APP.gC,$APP.bG.Icon,new $APP.O(null,2,5,$APP.P,[$APP.cw,new $APP.l(null,2,[$APP.mu,new $APP.l(null,1,[$APP.ru,"0.825rem"],null),$APP.tD,"/images/select-down-arrow.svg"],null)],null)],null)],null),new $APP.O(null,4,5,$APP.P,[$APP.gC,$APP.bG.Content,new $APP.l(null,2,[$APP.Cp,"text-xl text-center pl-12 pr-12 py-0.5 rounded",
$APP.mu,new $APP.l(null,1,[$APP.su,"rgba(129, 198, 221, 0.2)"],null)],null),new $APP.O(null,4,5,$APP.P,[$APP.gC,$APP.bG.Viewport,$APP.Fh(new $APP.O(null,5,5,$APP.P,[$APP.gC,$APP.bG.Item,new $APP.l(null,1,[$APP.Jy,$APP.$B],null),new $APP.O(null,4,5,$APP.P,[$APP.gC,$APP.bG.ItemText,new $APP.l(null,1,[$APP.Cp,"text-2xl"],null),"Staked"],null),new $APP.O(null,3,5,$APP.P,[$APP.gC,$APP.bG.ItemIndicator,null==b||$APP.B.j(b,$APP.$B)],null)],null),new $APP.l(null,1,[$APP.Nn,$APP.XB],null)),$APP.Fh(new $APP.O(null,
5,5,$APP.P,[$APP.gC,$APP.bG.Item,new $APP.l(null,1,[$APP.Jy,$APP.fz],null),new $APP.O(null,4,5,$APP.P,[$APP.gC,$APP.bG.ItemText,new $APP.l(null,1,[$APP.Cp,"text-2xl"],null),"Unstaked"],null),new $APP.O(null,3,5,$APP.P,[$APP.gC,$APP.bG.ItemIndicator,$APP.B.j(b,$APP.fz)],null)],null),new $APP.l(null,1,[$APP.Nn,$APP.bC],null))],null)],null)],null)}};
uJ=function(a,b,c,d,e,f,h){var k=[$APP.m(b)?"Lord#":"Knight#",$APP.p.o(a)].join("");return new $APP.O(null,3,5,$APP.P,[$APP.eG,$APP.pl([$APP.$B,$APP.ZA,$APP.xA,$APP.U,$APP.ru,$APP.ew,$APP.sx,$APP.Bp,$APP.nC,$APP.oC,$APP.XC,$APP.JA],[e,f,h,k,"16rem",c,d,a,f,function(n){return $APP.fr(new $APP.O(null,2,5,$APP.P,[$APP.m(n)?sJ:tJ,a],null))},$APP.m(b)?"/images/lord-example.png":"/images/knight-example.png",$APP.m(c)?$APP.ef(d):c]),new $APP.l(null,2,[$APP.Cp,"mr-4",$APP.mu,new $APP.l(null,1,[$APP.gB,0],
null)],null)],null)};
wJ=function(){return function(){var a=$APP.Uf($APP.$r(new $APP.O(null,1,5,$APP.P,[qJ],null))),b=$APP.G(a,0,null);a=$APP.G(a,1,null);var c=$APP.B.j(b,$APP.$B),d=$APP.Uf($APP.$r(new $APP.O(null,1,5,$APP.P,[vJ],null)));return $APP.rj.j(new $APP.O(null,1,5,$APP.P,[$APP.IB],null),$APP.Cj.j(function(e){var f=$APP.fj(e);e=$APP.H.j(f,$APP.Bp);var h=$APP.H.j(f,$APP.UB),k=$APP.H.j(f,$APP.ew);f=$APP.H.j(f,$APP.sx);return $APP.Fh(new $APP.O(null,8,5,$APP.P,[uJ,e,h,k,f,c,null!=$APP.oj($APP.Cl([e]),d),!1],null),
new $APP.l(null,1,[$APP.Nn,e],null))},a))}};
zJ=function(){function a(b){return $APP.fr(new $APP.O(null,2,5,$APP.P,[xJ,b],null))}return function(){var b=$APP.Uf($APP.$r(new $APP.O(null,1,5,$APP.P,[qJ],null)));$APP.G(b,0,null);$APP.G(b,1,null);$APP.G(b,2,null);b=$APP.G(b,3,null);return new $APP.O(null,3,5,$APP.P,[$APP.aG,new $APP.l(null,2,[$APP.ru,"1.5rem",$APP.RB,new $APP.O(null,3,5,$APP.P,[yJ,new $APP.l(null,1,[$APP.mu,new $APP.l(null,1,[$APP.hy,"rgb(213, 228, 232)"],null)],null),"SELECT ALL"],null)],null),new $APP.l(null,3,[$APP.Cp,"flex flex-row cs1 ce2 rs5 re6 justify-self-start items-center",
$APP.oC,a,$APP.nC,b],null)],null)}};
AJ=function(){function a(e){return function(){return $APP.fr(new $APP.O(null,2,5,$APP.P,[$APP.jz,new $APP.l(null,2,[$APP.Qt,$APP.pw,$APP.Rt,new $APP.O(null,1,5,$APP.P,[$APP.Ft(e)],null)],null)],null))}}function b(e){return function(){return $APP.fr(new $APP.O(null,2,5,$APP.P,[$APP.jz,new $APP.l(null,2,[$APP.Qt,$APP.ND,$APP.Rt,new $APP.O(null,1,5,$APP.P,[$APP.Ft(e)],null)],null)],null))}}function c(e){return function(){return $APP.fr(new $APP.O(null,2,5,$APP.P,[$APP.jz,new $APP.l(null,2,[$APP.Qt,$APP.Jx,
$APP.Rt,new $APP.O(null,1,5,$APP.P,[$APP.Ft(e)],null)],null)],null))}}function d(){return $APP.fr(new $APP.O(null,2,5,$APP.P,[$APP.DB,new $APP.l(null,2,[$APP.Qt,$APP.SC,$APP.Rt,new $APP.O(null,2,5,$APP.P,["0xC4C8BC4784DDB88990d346134523B43B0F2a21eD",!0],null)],null)],null))}return function(){var e=$APP.Uf($APP.$r(new $APP.O(null,1,5,$APP.P,[qJ],null))),f=$APP.G(e,0,null);$APP.G(e,1,null);e=$APP.G(e,2,null);var h=$APP.Uf($APP.$r(new $APP.O(null,1,5,$APP.P,[vJ],null)));f=$APP.B.j(f,$APP.$B);var k=$APP.ef($APP.v(h)),
n=$APP.ef(e);return new $APP.O(null,6,5,$APP.P,[$APP.$w,new $APP.l(null,1,[$APP.Cp,f?"grid-cols-3 gap-4":"grid-cols-1"],null),n?new $APP.O(null,3,5,$APP.P,[$APP.Bu,new $APP.l(null,4,[$APP.wu,$APP.GD,$APP.xA,k,$APP.Cp,"mr-4",$APP.GA,d],null),"APPROVE"],null):n,$APP.m(e)?new $APP.O(null,3,5,$APP.P,[$APP.Bu,new $APP.l(null,4,[$APP.wu,$APP.GD,$APP.xA,k,$APP.Cp,"mr-4",$APP.GA,c(h)],null),"ENTER"],null):e,$APP.m(e)?f?new $APP.O(null,3,5,$APP.P,[$APP.Bu,new $APP.l(null,4,[$APP.wu,$APP.GD,$APP.xA,k,$APP.Cp,
"mr-4",$APP.GA,a(h)],null),"FLEE"],null):f:e,$APP.m(e)?f?new $APP.O(null,3,5,$APP.P,[$APP.Bu,new $APP.l(null,3,[$APP.xA,k,$APP.GA,b(h),$APP.wu,$APP.DD],null),"CLAIM"],null):f:e],null)}};
$APP.BJ=function(){return new $APP.O(null,7,5,$APP.P,[$APP.DA,new $APP.l(null,1,[$APP.mu,new $APP.l(null,2,[$APP.pC,"2%",$APP.ru,"98%"],null)],null),new $APP.O(null,1,5,$APP.P,[rJ],null),new $APP.O(null,2,5,$APP.P,[$APP.MF,new $APP.l(null,1,[$APP.Cp,"cs1 ce4 rs2 re3 mt-2 mb-4"],null)],null),new $APP.O(null,2,5,$APP.P,[$APP.uA,new $APP.O(null,1,5,$APP.P,[wJ],null)],null),new $APP.O(null,1,5,$APP.P,[zJ],null),new $APP.O(null,1,5,$APP.P,[AJ],null)],null)};xJ=$APP.T("fgl.app.views.battlefield","select-all");
pJ=$APP.T("fgl.app.views.battlefield","set-type");tJ=$APP.T("fgl.app.views.battlefield","deselect");sJ=$APP.T("fgl.app.views.battlefield","select");yJ=$APP.S("span.text-xl.ml-2.fb");vJ=$APP.T("fgl.app.views.battlefield","selected");CJ=$APP.T("fgl.app.views.battlefield","type");qJ=$APP.T("fgl.app.views.battlefield","data");$APP.hd("battlefield");$APP.DJ={};$APP.iF.j(pJ,function(a,b){$APP.G(b,0,null);b=$APP.G(b,1,null);return $APP.R.B(a,CJ,b,$APP.D([vJ,$APP.Bl]))});
$APP.Sr(xJ,new $APP.O(null,1,5,$APP.P,[$APP.xr(new $APP.O(null,1,5,$APP.P,[qJ],null))],null),function(a,b){var c=$APP.fj(a);a=$APP.H.j(c,qJ);c=$APP.H.j(c,$APP.Mr);$APP.G(b,0,null);b=$APP.G(b,1,null);return $APP.m(b)?($APP.G(a,0,null),b=$APP.G(a,1,null),new $APP.l(null,1,[$APP.Mr,$APP.R.A(c,vJ,$APP.rj.j($APP.Bl,$APP.Cj.j($APP.Bp,b)))],null)):new $APP.l(null,1,[$APP.Mr,$APP.R.A(c,vJ,$APP.Bl)],null)});
$APP.iF.j(sJ,function(a,b){$APP.G(b,0,null);b=$APP.G(b,1,null);return $APP.R.A(a,vJ,$APP.wi.j($APP.H.A(a,vJ,$APP.Bl),b))});$APP.iF.j(tJ,function(a,b){$APP.G(b,0,null);b=$APP.G(b,1,null);return $APP.R.A(a,vJ,$APP.vv.j($APP.H.A(a,vJ,$APP.Bl),b))});$APP.Yr(vJ,$APP.D([function(a){return $APP.H.A(a,vJ,$APP.Bl)}]));
$APP.Yr(qJ,$APP.D([function(a){var b=function(){var n=CJ.o(a);return $APP.m(n)?n:$APP.$B}(),c=$APP.fj(a);c=$APP.H.j(c,$APP.Tz);var d=$APP.H.j(a,c),e=$APP.fj(d);c=$APP.H.j(e,$APP.Iz);var f=$APP.H.j(e,$APP.mw),h=$APP.iy.o(a);e=$APP.Gw.o(d);d=$APP.rz.o(d);var k=vJ.o(a);c=$APP.H.j(new $APP.l(null,2,[$APP.$B,$APP.Cj.j(function(n){n=n.toString();return $APP.Po.B($APP.D([$APP.Po.B($APP.D([new $APP.l(null,1,[$APP.Bp,n],null),$APP.H.j(h,n)])),$APP.H.j(f,n)]))},c),$APP.fz,$APP.Cj.j(function(n){n=n.toString();
return $APP.Po.B($APP.D([new $APP.l(null,1,[$APP.Bp,n],null),$APP.H.j(h,n)]))},e)],null),b);e=$APP.B.j($APP.rh(k),$APP.rh(c));return new $APP.O(null,4,5,$APP.P,[b,c,d,e],null)}]));$APP.Re();
}).call(this);