(function(){
'use strict';var nQ,vQ,CQ,DQ,FQ,zQ,oQ,yQ,wQ,BQ,qQ,xQ,EQ,pQ;nQ=function(){return new $APP.J(null,2,5,$APP.K,[$APP.On,"\n      .kingdom .mask {\n        background: linear-gradient(#000000a6, #000000a6),\n          linear-gradient(to top, transparent 80%, #000000a6),\n          linear-gradient(to bottom, transparent 80%, #000000a6),\n          linear-gradient(155deg, #ffffff, transparent 30%);\n      }\n      .kingdom .section {\n        hyphens: auto;\n      }"],null)};
$APP.QL=function(){return new $APP.J(null,1,5,$APP.K,[new $APP.g(null,2,[$APP.Aq,function(){return $APP.R(new $APP.J(null,1,5,$APP.K,[$APP.HF],null))},$APP.xv,$APP.$h],null)],null)};
vQ=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[oQ],null))),b=$APP.H(a);a=$APP.E.j(b,pQ);b=$APP.E.j(b,qQ);a=$APP.h(a)?a:$APP.h(b)?b:1;return new $APP.J(null,3,5,$APP.K,[$APP.Xz,new $APP.g(null,2,[$APP.Zn,"relative w-1/2 h-full flex",$APP.On,new $APP.g(null,1,[$APP.sv,["linear-gradient(120deg, ",$APP.n.o($APP.E.j(rQ,a)),", transparent 50%)"].join("")],null)],null),new $APP.J(null,5,5,$APP.K,[$APP.Xz,new $APP.g(null,2,[$APP.Zn,"w-40% h-full ml-32 bg-no-repeat z-2 text-center",$APP.On,
new $APP.g(null,2,[$APP.xA,["url(",$APP.n.o($APP.E.j(sQ,a)),")"].join(""),$APP.bI,"100% 100%"],null)],null),new $APP.J(null,2,5,$APP.K,[$APP.tv,new $APP.g(null,2,[$APP.Zn,"w-48 inline-block mt-16",$APP.T,$APP.E.j(tQ,a)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.Ms,new $APP.g(null,1,[$APP.Zn,"text-2xl tracking-widest mt-10 mb-4"],null),$APP.E.j($APP.UK,a)],null),new $APP.J(null,3,5,$APP.K,[$APP.Xz,new $APP.g(null,1,[$APP.Zn,"text-xs text-C97979a text-left ffd px-9 section"],null),$APP.E.j(uQ,a)],
null)],null)],null)};
CQ=function(a){var b=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[oQ],null))),c=$APP.H(b);b=$APP.E.j(c,qQ);c=$APP.E.j(c,pQ);b=$APP.z.j(b,a);c=$APP.z.j(c,a);return new $APP.J(null,5,5,$APP.K,[wQ,new $APP.g(null,5,[$APP.Zn,"relative",$APP.qG,function(){return $APP.R(new $APP.J(null,2,5,$APP.K,[xQ,a],null))},$APP.iB,function(){return $APP.R(new $APP.J(null,1,5,$APP.K,[xQ],null))},$APP.ss,function(){return $APP.R(new $APP.J(null,2,5,$APP.K,[yQ,a],null))},$APP.On,new $APP.g(null,2,[zQ,c||b?"":"brightness(0.6)",
$APP.TF,"6.3rem"],null)],null),new $APP.J(null,2,5,$APP.K,[$APP.tv,new $APP.g(null,1,[$APP.T,$APP.E.j(AQ,a)],null)],null),new $APP.J(null,2,5,$APP.K,[$APP.tv,new $APP.g(null,2,[$APP.Zn,"absolute w-28 max-w-none top-2 left-1/2 transform -translate-x-1/2",$APP.T,$APP.E.j(tQ,a)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.Ms,new $APP.g(null,2,[$APP.Zn,"absolute w-full text-sm text-Cd5e4e8",$APP.On,new $APP.g(null,1,[BQ,"15%"],null)],null),$APP.E.j($APP.UK,a)],null)],null)};
DQ=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[oQ],null)));a=$APP.H(a);var b=$APP.E.j(a,qQ);return new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,3,[$APP.Yn,$APP.KI,$APP.ss,function(){return $APP.R(new $APP.J(null,2,5,$APP.K,[$APP.II,new $APP.g(null,2,[$APP.uu,$APP.zB,$APP.vu,b],null)],null))},$APP.Zn,"absolute bottom-12 right-16"],null),"CONFIRM"],null)};
FQ=function(){return new $APP.J(null,7,5,$APP.K,[$APP.Xz,new $APP.g(null,2,[$APP.Zn,"absolute top-0 right-0 w-2/3 h-full px-24",$APP.On,new $APP.g(null,1,[EQ,"10%"],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.Ms,new $APP.g(null,1,[$APP.Zn,"text-Cd5e4e8 text-3xl tracking-wider"],null),"Choose Your Kingdom"],null),new $APP.J(null,3,5,$APP.K,[$APP.Xz,new $APP.g(null,1,[$APP.Zn,"ffd text-sm my-2"],null),"Decades passed, villages nearby started to get constantly raided by powerful rangers. Riding on the wolf, fighting with primitive power and treating enemies with no mercy - Notorious name of “The Astas” had soon spread over the Gloryverse. According to rumors from the survivors, they are orphans raised by wolves. Aiming to make a blood sacrifice to Fenrir for some reason..."],
null),new $APP.J(null,3,5,$APP.K,[$APP.Ms,new $APP.g(null,1,[$APP.Zn,"text-sm text-Cababab ffd font-bold italic"],null),"You can modify the kingdom after selection"],null),new $APP.J(null,7,5,$APP.K,[$APP.Xz,new $APP.g(null,2,[$APP.Zn,"relative grid grid-cols-5 gap-x-16 mt-8 text-center",$APP.On,new $APP.g(null,1,[$APP.TF,"30rem"],null)],null),new $APP.J(null,2,5,$APP.K,[CQ,1],null),new $APP.J(null,2,5,$APP.K,[CQ,2],null),new $APP.J(null,2,5,$APP.K,[CQ,3],null),new $APP.J(null,2,5,$APP.K,[CQ,4],null),
new $APP.J(null,2,5,$APP.K,[CQ,5],null)],null),new $APP.J(null,1,5,$APP.K,[DQ],null)],null)};
$APP.PL=function(){return new $APP.J(null,3,5,$APP.K,[$APP.ys,new $APP.J(null,1,5,$APP.K,[nQ],null),new $APP.J(null,5,5,$APP.K,[$APP.Xz,new $APP.g(null,2,[$APP.Zn,"fixed top-0 left-0 z-100 kingdom w-screen h-screen bg-cover bg-center",$APP.On,new $APP.g(null,1,[$APP.xA,"url(/images/select-kingdom-bg.png)"],null)],null),new $APP.J(null,2,5,$APP.K,[$APP.Xz,new $APP.g(null,1,[$APP.Zn,"mask absolute w-full h-full top-0"],null)],null),new $APP.J(null,1,5,$APP.K,[vQ],null),new $APP.J(null,1,5,$APP.K,[FQ],
null)],null)],null)};zQ=$APP.N("filter");oQ=$APP.O("fgl.app.views.choose-kingdom","data");yQ=$APP.O("fgl.app.views.choose-kingdom","select");wQ=$APP.N("button.block");BQ=$APP.N("bottom");qQ=$APP.N("select");xQ=$APP.O("fgl.app.views.choose-kingdom","hover");EQ=$APP.N("paddingTop");pQ=$APP.N("hover");$APP.dd("choose-kingdom");$APP.OL={};$APP.tK.j(xQ,function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);return $APP.M.A(a,xQ,b)});$APP.tK.j(yQ,function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);return $APP.M.A(a,yQ,b)});$APP.ms(oQ,$APP.B([function(a){var b=$APP.H(a);a=$APP.E.j(b,yQ);b=$APP.E.j(b,xQ);return new $APP.g(null,2,[qQ,a,pQ,b],null)}]));
var tQ=new $APP.g(null,5,[1,"/images/select-kingdom-woff.png",2,"/images/select-kingdom-lion.png",3,"/images/select-kingdom-griffin.png",4,"/images/select-kingdom-dragon.png",5,"/images/select-kingdom-phoenix.png"],null),sQ=new $APP.g(null,5,[1,"/images/select-kingdom-woff-bg.png",2,"/images/select-kingdom-lion-bg.png",3,"/images/select-kingdom-griffin-bg.png",4,"/images/select-kingdom-dragon-bg.png",5,"/images/select-kingdom-phoenix-bg.png"],null),uQ=new $APP.g(null,5,[1,"A highland covered with eternal ice located on the southeast of the Gloryverse. Severe climate make it uninhabitable for almost all creatures. Wolves, however, treat it as unrestrained paradise. Some said they are governed by Fenrir, one of the most mythical and powerful beasts.",
2,"A highland covered with eternal ice located on the southeast of the Gloryverse. Severe climate make it uninhabitable for almost all creatures. Wolves, however, treat it as unrestrained paradise. Some said they are governed by Fenrir, one of the most mythical and powerful beasts.",3,"A highland covered with eternal ice located on the southeast of the Gloryverse. Severe climate make it uninhabitable for almost all creatures. Wolves, however, treat it as unrestrained paradise. Some said they are governed by Fenrir, one of the most mythical and powerful beasts.",
4,"A highland covered with eternal ice located on the southeast of the Gloryverse. Severe climate make it uninhabitable for almost all creatures. Wolves, however, treat it as unrestrained paradise. Some said they are governed by Fenrir, one of the most mythical and powerful beasts.",5,"A highland covered with eternal ice located on the southeast of the Gloryverse. Severe climate make it uninhabitable for almost all creatures. Wolves, however, treat it as unrestrained paradise. Some said they are governed by Fenrir, one of the most mythical and powerful beasts."],
null),rQ=new $APP.g(null,5,[1,"#5788c640",2,"#53b5c440",3,"#d1ac5b40",4,"#be675240",5,"#6d57c640"],null),AQ=new $APP.g(null,5,[1,"/images/select-kingdom-woff-flag.png",2,"/images/select-kingdom-lion-flag.png",3,"/images/select-kingdom-griffin-flag.png",4,"/images/select-kingdom-dragon-flag.png",5,"/images/select-kingdom-phoenix-flag.png"],null);$APP.Ke();
}).call(this);