(function(){
'use strict';var mG,nG,qG,EG,IG,LG,MG,OG,QG,GG;mG=function(a){return[$APP.p.o(a.substring(0,6)),"....",$APP.p.o(a.substring(34))].join("")};
nG=function(a){var b=document.createElement("textarea"),c=document.activeElement,d=function(){var e=window.pageYOffset;return $APP.m(e)?e:document.documentElement.scrollTop}();b.style={position:"absolute",left:"-9999px",top:[$APP.p.o(d),"px"].join(""),fontSize:"12pt",border:"0",padding:"0",margin:"0"};b.value=a;b.addEventListener("focus",function(){return window.scrollTo(0,d)});document.body.appendChild(b);b.setSelectionRange(0,b.value.length);b.focus();document.execCommand("copy");b.blur();$APP.m(c)&&
c.focus();window.getSelection().removeAllRanges();window.document.body.removeChild(b)};$APP.oG=function(){return new $APP.O(null,1,5,$APP.P,[new $APP.l(null,2,[$APP.cq,function(){$APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.vC],null));$APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.Zy],null));$APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.wA],null));$APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.Vv],null));return $APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.Zx],null))},$APP.nA,$APP.ki],null)],null)};
qG=function(){var a=$APP.$l.o,b=localStorage.getItem("user-avatar");a=a.call($APP.$l,$APP.m(b)?b:"knight");a:switch(a instanceof $APP.Bi?a.qa:null){case "knight":a="/images/avatar-knight.png";break a;default:a="/images/avatar-lord.png"}return new $APP.O(null,2,5,$APP.P,[pG,new $APP.O(null,2,5,$APP.P,[$APP.dy,new $APP.l(null,1,[$APP.rD,a],null)],null)],null)};
EG=function(){var a=$APP.Uf($APP.Tr(new $APP.O(null,1,5,$APP.P,[rG],null)));a=$APP.fj(a);var b=$APP.H.j(a,$APP.Nx);return new $APP.O(null,3,5,$APP.P,[sG,new $APP.O(null,3,5,$APP.P,[tG,new $APP.O(null,2,5,$APP.P,[uG,$APP.m(b)?mG(b):b],null),new $APP.O(null,3,5,$APP.P,[vG,new $APP.O(null,3,5,$APP.P,[$APP.uu,new $APP.l(null,3,[$APP.AA,function(){return open($APP.zt($APP.D(["/address/",b])))},$APP.pu,$APP.ZD,$APP.up,"mr-4"],null),new $APP.O(null,3,5,$APP.P,[wG,new $APP.O(null,2,5,$APP.P,[xG,new $APP.l(null,
1,[$APP.rD,"/images/share.png"],null)],null),"View on explorer"],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.uu,new $APP.l(null,2,[$APP.pu,$APP.ZD,$APP.AA,function(){nG(b);return $APP.Zq(new $APP.O(null,2,5,$APP.P,[$APP.Rt,new $APP.l(null,2,[$APP.Vt,"Copied!",$APP.jD,!0],null)],null))}],null),new $APP.O(null,3,5,$APP.P,[wG,new $APP.O(null,2,5,$APP.P,[yG,new $APP.l(null,1,[$APP.rD,"/images/copy.png"],null)],null),"Copy Address"],null)],null)],null)],null),new $APP.O(null,3,5,$APP.P,[zG,new $APP.O(null,
2,5,$APP.P,[AG,new $APP.l(null,1,[$APP.rD,"/images/k1.png"],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.pw,new $APP.O(null,3,5,$APP.P,[BG,new $APP.O(null,2,5,$APP.P,[CG,"ASTAS"],null),new $APP.O(null,2,5,$APP.P,[DG,"ROLE:XXXXX"],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.uu,new $APP.l(null,2,[$APP.AA,function(){return open($APP.zt($APP.D(["/address/",b])))},$APP.pu,$APP.ZD],null),new $APP.O(null,3,5,$APP.P,[wG,new $APP.O(null,2,5,$APP.P,[xG,new $APP.l(null,1,[$APP.rD,"/images/share.png"],null)],
null),"View on explorer"],null)],null)],null)],null)],null)};
IG=function(){var a=$APP.Uf($APP.Tr(new $APP.O(null,1,5,$APP.P,[rG],null))),b=$APP.fj(a);a=$APP.H.j(b,$APP.lx);var c=$APP.H.j(b,$APP.Yv),d=$APP.H.j(b,$APP.Rz);b=$APP.H.j(b,$APP.qy);return new $APP.O(null,5,5,$APP.P,[FG,new $APP.O(null,3,5,$APP.P,[$APP.OF,new $APP.l(null,1,[$APP.up,"w-32"],null),new $APP.O(null,3,5,$APP.P,[$APP.vx,new $APP.O(null,3,5,$APP.P,[$APP.VF,"3rem",new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.ew,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.O(null,3,5,$APP.P,
[$APP.JF,c,new $APP.l(null,1,[$APP.up,"mr-2"],null)],null)],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.OF,new $APP.l(null,1,[$APP.up,"w-32"],null),new $APP.O(null,3,5,$APP.P,[$APP.vx,new $APP.O(null,3,5,$APP.P,[$APP.LF,"3rem",new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.ew,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.JF,a,new $APP.l(null,1,[$APP.up,"mr-2"],null)],null)],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.OF,new $APP.l(null,1,[$APP.up,"w-32"],
null),new $APP.O(null,3,5,$APP.P,[$APP.vx,new $APP.O(null,3,5,$APP.P,[GG,"3rem",new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.ew,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.JF,d,new $APP.l(null,1,[$APP.up,"mr-2"],null)],null)],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.OF,new $APP.l(null,1,[$APP.up,"w-32"],null),new $APP.O(null,3,5,$APP.P,[$APP.vx,new $APP.O(null,3,5,$APP.P,[HG,"3rem",new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.ew,"-1.4rem 0 -1.4rem -1.4rem"],
null)],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.JF,b,new $APP.l(null,1,[$APP.up,"mr-2"],null)],null)],null)],null)],null)};LG=function(){return new $APP.O(null,3,5,$APP.P,[JG,new $APP.O(null,1,5,$APP.P,[qG],null),new $APP.O(null,3,5,$APP.P,[KG,new $APP.O(null,1,5,$APP.P,[EG],null),new $APP.O(null,1,5,$APP.P,[IG],null)],null)],null)};MG=function(a){return 10>a?["0",$APP.p.o(a)].join(""):a};
OG=function(a){var b=$APP.G(a,0,null);a=$APP.G(a,1,null);var c=$APP.fj(a);a=$APP.H.j(c,$APP.bu);var d=$APP.H.j(c,$APP.cu);c=$APP.P;var e=new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.ax,"1fr 3fr 1fr"],null)],null),f=$APP.P;d=[$APP.p.o(d.getFullYear()),".",$APP.p.o(MG(d.getMonth()+1)),".",$APP.p.o(MG(d.getDate()))].join("");return $APP.Fh(new $APP.O(null,5,5,c,[NG,e,new $APP.O(null,2,5,f,[$APP.dB,d],null),new $APP.O(null,3,5,$APP.P,[wG,new $APP.O(null,2,5,$APP.P,[$APP.VF,"1.5rem"],null),new $APP.O(null,
2,5,$APP.P,[$APP.dB,"Gold"],null)],null),new $APP.O(null,2,5,$APP.P,[$APP.JF,a],null)],null),new $APP.l(null,1,[$APP.Fn,b],null))};
QG=function(){return new $APP.O(null,3,5,$APP.P,[PG,new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.hu,"calc(100% - 180px - 7.5rem)"],null)],null),new $APP.O(null,4,5,$APP.P,[$APP.Uv,new $APP.l(null,1,[$APP.fu,new $APP.l(null,3,[$APP.hu,"calc(100% - 2.25rem)",$APP.qz,"2px ridge #50929e33",$APP.oz,"linear-gradient(\n    rgba(163, 218, 226, 0.1),\n    rgba(163, 218, 226, 0.05)\n  )"],null)],null),new $APP.O(null,5,5,$APP.P,[$APP.RC,new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.ax,"1fr 3fr 1fr"],
null)],null),new $APP.O(null,2,5,$APP.P,[$APP.dB,"DATE"],null),new $APP.O(null,2,5,$APP.P,[$APP.dB,"ASSET"],null),new $APP.O(null,2,5,$APP.P,[$APP.dB,"sGold locked"],null)],null),function(){var a=$APP.Uf($APP.Tr(new $APP.O(null,1,5,$APP.P,[rG],null)));a=$APP.fj(a);a=$APP.H.j(a,$APP.Qx);return new $APP.O(null,3,5,$APP.P,[$APP.rj,new $APP.O(null,2,5,$APP.P,[$APP.JD,new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.hu,"calc(100% - 1.25rem)"],null)],null)],null),$APP.uj(function(b,c){return new $APP.O(null,
2,5,$APP.P,[OG,new $APP.O(null,2,5,$APP.P,[b,c],null)],null)},a)],null)}()],null)],null)};$APP.SG=function(){return new $APP.O(null,3,5,$APP.P,[RG,new $APP.O(null,1,5,$APP.P,[LG],null),new $APP.O(null,1,5,$APP.P,[QG],null)],null)};GG=function GG(a){switch(arguments.length){case 1:return GG.o(arguments[0]);case 2:return GG.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};GG.o=function(a){return GG.j(a,$APP.M)};
GG.j=function(a,b){a=$APP.ff?a:[$APP.p.o(a),"rem"].join("");return new $APP.O(null,2,5,$APP.P,[$APP.dy,$APP.zn($APP.D([b,new $APP.l(null,2,[$APP.fu,new $APP.l(null,2,[$APP.ku,a,$APP.hu,a],null),$APP.rD,"/images/rune-token.png"],null)]))],null)};GG.H=2;
var JG=$APP.S("div.flex.flex-row.justify-between.items-center.p-8"),BG=$APP.S("div.flex.flex-row.items-baseline.mb-4"),vG=$APP.S("div.flex.flex-row.justify-between.items-center"),CG=$APP.S("div.uppercase.text-3xl.fi.mr-4"),yG=$APP.S("img.mr-2.w-4"),xG=$APP.S("img.w-4.mr-2"),RG=$APP.S("div.h-full.w-full"),DG=$APP.S("div.text-xl"),zG=$APP.S("div.flexr"),rG=$APP.T("fgl.app.views.dashboard","data"),AG=$APP.S("img.h-30.mr-4"),FG=$APP.S("div.flex.flex-row.justify-around.items-cednter.bg-C81c6dd33.py-3.rounded-lg.fb"),
uG=$APP.S("div.text-3xl.fi.mb-4"),PG=$APP.S("div.px-6"),tG=$APP.S("div.mr-8"),pG=$APP.S("div.rounded-full.bg-C25376f.w-40.h-40.mr-8.self-start"),sG=$APP.S("div.flexrs.mb-4"),KG=$APP.S("div.grow"),wG=$APP.S("span.flexr"),NG=$APP.S("div.grid.justify-items-center.pb-1.border-b.border-C79c5da.pt-1_125rem.fp.font-bold.items-center");$APP.hd("dashboard");var HG=function HG(a){switch(arguments.length){case 1:return HG.o(arguments[0]);case 2:return HG.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};HG.o=function(a){return HG.j(a,$APP.M)};
HG.j=function(a,b){a=$APP.ff?a:[$APP.p.o(a),"rem"].join("");return new $APP.O(null,2,5,$APP.P,[$APP.dy,$APP.zn($APP.D([b,new $APP.l(null,2,[$APP.fu,new $APP.l(null,3,[$APP.ku,$APP.xt(a,.81818182),$APP.hu,a,$APP.ju,"translateY(5%)"],null),$APP.rD,"/images/landeed-token.png"],null)]))],null)};HG.H=2;$APP.TG={};$APP.Rr(rG,$APP.D([function(a){var b=$APP.fj(a);b=$APP.H.j(b,$APP.Nz);a=$APP.H.j(a,b);var c=$APP.fj(a);a=$APP.H.j(c,$APP.Ex);var d=$APP.H.j(c,$APP.JC),e=$APP.H.j(c,$APP.Fv),f=$APP.H.j(c,$APP.Ly);c=$APP.H.j(c,$APP.kD);return new $APP.l(null,6,[$APP.Nx,b,$APP.Yv,a,$APP.lx,d,$APP.Rz,e,$APP.qy,f,$APP.Qx,$APP.du(c)],null)}]));$APP.m(localStorage.getItem("user-avatar"))||localStorage.setItem("user-avatar","knight");$APP.Re();
}).call(this);