(function(){
'use strict';var TO,VO,XO,kP,nP,qP,rP,tP,vP,oP,hP,cP,WO,iP,fP,mP,eP,ZO,wP,YO,gP,lP,bP,uP,aP,UO,$O,jP,pP,dP,sP;
TO=function(a){var b=document.createElement("textarea"),c=document.activeElement,d=function(){var e=window.pageYOffset;return $APP.h(e)?e:document.documentElement.scrollTop}();b.style={position:"absolute",left:"-9999px",top:[$APP.n.o(d),"px"].join(""),fontSize:"12pt",border:"0",padding:"0",margin:"0"};b.value=a;b.addEventListener("focus",function(){return window.scrollTo(0,d)});document.body.appendChild(b);b.setSelectionRange(0,b.value.length);b.focus();document.execCommand("copy");b.blur();$APP.h(c)&&
c.focus();window.getSelection().removeAllRanges();window.document.body.removeChild(b)};$APP.$L=function(){return new $APP.J(null,1,5,$APP.K,[new $APP.g(null,2,[$APP.Aq,function(){$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.JH],null));$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.zD],null));$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.ZE],null));$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.zz],null));return $APP.R(new $APP.J(null,1,5,$APP.K,[$APP.lC],null))},$APP.xv,$APP.$h],null)],null)};
VO=function(){var a=$APP.Sl.o,b=localStorage.getItem("user-avatar");a=a.call($APP.Sl,$APP.h(b)?b:"knight");a:switch(a instanceof $APP.ri?a.ka:null){case "knight":a="/images/avatar-knight.png";break a;default:a="/images/avatar-lord.png"}return new $APP.J(null,2,5,$APP.K,[UO,new $APP.J(null,2,5,$APP.K,[$APP.tv,new $APP.g(null,1,[$APP.T,a],null)],null)],null)};
XO=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[WO],null)));return new $APP.J(null,3,5,$APP.K,[$APP.rL,new $APP.g(null,2,[$APP.Tn,"1.5rem",$APP.TG,new $APP.J(null,2,5,$APP.K,[$APP.EB,"Do not remind me next time"],null)],null),new $APP.g(null,3,[$APP.Zn,"flex flex-row cs1 ce2 rs1 re2 justify-self-start items-center",$APP.uH,function(b){return $APP.R(new $APP.J(null,2,5,$APP.K,[WO,b],null))},$APP.tH,a],null)],null)};
kP=function(){function a(){return $APP.h(localStorage.getItem("leave-checked"))?b():$APP.R(new $APP.J(null,9,5,$APP.K,[$APP.ts,$APP.Ds,!0,$APP.Ls,"",$APP.Fs,new $APP.J(null,4,5,$APP.K,[$APP.ys,new $APP.J(null,2,5,$APP.K,[$APP.Lz,"Notice: Since you are trying to leave your current Kingdom, 10% of your Glony will be charged as handling fee. And 24h cool-down will be applied. Click Confirm to proceed."],null),new $APP.J(null,1,5,$APP.K,[$APP.As],null),new $APP.J(null,1,5,$APP.K,[XO],null)],null),$APP.Gs,
new $APP.J(null,3,5,$APP.K,[$APP.ys,new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,3,[$APP.Yn,$APP.vJ,$APP.ss,$APP.Cu.j(b,c),$APP.Zn,"mr-8"],null),"Confirm"],null),new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,2,[$APP.Yn,$APP.Hs,$APP.ss,function(){return $APP.R(new $APP.J(null,3,5,$APP.K,[$APP.ts,$APP.us,!0],null))}],null),"Cancel"],null)],null)],null))}function b(){return $APP.R(new $APP.J(null,2,5,$APP.K,[$APP.WI,new $APP.g(null,3,[$APP.uu,$APP.JC,$APP.Ls,"Leave Kingdom",$APP.xu,function(){$APP.Is();
return $APP.R(new $APP.J(null,2,5,$APP.K,[$APP.DI,!0],null))}],null)],null))}function c(){return $APP.h(m)?localStorage.setItem("leave-checked",1):localStorage.removeItem("leave-checked")}var d=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[YO],null)));d=$APP.H(d);var e=$APP.E.j(d,$APP.TB),k=$APP.E.j(d,$APP.kG);d=$APP.E.j(d,ZO);var l=$APP.h(d)?d:$APP.lJ,m=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[WO],null)));return new $APP.J(null,3,5,$APP.K,[$O,new $APP.J(null,3,5,$APP.K,[aP,new $APP.J(null,2,5,$APP.K,
[bP,$APP.h(e)?$APP.rn(e):e],null),new $APP.J(null,3,5,$APP.K,[cP,new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,3,[$APP.ss,function(){return open($APP.qn($APP.B(["/address/",e])))},$APP.Yn,$APP.rJ,$APP.Zn,"mr-4"],null),new $APP.J(null,3,5,$APP.K,[dP,new $APP.J(null,2,5,$APP.K,[eP,new $APP.g(null,1,[$APP.T,"/images/share.png"],null)],null),"View on explorer"],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,2,[$APP.Yn,$APP.rJ,$APP.ss,function(){TO(e);return $APP.R(new $APP.J(null,
2,5,$APP.K,[$APP.dG,new $APP.g(null,2,[$APP.Ls,"Copied!",$APP.GI,!0],null)],null))}],null),new $APP.J(null,3,5,$APP.K,[dP,new $APP.J(null,2,5,$APP.K,[fP,new $APP.g(null,1,[$APP.T,"/images/copy.png"],null)],null),"Copy Address"],null)],null)],null)],null),function(){if($APP.h(k)){var r=0<k;return r?new $APP.J(null,3,5,$APP.K,[$APP.sF,new $APP.J(null,2,5,$APP.K,[gP,new $APP.g(null,1,[$APP.T,["/images/k",$APP.n.o(k),".png"].join("")],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.Zz,new $APP.J(null,3,
5,$APP.K,[hP,new $APP.J(null,2,5,$APP.K,[iP,$APP.E.j($APP.hL,k)],null),new $APP.J(null,2,5,$APP.K,[jP,["ROLE:",$APP.zl(l)].join("")],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,2,[$APP.ss,a,$APP.Yn,$APP.rJ],null),"Leave My Kingdom"],null)],null)],null):r}return k}()],null)};
nP=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[YO],null))),b=$APP.H(a);a=$APP.E.j(b,$APP.lB);var c=$APP.E.j(b,$APP.Ez),d=$APP.E.j(b,$APP.uE);b=$APP.E.j(b,$APP.LC);return new $APP.J(null,5,5,$APP.K,[lP,new $APP.J(null,3,5,$APP.K,[$APP.qK,new $APP.g(null,1,[$APP.Zn,"w-32"],null),new $APP.J(null,3,5,$APP.K,[mP,new $APP.J(null,3,5,$APP.K,[$APP.sL,"3rem",new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.vv,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.pK,
c,new $APP.g(null,1,[$APP.Zn,"mr-2"],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.qK,new $APP.g(null,1,[$APP.Zn,"w-32"],null),new $APP.J(null,3,5,$APP.K,[mP,new $APP.J(null,3,5,$APP.K,[$APP.jL,"3rem",new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.vv,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.pK,a,new $APP.g(null,1,[$APP.Zn,"mr-2"],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.qK,new $APP.g(null,1,[$APP.Zn,"w-32"],null),new $APP.J(null,
3,5,$APP.K,[mP,new $APP.J(null,3,5,$APP.K,[$APP.rK,"3rem",new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.vv,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.pK,d,new $APP.g(null,1,[$APP.Zn,"mr-2"],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.qK,new $APP.g(null,1,[$APP.Zn,"w-32"],null),new $APP.J(null,3,5,$APP.K,[mP,new $APP.J(null,3,5,$APP.K,[$APP.tL,"3rem",new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.vv,"-1.4rem 0 -1.4rem -1.4rem"],null)],
null)],null),new $APP.J(null,3,5,$APP.K,[$APP.pK,b,new $APP.g(null,1,[$APP.Zn,"mr-2"],null)],null)],null)],null)],null)};qP=function(){return new $APP.J(null,3,5,$APP.K,[oP,new $APP.J(null,1,5,$APP.K,[VO],null),new $APP.J(null,3,5,$APP.K,[pP,new $APP.J(null,1,5,$APP.K,[kP],null),new $APP.J(null,1,5,$APP.K,[nP],null)],null)],null)};rP=function(a){return 10>a?["0",$APP.n.o(a)].join(""):a};
tP=function(a){var b=$APP.D(a,0,null);a=$APP.D(a,1,null);var c=$APP.H(a);a=$APP.E.j(c,$APP.jv);var d=$APP.E.j(c,$APP.kv);c=$APP.K;var e=new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.XA,"1fr 3fr 1fr"],null)],null),k=$APP.K;d=[$APP.n.o(d.getFullYear()),".",$APP.n.o(rP(d.getMonth()+1)),".",$APP.n.o(rP(d.getDate()))].join("");return $APP.vh(new $APP.J(null,5,5,c,[sP,e,new $APP.J(null,2,5,k,[$APP.zs,d],null),new $APP.J(null,3,5,$APP.K,[dP,new $APP.J(null,2,5,$APP.K,[$APP.sL,"1.5rem"],null),new $APP.J(null,
2,5,$APP.K,[$APP.zs,"Gold"],null)],null),new $APP.J(null,2,5,$APP.K,[$APP.pK,a],null)],null),new $APP.g(null,1,[$APP.oo,b],null))};
vP=function(){return new $APP.J(null,3,5,$APP.K,[uP,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.Qn,"calc(100% - 180px - 7.5rem)"],null)],null),new $APP.J(null,4,5,$APP.K,[$APP.yz,new $APP.g(null,1,[$APP.On,new $APP.g(null,3,[$APP.Qn,"calc(100% - 2.25rem)",$APP.VD,"2px ridge #50929e33",$APP.sv,"linear-gradient(\n    rgba(163, 218, 226, 0.1),\n    rgba(163, 218, 226, 0.05)\n  )"],null)],null),new $APP.J(null,5,5,$APP.K,[$APP.iI,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.XA,"1fr 3fr 1fr"],
null)],null),new $APP.J(null,2,5,$APP.K,[$APP.zs,"DATE"],null),new $APP.J(null,2,5,$APP.K,[$APP.zs,"ASSET"],null),new $APP.J(null,2,5,$APP.K,[$APP.zs,"sGold locked"],null)],null),function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[YO],null)));a=$APP.H(a);a=$APP.E.j(a,$APP.WB);return new $APP.J(null,3,5,$APP.K,[$APP.ej,new $APP.J(null,2,5,$APP.K,[$APP.dJ,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.Qn,"calc(100% - 1.25rem)"],null)],null)],null),$APP.jj(function(b,c){return new $APP.J(null,
2,5,$APP.K,[tP,new $APP.J(null,2,5,$APP.K,[b,c],null)],null)},a)],null)}()],null)],null)};$APP.ZL=function(){return new $APP.J(null,3,5,$APP.K,[wP,new $APP.J(null,1,5,$APP.K,[qP],null),new $APP.J(null,1,5,$APP.K,[vP],null)],null)};oP=$APP.N("div.flex.flex-row.justify-between.items-center.p-8");hP=$APP.N("div.flex.flex-row.items-baseline.mb-4");cP=$APP.N("div.flex.flex-row.justify-between.items-center");WO=$APP.O("fgl.app.views.dashboard","leave-checked");iP=$APP.N("div.uppercase.text-3xl.fi.mr-4");
fP=$APP.N("img.mr-2.w-4");mP=$APP.N("div.flex.flex-row.justify-between.items-center.text-xl");eP=$APP.N("img.w-4.mr-2");ZO=$APP.N("kingdom-role");wP=$APP.N("div.h-full.w-full");YO=$APP.O("fgl.app.views.dashboard","data");gP=$APP.N("img.h-30.mr-4");lP=$APP.N("div.flex.flex-row.justify-around.items-cednter.bg-C81c6dd33.py-3.rounded-lg.fb");bP=$APP.N("div.text-3xl.fi.mb-4");uP=$APP.N("div.px-6");aP=$APP.N("div.mr-8");UO=$APP.N("div.rounded-full.bg-C25376f.w-40.h-40.mr-8.self-start");$O=$APP.N("div.flexrs.mb-4");
jP=$APP.N("div.text-xl.uppercase");pP=$APP.N("div.grow");dP=$APP.N("span.flexr");sP=$APP.N("div.grid.justify-items-center.pb-1.border-b.border-C79c5da.pt-1_125rem.fp.font-bold.items-center");$APP.dd("dashboard");$APP.YL={};$APP.ms(YO,$APP.B([function(a){var b=$APP.H(a);b=$APP.E.j(b,$APP.Ou);a=$APP.E.j(a,b);var c=$APP.H(a);a=$APP.E.j(c,$APP.JB);var d=$APP.E.j(c,$APP.WH),e=$APP.E.j(c,$APP.hz),k=$APP.E.j(c,$APP.oD),l=$APP.E.j(c,$APP.II),m=$APP.E.j(c,$APP.Wu);c=$APP.E.j(c,$APP.Zu);return new $APP.g(null,8,[$APP.TB,b,$APP.Ez,a,$APP.lB,d,$APP.uE,e,$APP.LC,k,$APP.kG,m,ZO,c,$APP.WB,$APP.lv(l)],null)}]));$APP.h(localStorage.getItem("user-avatar"))||localStorage.setItem("user-avatar","knight");
$APP.HK.j(WO,function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);return $APP.M.A(a,WO,b)});$APP.ms(WO,$APP.B([function(a){return $APP.E.A(a,WO,!1)}]));$APP.Ke();
}).call(this);