(function(){
'use strict';var PL,RL,dM,hM,kM,lM,nM,pM,fM;
PL=function(a){var b=document.createElement("textarea"),c=document.activeElement,d=function(){var e=window.pageYOffset;return $APP.k(e)?e:document.documentElement.scrollTop}();b.style={position:"absolute",left:"-9999px",top:[$APP.n.o(d),"px"].join(""),fontSize:"12pt",border:"0",padding:"0",margin:"0"};b.value=a;b.addEventListener("focus",function(){return window.scrollTo(0,d)});document.body.appendChild(b);b.setSelectionRange(0,b.value.length);b.focus();document.execCommand("copy");b.blur();$APP.k(c)&&
c.focus();window.getSelection().removeAllRanges();window.document.body.removeChild(b)};$APP.yK=function(){return new $APP.J(null,1,5,$APP.K,[new $APP.h(null,2,[$APP.hr,function(){$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.vG],null));$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.BC],null));$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.cE],null));$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.Zy],null));return $APP.S(new $APP.J(null,1,5,$APP.K,[$APP.wB],null))},$APP.$u,$APP.ai],null)],null)};
RL=function(){var a=$APP.Tl.o,b=localStorage.getItem("user-avatar");a=a.call($APP.Tl,$APP.k(b)?b:"knight");a:switch(a instanceof $APP.si?a.ka:null){case "knight":a="/images/avatar-knight.png";break a;default:a="/images/avatar-lord.png"}return new $APP.J(null,2,5,$APP.K,[QL,new $APP.J(null,2,5,$APP.K,[$APP.Vu,new $APP.h(null,1,[$APP.Wu,a],null)],null)],null)};
dM=function(){var a=$APP.p($APP.Ws(new $APP.J(null,1,5,$APP.K,[SL],null)));a=$APP.H(a);var b=$APP.E.j(a,$APP.eB);return new $APP.J(null,3,5,$APP.K,[TL,new $APP.J(null,3,5,$APP.K,[UL,new $APP.J(null,2,5,$APP.K,[VL,$APP.k(b)?$APP.Zs(b):b],null),new $APP.J(null,3,5,$APP.K,[WL,new $APP.J(null,3,5,$APP.K,[$APP.Ft,new $APP.h(null,3,[$APP.Ut,function(){return open($APP.Ys($APP.B(["/address/",b])))},$APP.At,$APP.YH,$APP.Jq,"mr-4"],null),new $APP.J(null,3,5,$APP.K,[XL,new $APP.J(null,2,5,$APP.K,[YL,new $APP.h(null,
1,[$APP.Wu,"/images/share.png"],null)],null),"View on explorer"],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.Ft,new $APP.h(null,2,[$APP.At,$APP.YH,$APP.Ut,function(){PL(b);return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.aF,new $APP.h(null,2,[$APP.nu,"Copied!",$APP.mH,!0],null)],null))}],null),new $APP.J(null,3,5,$APP.K,[XL,new $APP.J(null,2,5,$APP.K,[ZL,new $APP.h(null,1,[$APP.Wu,"/images/copy.png"],null)],null),"Copy Address"],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.rE,new $APP.J(null,
2,5,$APP.K,[$L,new $APP.h(null,1,[$APP.Wu,"/images/k1.png"],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.vz,new $APP.J(null,3,5,$APP.K,[aM,new $APP.J(null,2,5,$APP.K,[bM,"ASTAS"],null),new $APP.J(null,2,5,$APP.K,[cM,"ROLE:XXXXX"],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.Ft,new $APP.h(null,2,[$APP.Ut,function(){return open($APP.Ys($APP.B(["/address/",b])))},$APP.At,$APP.YH],null),new $APP.J(null,3,5,$APP.K,[XL,new $APP.J(null,2,5,$APP.K,[YL,new $APP.h(null,1,[$APP.Wu,"/images/share.png"],null)],
null),"View on explorer"],null)],null)],null)],null)],null)};
hM=function(){var a=$APP.p($APP.Ws(new $APP.J(null,1,5,$APP.K,[SL],null))),b=$APP.H(a);a=$APP.E.j(b,$APP.zA);var c=$APP.E.j(b,$APP.cz),d=$APP.E.j(b,$APP.yD);b=$APP.E.j(b,$APP.TB);return new $APP.J(null,5,5,$APP.K,[eM,new $APP.J(null,3,5,$APP.K,[$APP.VJ,new $APP.h(null,1,[$APP.Jq,"w-32"],null),new $APP.J(null,3,5,$APP.K,[$APP.LA,new $APP.J(null,3,5,$APP.K,[$APP.UJ,"3rem",new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.Yu,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.J(null,3,5,$APP.K,
[$APP.BJ,c,new $APP.h(null,1,[$APP.Jq,"mr-2"],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.VJ,new $APP.h(null,1,[$APP.Jq,"w-32"],null),new $APP.J(null,3,5,$APP.K,[$APP.LA,new $APP.J(null,3,5,$APP.K,[$APP.CJ,"3rem",new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.Yu,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.BJ,a,new $APP.h(null,1,[$APP.Jq,"mr-2"],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.VJ,new $APP.h(null,1,[$APP.Jq,"w-32"],
null),new $APP.J(null,3,5,$APP.K,[$APP.LA,new $APP.J(null,3,5,$APP.K,[fM,"3rem",new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.Yu,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.BJ,d,new $APP.h(null,1,[$APP.Jq,"mr-2"],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.VJ,new $APP.h(null,1,[$APP.Jq,"w-32"],null),new $APP.J(null,3,5,$APP.K,[$APP.LA,new $APP.J(null,3,5,$APP.K,[gM,"3rem",new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.Yu,"-1.4rem 0 -1.4rem -1.4rem"],
null)],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.BJ,b,new $APP.h(null,1,[$APP.Jq,"mr-2"],null)],null)],null)],null)],null)};kM=function(){return new $APP.J(null,3,5,$APP.K,[iM,new $APP.J(null,1,5,$APP.K,[RL],null),new $APP.J(null,3,5,$APP.K,[jM,new $APP.J(null,1,5,$APP.K,[dM],null),new $APP.J(null,1,5,$APP.K,[hM],null)],null)],null)};lM=function(a){return 10>a?["0",$APP.n.o(a)].join(""):a};
nM=function(a){var b=$APP.C(a,0,null);a=$APP.C(a,1,null);var c=$APP.H(a);a=$APP.E.j(c,$APP.Pu);var d=$APP.E.j(c,$APP.Qu);c=$APP.K;var e=new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.lA,"1fr 3fr 1fr"],null)],null),f=$APP.K;d=[$APP.n.o(d.getFullYear()),".",$APP.n.o(lM(d.getMonth()+1)),".",$APP.n.o(lM(d.getDate()))].join("");return $APP.wh(new $APP.J(null,5,5,c,[mM,e,new $APP.J(null,2,5,f,[$APP.au,d],null),new $APP.J(null,3,5,$APP.K,[XL,new $APP.J(null,2,5,$APP.K,[$APP.UJ,"1.5rem"],null),new $APP.J(null,
2,5,$APP.K,[$APP.au,"Gold"],null)],null),new $APP.J(null,2,5,$APP.K,[$APP.BJ,a],null)],null),new $APP.h(null,1,[$APP.Uo,b],null))};
pM=function(){return new $APP.J(null,3,5,$APP.K,[oM,new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.st,"calc(100% - 180px - 7.5rem)"],null)],null),new $APP.J(null,4,5,$APP.K,[$APP.Yy,new $APP.h(null,1,[$APP.qt,new $APP.h(null,3,[$APP.st,"calc(100% - 2.25rem)",$APP.XC,"2px ridge #50929e33",$APP.Uu,"linear-gradient(\n    rgba(163, 218, 226, 0.1),\n    rgba(163, 218, 226, 0.05)\n  )"],null)],null),new $APP.J(null,5,5,$APP.K,[$APP.TG,new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.lA,"1fr 3fr 1fr"],
null)],null),new $APP.J(null,2,5,$APP.K,[$APP.au,"DATE"],null),new $APP.J(null,2,5,$APP.K,[$APP.au,"ASSET"],null),new $APP.J(null,2,5,$APP.K,[$APP.au,"sGold locked"],null)],null),function(){var a=$APP.p($APP.Ws(new $APP.J(null,1,5,$APP.K,[SL],null)));a=$APP.H(a);a=$APP.E.j(a,$APP.hB);return new $APP.J(null,3,5,$APP.K,[$APP.fj,new $APP.J(null,2,5,$APP.K,[$APP.LH,new $APP.h(null,1,[$APP.qt,new $APP.h(null,1,[$APP.st,"calc(100% - 1.25rem)"],null)],null)],null),$APP.kj(function(b,c){return new $APP.J(null,
2,5,$APP.K,[nM,new $APP.J(null,2,5,$APP.K,[b,c],null)],null)},a)],null)}()],null)],null)};$APP.xK=function(){return new $APP.J(null,3,5,$APP.K,[qM,new $APP.J(null,1,5,$APP.K,[kM],null),new $APP.J(null,1,5,$APP.K,[pM],null)],null)};fM=function fM(a){switch(arguments.length){case 1:return fM.o(arguments[0]);case 2:return fM.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.n.o(arguments.length)].join(""));}};fM.o=function(a){return fM.j(a,$APP.F)};
fM.j=function(a,b){a=$APP.$e?a:[$APP.n.o(a),"rem"].join("");return new $APP.J(null,2,5,$APP.K,[$APP.Vu,$APP.ot($APP.B([b,new $APP.h(null,2,[$APP.qt,new $APP.h(null,2,[$APP.vt,a,$APP.st,a],null),$APP.Wu,"/images/rune-token.png"],null)]))],null)};fM.I=2;
var iM=$APP.O("div.flex.flex-row.justify-between.items-center.p-8"),aM=$APP.O("div.flex.flex-row.items-baseline.mb-4"),WL=$APP.O("div.flex.flex-row.justify-between.items-center"),bM=$APP.O("div.uppercase.text-3xl.fi.mr-4"),ZL=$APP.O("img.mr-2.w-4"),YL=$APP.O("img.w-4.mr-2"),qM=$APP.O("div.h-full.w-full"),cM=$APP.O("div.text-xl"),SL=$APP.P("fgl.app.views.dashboard","data"),$L=$APP.O("img.h-30.mr-4"),eM=$APP.O("div.flex.flex-row.justify-around.items-cednter.bg-C81c6dd33.py-3.rounded-lg.fb"),VL=$APP.O("div.text-3xl.fi.mb-4"),
oM=$APP.O("div.px-6"),UL=$APP.O("div.mr-8"),QL=$APP.O("div.rounded-full.bg-C25376f.w-40.h-40.mr-8.self-start"),TL=$APP.O("div.flexrs.mb-4"),jM=$APP.O("div.grow"),XL=$APP.O("span.flexr"),mM=$APP.O("div.grid.justify-items-center.pb-1.border-b.border-C79c5da.pt-1_125rem.fp.font-bold.items-center");$APP.ed("dashboard");var gM=function gM(a){switch(arguments.length){case 1:return gM.o(arguments[0]);case 2:return gM.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.n.o(arguments.length)].join(""));}};gM.o=function(a){return gM.j(a,$APP.F)};
gM.j=function(a,b){a=$APP.$e?a:[$APP.n.o(a),"rem"].join("");return new $APP.J(null,2,5,$APP.K,[$APP.Vu,$APP.ot($APP.B([b,new $APP.h(null,2,[$APP.qt,new $APP.h(null,3,[$APP.vt,$APP.Xs(a,.81818182),$APP.st,a,$APP.ut,"translateY(5%)"],null),$APP.Wu,"/images/landeed-token.png"],null)]))],null)};gM.I=2;$APP.wK={};$APP.Us(SL,$APP.B([function(a){var b=$APP.H(a);b=$APP.E.j(b,$APP.tD);a=$APP.E.j(a,b);var c=$APP.H(a);a=$APP.E.j(c,$APP.WA);var d=$APP.E.j(c,$APP.IG),e=$APP.E.j(c,$APP.Iy),f=$APP.E.j(c,$APP.pC);c=$APP.E.j(c,$APP.oH);return new $APP.h(null,6,[$APP.eB,b,$APP.cz,a,$APP.zA,d,$APP.yD,e,$APP.TB,f,$APP.hB,$APP.Ru(c)],null)}]));$APP.k(localStorage.getItem("user-avatar"))||localStorage.setItem("user-avatar","knight");$APP.Le();
}).call(this);