(function(){
'use strict';var RH,SH,qI,tI,vI,dJ,VI,ZH,bJ,yI,lI,PI,uI,ZI,hI,kI,mI,fJ,bI,LI,gJ,QI,hJ,NI,YH,cJ,cI,oI,iJ,OI,VH,YI,jJ,UH,xI,kJ,lJ,KI,aJ,TI,$I,eI,wI,XI,MI,HI,DI,WH,RI,pI,FI,mJ,JI,nJ,AI,oJ,$H,pJ,sI,GI,qJ,zI,rJ,SI,EI,iI,BI,sJ,WI,CI,XH,fI,nI,tJ,jI,uJ,vJ,gI,wJ,UI,xJ,dI,rI,aI,II;RH=function(a){var b=a.getDate(),c=a.getFullYear(),d=$APP.C.j($APP.VF,a.getMonth()+1),e=a.getHours(),k=12<e;e=k?e-12:e;a=a.getMinutes();return[$APP.m.o(d)," ",$APP.m.o(b),",",$APP.m.o(c),",",$APP.m.o(e),":",$APP.m.o(a),k?"PM":"AM"].join("")};
SH=function(a,b){$APP.Wt($APP.Ut($APP.Ut(fetch("https://hub.snapshot.org/graphql",$APP.Mo(new $APP.g(null,4,[$APP.mu,$APP.bv,$APP.Xu,$APP.Yu,$APP.Zu,new $APP.g(null,1,["content-type","application/json"],null),$APP.cv,JSON.stringify($APP.Mo(a))],null))),function(c){if($APP.h(c.ok)){c=[c,c.json];var d=c[1];return null!=d?d.call(c[0]):null}console.error("Error in response",c);throw Error(c);}),b),console.error)};
$APP.TH=function(){return new $APP.H(null,1,5,$APP.I,[new $APP.g(null,2,[$APP.Cp,function(){return $APP.P(new $APP.H(null,1,5,$APP.I,[$APP.My],null))},$APP.bB,$APP.Zh],null)],null)};
qI=function(a){return $APP.hp(new $APP.g(null,2,[$APP.wA,function(){return $APP.h(a)?($APP.P(new $APP.H(null,2,5,$APP.I,[UH,a],null)),$APP.P(new $APP.H(null,2,5,$APP.I,[VH,a],null))):null},$APP.So,function(){var b=$APP.p($APP.qr(new $APP.H(null,2,5,$APP.I,[WH,a],null)));b=$APP.E(b);var c=$APP.C.j(b,XH);$APP.C.j(b,YH);var d=$APP.E(c);b=$APP.C.j(d,$APP.Ds);var e=$APP.C.j(d,ZH);c=$APP.C.j(d,$APP.cv);var k=$APP.C.j(d,$H);d=$APP.C.j(d,YH);return $APP.uh(new $APP.H(null,5,5,$APP.I,[aI,new $APP.H(null,3,
5,$APP.I,[bI,new $APP.H(null,3,5,$APP.I,[cI,new $APP.H(null,2,5,$APP.I,[dI,b],null),new $APP.H(null,2,5,$APP.I,[eI,k],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.gs,new $APP.g(null,3,[$APP.bs,$APP.kE,$APP.bp,"justify-self-end",$APP.ks,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[$APP.Su,$APP.PC,new $APP.g(null,1,[fI,a],null)],null))}],null),"Check detail"],null)],null),new $APP.H(null,4,5,$APP.I,[gI,new $APP.g(null,1,[$APP.ks,function(){return open($APP.Ar($APP.y(["/address/",e])))}],null),
new $APP.H(null,2,5,$APP.I,[hI,["by ",$APP.Br(e)].join("")],null),new $APP.H(null,2,5,$APP.I,[$APP.vu,new $APP.H(null,2,5,$APP.I,[iI,new $APP.g(null,1,[$APP.R,"/images/share.png"],null)],null)],null)],null),new $APP.H(null,3,5,$APP.I,[jI,new $APP.H(null,2,5,$APP.I,[kI,"DESCRIPTIONS"],null),new $APP.H(null,2,5,$APP.I,[lI,c],null)],null),new $APP.H(null,5,5,$APP.I,[mI,new $APP.H(null,2,5,$APP.I,[nI,new $APP.g(null,1,[$APP.R,"/images/votes-no.png"],null)],null),"NO",new $APP.H(null,2,5,$APP.I,[oI,d],
null),new $APP.H(null,2,5,$APP.I,[pI,"VOTES"],null)],null)],null),new $APP.g(null,1,[$APP.hn,a],null))}],null))};
tI=function(){return $APP.hp(new $APP.g(null,1,[$APP.So,function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[$APP.Ou],null)));a=$APP.C.j($APP.NG,a);var b=$APP.p($APP.qr(new $APP.H(null,2,5,$APP.I,[rI,a],null)));b=$APP.E(b);b=$APP.C.j(b,$APP.Wx);return $APP.h(a)?($APP.P(new $APP.H(null,2,5,$APP.I,[$APP.tx,a],null)),new $APP.H(null,3,5,$APP.I,[$APP.cj,new $APP.H(null,1,5,$APP.I,[sI],null),$APP.nj.j(function(c){var d=$APP.E(c);c=$APP.C.j(d,$APP.ap);d=$APP.C.j(d,$APP.Ey);return new $APP.H(null,
3,5,$APP.I,[qI,c,d],null)},b)],null)):null}],null))};vI=function(a,b){return new $APP.H(null,4,5,$APP.I,[uI,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Fx,"3fr 1fr"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.rs,a],null),new $APP.H(null,2,5,$APP.I,[$APP.rs,b],null)],null)};
dJ=function(a){return $APP.hp(new $APP.g(null,2,[$APP.wA,function(){return $APP.h(a)?($APP.P(new $APP.H(null,2,5,$APP.I,[UH,a],null)),$APP.P(new $APP.H(null,2,5,$APP.I,[VH,a],null))):null},$APP.So,function(){var b=$APP.p($APP.qr(new $APP.H(null,2,5,$APP.I,[WH,a],null)));b=$APP.E(b);var c=$APP.C.j(b,XH);b=$APP.C.j(b,YH);var d=$APP.E(c),e=$APP.C.j(d,$APP.$p);c=$APP.C.j(d,$APP.cv);var k=$APP.C.j(d,$APP.Cp),l=$APP.C.j(d,YH),n=$APP.C.j(d,$H),r=$APP.C.j(d,wI),u=$APP.C.j(d,$APP.Ds),w=$APP.C.j(d,xI),z=$APP.C.j(d,
ZH);d=$APP.C.j(d,$APP.vx);var B=$APP.p($APP.qr(new $APP.H(null,2,5,$APP.I,[yI,a],null)));B=$APP.E(B);var D=$APP.C.j(B,zI);k=$APP.h(k)?RH(new Date(1E3*k)):k;e=$APP.h(e)?RH(new Date(1E3*e)):e;B=$APP.nj.j(zI,b);var G=$APP.gh(B),N=$APP.gh($APP.uj(function(X){return $APP.x.j(1,X)},B)),S=G-N;return new $APP.H(null,3,5,$APP.I,[AI,new $APP.H(null,2,5,$APP.I,[$APP.Q,"\n      .vote-desc {\n        height: calc(100% - 1.75rem);\n      }\n\n"],null),new $APP.H(null,2,5,$APP.I,[BI,new $APP.H(null,5,5,$APP.I,[CI,
new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Fx,"1fr 2.8fr"],null)],null),new $APP.H(null,4,5,$APP.I,[DI,new $APP.H(null,3,5,$APP.I,[EI,new $APP.H(null,2,5,$APP.I,[FI,u],null),new $APP.H(null,3,5,$APP.I,[$APP.By,new $APP.g(null,1,[$APP.ks,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.Su,$APP.tB],null))}],null),new $APP.H(null,2,5,$APP.I,[$APP.jC,new $APP.g(null,1,[$APP.R,"/images/eject.png"],null)],null)],null)],null),new $APP.H(null,3,5,$APP.I,[GI,new $APP.H(null,2,5,$APP.I,[HI,
["by ",$APP.Br(z)].join("")],null),new $APP.H(null,2,5,$APP.I,[II,new $APP.g(null,1,[$APP.bp,"bg-url(/images/link.png)"],null)],null)],null),new $APP.H(null,3,5,$APP.I,[JI,new $APP.H(null,3,5,$APP.I,[KI,new $APP.H(null,2,5,$APP.I,[LI,"descriptions:"],null),c],null),function(){var X=$APP.x.j(n,"active");return X?new $APP.H(null,3,5,$APP.I,[MI,new $APP.H(null,3,5,$APP.I,[$APP.Sw,new $APP.H(null,3,5,$APP.I,[NI,new $APP.g(null,2,[$APP.bp,$APP.x.j(D,1)?"bg-C71edf59c":"bg-Cffffff26 text-Cb2f4fa",$APP.ks,
function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[OI,a,1],null))}],null),$APP.t(r)],null),new $APP.H(null,3,5,$APP.I,[PI,new $APP.g(null,2,[$APP.bp,$APP.x.j(D,2)?"bg-C71edf59c":"bg-Cffffff26 text-Cb2f4fa",$APP.ks,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[OI,a,2],null))}],null),$APP.nh(r)],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.gs,new $APP.g(null,3,[$APP.bs,$APP.aF,$APP.bp,"text-white",$APP.ks,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[QI,a,D],null))}],null),"VOTE"],
null)],null):X}()],null)],null),new $APP.H(null,8,5,$APP.I,[RI,new $APP.H(null,2,5,$APP.I,[SI,"MESSAGE"],null),new $APP.H(null,10,5,$APP.I,[TI,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Fx,"max-content 1fr"],null)],null),new $APP.H(null,2,5,$APP.I,[UI,"IPFS"],null),new $APP.H(null,2,5,$APP.I,[VI,w],null),new $APP.H(null,2,5,$APP.I,[UI,"Start date"],null),new $APP.H(null,2,5,$APP.I,[VI,k],null),new $APP.H(null,2,5,$APP.I,[UI,"End date"],null),new $APP.H(null,2,5,$APP.I,[VI,e],null),new $APP.H(null,
2,5,$APP.I,[UI,"Snapshot"],null),new $APP.H(null,2,5,$APP.I,[VI,d],null)],null),new $APP.H(null,2,5,$APP.I,[WI,"THE CURRENT RESULT"],null),new $APP.H(null,4,5,$APP.I,[XI,new $APP.H(null,2,5,$APP.I,[$APP.rs,$APP.t(r)],null),function(){var X=0<G;return X?(X=N>S)?new $APP.H(null,2,5,$APP.I,[$APP.rs,"The current result"],null):X:X}(),function(){var X=0<G;return X?(X=N<S)?new $APP.H(null,2,5,$APP.I,[$APP.rs,[$APP.m.o(N),1<N?" Votes ":" Vote ",0<G?$APP.m.o(N/G*100):"0","%"].join("")],null):X:X}()],null),
new $APP.H(null,2,5,$APP.I,[YI,new $APP.H(null,2,5,$APP.I,[ZI,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Xr,0<G?[$APP.m.o(N/G*100),"%"].join(""):0],null)],null)],null)],null),new $APP.H(null,4,5,$APP.I,[XI,new $APP.H(null,2,5,$APP.I,[$APP.rs,$APP.nh(r)],null),function(){var X=0<G;return X?(X=S>N)?new $APP.H(null,2,5,$APP.I,[$APP.rs,"The current result"],null):X:X}(),function(){var X=0<G;return X?(X=S<N)?new $APP.H(null,2,5,$APP.I,[$APP.rs,[$APP.m.o(S),1<S?" Votes ":" Vote ",0<G?$APP.m.o(S/
G*100):"0","%"].join("")],null):X:X}()],null),new $APP.H(null,2,5,$APP.I,[$I,new $APP.H(null,2,5,$APP.I,[ZI,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Xr,0<G?["",$APP.m.o(S/G*100),"%"].join(""):0],null)],null)],null)],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.WC,new $APP.H(null,2,5,$APP.I,[aJ,["VOTE (",$APP.m.o(l),")"].join("")],null),new $APP.H(null,3,5,$APP.I,[$APP.cj,new $APP.H(null,1,5,$APP.I,[bJ],null),$APP.Aj(function(X){var da=$APP.E(X);X=$APP.C.j(da,cJ);var pa=$APP.C.j(da,xI);da=
$APP.C.j(da,zI);return new $APP.H(null,4,5,$APP.I,[vI,X,$APP.hh(r,da-1),pa],null)},b)],null)],null)],null)],null)],null)}],null))};$APP.eJ=function(a){a=$APP.E(a);a=$APP.C.j(a,$APP.Cy);a=$APP.E(a);a=$APP.C.j(a,fI);return $APP.h(a)?new $APP.H(null,2,5,$APP.I,[dJ,a],null):new $APP.H(null,1,5,$APP.I,[tI],null)};VI=$APP.K("span.justify-self-end");ZH=$APP.K("author");bJ=$APP.K("div.flex-1.guild-table-body.text-sm.overflow-auto");yI=$APP.M("fgl.app.views.guild-vote","pdata");lI=$APP.K("p.ffd.text-base");
PI=$APP.K("button.guild-font-family.text-sm.tracking-wider.rounded.px-16.py-0_5.ml-2");uI=$APP.K("div.grid.py-3.justify-items-center.border-b-1px.border-solid.border-C79c5da");ZI=$APP.K("div.absolute.h-1_5.rounded-l-full.bg-C96a1ae");hI=$APP.K("span.block.mr-2");kI=$APP.K("h3.text-xl");mI=$APP.K("div.flexrr.justify-end.mt-2");fJ=$APP.M("fgl.app.snapshot","set");bI=$APP.K("div.flexrr.justify-between");LI=$APP.K("span.uppercase.pr-2");gJ=$APP.K("domain");QI=$APP.M("fgl.app.views.guild-vote","vote");
hJ=$APP.K("variables");NI=$APP.K("button.guild-font-family.text-sm.tracking-wider.rounded.px-16.py-0_5");YH=$APP.K("votes");cJ=$APP.K("voter");cI=$APP.K("div.flexrr.items-center");oI=$APP.K("span.text-Cd6d6d6.mx-1");iJ=$APP.K("operationName");OI=$APP.M("fgl.app.views.guild-vote","choice");VH=$APP.M("fgl.app.snapshot","votes");YI=$APP.K("div.relative.w-full.h-1_5.rounded-l-full.bg-C00000033.mb-4");jJ=$APP.K("metadata");UH=$APP.M("fgl.app.snapshot","proposal");xI=$APP.K("ipfs");kJ=$APP.K("space");
lJ=$APP.K("timestamp");KI=$APP.K("div.vote-desc.overflow-auto.text-sm");aJ=$APP.K("div.rounded-sm.bg-C79c5da66.text-lg.text-center");TI=$APP.K("p.grid.gap-y-1");$I=$APP.K("div.relative.w-full.h-1_5.rounded-l-full.bg-C00000033");eI=$APP.K("div.bg-Ced8e28.px-12.rounded-md.text-base.capitalize");wI=$APP.K("choices");XI=$APP.K("p.flex.justify-between.mb-1_5");MI=$APP.K("div.mt-1.flexb");HI=$APP.K("span.align-middle");DI=$APP.K("div.col-span-2");WH=$APP.M("fgl.app.views.guild-vote","data");RI=$APP.K("div.text-xs");
pI=$APP.K("span.text-Cd6d6d6");FI=$APP.K("p.guild-font-family.text-2xl.uppercase.tracking-wider");mJ=$APP.K("from");JI=$APP.K("div.bg-C81c6dd1a.rounded-sm.p-3.mt-2.text-Cd6d6d6.h-48");nJ=$APP.K("author_in");AI=$APP.K("div.py-6.px-8");oJ=$APP.K("orderDirection");$H=$APP.K("state");pJ=$APP.K("Vote");sI=$APP.K("div.overflow-y-auto");GI=$APP.K("p.text-xs.text-Cd6d6d6.pl-1");qJ=$APP.K("first");zI=$APP.K("choice");rJ=$APP.K("sig");SI=$APP.K("p.guild-font-family.text-base.mb-1");EI=$APP.K("div.flexb");
iI=$APP.K("img.w-3");BI=$APP.K("div.p-3.pb-3.bg-C81c6dd1a.h-full");sJ=$APP.K("skip");WI=$APP.K("p.guild-font-family.text-base.mt-3.mb-1");CI=$APP.K("div.grid.grid-rows-2.gap-x-10.gap-y-8.h-full.pr-9");XH=$APP.K("proposal");fI=$APP.K("proposal-id");nI=$APP.K("img.w-2.mr-2");tJ=$APP.K("uint32");jI=$APP.K("div.bg-C81c6dd1a.p-4.text-Cd6d6d6.rounded-md.mt-4");uJ=$APP.K("types");vJ=$APP.K("orderBy");gI=$APP.K("div.flexrr.items-center.mt-4.text-Cd6d6d6.cursor-pointer");wJ=$APP.M("fgl.app.snapshot","proposals");
UI=$APP.K("span.text-C96a1ae");xJ=$APP.K("bytes32");dI=$APP.K("span.text-4xl.mr-4.uppercase");rI=$APP.M("fgl.app.views.guild-vote","proposals");aI=$APP.K("div.bg-C81c6dd1a.rounded-md.p-4.fb.mx-8.my-4");II=$APP.K("span.align-middle.inline-block.w-0_65rem.h-0_65rem.bg-no-repeat.bg-contain.bg-center");$APP.cd("guild-vote");$APP.TF.j(fJ,function(a,b){b=$APP.q(b);$APP.t(b);var c=$APP.v(b);b=$APP.t(c);c=$APP.v(c);return $APP.up(a,c,b)});
$APP.jr(UH,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);SH(new $APP.g(null,3,[iJ,"Proposal",hJ,new $APP.g(null,1,[$APP.ap,c],null),$APP.yE,"query Proposal($id: String!) {\nproposal(id: $id) {\nid\nipfs\ntitle\nbody\ndiscussion\nchoices\nstart\nend\nsnapshot\nstate\nauthor\ncreated\nplugins\nnetwork\ntype\nquorum\nsymbol\nstrategies {\nname\nnetwork\nparams\n}\nspace {\nid\nname\n}\nscores_state\nscores\nscores_by_strategy\nscores_total\nvotes\n}\n}"],null),function(d){return $APP.P(new $APP.H(null,
4,5,$APP.I,[fJ,$APP.bm(d.data.proposal,$APP.y([$APP.cm,!0])),UH,c],null))});return $APP.Ri});
$APP.jr(wJ,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);SH(new $APP.g(null,3,[iJ,"Proposals",hJ,new $APP.g(null,5,[qJ,6,sJ,0,kJ,$APP.h(c)?c:"test1234567.eth",$H,"all",nJ,$APP.F],null),$APP.yE,"query Proposals($first: Int!, $skip: Int!, $state: String!, $space: String, $space_in: [String], $author_in: [String]) {\nproposals(\nfirst: $first\nskip: $skip\nwhere: {space: $space, state: $state, space_in: $space_in, author_in: $author_in}\n) {\nid\nipfs\ntitle\nbody\nstart\nend\nstate\nauthor\ncreated\nchoices\nspace {\nid\nname\nmembers\navatar\nsymbol\n}\nscores_state\nscores_total\nscores\nvotes\nquorum\nsymbol\n}\n}"],null),
function(d){return $APP.P(new $APP.H(null,4,5,$APP.I,[fJ,$APP.bm(d.data.proposals,$APP.y([$APP.cm,!0])),wJ,$APP.h(c)?c:"test1234567.eth"],null))});return $APP.Ri});
$APP.jr(VH,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);SH(new $APP.g(null,3,[iJ,"Votes",hJ,new $APP.g(null,5,[$APP.ap,c,vJ,"vp",oJ,"desc",qJ,1,cJ,""],null),$APP.yE,"query Votes($id: String!, $first: Int, $skip: Int, $orderBy: String, $orderDirection: OrderDirection, $voter: String) {\nvotes(\nfirst: $first\nskip: $skip\nwhere: {proposal: $id, vp_gt: 0, voter: $voter}\norderBy: $orderBy\norderDirection: $orderDirection\n) {\nipfs\nvoter\nchoice\nvp\nvp_by_strategy\n}\n}"],null),function(d){return $APP.P(new $APP.H(null,
4,5,$APP.I,[fJ,$APP.bm(d.data.votes,$APP.y([$APP.cm,!0])),VH,c],null))});return $APP.Ri});$APP.yJ={};$APP.or(WH,$APP.y([function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);b=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[UH,c],null));a=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[VH,c],null));return new $APP.g(null,2,[XH,b,YH,a],null)}]));$APP.or(rI,$APP.y([function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);a=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[$APP.tx,b],null));return new $APP.g(null,1,[$APP.Wx,a],null)}]));
$APP.TF.j(OI,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);b=$APP.A(b,2,null);return $APP.up(a,new $APP.H(null,2,5,$APP.I,[OI,c],null),b)});$APP.or(yI,$APP.y([function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);var c=$APP.E(a),d=$APP.C.j(c,OI);c=$APP.C.j(c,$APP.Gu);a=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[c,$APP.Ou],null));return new $APP.g(null,3,[zI,$APP.C.A(d,b,1),$APP.gC,a,$APP.xy,c],null)}]));
$APP.jr(QI,function(a,b){a=$APP.E(a);a=$APP.C.j(a,$APP.cr);$APP.A(b,0,null);var c=$APP.A(b,1,null);b=$APP.A(b,2,null);a=$APP.E(a);var d=$APP.C.j(a,$APP.tu),e=$APP.C.j(a,$APP.Gu),k=new $APP.g(null,2,[$APP.O,"snapshot",$APP.vw,"0.1.4"],null),l=new $APP.g(null,1,[pJ,new $APP.H(null,6,5,$APP.I,[new $APP.g(null,2,[$APP.O,mJ,$APP.T,$APP.bu],null),new $APP.g(null,2,[$APP.O,kJ,$APP.T,$APP.qw],null),new $APP.g(null,2,[$APP.O,lJ,$APP.T,$APP.yD],null),new $APP.g(null,2,[$APP.O,XH,$APP.T,xJ],null),new $APP.g(null,
2,[$APP.O,zI,$APP.T,tJ],null),new $APP.g(null,2,[$APP.O,jJ,$APP.T,$APP.qw],null)],null)],null),n=new $APP.g(null,7,[kJ,"test1234567.eth",mJ,e,$APP.T,"single-choice",zI,b,lJ,parseInt((new Date).getTime()/1E3),XH,c,jJ,"{}"],null);$APP.iu($APP.St(null),function(){return $APP.iu($APP.St($APP.Cs()),function(){return $APP.iu($APP.St($APP.Wt(function(){var r=[d,d.getSigner];var u=r[1];r=null!=u?u.call(r[0]):null;r=[r,r._signTypedData];u=r[1];return null!=u?u.call(r[0],$APP.Mo(k),$APP.Mo(l),$APP.Mo(n)):null}(),
function(){return $APP.Fs(new $APP.g(null,2,[$APP.Ds,"Typed Sign Failed",$APP.xs,"User rejected typed sign in wallet"],null))})),function(r){return $APP.iu($APP.St($APP.Wt($APP.Ut(fetch("https://hub.snapshot.org/api/msg",new $APP.g(null,4,[$APP.mu,$APP.bv,$APP.Xu,$APP.Yu,$APP.Zu,new $APP.g(null,1,["content-type","application/json"],null),$APP.cv,JSON.stringify($APP.Mo(new $APP.g(null,3,[$APP.bu,e,rJ,r,$APP.rw,new $APP.g(null,3,[gJ,k,uJ,l,$APP.Vx,n],null)],null)))],null)),$APP.Vu),function(u){return $APP.P(new $APP.H(null,
7,5,$APP.I,[$APP.ls,$APP.vs,!0,$APP.bz,!0,$APP.xs,new $APP.H(null,5,5,$APP.I,[$APP.os,new $APP.H(null,2,5,$APP.I,[$APP.rs,"Message signed"],null),new $APP.H(null,1,5,$APP.I,[$APP.ss],null),new $APP.H(null,2,5,$APP.I,[$APP.rs,"Failed to create proposal, please try again"],null),new $APP.H(null,2,5,$APP.I,[$APP.rs,u.message],null)],null)],null))})),function(u){return $APP.iu($APP.St(null),function(){if($APP.h(u)){$APP.P(new $APP.H(null,2,5,$APP.I,[VH,c],null));var w=$APP.P(new $APP.H(null,7,5,$APP.I,
[$APP.ls,$APP.vs,!0,$APP.bz,!0,$APP.xs,new $APP.H(null,4,5,$APP.I,[$APP.os,new $APP.H(null,2,5,$APP.I,[$APP.rs,"Message signed"],null),new $APP.H(null,1,5,$APP.I,[$APP.ss],null),new $APP.H(null,2,5,$APP.I,[$APP.rs,"Vote created"],null)],null)],null))}else w=null;return $APP.St(w)})})})})});return $APP.Ri});$APP.Je();
}).call(this);