(function(){
'use strict';var BN,CN,DN,EN,HN,JN,LN,VN,YN;BN=function(a){this.Sa=a;this.F=32769;this.P=0};CN=function(){return new BN($APP.nj(0))};DN=function(a){switch(arguments.length){case 0:return CN();case 1:return new BN($APP.nj(arguments[0]));default:throw Error(["Invalid arity: ",$APP.m.o(arguments.length)].join(""));}};EN=function(a,b,c){var d=CN?CN():DN.call(null);return $APP.cf.A(function(e,k){var l=d.D?d.D():d.call(null);return a.A?a.A(e,l,k):a.call(null,e,l,k)},b,c)};
$APP.FN=function(){return new $APP.H(null,1,5,$APP.I,[new $APP.g(null,2,[$APP.tp,function(){$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.Vy],null));$APP.P(new $APP.H(null,2,5,$APP.I,[$APP.BE,!0],null));$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.eC],null));return $APP.P(new $APP.H(null,1,5,$APP.I,[$APP.kA],null))},$APP.oB,$APP.$h],null)],null)};
HN=function(a,b){return $APP.Zo(new $APP.g(null,2,[$APP.HA,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.nw,b],null))},$APP.Jo,function(){var c=$APP.p($APP.hr(new $APP.H(null,2,5,$APP.I,[$APP.nw,b],null)));return $APP.vh(new $APP.H(null,5,5,$APP.I,[GN,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Ox,"1fr 3fr 1fr"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,"Elder"],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,b],null),new $APP.H(null,2,5,$APP.I,[$APP.wG,c],null)],null),new $APP.g(null,
1,[$APP.Zm,a],null))}],null))};JN=function(a){return new $APP.H(null,2,5,$APP.I,[IN,new $APP.g(null,1,[$APP.R,a],null)],null)};
LN=function(){var a=$APP.p($APP.hr(new $APP.H(null,1,5,$APP.I,[KN],null)));return new $APP.H(null,3,5,$APP.I,[$APP.fH,new $APP.g(null,2,[$APP.es,"1.5rem",$APP.YC,new $APP.H(null,2,5,$APP.I,[$APP.sy,"Do not remind me next time"],null)],null),new $APP.g(null,3,[$APP.To,"flex flex-row cs1 ce2 rs1 re2 justify-self-start items-center",$APP.CD,function(b){return $APP.P(new $APP.H(null,2,5,$APP.I,[KN,b],null))},$APP.BD,a],null)],null)};
VN=function(){function a(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.SE,new $APP.g(null,3,[$APP.uu,$APP.pz,$APP.Ls,"Leave Kingdom",$APP.xu,function(){$APP.Is();return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.BE,!0],null))}],null)],null))}function b(){return $APP.h(l)?localStorage.setItem("leave-checked",1):localStorage.removeItem("leave-checked")}var c=$APP.p($APP.hr(new $APP.H(null,1,5,$APP.I,[MN],null))),d=$APP.E(c);c=$APP.C.j(d,NN);var e=$APP.C.j(d,$APP.Nz),k=$APP.C.j(d,$APP.ez);d=$APP.C.j(d,
ON);var l=$APP.p($APP.hr(new $APP.H(null,1,5,$APP.I,[KN],null)));return new $APP.H(null,3,5,$APP.I,[PN,new $APP.H(null,2,5,$APP.I,[JN,"/images/guild-avatar.png"],null),new $APP.H(null,6,5,$APP.I,[QN,new $APP.H(null,3,5,$APP.I,[RN,new $APP.H(null,2,5,$APP.I,[SN,c],null),new $APP.H(null,3,5,$APP.I,[$APP.os,new $APP.g(null,3,[$APP.js,$APP.yE,$APP.To,"text-base ml-12",$APP.ss,function(){return $APP.h(localStorage.getItem("leave-checked"))?a():$APP.P(new $APP.H(null,9,5,$APP.I,[$APP.ts,$APP.Ds,!0,$APP.Ls,
"",$APP.Fs,new $APP.H(null,4,5,$APP.I,[$APP.HB,new $APP.H(null,2,5,$APP.I,[$APP.gC,"Notice: Since you are trying to leave your current Kingdom, 10% of your Glony will be charged as handling fee. And 24h cool-down will be applied. Click Confirm to proceed."],null),new $APP.H(null,1,5,$APP.I,[$APP.As],null),new $APP.H(null,1,5,$APP.I,[LN],null)],null),$APP.Gs,new $APP.H(null,3,5,$APP.I,[$APP.HB,new $APP.H(null,3,5,$APP.I,[$APP.os,new $APP.g(null,3,[$APP.js,$APP.oF,$APP.ss,$APP.Cu.j(a,b),$APP.To,"mr-8"],
null),"Confirm"],null),new $APP.H(null,3,5,$APP.I,[$APP.os,new $APP.g(null,2,[$APP.js,$APP.Hs,$APP.ss,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[$APP.ts,$APP.us,!0],null))}],null),"Cancel"],null)],null)],null))}],null),"Leave My Kingdom"],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.zs,new $APP.H(null,2,5,$APP.I,[$APP.zs,e],null),new $APP.H(null,2,5,$APP.I,[TN,"/ Members"],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.zs,new $APP.H(null,2,5,$APP.I,[$APP.zs,["No.",$APP.m.o(k)].join("")],
null),new $APP.H(null,2,5,$APP.I,[TN,"/ Rank"],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.zs,new $APP.H(null,2,5,$APP.I,[$APP.zs,"XXX"],null),new $APP.H(null,2,5,$APP.I,[TN,"/ Locked"],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.zs,new $APP.H(null,2,5,$APP.I,[UN,$APP.rl(d)],null),new $APP.H(null,2,5,$APP.I,[TN,"/ Your Role"],null)],null)],null)],null)};
YN=function(){var a=$APP.p($APP.hr(new $APP.H(null,1,5,$APP.I,[MN],null)));a=$APP.E(a);a=$APP.C.j(a,$APP.Tu);return new $APP.H(null,4,5,$APP.I,[WN,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.cs,"calc(100% - 180px - 3.5rem)"],null)],null),new $APP.H(null,2,5,$APP.I,[XN,"Member status"],null),new $APP.H(null,4,5,$APP.I,[$APP.Ew,new $APP.g(null,1,[$APP.Q,new $APP.g(null,3,[$APP.cs,"calc(100% - 2.25rem)",$APP.rA,"2px ridge #50929e33",$APP.Ar,"linear-gradient(\n    rgba(163, 218, 226, 0.1),\n    rgba(163, 218, 226, 0.05)\n  )"],
null)],null),new $APP.H(null,5,5,$APP.I,[$APP.iE,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Ox,"1fr 3fr 1fr"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,"ROLE"],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,"ADDRESS"],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,"sGLORY LOCKED"],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.ej,new $APP.H(null,2,5,$APP.I,[$APP.ZE,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.cs,"calc(100% - 1.625rem)"],null)],null)],null),$APP.hj(function(b,c){return new $APP.H(null,
3,5,$APP.I,[HN,b,c],null)},a)],null)],null)],null)};$APP.ZN=function(){return new $APP.H(null,4,5,$APP.I,[$APP.$w,new $APP.H(null,1,5,$APP.I,[VN],null),new $APP.H(null,1,5,$APP.I,[$APP.AH],null),new $APP.H(null,1,5,$APP.I,[YN],null)],null)};$APP.f=BN.prototype;$APP.f.Ra=function(){return $APP.p(this.Sa)};
$APP.f.call=function(a){switch(arguments.length-1){case 0:return this.D();case 1:return this.o(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.o(arguments.length-1)].join(""));}};$APP.f.apply=function(a,b){return this.call.apply(this,[this].concat($APP.bf(b)))};$APP.f.D=function(){var a=$APP.p(this.Sa);$APP.rg(this.Sa,$APP.p(this.Sa)+1);return a};$APP.f.o=function(a){var b=$APP.p(this.Sa);$APP.rg(this.Sa,$APP.p(this.Sa)+a);return b};
$APP.f.j=function(a,b){a=a instanceof $APP.qi?a.ka:null;switch(a){case "add":return $APP.rg(this.Sa,$APP.p(this.Sa)+b),null;case "set":return $APP.rg(this.Sa,b),null;case "set\x3d":case "set-get":return $APP.rg(this.Sa,b);case "\x3dset":case "get-set":return a=$APP.p(this.Sa),$APP.rg(this.Sa,b),a;case "\x3d+":case "get-add":return a=$APP.p(this.Sa),$APP.rg(this.Sa,$APP.p(this.Sa)+b),a;case "+\x3d":case "add-get":return $APP.rg(this.Sa,$APP.p(this.Sa)+b);default:throw Error(["No matching clause: ",
$APP.m.o(a)].join(""));}};
var ON=$APP.K("role"),NN=$APP.K("kname"),PN=$APP.K("div.flex.pt-9.pb-4.pl-11"),KN=$APP.M("fgl.app.views.guild-basic","leave-checked"),TN=$APP.K("span.text-xl.text-C74bfcee6"),UN=$APP.K("span.capitalize"),IN=$APP.K("img.w-36.mr-12"),MN=$APP.M("fgl.app.views.guild-basic","data"),WN=$APP.K("div.px-6.py-4"),$N=$APP.K("elder"),XN=$APP.K("div.text-xl.mb-2"),RN=$APP.K("div.flexrr.col-span-full"),QN=$APP.K("div.grid.grid-cols-3.text-3xl.gap-x-8.items-center"),aO=$APP.K("senator"),SN=$APP.K("span.text-4xl.col-span-full"),
GN=$APP.K("div.grid.justify-items-center.pb-1.border-b.border-C79c5da.pt-1_125rem.fp.font-bold");$APP.cd("guild-basic");$APP.bO={};
$APP.fr(MN,$APP.y([function(a,b){$APP.A(b,0,null);b=$APP.E(a);b=$APP.C.j(b,$APP.Ou);var c=$APP.C.j(a,$APP.Xu);a=$APP.Hj(a,new $APP.H(null,2,5,$APP.I,[b,$APP.Wu],null),0);var d=EN(function(n,r,v){v=$APP.A(v,0,null);return $APP.J.A(n,v,r+1)},$APP.Ti,$APP.Th($APP.oh,function(n,r){try{return n.gt(r)}catch(v){if(v instanceof Error)return!0;throw v;}},$APP.pj.j(function(n){var r=$APP.A(n,0,null);n=$APP.A(n,1,null);return new $APP.H(null,2,5,$APP.I,[r,$APP.LE.o($APP.h(n)?n:$APP.Jr.BigNumber.from(1))],null)},
c)));c=$APP.C.j(c,a);var e=$APP.E(c);c=$APP.C.j(e,$APP.Tu);var k=$APP.C.j(e,$APP.Uu),l=$APP.C.j(e,$APP.Nz);e=$APP.C.j(e,$APP.N);k=$APP.h($APP.cj($APP.nl([b]),c))?$N:$APP.h($APP.cj($APP.nl([b]),k))?aO:$APP.eF;return new $APP.g(null,6,[$APP.Gy,b,$APP.ez,$APP.C.j(d,a),ON,k,NN,e,$APP.Tu,c,$APP.Nz,function(){var n=$APP.h(l)?l.toNumber():l;return $APP.h(n)?n:0}()],null)}]));$APP.BF.j(KN,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return $APP.J.A(a,KN,b)});
$APP.fr(KN,$APP.y([function(a){return $APP.C.A(a,KN,!1)}]));$APP.Je();
}).call(this);