(function(){
'use strict';var fI,gI,FI,II,KI,sJ,jJ,nI,qJ,NI,AI,dJ,JI,nJ,wI,zI,BI,uJ,qI,$I,vJ,eJ,wJ,bJ,mI,rJ,rI,DI,xJ,cJ,jI,mJ,yJ,iI,MI,zJ,AJ,ZI,pJ,hJ,oJ,tI,LI,lJ,aJ,WI,SI,kI,fJ,EI,UI,BJ,YI,CJ,PI,DJ,oI,EJ,HI,VI,FJ,OI,GJ,gJ,TI,xI,QI,HJ,kJ,RI,lI,uI,CI,IJ,yI,JJ,KJ,vI,LJ,iJ,MJ,sI,GI,pI,XI;fI=function(a){var b=a.getDate(),c=a.getFullYear(),d=$APP.C.j($APP.iG,a.getMonth()+1),e=a.getHours(),k=12<e;e=k?e-12:e;a=a.getMinutes();return[$APP.m.o(d)," ",$APP.m.o(b),",",$APP.m.o(c),",",$APP.m.o(e),":",$APP.m.o(a),k?"PM":"AM"].join("")};
gI=function(a,b){$APP.du($APP.bu($APP.bu(fetch("https://hub.snapshot.org/graphql",$APP.Do(new $APP.g(null,4,[$APP.uu,$APP.jv,$APP.ev,$APP.fv,$APP.gv,new $APP.g(null,1,["content-type","application/json"],null),$APP.kv,JSON.stringify($APP.Do(a))],null))),function(c){if($APP.h(c.ok)){c=[c,c.json];var d=c[1];return null!=d?d.call(c[0]):null}console.error("Error in response",c);throw Error(c);}),b),console.error)};
$APP.hI=function(){return new $APP.H(null,1,5,$APP.I,[new $APP.g(null,2,[$APP.tp,function(){return $APP.P(new $APP.H(null,1,5,$APP.I,[$APP.Vy],null))},$APP.oB,$APP.$h],null)],null)};
FI=function(a){return $APP.Zo(new $APP.g(null,2,[$APP.HA,function(){return $APP.h(a)?($APP.P(new $APP.H(null,2,5,$APP.I,[iI,a],null)),$APP.P(new $APP.H(null,2,5,$APP.I,[jI,a],null))):null},$APP.Jo,function(){var b=$APP.p($APP.hr(new $APP.H(null,2,5,$APP.I,[kI,a],null)));b=$APP.E(b);var c=$APP.C.j(b,lI);$APP.C.j(b,mI);var d=$APP.E(c);b=$APP.C.j(d,$APP.Ls);var e=$APP.C.j(d,nI);c=$APP.C.j(d,$APP.kv);var k=$APP.C.j(d,oI);d=$APP.C.j(d,mI);return $APP.vh(new $APP.H(null,5,5,$APP.I,[pI,new $APP.H(null,3,
5,$APP.I,[qI,new $APP.H(null,3,5,$APP.I,[rI,new $APP.H(null,2,5,$APP.I,[sI,b],null),new $APP.H(null,2,5,$APP.I,[tI,k],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.os,new $APP.g(null,3,[$APP.js,$APP.yE,$APP.To,"justify-self-end",$APP.ss,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[$APP.$u,$APP.bD,new $APP.g(null,1,[uI,a],null)],null))}],null),"Check detail"],null)],null),new $APP.H(null,4,5,$APP.I,[vI,new $APP.g(null,1,[$APP.ss,function(){return open($APP.Hr($APP.y(["/address/",e])))}],null),
new $APP.H(null,2,5,$APP.I,[wI,["by ",$APP.Ir(e)].join("")],null),new $APP.H(null,2,5,$APP.I,[$APP.Du,new $APP.H(null,2,5,$APP.I,[xI,new $APP.g(null,1,[$APP.R,"/images/share.png"],null)],null)],null)],null),new $APP.H(null,3,5,$APP.I,[yI,new $APP.H(null,2,5,$APP.I,[zI,"DESCRIPTIONS"],null),new $APP.H(null,2,5,$APP.I,[AI,c],null)],null),new $APP.H(null,5,5,$APP.I,[BI,new $APP.H(null,2,5,$APP.I,[CI,new $APP.g(null,1,[$APP.R,"/images/votes-no.png"],null)],null),"NO",new $APP.H(null,2,5,$APP.I,[DI,d],
null),new $APP.H(null,2,5,$APP.I,[EI,"VOTES"],null)],null)],null),new $APP.g(null,1,[$APP.Zm,a],null))}],null))};
II=function(){return $APP.Zo(new $APP.g(null,1,[$APP.Jo,function(){var a=$APP.p($APP.hr(new $APP.H(null,1,5,$APP.I,[$APP.Wu],null)));a=$APP.C.j($APP.bH,a);var b=$APP.p($APP.hr(new $APP.H(null,2,5,$APP.I,[GI,a],null)));b=$APP.E(b);b=$APP.C.j(b,$APP.ey);return $APP.h(a)?($APP.P(new $APP.H(null,2,5,$APP.I,[$APP.Cx,a],null)),new $APP.H(null,3,5,$APP.I,[$APP.ej,new $APP.H(null,1,5,$APP.I,[HI],null),$APP.pj.j(function(c){var d=$APP.E(c);c=$APP.C.j(d,$APP.So);d=$APP.C.j(d,$APP.Ny);return new $APP.H(null,
3,5,$APP.I,[FI,c,d],null)},b)],null)):null}],null))};KI=function(a,b){return new $APP.H(null,4,5,$APP.I,[JI,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Ox,"3fr 1fr"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,a],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,b],null)],null)};
sJ=function(a){return $APP.Zo(new $APP.g(null,2,[$APP.HA,function(){return $APP.h(a)?($APP.P(new $APP.H(null,2,5,$APP.I,[iI,a],null)),$APP.P(new $APP.H(null,2,5,$APP.I,[jI,a],null))):null},$APP.Jo,function(){var b=$APP.p($APP.hr(new $APP.H(null,2,5,$APP.I,[kI,a],null)));b=$APP.E(b);var c=$APP.C.j(b,lI);b=$APP.C.j(b,mI);var d=$APP.E(c),e=$APP.C.j(d,$APP.Rp);c=$APP.C.j(d,$APP.kv);var k=$APP.C.j(d,$APP.tp),l=$APP.C.j(d,mI),n=$APP.C.j(d,oI),r=$APP.C.j(d,LI),v=$APP.C.j(d,$APP.Ls),w=$APP.C.j(d,MI),z=$APP.C.j(d,
nI);d=$APP.C.j(d,$APP.Ex);var B=$APP.p($APP.hr(new $APP.H(null,2,5,$APP.I,[NI,a],null)));B=$APP.E(B);var D=$APP.C.j(B,OI);k=$APP.h(k)?fI(new Date(1E3*k)):k;e=$APP.h(e)?fI(new Date(1E3*e)):e;B=$APP.pj.j(OI,b);var G=$APP.hh(B),O=$APP.hh($APP.wj(function(Y){return $APP.x.j(1,Y)},B)),S=G-O;return new $APP.H(null,3,5,$APP.I,[PI,new $APP.H(null,2,5,$APP.I,[$APP.Q,"\n      .vote-desc {\n        height: calc(100% - 1.75rem);\n      }\n\n"],null),new $APP.H(null,2,5,$APP.I,[QI,new $APP.H(null,5,5,$APP.I,[RI,
new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Ox,"1fr 2.8fr"],null)],null),new $APP.H(null,4,5,$APP.I,[SI,new $APP.H(null,3,5,$APP.I,[TI,new $APP.H(null,2,5,$APP.I,[UI,v],null),new $APP.H(null,3,5,$APP.I,[$APP.Ky,new $APP.g(null,1,[$APP.ss,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.$u,$APP.FB],null))}],null),new $APP.H(null,2,5,$APP.I,[$APP.wC,new $APP.g(null,1,[$APP.R,"/images/eject.png"],null)],null)],null)],null),new $APP.H(null,3,5,$APP.I,[VI,new $APP.H(null,2,5,$APP.I,[WI,
["by ",$APP.Ir(z)].join("")],null),new $APP.H(null,2,5,$APP.I,[XI,new $APP.g(null,1,[$APP.To,"bg-url(/images/link.png)"],null)],null)],null),new $APP.H(null,3,5,$APP.I,[YI,new $APP.H(null,3,5,$APP.I,[ZI,new $APP.H(null,2,5,$APP.I,[$I,"descriptions:"],null),c],null),function(){var Y=$APP.x.j(n,"active");return Y?new $APP.H(null,3,5,$APP.I,[aJ,new $APP.H(null,3,5,$APP.I,[$APP.$w,new $APP.H(null,3,5,$APP.I,[bJ,new $APP.g(null,2,[$APP.To,$APP.x.j(D,1)?"bg-C71edf59c":"bg-Cffffff26 text-Cb2f4fa",$APP.ss,
function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[cJ,a,1],null))}],null),$APP.t(r)],null),new $APP.H(null,3,5,$APP.I,[dJ,new $APP.g(null,2,[$APP.To,$APP.x.j(D,2)?"bg-C71edf59c":"bg-Cffffff26 text-Cb2f4fa",$APP.ss,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[cJ,a,2],null))}],null),$APP.oh(r)],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.os,new $APP.g(null,3,[$APP.js,$APP.oF,$APP.To,"text-white",$APP.ss,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[eJ,a,D],null))}],null),"VOTE"],
null)],null):Y}()],null)],null),new $APP.H(null,8,5,$APP.I,[fJ,new $APP.H(null,2,5,$APP.I,[gJ,"MESSAGE"],null),new $APP.H(null,10,5,$APP.I,[hJ,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Ox,"max-content 1fr"],null)],null),new $APP.H(null,2,5,$APP.I,[iJ,"IPFS"],null),new $APP.H(null,2,5,$APP.I,[jJ,w],null),new $APP.H(null,2,5,$APP.I,[iJ,"Start date"],null),new $APP.H(null,2,5,$APP.I,[jJ,k],null),new $APP.H(null,2,5,$APP.I,[iJ,"End date"],null),new $APP.H(null,2,5,$APP.I,[jJ,e],null),new $APP.H(null,
2,5,$APP.I,[iJ,"Snapshot"],null),new $APP.H(null,2,5,$APP.I,[jJ,d],null)],null),new $APP.H(null,2,5,$APP.I,[kJ,"THE CURRENT RESULT"],null),new $APP.H(null,4,5,$APP.I,[lJ,new $APP.H(null,2,5,$APP.I,[$APP.zs,$APP.t(r)],null),function(){var Y=0<G;return Y?(Y=O>S)?new $APP.H(null,2,5,$APP.I,[$APP.zs,"The current result"],null):Y:Y}(),function(){var Y=0<G;return Y?(Y=O<S)?new $APP.H(null,2,5,$APP.I,[$APP.zs,[$APP.m.o(O),1<O?" Votes ":" Vote ",0<G?$APP.m.o(O/G*100):"0","%"].join("")],null):Y:Y}()],null),
new $APP.H(null,2,5,$APP.I,[mJ,new $APP.H(null,2,5,$APP.I,[nJ,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.es,0<G?[$APP.m.o(O/G*100),"%"].join(""):0],null)],null)],null)],null),new $APP.H(null,4,5,$APP.I,[lJ,new $APP.H(null,2,5,$APP.I,[$APP.zs,$APP.oh(r)],null),function(){var Y=0<G;return Y?(Y=S>O)?new $APP.H(null,2,5,$APP.I,[$APP.zs,"The current result"],null):Y:Y}(),function(){var Y=0<G;return Y?(Y=S<O)?new $APP.H(null,2,5,$APP.I,[$APP.zs,[$APP.m.o(S),1<S?" Votes ":" Vote ",0<G?$APP.m.o(S/
G*100):"0","%"].join("")],null):Y:Y}()],null),new $APP.H(null,2,5,$APP.I,[oJ,new $APP.H(null,2,5,$APP.I,[nJ,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.es,0<G?["",$APP.m.o(S/G*100),"%"].join(""):0],null)],null)],null)],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.hD,new $APP.H(null,2,5,$APP.I,[pJ,["VOTE (",$APP.m.o(l),")"].join("")],null),new $APP.H(null,3,5,$APP.I,[$APP.ej,new $APP.H(null,1,5,$APP.I,[qJ],null),$APP.Cj(function(Y){var da=$APP.E(Y);Y=$APP.C.j(da,rJ);var pa=$APP.C.j(da,MI);da=
$APP.C.j(da,OI);return new $APP.H(null,4,5,$APP.I,[KI,Y,$APP.ih(r,da-1),pa],null)},b)],null)],null)],null)],null)],null)}],null))};$APP.tJ=function(a){a=$APP.E(a);a=$APP.C.j(a,$APP.Ly);a=$APP.E(a);a=$APP.C.j(a,uI);return $APP.h(a)?new $APP.H(null,2,5,$APP.I,[sJ,a],null):new $APP.H(null,1,5,$APP.I,[II],null)};jJ=$APP.K("span.justify-self-end");nI=$APP.K("author");qJ=$APP.K("div.flex-1.guild-table-body.text-sm.overflow-auto");NI=$APP.M("fgl.app.views.guild-vote","pdata");AI=$APP.K("p.ffd.text-base");
dJ=$APP.K("button.guild-font-family.text-sm.tracking-wider.rounded.px-16.py-0_5.ml-2");JI=$APP.K("div.grid.py-3.justify-items-center.border-b-1px.border-solid.border-C79c5da");nJ=$APP.K("div.absolute.h-1_5.rounded-l-full.bg-C96a1ae");wI=$APP.K("span.block.mr-2");zI=$APP.K("h3.text-xl");BI=$APP.K("div.flexrr.justify-end.mt-2");uJ=$APP.M("fgl.app.snapshot","set");qI=$APP.K("div.flexrr.justify-between");$I=$APP.K("span.uppercase.pr-2");vJ=$APP.K("domain");eJ=$APP.M("fgl.app.views.guild-vote","vote");
wJ=$APP.K("variables");bJ=$APP.K("button.guild-font-family.text-sm.tracking-wider.rounded.px-16.py-0_5");mI=$APP.K("votes");rJ=$APP.K("voter");rI=$APP.K("div.flexrr.items-center");DI=$APP.K("span.text-Cd6d6d6.mx-1");xJ=$APP.K("operationName");cJ=$APP.M("fgl.app.views.guild-vote","choice");jI=$APP.M("fgl.app.snapshot","votes");mJ=$APP.K("div.relative.w-full.h-1_5.rounded-l-full.bg-C00000033.mb-4");yJ=$APP.K("metadata");iI=$APP.M("fgl.app.snapshot","proposal");MI=$APP.K("ipfs");zJ=$APP.K("space");
AJ=$APP.K("timestamp");ZI=$APP.K("div.vote-desc.overflow-auto.text-sm");pJ=$APP.K("div.rounded-sm.bg-C79c5da66.text-lg.text-center");hJ=$APP.K("p.grid.gap-y-1");oJ=$APP.K("div.relative.w-full.h-1_5.rounded-l-full.bg-C00000033");tI=$APP.K("div.bg-Ced8e28.px-12.rounded-md.text-base.capitalize");LI=$APP.K("choices");lJ=$APP.K("p.flex.justify-between.mb-1_5");aJ=$APP.K("div.mt-1.flexb");WI=$APP.K("span.align-middle");SI=$APP.K("div.col-span-2");kI=$APP.M("fgl.app.views.guild-vote","data");fJ=$APP.K("div.text-xs");
EI=$APP.K("span.text-Cd6d6d6");UI=$APP.K("p.guild-font-family.text-2xl.uppercase.tracking-wider");BJ=$APP.K("from");YI=$APP.K("div.bg-C81c6dd1a.rounded-sm.p-3.mt-2.text-Cd6d6d6.h-48");CJ=$APP.K("author_in");PI=$APP.K("div.py-6.px-8");DJ=$APP.K("orderDirection");oI=$APP.K("state");EJ=$APP.K("Vote");HI=$APP.K("div.overflow-y-auto");VI=$APP.K("p.text-xs.text-Cd6d6d6.pl-1");FJ=$APP.K("first");OI=$APP.K("choice");GJ=$APP.K("sig");gJ=$APP.K("p.guild-font-family.text-base.mb-1");TI=$APP.K("div.flexb");
xI=$APP.K("img.w-3");QI=$APP.K("div.p-3.pb-3.bg-C81c6dd1a.h-full");HJ=$APP.K("skip");kJ=$APP.K("p.guild-font-family.text-base.mt-3.mb-1");RI=$APP.K("div.grid.grid-rows-2.gap-x-10.gap-y-8.h-full.pr-9");lI=$APP.K("proposal");uI=$APP.K("proposal-id");CI=$APP.K("img.w-2.mr-2");IJ=$APP.K("uint32");yI=$APP.K("div.bg-C81c6dd1a.p-4.text-Cd6d6d6.rounded-md.mt-4");JJ=$APP.K("types");KJ=$APP.K("orderBy");vI=$APP.K("div.flexrr.items-center.mt-4.text-Cd6d6d6.cursor-pointer");LJ=$APP.M("fgl.app.snapshot","proposals");
iJ=$APP.K("span.text-C96a1ae");MJ=$APP.K("bytes32");sI=$APP.K("span.text-4xl.mr-4.uppercase");GI=$APP.M("fgl.app.views.guild-vote","proposals");pI=$APP.K("div.bg-C81c6dd1a.rounded-md.p-4.fb.mx-8.my-4");XI=$APP.K("span.align-middle.inline-block.w-0_65rem.h-0_65rem.bg-no-repeat.bg-contain.bg-center");$APP.cd("guild-vote");$APP.BF.j(uJ,function(a,b){b=$APP.q(b);$APP.t(b);var c=$APP.u(b);b=$APP.t(c);c=$APP.u(c);return $APP.lp(a,c,b)});
$APP.ar(iI,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);gI(new $APP.g(null,3,[xJ,"Proposal",wJ,new $APP.g(null,1,[$APP.So,c],null),$APP.NE,"query Proposal($id: String!) {\nproposal(id: $id) {\nid\nipfs\ntitle\nbody\ndiscussion\nchoices\nstart\nend\nsnapshot\nstate\nauthor\ncreated\nplugins\nnetwork\ntype\nquorum\nsymbol\nstrategies {\nname\nnetwork\nparams\n}\nspace {\nid\nname\n}\nscores_state\nscores\nscores_by_strategy\nscores_total\nvotes\n}\n}"],null),function(d){return $APP.P(new $APP.H(null,
4,5,$APP.I,[uJ,$APP.fm(d.data.proposal,$APP.y([$APP.gm,!0])),iI,c],null))});return $APP.Ti});
$APP.ar(LJ,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);gI(new $APP.g(null,3,[xJ,"Proposals",wJ,new $APP.g(null,5,[FJ,6,HJ,0,zJ,$APP.h(c)?c:"test1234567.eth",oI,"all",CJ,$APP.F],null),$APP.NE,"query Proposals($first: Int!, $skip: Int!, $state: String!, $space: String, $space_in: [String], $author_in: [String]) {\nproposals(\nfirst: $first\nskip: $skip\nwhere: {space: $space, state: $state, space_in: $space_in, author_in: $author_in}\n) {\nid\nipfs\ntitle\nbody\nstart\nend\nstate\nauthor\ncreated\nchoices\nspace {\nid\nname\nmembers\navatar\nsymbol\n}\nscores_state\nscores_total\nscores\nvotes\nquorum\nsymbol\n}\n}"],null),
function(d){return $APP.P(new $APP.H(null,4,5,$APP.I,[uJ,$APP.fm(d.data.proposals,$APP.y([$APP.gm,!0])),LJ,$APP.h(c)?c:"test1234567.eth"],null))});return $APP.Ti});
$APP.ar(jI,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);gI(new $APP.g(null,3,[xJ,"Votes",wJ,new $APP.g(null,5,[$APP.So,c,KJ,"vp",DJ,"desc",FJ,1,rJ,""],null),$APP.NE,"query Votes($id: String!, $first: Int, $skip: Int, $orderBy: String, $orderDirection: OrderDirection, $voter: String) {\nvotes(\nfirst: $first\nskip: $skip\nwhere: {proposal: $id, vp_gt: 0, voter: $voter}\norderBy: $orderBy\norderDirection: $orderDirection\n) {\nipfs\nvoter\nchoice\nvp\nvp_by_strategy\n}\n}"],null),function(d){return $APP.P(new $APP.H(null,
4,5,$APP.I,[uJ,$APP.fm(d.data.votes,$APP.y([$APP.gm,!0])),jI,c],null))});return $APP.Ti});$APP.NJ={};$APP.fr(kI,$APP.y([function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);b=$APP.Gj(a,new $APP.H(null,2,5,$APP.I,[iI,c],null));a=$APP.Gj(a,new $APP.H(null,2,5,$APP.I,[jI,c],null));return new $APP.g(null,2,[lI,b,mI,a],null)}]));$APP.fr(GI,$APP.y([function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);a=$APP.Gj(a,new $APP.H(null,2,5,$APP.I,[$APP.Cx,b],null));return new $APP.g(null,1,[$APP.ey,a],null)}]));
$APP.BF.j(cJ,function(a,b){$APP.A(b,0,null);var c=$APP.A(b,1,null);b=$APP.A(b,2,null);return $APP.lp(a,new $APP.H(null,2,5,$APP.I,[cJ,c],null),b)});$APP.fr(NI,$APP.y([function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);var c=$APP.E(a),d=$APP.C.j(c,cJ);c=$APP.C.j(c,$APP.Ou);a=$APP.Gj(a,new $APP.H(null,2,5,$APP.I,[c,$APP.Wu],null));return new $APP.g(null,3,[OI,$APP.C.A(d,b,1),$APP.tC,a,$APP.Gy,c],null)}]));
$APP.ar(eJ,function(a,b){a=$APP.E(a);a=$APP.C.j(a,$APP.Uq);$APP.A(b,0,null);var c=$APP.A(b,1,null);b=$APP.A(b,2,null);a=$APP.E(a);var d=$APP.C.j(a,$APP.Bu),e=$APP.C.j(a,$APP.Ou),k=new $APP.g(null,2,[$APP.N,"snapshot",$APP.Dw,"0.1.4"],null),l=new $APP.g(null,1,[EJ,new $APP.H(null,6,5,$APP.I,[new $APP.g(null,2,[$APP.N,BJ,$APP.T,$APP.ju],null),new $APP.g(null,2,[$APP.N,zJ,$APP.T,$APP.yw],null),new $APP.g(null,2,[$APP.N,AJ,$APP.T,$APP.MD],null),new $APP.g(null,2,[$APP.N,lI,$APP.T,MJ],null),new $APP.g(null,
2,[$APP.N,OI,$APP.T,IJ],null),new $APP.g(null,2,[$APP.N,yJ,$APP.T,$APP.yw],null)],null)],null),n=new $APP.g(null,7,[zJ,"test1234567.eth",BJ,e,$APP.T,"single-choice",OI,b,AJ,parseInt((new Date).getTime()/1E3),lI,c,yJ,"{}"],null);$APP.qu($APP.$t(null),function(){return $APP.qu($APP.$t($APP.Ks()),function(){return $APP.qu($APP.$t($APP.du(function(){var r=[d,d.getSigner];var v=r[1];r=null!=v?v.call(r[0]):null;r=[r,r._signTypedData];v=r[1];return null!=v?v.call(r[0],$APP.Do(k),$APP.Do(l),$APP.Do(n)):null}(),
function(){return $APP.Ns(new $APP.g(null,2,[$APP.Ls,"Typed Sign Failed",$APP.Fs,"User rejected typed sign in wallet"],null))})),function(r){return $APP.qu($APP.$t($APP.du($APP.bu(fetch("https://hub.snapshot.org/api/msg",new $APP.g(null,4,[$APP.uu,$APP.jv,$APP.ev,$APP.fv,$APP.gv,new $APP.g(null,1,["content-type","application/json"],null),$APP.kv,JSON.stringify($APP.Do(new $APP.g(null,3,[$APP.ju,e,GJ,r,$APP.zw,new $APP.g(null,3,[vJ,k,JJ,l,$APP.dy,n],null)],null)))],null)),$APP.cv),function(v){return $APP.P(new $APP.H(null,
7,5,$APP.I,[$APP.ts,$APP.Ds,!0,$APP.kz,!0,$APP.Fs,new $APP.H(null,5,5,$APP.I,[$APP.ws,new $APP.H(null,2,5,$APP.I,[$APP.zs,"Message signed"],null),new $APP.H(null,1,5,$APP.I,[$APP.As],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,"Failed to create proposal, please try again"],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,v.message],null)],null)],null))})),function(v){return $APP.qu($APP.$t(null),function(){if($APP.h(v)){$APP.P(new $APP.H(null,2,5,$APP.I,[jI,c],null));var w=$APP.P(new $APP.H(null,7,5,$APP.I,
[$APP.ts,$APP.Ds,!0,$APP.kz,!0,$APP.Fs,new $APP.H(null,4,5,$APP.I,[$APP.ws,new $APP.H(null,2,5,$APP.I,[$APP.zs,"Message signed"],null),new $APP.H(null,1,5,$APP.I,[$APP.As],null),new $APP.H(null,2,5,$APP.I,[$APP.zs,"Vote created"],null)],null)],null))}else w=null;return $APP.$t(w)})})})})});return $APP.Ti});$APP.Je();
}).call(this);