(function(){
'use strict';var QJ,ZJ,dK,UJ,eK,bK,aK,YJ,NJ,PJ,OJ,WJ,cK,SJ,gK,RJ,XJ,VJ,$J,TJ;$APP.MJ=function(){return new $APP.O(null,1,5,$APP.P,[new $APP.l(null,2,[$APP.cq,function(){$APP.Zq(new $APP.O(null,2,5,$APP.P,[$APP.qD,$APP.HF.address],null));$APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.Zx],null));$APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.wC],null));return $APP.Zq(new $APP.O(null,1,5,$APP.P,[$APP.xA],null))},$APP.oA,$APP.ki],null)],null)};
QJ=function(a){var b=$APP.Uf($APP.Tr(new $APP.O(null,1,5,$APP.P,[NJ],null)));b=$APP.fj(b);b=$APP.H.j(b,$APP.Pz);return $APP.Fh(new $APP.O(null,3,5,$APP.P,[OJ,new $APP.l(null,2,[$APP.BA,function(){return $APP.Zq(new $APP.O(null,2,5,$APP.P,[PJ,a],null))},$APP.up,$APP.B.j(b,a)?"bg-C71edf59c":"bg-Cffffff26"],null),[$APP.p.o(a)," WEEKS"].join("")],null),new $APP.l(null,1,[$APP.Fn,a],null))};
ZJ=function(){var a=$APP.Uf($APP.Tr(new $APP.O(null,1,5,$APP.P,[NJ],null)));a=$APP.fj(a);var b=$APP.H.j(a,$APP.dC),c=$APP.H.j(a,$APP.zx),d=$APP.H.j(a,$APP.Zv),e=$APP.H.j(a,$APP.Pz),f=$APP.H.j(a,$APP.Hz),h=$APP.H.j(a,$APP.dz);return new $APP.O(null,10,5,$APP.P,[RJ,new $APP.O(null,4,5,$APP.P,[$APP.xx,"Amount ",new $APP.O(null,2,5,$APP.P,[$APP.WF,"2.5rem"],null),"sacrificed:"],null),new $APP.O(null,2,5,$APP.P,[$APP.Xx,new $APP.l(null,3,[$APP.Iv,function(k){return $APP.Zq(new $APP.O(null,2,5,$APP.P,[SJ,
k.target.value],null))},$APP.Ey,c,$APP.fu,new $APP.l(null,1,[$APP.ru,"inset 1px 1px #111, 1px 1px rgba(116, 191, 206, 0.2)"],null)],null)],null),new $APP.O(null,3,5,$APP.P,[TJ,"MAX:",new $APP.O(null,3,5,$APP.P,[$APP.KF,f,new $APP.l(null,1,[$APP.up,"ffd"],null)],null)],null),new $APP.O(null,2,5,$APP.P,[UJ,"Locked weeks:"],null),new $APP.O(null,5,5,$APP.P,[VJ,new $APP.O(null,2,5,$APP.P,[QJ,4],null),new $APP.O(null,2,5,$APP.P,[QJ,8],null),new $APP.O(null,2,5,$APP.P,[QJ,16],null),new $APP.O(null,2,5,
$APP.P,[QJ,32],null)],null),new $APP.O(null,2,5,$APP.P,[$APP.LF,new $APP.l(null,1,[$APP.up,"my-12"],null)],null),new $APP.O(null,2,5,$APP.P,[WJ,"Your sGOLD in return will be:"],null),new $APP.O(null,3,5,$APP.P,[$APP.BD,new $APP.O(null,2,5,$APP.P,[$APP.MF,"2.5rem"],null),new $APP.O(null,3,5,$APP.P,[$APP.KF,d,new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.CC,"40rem"],null)],null)],null)],null),new $APP.O(null,3,5,$APP.P,[$APP.uu,new $APP.l(null,3,[$APP.up,"absolute bottom-12 transform left-1/2 -translate-x-1/2 bg-Ced8e28 border-Cffd386 w-14rem text-xl",
$APP.pu,$APP.CD,$APP.BA,function(){return $APP.Zq($APP.m(h)?new $APP.O(null,2,5,$APP.P,[$APP.Ax,new $APP.l(null,3,[$APP.Jt,$APP.RB,$APP.Kt,new $APP.O(null,2,5,$APP.P,[b,e],null),$APP.Lt,function(){$APP.Zq(new $APP.O(null,2,5,$APP.P,[SJ,""],null));$APP.Zq(new $APP.O(null,1,5,$APP.P,[XJ],null));$APP.Zq(new $APP.O(null,2,5,$APP.P,[$APP.qD,$APP.HF.address],null));return $APP.Zq(new $APP.O(null,1,5,$APP.P,[YJ],null))}],null)],null):new $APP.O(null,2,5,$APP.P,[$APP.pD,new $APP.l(null,3,[$APP.Jt,$APP.my,
$APP.Kt,new $APP.O(null,2,5,$APP.P,[$APP.HF.address,"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],null),$APP.Lt,function(){return $APP.Zq(new $APP.O(null,2,5,$APP.P,[$APP.qD,$APP.HF.address],null))}],null)],null))}],null),$APP.m(h)?"SACRIFICED":"APPROVE"],null)],null)};
dK=function(){var a=$APP.Uf($APP.Tr(new $APP.O(null,1,5,$APP.P,[$J],null)));return new $APP.O(null,5,5,$APP.P,[aK,new $APP.l(null,1,[$APP.fu,new $APP.l(null,3,[$APP.Lw,"url(/images/for-glory-bg.svg)",$APP.ZC,"140%",$APP.VC,"50% 2%"],null)],null),new $APP.O(null,2,5,$APP.P,[bK,"Your $GOLD eligible to redeem"],null),new $APP.O(null,3,5,$APP.P,[cK,new $APP.O(null,2,5,$APP.P,[$APP.WF,"2.5rem"],null),$APP.KF.o(a)],null),new $APP.O(null,3,5,$APP.P,[$APP.uu,new $APP.l(null,3,[$APP.up,"absolute bottom-12 left-1/2 transform -translate-x-1/2 text-xl",
$APP.pu,$APP.FD,$APP.fu,new $APP.l(null,1,[$APP.ku,"10rem"],null)],null),"REDEEM"],null)],null)};$APP.fK=function(){return new $APP.O(null,4,5,$APP.P,[eK,new $APP.l(null,1,[$APP.fu,new $APP.l(null,1,[$APP.ax,"1fr 18rem"],null)],null),new $APP.O(null,1,5,$APP.P,[ZJ],null),new $APP.O(null,1,5,$APP.P,[dK],null)],null)};UJ=$APP.S("div.w-full.mt-6.mb-2.ffd.text-C6bc9db");eK=$APP.S("div.grid.fb");bK=$APP.S("p.mt-12.text-base.px-16.ffd");aK=$APP.S("div.relative.h-full.text-center.bg-gradient-to-b.from-transparent.to-C50929e3b.bg-no-repeat");
YJ=$APP.T("fgl.contracts.sgold","init-raw");NJ=$APP.T("fgl.app.views.guild-alter","left-data");PJ=$APP.T("fgl.app.views.guild-alter","weeks");OJ=$APP.S("button.rounded.py-1");WJ=$APP.S("div.w-full.mb-2.ffd.text-C6bc9db");cK=$APP.S("p.guild-font-family.text-4xl.mt-6.flexr");SJ=$APP.T("fgl.app.views.guild-alter","input");gK=$APP.T("fgl.app.views.guild-alter","input-str");RJ=$APP.S("div.relative.px-10");XJ=$APP.T("fgl.contracts.gold","init-raw");VJ=$APP.S("div.w-full.grid.grid-cols-4.gap-5.fb");
$J=$APP.T("fgl.app.views.guild-alter","right-data");TJ=$APP.S("div.w-full.text-right.mt-1.ffd.text-Cffffff80");$APP.hd("guild-alter");$APP.hK={};
$APP.hF.j(SJ,function(a,b){$APP.G(b,0,null);b=$APP.G(b,1,null);var c=$APP.fj(a);c=$APP.H.j(c,$APP.Oz);c=$APP.Uj(a,new $APP.O(null,2,5,$APP.P,[c,$APP.Ex],null));b=b.replace(/\.+/,".").replace(/-/,"");try{var d=module$node_modules$ethers$lib$index.utils.parseUnits(b)}catch(f){if(f instanceof Error)d=$APP.zy;else throw f;}if($APP.B.j(b,""))a=$APP.Q.B(a,SJ,module$node_modules$ethers$lib$index.BigNumber.from("0"),$APP.D([gK,""]));else if(!$APP.B.j(d,$APP.zy)||!$APP.Ma(b,".")||$APP.B.j($APP.dn(b,"."),$APP.en(b)))if($APP.B.j(d,
$APP.zy)&&$APP.Ma(b,"."))a=$APP.Q.A(a,gK,b);else if(!$APP.B.j(d,$APP.zy)){var e=d.gte(0);c=$APP.m(e)?d.lte(c):e;a=$APP.m(c)?$APP.Q.B(a,SJ,d,$APP.D([gK,b])):a}return a});$APP.hF.j(PJ,function(a,b){$APP.G(b,0,null);b=$APP.G(b,1,null);return $APP.Q.A(a,PJ,b)});
$APP.Rr(NJ,$APP.D([function(a){var b=$APP.fj(a),c=$APP.H.j(b,gK),d=$APP.H.j(b,SJ),e=$APP.H.j(b,PJ),f=$APP.H.j(b,$APP.Oz);e=$APP.m(e)?e:8;b=$APP.Vj(a,new $APP.O(null,3,5,$APP.P,[f,$APP.qD,$APP.HF.address],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));a=$APP.Vj(a,new $APP.O(null,2,5,$APP.P,[f,$APP.Ex],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));b=(f=$APP.df(d))?f:b.gte(d);return new $APP.l(null,6,[$APP.Pz,e,$APP.dz,b,$APP.Hz,a,$APP.dC,d,$APP.zx,c,$APP.Zv,($APP.m(d)?
d:module$node_modules$ethers$lib$index.BigNumber.from("0")).mul(e)],null)}]));$APP.Rr($J,$APP.D([function(a){var b=$APP.fj(a);b=$APP.H.j(b,$APP.Oz);return $APP.Uj(a,new $APP.O(null,2,5,$APP.P,[b,$APP.QD],null))}]));$APP.Re();
}).call(this);