(function(){
'use strict';var qK,yK,DK,uK,EK,BK,AK,xK,nK,pK,oK,wK,CK,sK,GK,rK,vK,zK,tK;$APP.mK=function(){return new $APP.P(null,1,5,$APP.Q,[new $APP.k(null,2,[$APP.bq,function(){$APP.Yq(new $APP.P(null,2,5,$APP.Q,[$APP.TD,$APP.mG.address],null));$APP.Yq(new $APP.P(null,1,5,$APP.Q,[$APP.xy],null));$APP.Yq(new $APP.P(null,1,5,$APP.Q,[$APP.aD],null));return $APP.Yq(new $APP.P(null,1,5,$APP.Q,[$APP.$A],null))},$APP.QA,$APP.ki],null)],null)};
qK=function(a){var b=$APP.Uf($APP.Sr(new $APP.P(null,1,5,$APP.Q,[nK],null)));b=$APP.N(b);b=$APP.H.j(b,$APP.qA);return $APP.Fh(new $APP.P(null,3,5,$APP.Q,[oK,new $APP.k(null,2,[$APP.St,function(){return $APP.Yq(new $APP.P(null,2,5,$APP.Q,[pK,a],null))},$APP.tp,$APP.B.j(b,a)?"bg-C71edf59c":"bg-Cffffff26"],null),[$APP.p.o(a)," WEEKS"].join("")],null),new $APP.k(null,1,[$APP.En,a],null))};
yK=function(){var a=$APP.Uf($APP.Sr(new $APP.P(null,1,5,$APP.Q,[nK],null)));a=$APP.N(a);var b=$APP.H.j(a,$APP.IC),c=$APP.H.j(a,$APP.Wx),d=$APP.H.j(a,$APP.tw),e=$APP.H.j(a,$APP.qA),f=$APP.H.j(a,$APP.iA),h=$APP.H.j(a,$APP.Dz);return new $APP.P(null,10,5,$APP.Q,[rK,new $APP.P(null,4,5,$APP.Q,[$APP.Ux,"Amount ",new $APP.P(null,2,5,$APP.Q,[$APP.BG,"2.5rem"],null),"sacrificed:"],null),new $APP.P(null,2,5,$APP.Q,[$APP.vy,new $APP.k(null,3,[$APP.bw,function(l){return $APP.Yq(new $APP.P(null,2,5,$APP.Q,[sK,
l.target.value],null))},$APP.ez,c,$APP.zt,new $APP.k(null,1,[$APP.Lt,"inset 1px 1px #111, 1px 1px rgba(116, 191, 206, 0.2)"],null)],null)],null),new $APP.P(null,3,5,$APP.Q,[tK,"MAX:",new $APP.P(null,3,5,$APP.Q,[$APP.pG,f,new $APP.k(null,1,[$APP.tp,"ffd"],null)],null)],null),new $APP.P(null,2,5,$APP.Q,[uK,"Locked weeks:"],null),new $APP.P(null,5,5,$APP.Q,[vK,new $APP.P(null,2,5,$APP.Q,[qK,4],null),new $APP.P(null,2,5,$APP.Q,[qK,8],null),new $APP.P(null,2,5,$APP.Q,[qK,16],null),new $APP.P(null,2,5,
$APP.Q,[qK,32],null)],null),new $APP.P(null,2,5,$APP.Q,[$APP.qG,new $APP.k(null,1,[$APP.tp,"my-12"],null)],null),new $APP.P(null,2,5,$APP.Q,[wK,"Your sGOLD in return will be:"],null),new $APP.P(null,3,5,$APP.Q,[$APP.gE,new $APP.P(null,2,5,$APP.Q,[$APP.rG,"2.5rem"],null),new $APP.P(null,3,5,$APP.Q,[$APP.pG,d,new $APP.k(null,1,[$APP.zt,new $APP.k(null,1,[$APP.gD,"40rem"],null)],null)],null)],null),new $APP.P(null,3,5,$APP.Q,[$APP.Ot,new $APP.k(null,3,[$APP.tp,"absolute bottom-12 transform left-1/2 -translate-x-1/2 bg-Ced8e28 border-Cffd386 w-14rem text-xl",
$APP.Jt,$APP.hE,$APP.St,function(){return $APP.Yq($APP.m(h)?new $APP.P(null,2,5,$APP.Q,[$APP.Xx,new $APP.k(null,3,[$APP.xu,$APP.uC,$APP.yu,new $APP.P(null,2,5,$APP.Q,[b,e],null),$APP.Au,function(){$APP.Yq(new $APP.P(null,2,5,$APP.Q,[sK,""],null));$APP.Yq(new $APP.P(null,1,5,$APP.Q,[$APP.MD],null));$APP.Yq(new $APP.P(null,2,5,$APP.Q,[$APP.TD,$APP.mG.address],null));return $APP.Yq(new $APP.P(null,1,5,$APP.Q,[xK],null))}],null)],null):new $APP.P(null,2,5,$APP.Q,[$APP.SD,new $APP.k(null,3,[$APP.xu,$APP.My,
$APP.yu,new $APP.P(null,2,5,$APP.Q,[$APP.mG.address,"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],null),$APP.Au,function(){return $APP.Yq(new $APP.P(null,2,5,$APP.Q,[$APP.TD,$APP.mG.address],null))}],null)],null))}],null),$APP.m(h)?"SACRIFICED":"APPROVE"],null)],null)};
DK=function(){var a=$APP.Uf($APP.Sr(new $APP.P(null,1,5,$APP.Q,[zK],null)));return new $APP.P(null,5,5,$APP.Q,[AK,new $APP.k(null,1,[$APP.zt,new $APP.k(null,3,[$APP.gx,"url(/images/for-glory-bg.svg)",$APP.BD,"140%",$APP.xD,"50% 2%"],null)],null),new $APP.P(null,2,5,$APP.Q,[BK,"Your $GOLD eligible to redeem"],null),new $APP.P(null,3,5,$APP.Q,[CK,new $APP.P(null,2,5,$APP.Q,[$APP.BG,"2.5rem"],null),$APP.pG.o(a)],null),new $APP.P(null,3,5,$APP.Q,[$APP.Ot,new $APP.k(null,3,[$APP.tp,"absolute bottom-12 left-1/2 transform -translate-x-1/2 text-xl",
$APP.Jt,$APP.gu,$APP.zt,new $APP.k(null,1,[$APP.Et,"10rem"],null)],null),"REDEEM"],null)],null)};$APP.FK=function(){return new $APP.P(null,4,5,$APP.Q,[EK,new $APP.k(null,1,[$APP.zt,new $APP.k(null,1,[$APP.xx,"1fr 18rem"],null)],null),new $APP.P(null,1,5,$APP.Q,[yK],null),new $APP.P(null,1,5,$APP.Q,[DK],null)],null)};uK=$APP.S("div.w-full.mt-6.mb-2.ffd.text-C6bc9db");EK=$APP.S("div.grid.fb");BK=$APP.S("p.mt-12.text-base.px-16.ffd");AK=$APP.S("div.relative.h-full.text-center.bg-gradient-to-b.from-transparent.to-C50929e3b.bg-no-repeat");
xK=$APP.T("fgl.contracts.sgold","init-raw");nK=$APP.T("fgl.app.views.guild-alter","left-data");pK=$APP.T("fgl.app.views.guild-alter","weeks");oK=$APP.S("button.rounded.py-1");wK=$APP.S("div.w-full.mb-2.ffd.text-C6bc9db");CK=$APP.S("p.guild-font-family.text-4xl.mt-6.flexr");sK=$APP.T("fgl.app.views.guild-alter","input");GK=$APP.T("fgl.app.views.guild-alter","input-str");rK=$APP.S("div.relative.px-10");vK=$APP.S("div.w-full.grid.grid-cols-4.gap-5.fb");zK=$APP.T("fgl.app.views.guild-alter","right-data");
tK=$APP.S("div.w-full.text-right.mt-1.ffd.text-Cffffff80");$APP.hd("guild-alter");$APP.HK={};
$APP.KF.j(sK,function(a,b){$APP.G(b,0,null);b=$APP.G(b,1,null);var c=$APP.N(a);c=$APP.H.j(c,$APP.pA);c=$APP.Sj(a,new $APP.P(null,2,5,$APP.Q,[c,$APP.ay],null));b=b.replace(/\.+/,".").replace(/-/,"");try{var d=module$node_modules$ethers$lib$index.utils.parseUnits(b)}catch(f){if(f instanceof Error)d=$APP.$y;else throw f;}if($APP.B.j(b,""))a=$APP.wl.B(a,sK,module$node_modules$ethers$lib$index.BigNumber.from("0"),$APP.D([GK,""]));else if(!$APP.B.j(d,$APP.$y)||!$APP.Ma(b,".")||$APP.B.j($APP.cn(b,"."),$APP.dn(b)))if($APP.B.j(d,
$APP.$y)&&$APP.Ma(b,"."))a=$APP.wl.A(a,GK,b);else if(!$APP.B.j(d,$APP.$y)){var e=d.gte(0);c=$APP.m(e)?d.lte(c):e;a=$APP.m(c)?$APP.wl.B(a,sK,d,$APP.D([GK,b])):a}return a});$APP.KF.j(pK,function(a,b){$APP.G(b,0,null);b=$APP.G(b,1,null);return $APP.wl.A(a,pK,b)});
$APP.Qr(nK,$APP.D([function(a){var b=$APP.N(a),c=$APP.H.j(b,GK),d=$APP.H.j(b,sK),e=$APP.H.j(b,pK),f=$APP.H.j(b,$APP.pA);e=$APP.m(e)?e:8;b=$APP.Tj(a,new $APP.P(null,3,5,$APP.Q,[f,$APP.TD,$APP.mG.address],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));a=$APP.Tj(a,new $APP.P(null,2,5,$APP.Q,[f,$APP.ay],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));b=(f=$APP.df(d))?f:b.gte(d);return new $APP.k(null,6,[$APP.qA,e,$APP.Dz,b,$APP.iA,a,$APP.IC,d,$APP.Wx,c,$APP.tw,($APP.m(d)?
d:module$node_modules$ethers$lib$index.BigNumber.from("0")).mul(e)],null)}]));$APP.Qr(zK,$APP.D([function(a){var b=$APP.N(a);b=$APP.H.j(b,$APP.pA);return $APP.Sj(a,new $APP.P(null,2,5,$APP.Q,[b,$APP.rE],null))}]));$APP.Re();
}).call(this);