(function(){
'use strict';var l4,s4,x4,p4,y4,v4,u4,i4,k4,j4,r4,w4,n4,z4,m4,q4,t4,o4;$APP.s_=function(){return new $APP.P(null,1,5,$APP.R,[new $APP.k(null,2,[$APP.kt,function(){$APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.GW,$APP.dZ.address],null));$APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.OP],null));$APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.yV],null));return $APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.LS],null))},$APP.KA,$APP.Zi],null)],null)};
l4=function(a){var b=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[i4],null)));b=$APP.N(b);b=$APP.K.j(b,$APP.$R);return $APP.gi(new $APP.P(null,3,5,$APP.R,[j4,new $APP.k(null,2,[$APP.$w,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[k4,a],null))},$APP.xs,$APP.D.j(b,a)?"bg-C71edf59c":"bg-Cffffff26"],null),[$APP.p.o(a)," WEEKS"].join("")],null),new $APP.k(null,1,[$APP.Kq,a],null))};
s4=function(){var a=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[i4],null)));a=$APP.N(a);var b=$APP.K.j(a,$APP.bD),c=$APP.K.j(a,$APP.fP),d=$APP.K.j(a,$APP.cD),e=$APP.K.j(a,$APP.$R),f=$APP.K.j(a,$APP.RR),h=$APP.K.j(a,$APP.gR);return new $APP.P(null,10,5,$APP.R,[m4,new $APP.P(null,4,5,$APP.R,[$APP.cP,"Amount ",new $APP.P(null,2,5,$APP.R,[$APP.uZ,"2.5rem"],null),"sacrificed:"],null),new $APP.P(null,2,5,$APP.R,[$APP.LP,new $APP.k(null,3,[$APP.IM,function(m){return $APP.gu(new $APP.P(null,2,5,$APP.R,[n4,
m.target.value],null))},$APP.Zy,c,$APP.Hw,new $APP.k(null,1,[$APP.Tw,"inset 1px 1px #111, 1px 1px rgba(116, 191, 206, 0.2)"],null)],null)],null),new $APP.P(null,3,5,$APP.R,[o4,"MAX:",new $APP.P(null,3,5,$APP.R,[$APP.gZ,f,new $APP.k(null,1,[$APP.xs,"ffd"],null)],null)],null),new $APP.P(null,2,5,$APP.R,[p4,"Locked weeks:"],null),new $APP.P(null,5,5,$APP.R,[q4,new $APP.P(null,2,5,$APP.R,[l4,4],null),new $APP.P(null,2,5,$APP.R,[l4,8],null),new $APP.P(null,2,5,$APP.R,[l4,16],null),new $APP.P(null,2,5,
$APP.R,[l4,32],null)],null),new $APP.P(null,2,5,$APP.R,[$APP.hZ,new $APP.k(null,1,[$APP.xs,"my-12"],null)],null),new $APP.P(null,2,5,$APP.R,[r4,"Your sGOLD in return will be:"],null),new $APP.P(null,3,5,$APP.R,[$APP.PW,new $APP.P(null,2,5,$APP.R,[$APP.iZ,"2.5rem"],null),new $APP.P(null,3,5,$APP.R,[$APP.gZ,d,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.EV,"40rem"],null)],null)],null)],null),new $APP.P(null,3,5,$APP.R,[$APP.Ww,new $APP.k(null,3,[$APP.xs,"absolute bottom-12 transform left-1/2 -translate-x-1/2 bg-Ced8e28 border-Cffd386 w-14rem text-xl",
$APP.Rw,$APP.QW,$APP.$w,function(){return $APP.gu($APP.l(h)?new $APP.P(null,2,5,$APP.R,[$APP.gP,new $APP.k(null,3,[$APP.Gx,$APP.LU,$APP.Hx,new $APP.P(null,2,5,$APP.R,[b,e],null),$APP.Jx,function(){$APP.gu(new $APP.P(null,2,5,$APP.R,[n4,""],null));$APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.uW],null));$APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.GW,$APP.dZ.address],null));return $APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.hQ],null))}],null)],null):new $APP.P(null,2,5,$APP.R,[$APP.FW,new $APP.k(null,3,[$APP.Gx,
$APP.jQ,$APP.Hx,new $APP.P(null,2,5,$APP.R,[$APP.dZ.address,"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],null),$APP.Jx,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.GW,$APP.dZ.address],null))}],null)],null))}],null),$APP.l(h)?"SACRIFICED":"APPROVE"],null)],null)};
x4=function(){var a=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[t4],null)));return new $APP.P(null,5,5,$APP.R,[u4,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,3,[$APP.aO,"url(/images/for-glory-bg.svg)",$APP.fW,"140%",$APP.bW,"50% 2%"],null)],null),new $APP.P(null,2,5,$APP.R,[v4,"Your $GOLD eligible to redeem"],null),new $APP.P(null,3,5,$APP.R,[w4,new $APP.P(null,2,5,$APP.R,[$APP.uZ,"2.5rem"],null),$APP.gZ.o(a)],null),new $APP.P(null,3,5,$APP.R,[$APP.Ww,new $APP.k(null,3,[$APP.xs,"absolute bottom-12 left-1/2 transform -translate-x-1/2 text-xl",
$APP.Rw,$APP.ox,$APP.Hw,new $APP.k(null,1,[$APP.Mw,"10rem"],null)],null),"REDEEM"],null)],null)};$APP.r_=function(){return new $APP.P(null,4,5,$APP.R,[y4,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.zO,"1fr 18rem"],null)],null),new $APP.P(null,1,5,$APP.R,[s4],null),new $APP.P(null,1,5,$APP.R,[x4],null)],null)};p4=$APP.S("div.w-full.mt-6.mb-2.ffd.text-C6bc9db");y4=$APP.S("div.grid.fb");v4=$APP.S("p.mt-12.text-base.px-16.ffd");u4=$APP.S("div.relative.h-full.text-center.bg-gradient-to-b.from-transparent.to-C50929e3b.bg-no-repeat");
i4=$APP.T("fgl.app.views.guild-alter","left-data");k4=$APP.T("fgl.app.views.guild-alter","weeks");j4=$APP.S("button.rounded.py-1");r4=$APP.S("div.w-full.mb-2.ffd.text-C6bc9db");w4=$APP.S("p.guild-font-family.text-4xl.mt-6.flexr");n4=$APP.T("fgl.app.views.guild-alter","input");z4=$APP.T("fgl.app.views.guild-alter","input-str");m4=$APP.S("div.relative.px-10");q4=$APP.S("div.w-full.grid.grid-cols-4.gap-5.fb");t4=$APP.T("fgl.app.views.guild-alter","right-data");o4=$APP.S("div.w-full.text-right.mt-1.ffd.text-Cffffff80");$APP.kd("guild-alter");$APP.q_={};
$APP.xY.j(n4,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);var c=$APP.N(a);c=$APP.K.j(c,$APP.YR);c=$APP.$k(a,new $APP.P(null,2,5,$APP.R,[c,$APP.mP],null));b=b.replace(/\.+/,".").replace(/-/,"");try{var d=module$node_modules$ethers$lib$index.utils.parseUnits(b)}catch(f){if(f instanceof Error)d=$APP.zQ;else throw f;}if($APP.D.j(b,""))a=$APP.Bm.B(a,n4,module$node_modules$ethers$lib$index.BigNumber.from("0"),$APP.G([z4,""]));else if(!$APP.D.j(d,$APP.zQ)||!$APP.Oa(b,".")||$APP.D.j($APP.to(b,"."),$APP.vo(b)))if($APP.D.j(d,
$APP.zQ)&&$APP.Oa(b,"."))a=$APP.Bm.A(a,z4,b);else if(!$APP.D.j(d,$APP.zQ)){var e=d.gte(0);c=$APP.l(e)?d.lte(c):e;a=$APP.l(c)?$APP.Bm.B(a,n4,d,$APP.G([z4,b])):a}return a});$APP.xY.j(k4,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);return $APP.Bm.A(a,k4,b)});
$APP.Yu(i4,$APP.G([function(a){var b=$APP.N(a),c=$APP.K.j(b,z4),d=$APP.K.j(b,n4),e=$APP.K.j(b,k4),f=$APP.K.j(b,$APP.YR);e=$APP.l(e)?e:8;b=$APP.al(a,new $APP.P(null,3,5,$APP.R,[f,$APP.GW,$APP.dZ.address],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));a=$APP.al(a,new $APP.P(null,2,5,$APP.R,[f,$APP.mP],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));b=(f=$APP.Af(d))?f:b.gte(d);return new $APP.k(null,6,[$APP.$R,e,$APP.gR,b,$APP.RR,a,$APP.bD,d,$APP.fP,c,$APP.cD,($APP.l(d)?
d:module$node_modules$ethers$lib$index.BigNumber.from("0")).mul(e)],null)}]));$APP.Yu(t4,$APP.G([function(a){var b=$APP.N(a);b=$APP.K.j(b,$APP.YR);return $APP.$k(a,new $APP.P(null,2,5,$APP.R,[b,$APP.$W],null))}]));$APP.lf();
}).call(this);