(function(){
'use strict';var RN,lO,oO,qO,YO,QO,VN,XO,tO,gO,KO,pO,UO,cO,fO,hO,XN,GO,ZO,LO,IO,UN,YN,jO,JO,TO,$O,sO,aP,FO,WO,OO,VO,$N,rO,SO,HO,CO,yO,SN,MO,kO,AO,bP,EO,vO,cP,nO,BO,uO,dP,NO,zO,dO,wO,RO,xO,TN,aO,iO,eP,eO,fP,bO,PO,gP,ZN,mO,WN,DO;RN=function(a){var b=a.getDate(),c=a.getFullYear(),d=$APP.E.j($APP.mK,a.getMonth()+1),e=a.getHours(),k=12<e;e=k?e-12:e;a=a.getMinutes();return[$APP.n.o(d)," ",$APP.n.o(b),",",$APP.n.o(c),",",$APP.n.o(e),":",$APP.n.o(a),k?"PM":"AM"].join("")};
$APP.BM=function(){return new $APP.I(null,1,5,$APP.J,[new $APP.g(null,2,[$APP.Cq,function(){return $APP.Q(new $APP.I(null,1,5,$APP.J,[$APP.qC],null))},$APP.Av,$APP.Zh],null)],null)};
lO=function(a){return $APP.hq(new $APP.g(null,2,[$APP.rE,function(){return $APP.h(a)?($APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.pC,a],null)),$APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.WB,a],null))):null},$APP.Tp,function(){var b=$APP.p($APP.qs(new $APP.I(null,2,5,$APP.J,[SN,a],null)));b=$APP.G(b);var c=$APP.E.j(b,TN);$APP.E.j(b,UN);var d=$APP.G(c);b=$APP.E.j(d,$APP.Ns);var e=$APP.E.j(d,VN);c=$APP.E.j(d,$APP.mv);var k=$APP.E.j(d,$APP.pF);d=$APP.E.j(d,UN);return $APP.uh(new $APP.I(null,5,5,$APP.J,[WN,new $APP.I(null,
3,5,$APP.J,[XN,new $APP.I(null,3,5,$APP.J,[YN,new $APP.I(null,2,5,$APP.J,[ZN,b],null),new $APP.I(null,2,5,$APP.J,[$N,k],null)],null),new $APP.I(null,3,5,$APP.J,[$APP.eo,new $APP.g(null,3,[$APP.Yn,$APP.HI,$APP.Zn,"justify-self-end",$APP.us,function(){return $APP.Q(new $APP.I(null,3,5,$APP.J,[$APP.bv,$APP.eH,new $APP.g(null,1,[aO,a],null)],null))}],null),"Check detail"],null)],null),new $APP.I(null,4,5,$APP.J,[bO,new $APP.g(null,1,[$APP.us,function(){return open($APP.qn($APP.A(["/address/",e])))}],
null),new $APP.I(null,2,5,$APP.J,[cO,["by ",$APP.rn(e)].join("")],null),new $APP.I(null,2,5,$APP.J,[$APP.Fu,new $APP.I(null,2,5,$APP.J,[dO,new $APP.g(null,1,[$APP.R,"/images/share.png"],null)],null)],null)],null),new $APP.I(null,3,5,$APP.J,[eO,new $APP.I(null,2,5,$APP.J,[fO,"DESCRIPTIONS"],null),new $APP.I(null,2,5,$APP.J,[gO,c],null)],null),new $APP.I(null,5,5,$APP.J,[hO,new $APP.I(null,2,5,$APP.J,[iO,new $APP.g(null,1,[$APP.R,"/images/votes-no.png"],null)],null),"NO",new $APP.I(null,2,5,$APP.J,
[jO,d],null),new $APP.I(null,2,5,$APP.J,[kO,"VOTES"],null)],null)],null),new $APP.g(null,1,[$APP.oo,a],null))}],null))};
oO=function(){return $APP.hq(new $APP.g(null,1,[$APP.Tp,function(){var a=$APP.p($APP.qs(new $APP.I(null,1,5,$APP.J,[$APP.Yu],null)));a=$APP.E.j($APP.sL,a);var b=$APP.p($APP.qs(new $APP.I(null,2,5,$APP.J,[mO,a],null)));b=$APP.G(b);b=$APP.E.j(b,$APP.uB);return $APP.h(a)?($APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.LA,a],null)),new $APP.I(null,3,5,$APP.J,[$APP.ej,new $APP.I(null,1,5,$APP.J,[nO],null),$APP.uj.j(function(c){var d=$APP.G(c);c=$APP.E.j(d,$APP.bq);d=$APP.E.j(d,$APP.dC);return new $APP.I(null,
3,5,$APP.J,[lO,c,d],null)},b)],null)):null}],null))};qO=function(a,b){return new $APP.I(null,4,5,$APP.J,[pO,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.aB,"3fr 1fr"],null)],null),new $APP.I(null,2,5,$APP.J,[$APP.Bs,a],null),new $APP.I(null,2,5,$APP.J,[$APP.Bs,b],null)],null)};
YO=function(a){return $APP.hq(new $APP.g(null,2,[$APP.rE,function(){return $APP.h(a)?($APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.pC,a],null)),$APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.WB,a],null))):null},$APP.Tp,function(){var b=$APP.p($APP.qs(new $APP.I(null,2,5,$APP.J,[SN,a],null)));b=$APP.G(b);var c=$APP.E.j(b,TN);b=$APP.E.j(b,UN);var d=$APP.G(c),e=$APP.E.j(d,$APP.$q);c=$APP.E.j(d,$APP.mv);var k=$APP.E.j(d,$APP.Cq),l=$APP.E.j(d,UN),m=$APP.E.j(d,$APP.pF),r=$APP.E.j(d,rO),u=$APP.E.j(d,$APP.Ns),v=$APP.E.j(d,
sO),z=$APP.E.j(d,VN);d=$APP.E.j(d,$APP.NA);var B=$APP.p($APP.qs(new $APP.I(null,2,5,$APP.J,[tO,a],null)));B=$APP.G(B);var C=$APP.E.j(B,uO);k=$APP.h(k)?RN(new Date(1E3*k)):k;e=$APP.h(e)?RN(new Date(1E3*e)):e;B=$APP.uj.j(uO,b);var F=$APP.x(B),M=$APP.x($APP.Cj(function(V){return $APP.y.j(1,V)},B)),S=F-M;return new $APP.I(null,3,5,$APP.J,[vO,new $APP.I(null,2,5,$APP.J,[$APP.On,"\n      .vote-desc {\n        height: calc(100% - 1.75rem);\n      }\n\n"],null),new $APP.I(null,2,5,$APP.J,[wO,new $APP.I(null,
5,5,$APP.J,[xO,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.aB,"1fr 2.8fr"],null)],null),new $APP.I(null,4,5,$APP.J,[yO,new $APP.I(null,3,5,$APP.J,[zO,new $APP.I(null,2,5,$APP.J,[AO,u],null),new $APP.I(null,3,5,$APP.J,[$APP.bC,new $APP.g(null,1,[$APP.us,function(){return $APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.bv,$APP.qF],null))}],null),new $APP.I(null,2,5,$APP.J,[$APP.vG,new $APP.g(null,1,[$APP.R,"/images/eject.png"],null)],null)],null)],null),new $APP.I(null,3,5,$APP.J,[BO,new $APP.I(null,
2,5,$APP.J,[CO,["by ",$APP.rn(z)].join("")],null),new $APP.I(null,2,5,$APP.J,[DO,new $APP.g(null,1,[$APP.Zn,"bg-url(/images/link.png)"],null)],null)],null),new $APP.I(null,3,5,$APP.J,[EO,new $APP.I(null,3,5,$APP.J,[FO,new $APP.I(null,2,5,$APP.J,[GO,"descriptions:"],null),c],null),function(){var V=$APP.y.j(m,"active");return V?new $APP.I(null,3,5,$APP.J,[HO,new $APP.I(null,3,5,$APP.J,[$APP.bA,new $APP.I(null,3,5,$APP.J,[IO,new $APP.g(null,2,[$APP.Zn,$APP.y.j(C,1)?"bg-C71edf59c":"bg-Cffffff26 text-Cb2f4fa",
$APP.us,function(){return $APP.Q(new $APP.I(null,3,5,$APP.J,[JO,a,1],null))}],null),$APP.t(r)],null),new $APP.I(null,3,5,$APP.J,[KO,new $APP.g(null,2,[$APP.Zn,$APP.y.j(C,2)?"bg-C71edf59c":"bg-Cffffff26 text-Cb2f4fa",$APP.us,function(){return $APP.Q(new $APP.I(null,3,5,$APP.J,[JO,a,2],null))}],null),$APP.nh(r)],null)],null),new $APP.I(null,3,5,$APP.J,[$APP.eo,new $APP.g(null,3,[$APP.Yn,$APP.FJ,$APP.Zn,"text-white",$APP.us,function(){return $APP.Q(new $APP.I(null,3,5,$APP.J,[LO,a,C],null))}],null),
"VOTE"],null)],null):V}()],null)],null),new $APP.I(null,8,5,$APP.J,[MO,new $APP.I(null,2,5,$APP.J,[NO,"MESSAGE"],null),new $APP.I(null,10,5,$APP.J,[OO,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.aB,"max-content 1fr"],null)],null),new $APP.I(null,2,5,$APP.J,[PO,"IPFS"],null),new $APP.I(null,2,5,$APP.J,[QO,v],null),new $APP.I(null,2,5,$APP.J,[PO,"Start date"],null),new $APP.I(null,2,5,$APP.J,[QO,k],null),new $APP.I(null,2,5,$APP.J,[PO,"End date"],null),new $APP.I(null,2,5,$APP.J,[QO,e],null),
new $APP.I(null,2,5,$APP.J,[PO,"Snapshot"],null),new $APP.I(null,2,5,$APP.J,[QO,d],null)],null),new $APP.I(null,2,5,$APP.J,[RO,"THE CURRENT RESULT"],null),new $APP.I(null,4,5,$APP.J,[SO,new $APP.I(null,2,5,$APP.J,[$APP.Bs,$APP.t(r)],null),function(){var V=0<F;return V?(V=M>S)?new $APP.I(null,2,5,$APP.J,[$APP.Bs,"The current result"],null):V:V}(),function(){var V=0<F;return V?(V=M<S)?new $APP.I(null,2,5,$APP.J,[$APP.Bs,[$APP.n.o(M),1<M?" Votes ":" Vote ",0<F?$APP.n.o(M/F*100):"0","%"].join("")],null):
V:V}()],null),new $APP.I(null,2,5,$APP.J,[TO,new $APP.I(null,2,5,$APP.J,[UO,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.Tn,0<F?[$APP.n.o(M/F*100),"%"].join(""):0],null)],null)],null)],null),new $APP.I(null,4,5,$APP.J,[SO,new $APP.I(null,2,5,$APP.J,[$APP.Bs,$APP.nh(r)],null),function(){var V=0<F;return V?(V=S>M)?new $APP.I(null,2,5,$APP.J,[$APP.Bs,"The current result"],null):V:V}(),function(){var V=0<F;return V?(V=S<M)?new $APP.I(null,2,5,$APP.J,[$APP.Bs,[$APP.n.o(S),1<S?" Votes ":" Vote ",
0<F?$APP.n.o(S/F*100):"0","%"].join("")],null):V:V}()],null),new $APP.I(null,2,5,$APP.J,[VO,new $APP.I(null,2,5,$APP.J,[UO,new $APP.g(null,1,[$APP.On,new $APP.g(null,1,[$APP.Tn,0<F?["",$APP.n.o(S/F*100),"%"].join(""):0],null)],null)],null)],null)],null),new $APP.I(null,3,5,$APP.J,[$APP.jH,new $APP.I(null,2,5,$APP.J,[WO,["VOTE (",$APP.n.o(l),")"].join("")],null),new $APP.I(null,3,5,$APP.J,[$APP.ej,new $APP.I(null,1,5,$APP.J,[XO],null),$APP.Ij(function(V){var ba=$APP.G(V);V=$APP.E.j(ba,$APP.TA);var na=
$APP.E.j(ba,sO);ba=$APP.E.j(ba,uO);return new $APP.I(null,4,5,$APP.J,[qO,V,$APP.hh(r,ba-1),na],null)},b)],null)],null)],null)],null)],null)}],null))};$APP.AM=function(a){a=$APP.G(a);a=$APP.E.j(a,$APP.Nw);a=$APP.G(a);a=$APP.E.j(a,aO);return $APP.h(a)?new $APP.I(null,2,5,$APP.J,[YO,a],null):new $APP.I(null,1,5,$APP.J,[oO],null)};QO=$APP.N("span.justify-self-end");VN=$APP.N("author");XO=$APP.N("div.flex-1.guild-table-body.text-sm.overflow-auto");tO=$APP.O("fgl.app.views.guild-vote","pdata");gO=$APP.N("p.ffd.text-base");
KO=$APP.N("button.guild-font-family.text-sm.tracking-wider.rounded.px-16.py-0_5.ml-2");pO=$APP.N("div.grid.py-3.justify-items-center.border-b-1px.border-solid.border-C79c5da");UO=$APP.N("div.absolute.h-1_5.rounded-l-full.bg-C96a1ae");cO=$APP.N("span.block.mr-2");fO=$APP.N("h3.text-xl");hO=$APP.N("div.flexrr.justify-end.mt-2");XN=$APP.N("div.flexrr.justify-between");GO=$APP.N("span.uppercase.pr-2");ZO=$APP.N("domain");LO=$APP.O("fgl.app.views.guild-vote","vote");IO=$APP.N("button.guild-font-family.text-sm.tracking-wider.rounded.px-16.py-0_5");
UN=$APP.N("votes");YN=$APP.N("div.flexrr.items-center");jO=$APP.N("span.text-Cd6d6d6.mx-1");JO=$APP.O("fgl.app.views.guild-vote","choice");TO=$APP.N("div.relative.w-full.h-1_5.rounded-l-full.bg-C00000033.mb-4");$O=$APP.N("metadata");sO=$APP.N("ipfs");aP=$APP.N("timestamp");FO=$APP.N("div.vote-desc.overflow-auto.text-sm");WO=$APP.N("div.rounded-sm.bg-C79c5da66.text-lg.text-center");OO=$APP.N("p.grid.gap-y-1");VO=$APP.N("div.relative.w-full.h-1_5.rounded-l-full.bg-C00000033");$N=$APP.N("div.bg-Ced8e28.px-12.rounded-md.text-base.capitalize");
rO=$APP.N("choices");SO=$APP.N("p.flex.justify-between.mb-1_5");HO=$APP.N("div.mt-1.flexb");CO=$APP.N("span.align-middle");yO=$APP.N("div.col-span-2");SN=$APP.O("fgl.app.views.guild-vote","data");MO=$APP.N("div.text-xs");kO=$APP.N("span.text-Cd6d6d6");AO=$APP.N("p.guild-font-family.text-2xl.uppercase.tracking-wider");bP=$APP.N("from");EO=$APP.N("div.bg-C81c6dd1a.rounded-sm.p-3.mt-2.text-Cd6d6d6.h-48");vO=$APP.N("div.py-6.px-8");cP=$APP.N("Vote");nO=$APP.N("div.overflow-y-auto");BO=$APP.N("p.text-xs.text-Cd6d6d6.pl-1");
uO=$APP.N("choice");dP=$APP.N("sig");NO=$APP.N("p.guild-font-family.text-base.mb-1");zO=$APP.N("div.flexb");dO=$APP.N("img.w-3");wO=$APP.N("div.p-3.pb-3.bg-C81c6dd1a.h-full");RO=$APP.N("p.guild-font-family.text-base.mt-3.mb-1");xO=$APP.N("div.grid.grid-rows-2.gap-x-10.gap-y-8.h-full.pr-9");TN=$APP.N("proposal");aO=$APP.N("proposal-id");iO=$APP.N("img.w-2.mr-2");eP=$APP.N("uint32");eO=$APP.N("div.bg-C81c6dd1a.p-4.text-Cd6d6d6.rounded-md.mt-4");fP=$APP.N("types");bO=$APP.N("div.flexrr.items-center.mt-4.text-Cd6d6d6.cursor-pointer");
PO=$APP.N("span.text-C96a1ae");gP=$APP.N("bytes32");ZN=$APP.N("span.text-4xl.mr-4.uppercase");mO=$APP.O("fgl.app.views.guild-vote","proposals");WN=$APP.N("div.bg-C81c6dd1a.rounded-md.p-4.fb.mx-8.my-4");DO=$APP.N("span.align-middle.inline-block.w-0_65rem.h-0_65rem.bg-no-repeat.bg-contain.bg-center");$APP.cd("guild-vote");$APP.zM={};$APP.os(SN,$APP.A([function(a,b){$APP.D(b,0,null);var c=$APP.D(b,1,null);b=$APP.Mj(a,new $APP.I(null,2,5,$APP.J,[$APP.pC,c],null));a=$APP.Mj(a,new $APP.I(null,2,5,$APP.J,[$APP.WB,c],null));return new $APP.g(null,2,[TN,b,UN,a],null)}]));$APP.os(mO,$APP.A([function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);a=$APP.Mj(a,new $APP.I(null,2,5,$APP.J,[$APP.LA,b],null));return new $APP.g(null,1,[$APP.uB,a],null)}]));
$APP.RK.j(JO,function(a,b){$APP.D(b,0,null);var c=$APP.D(b,1,null);b=$APP.D(b,2,null);return $APP.uq(a,new $APP.I(null,2,5,$APP.J,[JO,c],null),b)});$APP.os(tO,$APP.A([function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);var c=$APP.G(a),d=$APP.E.j(c,JO);c=$APP.E.j(c,$APP.Qu);a=$APP.Mj(a,new $APP.I(null,2,5,$APP.J,[c,$APP.Yu],null));return new $APP.g(null,3,[uO,$APP.E.A(d,b,1),$APP.sG,a,$APP.YB,c],null)}]));
$APP.js(LO,function(a,b){a=$APP.G(a);a=$APP.E.j(a,$APP.cs);$APP.D(b,0,null);var c=$APP.D(b,1,null);b=$APP.D(b,2,null);a=$APP.G(a);var d=$APP.E.j(a,$APP.Du),e=$APP.E.j(a,$APP.Qu),k=new $APP.g(null,2,[$APP.P,"snapshot",$APP.Az,"0.1.4"],null),l=new $APP.g(null,1,[cP,new $APP.I(null,6,5,$APP.J,[new $APP.g(null,2,[$APP.P,bP,$APP.T,$APP.lu],null),new $APP.g(null,2,[$APP.P,$APP.LC,$APP.T,$APP.vz],null),new $APP.g(null,2,[$APP.P,aP,$APP.T,$APP.PH],null),new $APP.g(null,2,[$APP.P,TN,$APP.T,gP],null),new $APP.g(null,
2,[$APP.P,uO,$APP.T,eP],null),new $APP.g(null,2,[$APP.P,$O,$APP.T,$APP.vz],null)],null)],null),m=new $APP.g(null,7,[$APP.LC,"test1234567.eth",bP,e,$APP.T,"single-choice",uO,b,aP,parseInt((new Date).getTime()/1E3),TN,c,$O,"{}"],null);$APP.su($APP.bu(null),function(){return $APP.su($APP.bu($APP.Ms()),function(){return $APP.su($APP.bu($APP.fu(function(){var r=[d,d.getSigner];var u=r[1];r=null!=u?u.call(r[0]):null;r=[r,r._signTypedData];u=r[1];return null!=u?u.call(r[0],$APP.Np(k),$APP.Np(l),$APP.Np(m)):
null}(),function(){return $APP.Ps(new $APP.g(null,2,[$APP.Ns,"Typed Sign Failed",$APP.Hs,"User rejected typed sign in wallet"],null))})),function(r){return $APP.su($APP.bu($APP.fu($APP.du(fetch("https://hub.snapshot.org/api/msg",new $APP.g(null,4,[$APP.wu,$APP.lv,$APP.gv,$APP.hv,$APP.iv,new $APP.g(null,1,["content-type","application/json"],null),$APP.mv,JSON.stringify($APP.Np(new $APP.g(null,3,[$APP.lu,e,dP,r,$APP.Ev,new $APP.g(null,3,[ZO,k,fP,l,$APP.tB,m],null)],null)))],null)),$APP.ev),function(u){return $APP.Q(new $APP.I(null,
7,5,$APP.J,[$APP.vs,$APP.Fs,!0,$APP.GC,!0,$APP.Hs,new $APP.I(null,5,5,$APP.J,[$APP.ys,new $APP.I(null,2,5,$APP.J,[$APP.Bs,"Message signed"],null),new $APP.I(null,1,5,$APP.J,[$APP.Cs],null),new $APP.I(null,2,5,$APP.J,[$APP.Bs,"Failed to create proposal, please try again"],null),new $APP.I(null,2,5,$APP.J,[$APP.Bs,u.message],null)],null)],null))})),function(u){return $APP.su($APP.bu(null),function(){if($APP.h(u)){$APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.WB,c],null));var v=$APP.Q(new $APP.I(null,7,5,
$APP.J,[$APP.vs,$APP.Fs,!0,$APP.GC,!0,$APP.Hs,new $APP.I(null,4,5,$APP.J,[$APP.ys,new $APP.I(null,2,5,$APP.J,[$APP.Bs,"Message signed"],null),new $APP.I(null,1,5,$APP.J,[$APP.Cs],null),new $APP.I(null,2,5,$APP.J,[$APP.Bs,"Vote created"],null)],null)],null))}else v=null;return $APP.bu(v)})})})})});return $APP.Ti});$APP.Je();
}).call(this);