(function(){
shadow$provide[424]=function(Q,w,X,g){function E(q,B){return Object.keys(B).forEach(function(x){"default"!==x&&"__esModule"!==x&&Object.defineProperty(q,x,{enumerable:!0,get:function(){return B[x]}})}),q}function G(q,B,x){const D=x.originalEvent.currentTarget;x=new CustomEvent(q,{bubbles:!0,cancelable:!0,detail:x});B&&D.addEventListener(q,B,{once:!0});D.dispatchEvent(x)}var t,u=w(416).VisuallyHidden,b=w(394).useLayoutEffect,r=w(412).useControllableState,m=w(406).useCallbackRef,k=w(393).Primitive,
e=w(395).Presence,d=w(405).UnstablePortal,h=E({},w(411));Q=w(414).createContextScope;var v=w(352).useComposedRefs,C=w(410).composeEventHandlers,I=E({},w(404)),K=E({},w(351)),F=(t=w(353))&&t.__esModule?t.default:t;const [H,L]=Q("Toast");g.createToastScope=L;const [N,O]=H("ToastProvider");w=q=>{const {__scopeToast:B,label:x="Notification",duration:D=5E3,swipeDirection:A="right",swipeThreshold:R=50,children:T}=q,[S,V]=K.useState(null),[aa,ba]=K.useState(0);q=K.useRef(!1);const ca=K.useRef(!1);return K.createElement(N,
{scope:B,label:x,duration:D,swipeDirection:A,swipeThreshold:R,toastCount:aa,viewport:S,onViewportChange:V,onToastAdd:K.useCallback(()=>ba(Y=>Y+1),[]),onToastRemove:K.useCallback(()=>ba(Y=>Y-1),[]),isFocusedToastEscapeKeyDownRef:q,isClosePausedRef:ca},T)};g.ToastProvider=w;const M=["F8"];t=K.forwardRef((q,B)=>{const {__scopeToast:x,hotkey:D=M,label:A="Notifications ({hotkey})",...R}=q,T=O("ToastViewport",x),S=K.useRef(null),V=K.useRef(null);q=v(B,V,T.onViewportChange);B=D.join("+").replace(/Key/g,
"").replace(/Digit/g,"");return K.useEffect(()=>{const aa=ba=>{var ca;D.every(Y=>ba[Y]||ba.code===Y)&&(null===(ca=V.current)||void 0===ca||ca.focus())};return document.addEventListener("keydown",aa),()=>document.removeEventListener("keydown",aa)},[D]),K.useEffect(()=>{const aa=S.current,ba=V.current;if(aa&&ba){const ca=()=>{const fa=new Event("toast.viewportPause");ba.dispatchEvent(fa);T.isClosePausedRef.current=!0},Y=()=>{const fa=new Event("toast.viewportResume");ba.dispatchEvent(fa);T.isClosePausedRef.current=
!1};return aa.addEventListener("focusin",ca),aa.addEventListener("focusout",Y),aa.addEventListener("pointerenter",ca),aa.addEventListener("pointerleave",Y),window.addEventListener("blur",ca),window.addEventListener("focus",Y),()=>{aa.removeEventListener("focusin",ca);aa.removeEventListener("focusout",Y);aa.removeEventListener("pointerenter",ca);aa.removeEventListener("pointerleave",Y);window.removeEventListener("blur",ca);window.removeEventListener("focus",Y)}}},[T.isClosePausedRef]),K.useEffect(()=>
{const aa=V.current;if(aa){let ba=[];const ca=new MutationObserver(Y=>{[Y]=Y;Y.addedNodes.forEach(fa=>{ba.includes(fa)||(aa.prepend(fa),ba=[...ba,fa])})});return ca.observe(aa,{childList:!0}),()=>ca.disconnect()}},[]),K.createElement(h.Branch,{ref:S,role:"region","aria-label":A.replace("{hotkey}",B),tabIndex:-1,style:{pointerEvents:0<T.toastCount?void 0:"none"}},K.createElement(k.ol,F({tabIndex:-1},R,{ref:q})))});g.ToastViewport=t;Q=K.forwardRef((q,B)=>{const {forceMount:x,open:D,defaultOpen:A,onOpenChange:R,
...T}=q,[S=!0,V]=r({prop:D,defaultProp:A,onChange:R});return K.createElement(e,{present:x||S},K.createElement(c,F({open:S},T,{ref:B,onClose:()=>V(!1),onSwipeStart:C(q.onSwipeStart,aa=>{aa.currentTarget.setAttribute("data-swipe","start")}),onSwipeMove:C(q.onSwipeMove,aa=>{const {x:ba,y:ca}=aa.detail.delta;aa.currentTarget.setAttribute("data-swipe","move");aa.currentTarget.style.setProperty("--radix-toast-swipe-move-x",`${ba}px`);aa.currentTarget.style.setProperty("--radix-toast-swipe-move-y",`${ca}px`)}),
onSwipeCancel:C(q.onSwipeCancel,aa=>{aa.currentTarget.setAttribute("data-swipe","cancel");aa.currentTarget.style.removeProperty("--radix-toast-swipe-move-x");aa.currentTarget.style.removeProperty("--radix-toast-swipe-move-y");aa.currentTarget.style.removeProperty("--radix-toast-swipe-end-x");aa.currentTarget.style.removeProperty("--radix-toast-swipe-end-y")}),onSwipeEnd:C(q.onSwipeEnd,aa=>{const {x:ba,y:ca}=aa.detail.delta;aa.currentTarget.setAttribute("data-swipe","end");aa.currentTarget.style.removeProperty("--radix-toast-swipe-move-x");
aa.currentTarget.style.removeProperty("--radix-toast-swipe-move-y");aa.currentTarget.style.setProperty("--radix-toast-swipe-end-x",`${ba}px`);aa.currentTarget.style.setProperty("--radix-toast-swipe-end-y",`${ca}px`);V(!1)})})))});g.Toast=Q;const [U,P]=H("Toast",{isInteractive:!1,onClose(){}}),c=K.forwardRef((q,B)=>{const {__scopeToast:x,type:D="foreground",duration:A,open:R,onClose:T,onEscapeKeyDown:S,onSwipeStart:V,onSwipeMove:aa,onSwipeCancel:ba,onSwipeEnd:ca,...Y}=q,fa=O("Toast",x),ha=K.useRef(null);
B=v(B,ha);const ka=K.useRef(null),oa=K.useRef(null),la=A||fa.duration,va=K.useRef(0),ta=K.useRef(la),sa=K.useRef(0),{onToastAdd:ra,onToastRemove:na}=fa,pa=m(()=>{var ua,xa;(null===(ua=ha.current)||void 0===ua?0:ua.contains(document.activeElement))&&(null===(xa=fa.viewport)||void 0===xa||xa.focus());T()}),qa=K.useCallback(ua=>{ua&&ua!==1/0&&(window.clearTimeout(sa.current),va.current=(new Date).getTime(),sa.current=window.setTimeout(pa,ua))},[pa]);return K.useEffect(()=>{const ua=fa.viewport;if(ua){const xa=
()=>{qa(ta.current)},za=()=>{const Aa=(new Date).getTime()-va.current;ta.current-=Aa;window.clearTimeout(sa.current)};return ua.addEventListener("toast.viewportPause",za),ua.addEventListener("toast.viewportResume",xa),()=>{ua.removeEventListener("toast.viewportPause",za);ua.removeEventListener("toast.viewportResume",xa)}}},[fa.viewport,la,qa]),K.useEffect(()=>{R&&!fa.isClosePausedRef.current&&qa(la)},[R,la,fa.isClosePausedRef,qa]),K.useEffect(()=>(ra(),()=>na()),[ra,na]),fa.viewport?K.createElement(K.Fragment,
null,K.createElement(z,{__scopeToast:x,role:"status","aria-live":"foreground"===D?"assertive":"polite","aria-atomic":!0},q.children),K.createElement(U,{scope:x,isInteractive:!0,onClose:pa},I.createPortal(K.createElement(h.Root,{asChild:!0,onEscapeKeyDown:C(S,()=>{fa.isFocusedToastEscapeKeyDownRef.current||pa();fa.isFocusedToastEscapeKeyDownRef.current=!1})},K.createElement(k.li,F({role:"status","aria-live":"off","aria-atomic":!0,tabIndex:0,"data-state":R?"open":"closed","data-swipe-direction":fa.swipeDirection},
Y,{ref:B,style:{userSelect:"none",touchAction:"none",...q.style},onKeyDown:C(q.onKeyDown,ua=>{"Escape"===ua.key&&(null==S||S(ua.nativeEvent),ua.nativeEvent.defaultPrevented||(fa.isFocusedToastEscapeKeyDownRef.current=!0,pa()))}),onPointerDown:C(q.onPointerDown,ua=>{0===ua.button&&(ka.current={x:ua.clientX,y:ua.clientY})}),onPointerMove:C(q.onPointerMove,ua=>{if(ka.current){var xa=ua.clientX-ka.current.x,za=ua.clientY-ka.current.y,Aa=!!oa.current,Ba=["left","right"].includes(fa.swipeDirection),Ea=
["left","up"].includes(fa.swipeDirection)?Math.min:Math.max,Ga=Ba?Ea(0,xa):0;Ea=Ba?0:Ea(0,za);Ba="touch"===ua.pointerType?10:2;Ga={x:Ga,y:Ea};Ea={originalEvent:ua,delta:Ga};Aa?(oa.current=Ga,G("toast.swipeMove",aa,Ea)):n(Ga,fa.swipeDirection,Ba)?(oa.current=Ga,G("toast.swipeStart",V,Ea),ua.target.setPointerCapture(ua.pointerId)):(Math.abs(xa)>Ba||Math.abs(za)>Ba)&&(ka.current=null)}}),onPointerUp:C(q.onPointerUp,ua=>{const xa=oa.current;if(ua.target.releasePointerCapture(ua.pointerId),oa.current=
null,ka.current=null,xa){const za=ua.currentTarget;ua={originalEvent:ua,delta:xa};n(xa,fa.swipeDirection,fa.swipeThreshold)?G("toast.swipeEnd",ca,ua):G("toast.swipeCancel",ba,ua);za.addEventListener("click",Aa=>Aa.preventDefault(),{once:!0})}})}))),fa.viewport))):null});c.propTypes={type(q){if(q.type&&!["foreground","background"].includes(q.type))throw Error("Invalid prop `type` supplied to `Toast`. Expected `foreground | background`.");return null}};const z=q=>{const {__scopeToast:B,...x}=q,D=O("Toast",
B),[A,R]=K.useState(!1),[T,S]=K.useState(!1);return function(V=()=>{}){const aa=m(V);b(()=>{let ba=0,ca=0;return ba=window.requestAnimationFrame(()=>ca=window.requestAnimationFrame(aa)),()=>{window.cancelAnimationFrame(ba);window.cancelAnimationFrame(ca)}},[aa])}(()=>R(!0)),K.useEffect(()=>{const V=window.setTimeout(()=>S(!0),1E3);return()=>window.clearTimeout(V)},[]),T?null:K.createElement(d,{asChild:!0},K.createElement(u,{asChild:!0},K.createElement("div",x,A&&K.createElement(K.Fragment,null,D.label,
" ",q.children))))};X=K.forwardRef((q,B)=>{const {__scopeToast:x,...D}=q;return K.createElement(k.div,F({},D,{ref:B}))});g.ToastTitle=X;const a=K.forwardRef((q,B)=>{const {__scopeToast:x,...D}=q;return K.createElement(k.div,F({},D,{ref:B}))});g.ToastDescription=a;const f=K.forwardRef((q,B)=>{const {altText:x,...D}=q;q=P("ToastAction",q.__scopeToast);return x?q.isInteractive?K.createElement(l,F({},D,{ref:B})):K.createElement("span",null,x):null});g.ToastAction=f;f.propTypes={altText(q){if(!q.altText)throw Error("Missing prop `altText` expected on `ToastAction`");
return null}};const l=K.forwardRef((q,B)=>{const {__scopeToast:x,...D}=q,A=P("ToastClose",x);return A.isInteractive?K.createElement(k.button,F({type:"button"},D,{ref:B,onClick:C(q.onClick,A.onClose)})):null});g.ToastClose=l;const n=(q,B,x=0)=>{const D=Math.abs(q.x);q=Math.abs(q.y);const A=D>q;return"left"===B||"right"===B?A&&D>x:!A&&q>x};g.Provider=w;g.Viewport=t;g.Root=Q;g.Title=X;g.Description=a;g.Action=f;g.Close=l};
shadow$provide[425]=function(Q,w,X,g){var E,G,t=(E={},G=w(351),Object.keys(G).forEach(function(u){"default"!==u&&"__esModule"!==u&&Object.defineProperty(E,u,{enumerable:!0,get:function(){return G[u]}})}),E);g.useDirection=function(u,b){const [r,m]=t.useState("ltr"),[k,e]=t.useState(),d=t.useRef(0);return t.useEffect(()=>{if(void 0===b&&null!=u&&u.parentElement){const h=getComputedStyle(u.parentElement);e(h)}},[u,b]),t.useEffect(()=>(void 0===b&&function v(){d.current=requestAnimationFrame(()=>{const C=
null==k?void 0:k.direction;C&&m(C);v()})}(),()=>cancelAnimationFrame(d.current)),[k,b,m]),b||r}};
shadow$provide[426]=function(Q,w,X,g){function E(ra){return ra&&ra.__esModule?ra.default:ra}function G(ra,na){return Object.keys(na).forEach(function(pa){"default"!==pa&&"__esModule"!==pa&&Object.defineProperty(ra,pa,{enumerable:!0,get:function(){return na[pa]}})}),ra}function t(ra){const na=[];for(ra=document.createTreeWalker(ra,NodeFilter.SHOW_ELEMENT,{acceptNode:pa=>{const qa="INPUT"===pa.tagName&&"hidden"===pa.type;return pa.disabled||pa.hidden||qa?NodeFilter.FILTER_SKIP:0<=pa.tabIndex?NodeFilter.FILTER_ACCEPT:
NodeFilter.FILTER_SKIP}});ra.nextNode();)na.push(ra.currentNode);return na}function u(ra){const na=document.activeElement;return ra.some(pa=>pa===na||(pa.focus(),document.activeElement!==na))}function b(ra,na){const pa=k(na);e(()=>{let qa=0;if(ra){const ua=new ResizeObserver(()=>{cancelAnimationFrame(qa);qa=window.requestAnimationFrame(pa)});return ua.observe(ra),()=>{window.cancelAnimationFrame(qa);ua.unobserve(ra)}}},[ra,pa])}function r(ra){return na=>"mouse"===na.pointerType?ra(na):void 0}var m=
G({},w(416)),k=w(406).useCallbackRef,e=w(394).useLayoutEffect,d=w(417).usePrevious,h=w(411).DismissableLayer;Q=w(418).createCollection;var v=w(413).useId,C=w(395).Presence,I=w(425).useDirection;X=w(352);var K=X.composeRefs,F=X.useComposedRefs,H=w(412).useControllableState,L=w(393).Primitive,N=w(410).composeEventHandlers;X=w(414).createContextScope;var O=E(w(404)),M=G({},w(351)),U=E(w(353));const [P,c,z]=Q("NavigationMenu"),[a,f,l]=Q("NavigationMenu"),[n,q]=X("NavigationMenu",[z,l]);g.createNavigationMenuScope=
q;const [B,x]=n("NavigationMenu"),[D,A]=n("NavigationMenu");w=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,value:qa,onValueChange:ua,defaultValue:xa,orientation:za="horizontal",...Aa}=ra,[Ba,Ea]=M.useState(null);na=F(na,Ga=>Ea(Ga));return M.createElement(R,{scope:pa,isRootMenu:!0,value:qa,onValueChange:ua,defaultValue:xa,dir:I(Ba,ra.dir),orientation:za,rootNavigationMenu:Ba},M.createElement(L.nav,U({"aria-label":"Main","data-orientation":za},Aa,{ref:na})))});g.NavigationMenu=w;Q=M.forwardRef((ra,
na)=>{const {__scopeNavigationMenu:pa,value:qa,onValueChange:ua,defaultValue:xa,orientation:za="horizontal",...Aa}=ra;ra=x("NavigationMenuSub",pa);return M.createElement(R,{scope:pa,isRootMenu:!1,value:qa,onValueChange:ua,defaultValue:xa,dir:ra.dir,orientation:za,rootNavigationMenu:ra.rootNavigationMenu},M.createElement(L.div,U({"data-orientation":za},Aa,{ref:na})))});g.NavigationMenuSub=Q;const R=ra=>{const {scope:na,isRootMenu:pa,rootNavigationMenu:qa,value:ua,onValueChange:xa,defaultValue:za,dir:Aa,
orientation:Ba,children:Ea}=ra,[Ga,Ka]=M.useState(null),[Fa,La]=M.useState(new Map),[Ia,Qa]=M.useState(null),Na=M.useRef(0),[Ja="",ja]=H({prop:ua,onChange:xa,defaultProp:za});return M.useEffect(()=>()=>window.clearTimeout(Na.current),[Na]),M.createElement(B,{scope:na,isRootMenu:pa,rootNavigationMenu:qa,value:Ja,previousValue:d(Ja),baseId:v(),dir:Aa,orientation:Ba,viewport:Ga,onViewportChange:Ka,indicatorTrack:Ia,onIndicatorTrackChange:Qa,onItemOver:M.useCallback(Ra=>{pa&&window.clearTimeout(Na.current);
ja(Ra)},[ja,pa]),onItemLeave:M.useCallback(()=>{pa&&(window.clearTimeout(Na.current),Na.current=window.setTimeout(()=>ja(""),150))},[ja,pa]),onItemSelect:M.useCallback(Ra=>{ja(ea=>pa&&ea===Ra?"":Ra)},[ja,pa]),onItemDismiss:M.useCallback(()=>ja(""),[ja]),onViewportContentChange:M.useCallback((Ra,ea)=>{La(eb=>(eb.set(Ra,ea),new Map(eb)))},[]),onViewportContentRemove:M.useCallback(Ra=>{La(ea=>ea.has(Ra)?(ea.delete(Ra),new Map(ea)):ea)},[])},M.createElement(P.Provider,{scope:na},M.createElement(D,{scope:na,
items:Fa},Ea)))};X=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,...qa}=ra;ra=x("NavigationMenuList",pa);na=M.createElement(L.ul,U({"data-orientation":ra.orientation},qa,{ref:na}));return M.createElement(L.div,{style:{position:"relative"},ref:ra.onIndicatorTrackChange},M.createElement(P.Slot,{scope:pa},ra.isRootMenu?M.createElement(va,{asChild:!0},na):na))});g.NavigationMenuList=X;const [T,S]=n("NavigationMenuItem"),V=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,value:qa,...ua}=
ra;ra=v();ra=qa||ra||"LEGACY_REACT_AUTO_VALUE";const xa=M.useRef(null),za=M.useRef(null),Aa=M.useRef(null),Ba=M.useRef(()=>{}),Ea=M.useCallback((Ka="start")=>{if(xa.current){Ba.current();const Fa=t(xa.current);Fa.length&&u("start"===Ka?Fa:Fa.reverse())}},[]),Ga=M.useCallback(()=>{if(xa.current){const Ka=t(xa.current);Ka.length&&(Ba.current=function(Fa){return Fa.forEach(La=>{La.dataset.tabindex=La.getAttribute("tabindex")||"";La.setAttribute("tabindex","-1")}),()=>{Fa.forEach(La=>{La.setAttribute("tabindex",
La.dataset.tabindex)})}}(Ka))}},[]);return M.createElement(T,{scope:pa,value:ra,triggerRef:za,contentRef:xa,focusProxyRef:Aa,onEntryKeyDown:Ea,onFocusProxyEnter:Ea,onRootContentClose:Ga,onContentFocusOutside:Ga},M.createElement(L.li,U({},ua,{ref:na})))});g.NavigationMenuItem=V;const aa=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,disabled:qa,...ua}=ra,xa=x("NavigationMenuTrigger",ra.__scopeNavigationMenu),za=S("NavigationMenuTrigger",ra.__scopeNavigationMenu),Aa=M.useRef(null);na=F(Aa,za.triggerRef,
na);const Ba=`${xa.baseId}-trigger-${za.value}`,Ea=`${xa.baseId}-content-${za.value}`,Ga=M.useRef(!1),Ka=za.value===xa.value;return M.createElement(M.Fragment,null,M.createElement(P.ItemSlot,{scope:pa,value:za.value},M.createElement(sa,{asChild:!0},M.createElement(L.button,U({id:Ba,disabled:qa,"data-disabled":qa?"":void 0,"data-state":Ka?"open":"closed","aria-expanded":Ka,"aria-controls":Ea},ua,{ref:na,onPointerEnter:N(ra.onPointerEnter,()=>{Ga.current=!1}),onPointerMove:N(ra.onPointerMove,r(()=>
{qa||Ga.current||xa.onItemOver(za.value)})),onPointerLeave:N(ra.onPointerLeave,r(()=>{qa||xa.onItemLeave()})),onClick:N(ra.onClick,()=>{xa.onItemSelect(za.value);Ga.current=Ka}),onKeyDown:N(ra.onKeyDown,Fa=>{const La={horizontal:"ArrowDown",vertical:"rtl"===xa.dir?"ArrowLeft":"ArrowRight"}[xa.orientation];Ka&&Fa.key===La&&(za.onEntryKeyDown(),Fa.preventDefault())})})))),Ka&&M.createElement(M.Fragment,null,M.createElement(m.Root,{"aria-hidden":!0,tabIndex:0,ref:za.focusProxyRef,onFocus:Fa=>{var La=
za.contentRef.current;const Ia=Fa.relatedTarget;Fa=Ia===Aa.current;La=null==La?void 0:La.contains(Ia);!Fa&&La||za.onFocusProxyEnter(Fa?"start":"end")}}),xa.viewport&&M.createElement("span",{"aria-owns":Ea})))});g.NavigationMenuTrigger=aa;const ba=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,active:qa,...ua}=ra;return M.createElement(sa,{asChild:!0},M.createElement(L.a,U({"data-active":qa?"":void 0,"aria-current":qa?"page":void 0},ua,{ref:na})))});g.NavigationMenuLink=ba;const ca=M.forwardRef((ra,
na)=>{const {forceMount:pa,...qa}=ra;ra=x("NavigationMenuIndicator",ra.__scopeNavigationMenu);const ua=!!ra.value;return ra.indicatorTrack?O.createPortal(M.createElement(C,{present:pa||ua},M.createElement(Y,U({},qa,{ref:na}))),ra.indicatorTrack):null});g.NavigationMenuIndicator=ca;const Y=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,...qa}=ra,ua=x("NavigationMenuIndicator",pa),xa=c(pa),[za,Aa]=M.useState(null),[Ba,Ea]=M.useState(null),Ga="horizontal"===ua.orientation;ra=!!ua.value;M.useEffect(()=>
{var Fa;const La=null===(Fa=xa().find(Ia=>Ia.value===ua.value))||void 0===Fa?void 0:Fa.ref.current;La&&Aa(La)},[xa,ua.value]);const Ka=()=>{za&&Ea({size:Ga?za.offsetWidth:za.offsetHeight,offset:Ga?za.offsetLeft:za.offsetTop})};return b(za,Ka),b(ua.indicatorTrack,Ka),Ba?M.createElement(L.div,U({"aria-hidden":!0,"data-state":ra?"visible":"hidden","data-orientation":ua.orientation},qa,{ref:na,style:{position:"absolute",...(Ga?{left:0,width:Ba.size+"px",transform:`translateX(${Ba.offset}px)`}:{top:0,
height:Ba.size+"px",transform:`translateY(${Ba.offset}px)`}),...qa.style}})):null}),fa=M.forwardRef((ra,na)=>{const {forceMount:pa,...qa}=ra,ua=x("NavigationMenuContent",ra.__scopeNavigationMenu),xa=S("NavigationMenuContent",ra.__scopeNavigationMenu);na=F(xa.contentRef,na);const za=xa.value===ua.value,Aa={value:xa.value,triggerRef:xa.triggerRef,focusProxyRef:xa.focusProxyRef,onContentFocusOutside:xa.onContentFocusOutside,onRootContentClose:xa.onRootContentClose,...qa};return ua.viewport?M.createElement(ha,
U({forceMount:pa},Aa,{ref:na})):M.createElement(C,{present:pa||za},M.createElement(ka,U({"data-state":za?"open":"closed"},Aa,{ref:na,onPointerEnter:N(ra.onPointerEnter,()=>{ua.onItemOver(xa.value)}),onPointerLeave:N(ra.onPointerLeave,r(ua.onItemLeave)),style:{pointerEvents:!za&&ua.isRootMenu?"none":void 0,...Aa.style}})))});g.NavigationMenuContent=fa;const ha=M.forwardRef((ra,na)=>{const pa=x("NavigationMenuContent",ra.__scopeNavigationMenu),{onViewportContentChange:qa,onViewportContentRemove:ua}=
pa;return e(()=>{qa(ra.value,{ref:na,...ra})},[ra,na,qa]),e(()=>()=>ua(ra.value),[ra.value,ua]),null}),ka=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,value:qa,triggerRef:ua,focusProxyRef:xa,onRootContentClose:za,onContentFocusOutside:Aa,...Ba}=ra,Ea=x("NavigationMenuContent",pa),Ga=M.useRef(null);na=F(Ga,na);const Ka=`${Ea.baseId}-trigger-${qa}`,Fa=`${Ea.baseId}-content-${qa}`,La=c(pa),Ia=M.useRef(null),{onItemDismiss:Qa}=Ea;M.useEffect(()=>{const Ja=Ga.current;if(Ea.isRootMenu&&Ja){const ja=
()=>{var Ra;Qa();za();Ja.contains(document.activeElement)&&(null===(Ra=ua.current)||void 0===Ra||Ra.focus())};return Ja.addEventListener("navigationMenu.contentDismiss",ja),()=>Ja.removeEventListener("navigationMenu.contentDismiss",ja)}},[Ea.isRootMenu,ra.value,ua,Qa,za]);const Na=M.useMemo(()=>{var Ja=La().map(fb=>fb.value);"rtl"===Ea.dir&&Ja.reverse();const ja=Ja.indexOf(Ea.value),Ra=Ja.indexOf(Ea.previousValue),ea=qa===Ea.value,eb=Ra===Ja.indexOf(qa);if(!ea&&!eb)return Ia.current;Ja=(()=>{if(ja!==
Ra){if(ea&&-1!==Ra)return ja>Ra?"from-end":"from-start";if(eb&&-1!==ja)return ja>Ra?"to-start":"to-end"}return null})();return Ia.current=Ja,Ja},[Ea.previousValue,Ea.value,Ea.dir,La,qa]);return M.createElement(va,{asChild:!0},M.createElement(h,U({id:Fa,"aria-labelledby":Ka,"data-motion":Na,"data-orientation":Ea.orientation},Ba,{ref:na,onDismiss:()=>{var Ja;const ja=new Event("navigationMenu.contentDismiss",{bubbles:!0,cancelable:!0});null===(Ja=Ga.current)||void 0===Ja||Ja.dispatchEvent(ja)},onFocusOutside:N(ra.onFocusOutside,
Ja=>{var ja;Aa();const Ra=Ja.target;null!==(ja=Ea.rootNavigationMenu)&&void 0!==ja&&ja.contains(Ra)&&Ja.preventDefault()}),onPointerDownOutside:N(ra.onPointerDownOutside,Ja=>{var ja;const Ra=Ja.target,ea=La().some(fb=>{var jb;return null===(jb=fb.ref.current)||void 0===jb?void 0:jb.contains(Ra)}),eb=Ea.isRootMenu&&(null===(ja=Ea.viewport)||void 0===ja?void 0:ja.contains(Ra));(ea||eb||!Ea.isRootMenu)&&Ja.preventDefault()}),onKeyDown:N(ra.onKeyDown,Ja=>{var ja=Ja.altKey||Ja.ctrlKey||Ja.metaKey;if("Tab"===
Ja.key&&!ja){ja=t(Ja.currentTarget);const ea=document.activeElement,eb=ja.findIndex(fb=>fb===ea);var Ra;u(Ja.shiftKey?ja.slice(0,eb).reverse():ja.slice(eb+1,ja.length))?Ja.preventDefault():null===(Ra=xa.current)||void 0===Ra||Ra.focus()}})})))}),oa=M.forwardRef((ra,na)=>{const {forceMount:pa,...qa}=ra;ra=!!x("NavigationMenuViewport",ra.__scopeNavigationMenu).value;return M.createElement(C,{present:pa||ra},M.createElement(la,U({},qa,{ref:na})))});g.NavigationMenuViewport=oa;const la=M.forwardRef((ra,
na)=>{const {__scopeNavigationMenu:pa,children:qa,...ua}=ra,xa=x("NavigationMenuViewport",pa);na=F(na,xa.onViewportChange);const za=A("NavigationMenuContent",ra.__scopeNavigationMenu),[Aa,Ba]=M.useState(null),[Ea,Ga]=M.useState(null),Ka=Aa?(null==Aa?void 0:Aa.width)+"px":void 0,Fa=Aa?(null==Aa?void 0:Aa.height)+"px":void 0,La=!!xa.value,Ia=La?xa.value:xa.previousValue;return b(Ea,()=>{Ea&&Ba({width:Ea.offsetWidth,height:Ea.offsetHeight})}),M.createElement(L.div,U({"data-state":La?"open":"closed",
"data-orientation":xa.orientation},ua,{ref:na,style:{pointerEvents:!La&&xa.isRootMenu?"none":void 0,"--radix-navigation-menu-viewport-width":Ka,"--radix-navigation-menu-viewport-height":Fa,...ua.style},onPointerEnter:N(ra.onPointerEnter,()=>{xa.onItemOver(Ia)}),onPointerLeave:N(ra.onPointerLeave,r(xa.onItemLeave))}),Array.from(za.items).map(([Qa,{ref:Na,forceMount:Ja,...ja}])=>{const Ra=Ia===Qa;return M.createElement(C,{key:Qa,present:Ja||Ra},M.createElement(ka,U({},ja,{ref:K(Na,ea=>{Ra&&ea&&Ga(ea)})})))}))}),
va=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,...qa}=ra;ra=x("FocusGroup",pa);return M.createElement(a.Provider,{scope:pa},M.createElement(a.Slot,{scope:pa},M.createElement(L.div,U({dir:ra.dir},qa,{ref:na}))))}),ta=["ArrowRight","ArrowLeft","ArrowUp","ArrowDown"],sa=M.forwardRef((ra,na)=>{const {__scopeNavigationMenu:pa,...qa}=ra,ua=f(pa),xa=x("FocusGroupItem",pa);return M.createElement(a.ItemSlot,{scope:pa},M.createElement(L.button,U({},qa,{ref:na,onKeyDown:N(ra.onKeyDown,za=>{if(["Home",
"End",...ta].includes(za.key)){let Aa=ua().map(Ba=>Ba.ref.current);if(["rtl"===xa.dir?"ArrowRight":"ArrowLeft","ArrowUp","End"].includes(za.key)&&Aa.reverse(),ta.includes(za.key)){const Ba=Aa.indexOf(za.currentTarget);Aa=Aa.slice(Ba+1)}setTimeout(()=>u(Aa));za.preventDefault()}})})))});g.Root=w;g.Sub=Q;g.List=X;g.Item=V;g.Trigger=aa;g.Link=ba;g.Indicator=ca;g.Content=fa;g.Viewport=oa};
'use strict';var S4=function(a,b){return $APP.aa[a]=b},T4=function(a,b){if(null!=a&&null!=a.pc)a=a.pc(a,b);else{var c=T4[$APP.da(null==a?null:a)];if(null!=c)a=c.j?c.j(a,b):c.call(null,a,b);else if(c=T4._,null!=c)a=c.j?c.j(a,b):c.call(null,a,b);else throw $APP.If("Router.match-by-path",a);}return a},U4=function(a,b){a&&$APP.Ic($APP.Mc(),a.Od()).fg.push(b)},V4=function(a,b){a&&(a=$APP.Ic($APP.Mc(),a.Od()),b=a.fg.indexOf(b),-1!==b&&a.fg.splice(b,1))},W4=function(a){return a instanceof $APP.Xd?a.clone():
new $APP.Xd(a)},X4=function(a){a=a.toString();":"==a.charAt(0)&&(a=a.substring(1));return a},Y4=function(a){if(!$APP.eM)throw Error("shadow.loader API was called before shadow.loader.init!\nYou are probably calling module loader too early before shadow-cljs got fully initialized.");a=X4(a);return $APP.id.load(a)},Z4=function(){},$4=function(a,b){return"undefined"!==typeof $APP.ye&&"undefined"!==typeof $APP.Hs&&"undefined"!==typeof U4?U4(a,b):a.so(b)},a5=function(a,b){"undefined"!==typeof $APP.ye&&
"undefined"!==typeof $APP.Hs&&"undefined"!==typeof V4?V4(a,b):a.Qo(b)},b5=function(a,b){if($APP.si(b)){var c=$APP.Th(b);b=0<c?new $APP.P(null,2,5,$APP.R,[1<c?$APP.ji(b):null,$APP.ii(b)],null):null;c=$APP.H(b,0,null);b=$APP.H(b,1,null);return a.j?a.j(c,b):a.call(null,c,b)}for(c=$APP.O;;){var d=$APP.x(b);b=$APP.z(d);if(d=$APP.A(d))c=$APP.oj.j(c,b),b=d;else return a.j?a.j(c,b):a.call(null,c,b)}},e5=function(a,b,c){if($APP.ki(b))return c.o?c.o(a):c.call(null,a);var d=$APP.al(a,b,null);c=c.o?c.o(d):c.call(null,
d);return $APP.l($APP.vj.j?$APP.vj.j(c,$APP.mT):$APP.vj.call(null,c,$APP.mT))?a:$APP.l($APP.vj.j?$APP.vj.j(c,$APP.yq):$APP.vj.call(null,c,$APP.yq))?c5?c5(a,b):d5.call(null,a,b):$APP.ct(a,b,c)},d5=function(a){switch(arguments.length){case 3:return f5(arguments[0],arguments[1],arguments[2]);case 2:return c5(arguments[0],arguments[1]);default:for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=new $APP.uh(b.slice(3),0,null);return g5(arguments[0],arguments[1],arguments[2],
b)}},g5=function(a,b,c,d){return e5(a,b,function(e){return $APP.Xj($APP.zo,e,c,d)})},f5=function(a,b,c){return e5(a,b,function(d){return $APP.zo.j(d,c)})},c5=function(a,b){return $APP.x(b)?b5(function(c,d){return f5(a,c,d)},b):a},h5=function(a,b){b=$APP.Wj($APP.Bm,$APP.Ka(a,"__glogi_handlers__"),b);a.__glogi_handlers__=b},i5=function(a,b){function c(e){e=new $APP.k(null,6,[$APP.GS,e.sn,$APP.LV,e.un,$APP.HM,$APP.kn.o(e.bi.name.toLowerCase()),$APP.IJ,e.Qm,$APP.KR,e.Dl,$APP.Xt,e.Xf],null);return b.o?
b.o(e):b.call(null,e)}a=$APP.Nc($APP.Gs(a));if($APP.l(a)){var d=$APP.K.j($APP.Ka(a,"__glogi_handlers__"),b);$APP.l(d)&&a5(a,d);h5(a,$APP.G([b,c]));return null==a?null:$4(a,c)}return null},j5=function(a){return i5("",a)},k5=function(a){switch(arguments.length){case 1:j5(arguments[0]);break;case 2:i5(arguments[0],arguments[1]);break;default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}},l5=function(a){$APP.Jt(a);$APP.eu($APP.fu,a);return null},m5=function(a){return $APP.K.j($APP.Ms,
a).value},n5=function(a){a=$APP.N(a);a=$APP.K.j(a,$APP.BR);return l5(new $APP.P(null,2,5,$APP.R,[$APP.EM,a],null))},o5=function(a,b){var c=$APP.N(a),d=$APP.K.j(c,$APP.IS),e=$APP.K.j(c,$APP.sx),f=$APP.K.j(c,$APP.mx),h=$APP.K.j(c,$APP.cQ),m=$APP.K.j(c,$APP.nx);return $APP.Sr(new $APP.k(null,2,[$APP.OR,function(){return $APP.gu(new $APP.P(null,11,5,$APP.R,[$APP.ax,$APP.kx,d,$APP.sx,e,$APP.mx,f,$APP.nx,m,$APP.lx,h],null))},$APP.ns,function(){function n(){return $APP.gu(new $APP.P(null,3,5,$APP.R,[$APP.ax,
$APP.bx,!0],null))}var q=$APP.r($APP.$u(new $APP.P(null,2,5,$APP.R,[$APP.WT,$APP.kx],null))),u=$APP.N(q),w=$APP.K.j(u,$APP.kx);q=$APP.K.j(u,$APP.sx);var y=$APP.K.j(u,$APP.mx),B=$APP.K.j(u,$APP.lx);u=$APP.K.j(u,$APP.nx);w=$APP.zo.j($APP.zo.j($APP.zo.j($APP.Bm.A($APP.Bm.A(c,$APP.ws,"gglobal"),$APP.kx,w),$APP.nx),$APP.sx),$APP.mx);return new $APP.P(null,5,5,$APP.R,[$APP.Xw,$APP.Yw.Root,w,b,new $APP.P(null,4,5,$APP.R,[$APP.Xw,$APP.Yw.Portal,new $APP.P(null,3,5,$APP.R,[$APP.Xw,$APP.Yw.Overlay,new $APP.k(null,
2,[$APP.xs,"fixed inset-0 bg-black opacity-20",$APP.$w,$APP.l(B)?n:$APP.Zi],null)],null),new $APP.P(null,7,5,$APP.R,[$APP.Xw,$APP.Yw.Content,new $APP.k(null,2,[$APP.xs,"fixed top-50% left-50% transform -translate-x-50% -translate-y-50% bg-no-repeat p-4 fb",$APP.Hw,new $APP.k(null,4,[$APP.aO,"url(/images/popup.png)",$APP.fW,"100%",$APP.Mw,"40rem",$APP.Jw,"20.4775396rem"],null)],null),$APP.l(q)?new $APP.P(null,4,5,$APP.R,[$APP.Xw,$APP.Yw.Title,new $APP.k(null,1,[$APP.xs,"flexr text-center text-2xl"],
null),q],null):q,$APP.l(y)?new $APP.P(null,4,5,$APP.R,[$APP.Xw,$APP.Yw.Description,new $APP.k(null,2,[$APP.xs,"px-16 text-lg flex flex-col justify-center h-76% overflow-auto",$APP.Zw,!0],null),new $APP.P(null,2,5,$APP.R,[$APP.wN,y],null)],null):y,$APP.l(u)?new $APP.P(null,2,5,$APP.R,[$APP.bV,u],null):u,$APP.l(B)?new $APP.P(null,4,5,$APP.R,[$APP.Xw,$APP.Yw.Close,new $APP.k(null,2,[$APP.xs,"absolute top-4 right-4",$APP.$w,n],null),new $APP.P(null,2,5,$APP.R,[$APP.eU,new $APP.k(null,2,[$APP.Hw,new $APP.k(null,
2,[$APP.oQ,"-0.2rem",$APP.Lw,"translateX(10%)"],null),$APP.xL,"/images/panel-close.svg"],null)],null)],null):B],null)],null)],null)}],null),$APP.LX)},q5=function(){return new $APP.P(null,3,5,$APP.R,[o5,new $APP.k(null,4,[$APP.ws,$APP.OU,$APP.sx,"TX Status",$APP.mx,new $APP.P(null,1,5,$APP.R,[$APP.wN],null),$APP.pN,!0],null),new $APP.P(null,2,5,$APP.R,[p5,new $APP.k(null,1,[$APP.xs,"invisible"],null)],null)],null)},r5=function(a,b){return $APP.Yi(function(c,d,e){e=e.o?e.o(b):e.call(null,b);return $APP.Bm.A(c,
d,e)},$APP.dk,a)},s5=function(a){var b=$APP.HQ.o(a);return $APP.l(b)?r5(b,a):null},t5=function(a){var b=a.oc;return $APP.qk.j($APP.dk,$APP.Hk.j($APP.Xm($APP.kn,function(c){c=b.Ad(c);return 2>c.length?c[0]:$APP.rl(c)}),b.cg()))},u5=function(a,b,c){c=$APP.N(c);var d=$APP.K.j(c,$APP.gQ);b=W4(b);var e=$APP.l(d)?function(m){try{return s5(m)}catch(q){if(q instanceof Error){var n=q;d.j?d.j(m,n):d.call(null,m,n);throw n;}throw q;}}:s5;a=T4(a,b.mc);if($APP.l(a)){var f=t5(b),h=$APP.Bm.A(a,$APP.tU,f);a=function(){var m=
e.o?e.o(h):e.call(null,h);return $APP.l(m)?m:new $APP.k(null,2,[$APP.Dy,$APP.fz.o(h),$APP.KW,f],null)}();return $APP.Bm.A(h,$APP.qA,a)}return null},v5=function(a){if(null!=a&&null!=a.yi)a=a.yi(a);else{var b=v5[$APP.da(null==a?null:a)];if(null!=b)a=b.o?b.o(a):b.call(null,a);else if(b=v5._,null!=b)a=b.o?b.o(a):b.call(null,a);else throw $APP.If("History.-init",a);}return a},w5=function(a){if(null!=a&&null!=a.zi)a=a.zi(a);else{var b=w5[$APP.da(null==a?null:a)];if(null!=b)a=b.o?b.o(a):b.call(null,a);else if(b=
w5._,null!=b)a=b.o?b.o(a):b.call(null,a);else throw $APP.If("History.-stop",a);}return a},x5=function(a){if(null!=a&&null!=a.dh)a=a.dh(a);else{var b=x5[$APP.da(null==a?null:a)];if(null!=b)a=b.o?b.o(a):b.call(null,a);else if(b=x5._,null!=b)a=b.o?b.o(a):b.call(null,a);else throw $APP.If("History.-get-path",a);}return a},y5=function(a,b,c,d,e,f,h,m){this.za=a;this.Ea=b;this.nc=c;this.jc=d;this.kc=e;this.Z=f;this.G=h;this.N=m;this.D=2230716170;this.I=139264},z5=function(a,b,c,d){var e="undefined"!==typeof location?
W4(location).tc:null;return(e=$APP.Af(!!d.pd)&&$APP.Af(!!d.tc)||$APP.D.j(e,d.tc))?(e=$APP.Af(b.altKey))?(e=$APP.Af(b.ctrlKey))?(e=$APP.Af(b.metaKey))?(e=$APP.Af(b.shiftKey))?(e=$APP.Af(c.hasAttribute("target"))||$APP.Ki(new $APP.Hm(null,new $APP.k(null,2,["",null,"_self",null],null),null),c.getAttribute("target")))?(b=$APP.D.j(0,b.button))?(c=$APP.Af(c.isContentEditable))?T4(a,d.mc):c:b:e:e:e:e:e:e},A5=function(a,b,c,d,e,f,h){this.za=a;this.Ea=b;this.vc=c;this.sc=d;this.Z=e;this.G=f;this.N=h;this.D=
2230716170;this.I=139264},B5=function(a,b){b=$APP.N(b);var c=$APP.K.A(b,$APP.jR,!0);b=$APP.Bm.B($APP.zo.j(b,$APP.jR),$APP.zA,$APP.g_,$APP.G([$APP.XW,a]));a=v5;$APP.l(c)?(c=$APP.zo.B(b,$APP.XW,$APP.G([$APP.zA,$APP.jU,$APP.vQ,$APP.UV])),c=$APP.ri(b)?$APP.qk.j($APP.dk,c):c,b=new y5($APP.XW.o(b),$APP.zA.o(b),$APP.jU.o(b),$APP.vQ.o(b),$APP.UV.o(b),null,$APP.ek(c),null)):(c=$APP.zo.B(b,$APP.XW,$APP.G([$APP.zA,$APP.eS,$APP.BW])),c=$APP.ri(b)?$APP.qk.j($APP.dk,c):c,b=new A5($APP.XW.o(b),$APP.zA.o(b),$APP.eS.o(b),
$APP.BW.o(b),null,$APP.ek(c),null));a(b)},C5=function(a){return $APP.l(a)?w5(a):null},E5=function(){var a=D5,b=new $APP.k(null,1,[$APP.jR,!0],null);$APP.wn.j($APP.KZ,C5);B5(function(c,d){null==$APP.r($APP.KZ)&&$APP.Ak($APP.KZ,d);return a.j?a.j(c,d):a.call(null,c,d)},b)},F5=function(a,b){a=$APP.Nm(a);a=$APP.D.j(a,"council")?"battlefield":a;return $APP.l(!!$APP.id.cb[X4(a)].hd)?b.C?b.C():b.call(null):Y4(a).then(b,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,$APP.NP],null))})},D5=function(a){if($APP.l(a)){var b=
$APP.Xx.o(a),c=$APP.N(b);b=$APP.K.j(c,$APP.V);c=$APP.K.j(c,$APP.ND);$APP.Ps("fgl.app.routes",new $APP.k(null,2,[$APP.oV,b,$APP.To,229],null));return $APP.l(c)?F5(b,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.wW,a],null))}):$APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.wW,a],null))}return null},G5=function(){return new $APP.P(null,2,5,$APP.R,[$APP.Hw,".guild-outer-menu {\n        background-image: linear-gradient(\n            to bottom,\n            rgba(40, 84, 95),\n            rgba(40, 84, 95, 0.5) 60%,\n            transparent 80%\n          ),\n          linear-gradient(to bottom, #1a2a31, #1a2a31 60%, #1a2a3130);\n      }\n\n      .guild-outer-menu li\x3ebutton {\n        position: relative;\n        width: 100%;\n        margin-top: 2rem;\n        text-align: center;\n        display: flex;\n        justify-content: center;\n        align-items: center;\n      }\n\n      .guild-outer-menu .guild-icon {\n        position: relative;\n        display: inline-block;\n        width: 1.3rem;\n        height: 1.3rem;\n        background-position: center;\n        background-repeat: no-repeat;\n        background-size: contain;\n        cursor: pointer;\n        z-index: 1;\n      }\n\n      .guild-outer-menu .guild-bg-light {\n        visibility: hidden;\n        position: absolute;\n        display: inline-block;\n        width: 3rem;\n        height: 3rem;\n        top: 50%;\n        left: 50%;\n        transform: translate(-50%, -50%);\n        background-image: radial-gradient(\n          #55e6ff,\n          #55e6ff90 20%,\n          #55e6ff10 50%,\n          transparent 60%,\n          transparent\n        );\n        background-size: 100%;\n        z-index: 0;\n      }\n      .guild-outer-menu li\x3ebutton.active .guild-bg-light {\n        visibility: visible;\n      }"],
null)},H5=function(a,b){var c=$APP.D.j(a,$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[$APP.HN],null)))),d=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[$APP.jO],null)));d=$APP.K.A(d,$APP.Xx,$APP.dk);d=$APP.N(d);d=$APP.K.j(d,$APP.V);d=$APP.l(d)?$APP.Nm(d).startsWith(b):d;return $APP.gi(new $APP.P(null,4,5,$APP.R,[$APP.$P,new $APP.k(null,4,[$APP.xs,$APP.l(d)?"active":"",$APP.aN,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.pW,a],null))},$APP.uU,function(){return $APP.gu(new $APP.P(null,1,5,
$APP.R,[$APP.pW],null))},$APP.$w,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,a],null))}],null),new $APP.P(null,2,5,$APP.R,[$APP.AQ,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.aO,$APP.l(c?c:d)?["url(/images/menu-tab-",$APP.p.o(b),"-active.svg)"].join(""):["url(/images/menu-tab-",$APP.p.o(b),".svg)"].join("")],null)],null)],null),new $APP.P(null,1,5,$APP.R,[$APP.CQ],null)],null),new $APP.k(null,1,[$APP.Kq,b],null))},I5=function(){return new $APP.P(null,3,5,$APP.R,[$APP.fx,new $APP.P(null,
1,5,$APP.R,[G5],null),new $APP.P(null,6,5,$APP.R,[$APP.kT,new $APP.P(null,3,5,$APP.R,[H5,$APP.FS,"guild"],null),new $APP.P(null,3,5,$APP.R,[H5,$APP.UT,"battlefield"],null),new $APP.P(null,3,5,$APP.R,[H5,$APP.eO,"council"],null),new $APP.P(null,3,5,$APP.R,[H5,$APP.lP,"merchant"],null),new $APP.P(null,3,5,$APP.R,[H5,$APP.dV,"rank"],null)],null)],null)},J5=function(a,b){return[$APP.p.o(a/b),"rem"].join("")},L5=function(a,b,c,d,e){a=$APP.No.j(J5,c);var f=a(54.87179487);return new $APP.P(null,3,5,$APP.R,
[$APP.cO,new $APP.P(null,1,5,$APP.R,[I5],null),new $APP.P(null,4,5,$APP.R,[K5,c,new $APP.P(null,4,5,$APP.R,[$APP.tV,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.jV,"0.5%"],null)],null),new $APP.P(null,3,5,$APP.R,[$APP.gX,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.uL,a(60)],null)],null),b],null),new $APP.P(null,3,5,$APP.R,[$APP.DP,new $APP.k(null,1,[$APP.$w,d],null),new $APP.P(null,2,5,$APP.R,[$APP.wL,new $APP.k(null,2,[$APP.xL,"/images/panel-close.svg",$APP.Hw,new $APP.k(null,3,[$APP.Mw,
f,$APP.Jw,f,$APP.JR,a(685.89743588)],null)],null)],null)],null)],null),e],null)],null)},U5=function(a){var b=m5(a);return $APP.l(function(){var c=m5($APP.AV);return $APP.fJ.j?$APP.fJ.j(c,b):$APP.fJ.call(null,c,b)}())?M5:$APP.l(function(){var c=m5($APP.mQ);return $APP.fJ.j?$APP.fJ.j(c,b):$APP.fJ.call(null,c,b)}())?N5:$APP.l(function(){var c=m5($APP.rU);return $APP.fJ.j?$APP.fJ.j(c,b):$APP.fJ.call(null,c,b)}())?O5:$APP.l(function(){var c=m5($APP.pS);return $APP.fJ.j?$APP.fJ.j(c,b):$APP.fJ.call(null,
c,b)}())?P5:$APP.l(function(){var c=m5($APP.GT);return $APP.fJ.j?$APP.fJ.j(c,b):$APP.fJ.call(null,c,b)}())?Q5:$APP.l(function(){var c=m5($APP.nT);return $APP.fJ.j?$APP.fJ.j(c,b):$APP.fJ.call(null,c,b)}())?R5:$APP.l(function(){var c=m5($APP.JP);return $APP.fJ.j?$APP.fJ.j(c,b):$APP.fJ.call(null,c,b)}())?S5:T5},V5=function(a){var b=$APP.H(a,0,null);a=$APP.H(a,1,null);return new $APP.P(null,2,5,$APP.R,[[$APP.p.o(b),$APP.p.o(" ")].join(""),a],null)},X5=function(a,b,c){var d=$APP.H(a,0,null);a=$APP.H(a,
1,null);return new $APP.P(null,2,5,$APP.R,[[$APP.p.o(d),"%c",$APP.p.o(b),"%c"].join(""),$APP.oj.B(a,["color:",$APP.p.o($APP.K.j(W5,c))].join(""),$APP.G(["color:black"]))],null)},Z5=function(a,b,c){var d=$APP.H(a,0,null);a=$APP.H(a,1,null);return new $APP.P(null,2,5,$APP.R,[[$APP.p.o(d),"%c",$APP.p.o(b),"%c"].join(""),$APP.oj.B(a,["color:",$APP.p.o($APP.K.j(W5,Y5)),";background-color:",$APP.p.o($APP.K.j(W5,c))].join(""),$APP.G(["color:black;background-color:inherit"]))],null)},$5=function(a){function b(c,
d){return d>=c}a=m5(a);if(b(m5($APP.AV),a))return"error";if(b(m5($APP.mQ),a))return"warn";if(b(m5($APP.rU),a))return"info";b(m5($APP.pS),a);return"log"},a6=function(a){return function(b){b=$APP.N(b);var c=$APP.K.j(b,$APP.KR),d=$APP.K.j(b,$APP.HM),e=$APP.K.j(b,$APP.Xt);d=$5(d);d=$APP.Ka(console,d);d=$APP.l(d)?d:console.log;$APP.Vj(d,a.o?a.o(b):a.call(null,b));return $APP.l(e)?d(["[",$APP.p.o(c),"]"].join(""),$APP.p.o(e),"\n",e.stack):null}},c6=function(a,b,c){var d=$APP.Ar;$APP.Ar=!0;try{$APP.ZY.render(a.C?
a.C():a.call(null),b,function(){var e=$APP.Ar;$APP.Ar=!1;try{return $APP.wn.J(b6,$APP.Bm,b,a),$APP.Tq.flush_after_render(),null!=c?c.C?c.C():c.call(null):null}finally{$APP.Ar=e}})}finally{$APP.Ar=d}},g6=function(){var a=d6,b=new $APP.P(null,1,5,$APP.R,[e6],null);$APP.pr();var c=$APP.ei($APP.LX)?new $APP.P(null,2,5,$APP.R,[$APP.LX,$APP.LX],null):new $APP.P(null,2,5,$APP.R,[$APP.LX,f6.o($APP.LX)],null),d=$APP.H(c,0,null);c=$APP.H(c,1,null);c6(function(){return $APP.Xq(d,$APP.ei(b)?b.C?b.C():b.call(null):
b)},a,c)},h6=function(){return new $APP.P(null,2,5,$APP.R,[$APP.Hw,'button.menu-active::after {\n        content: "";\n        position: absolute;\n        width: 0;\n        height: 0;\n        border: 0.5rem solid transparent;\n        border-left: 0.5rem solid #25606a;\n        left: 100%;\n        top: 50%;\n        transform: translateY(-50%);\n      }'],null)},k6=function(a,b){function c(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,b],null))}return function(){var d=$APP.r($APP.$u(new $APP.P(null,
1,5,$APP.R,[$APP.jO],null))),e=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[i6],null)));d=$APP.K.A(d,$APP.Xx,$APP.dk);d=$APP.N(d);d=$APP.K.j(d,$APP.V);d=$APP.D.j(d,b);e=$APP.D.j(e,b);return $APP.gi(new $APP.P(null,3,5,$APP.R,[j6,new $APP.k(null,5,[$APP.oU,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[i6,b],null))},$APP.RO,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[i6,null],null))},$APP.$w,c,$APP.xs,d?"menu-active":"",$APP.Hw,e||d?new $APP.k(null,2,[$APP.vL,"radial-gradient(farthest-corner ellipse at top center, #3c8895, #1f545d)",
$APP.TP,"white"],null):$APP.dk],null),a],null),new $APP.k(null,1,[$APP.Kq,a],null))}},q6=function(a,b){a=$APP.N(a);a=$APP.K.j(a,l6);return new $APP.P(null,5,5,$APP.R,[m6,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,2,[$APP.zO,"12rem 1fr",$APP.Jw,"90.8%"],null)],null),$APP.l(a)?new $APP.P(null,2,5,$APP.R,[n6,new $APP.k(null,4,[$APP.Rx,"stylesheet",$APP.Qx,a,$APP.U,"text/css",o6,"screen"],null)],null):a,new $APP.P(null,6,5,$APP.R,[p6,new $APP.P(null,2,5,$APP.R,["Basic",$APP.FS],null),new $APP.P(null,
2,5,$APP.R,["Alter",$APP.WU],null),new $APP.P(null,2,5,$APP.R,["Vote",$APP.TS],null),new $APP.P(null,2,5,$APP.R,["Management",$APP.hU],null),new $APP.P(null,2,5,$APP.R,["Allocation",$APP.ZP],null)],null),b],null)},r6=function(a,b){a=$APP.N(a);a=$APP.K.j(a,l6);return new $APP.P(null,5,5,$APP.R,[m6,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,2,[$APP.zO,"12rem 1fr",$APP.Jw,"90.8%"],null)],null),$APP.l(a)?new $APP.P(null,2,5,$APP.R,[n6,new $APP.k(null,4,[$APP.Rx,"stylesheet",$APP.Qx,a,$APP.U,"text/css",
o6,"screen"],null)],null):a,new $APP.P(null,5,5,$APP.R,[p6,new $APP.P(null,2,5,$APP.R,["Mint",$APP.lP],null),new $APP.P(null,2,5,$APP.R,["Land Deeds",$APP.uO],null),new $APP.P(null,2,5,$APP.R,["Burn Land Deeds",$APP.nN],null),new $APP.P(null,2,5,$APP.R,["$GLORY for $GOLD",$APP.XM],null)],null),b],null)},w6=function(a,b,c,d,e,f){c="string"===typeof c?new $APP.P(null,2,5,$APP.R,[$APP.tx,c],null):c;return new $APP.P(null,7,5,$APP.R,[$APP.Xw,s6.Root,new $APP.k(null,2,[$APP.Kq,a,t6,function(h){return(h=
$APP.Af(h))?$APP.gu(new $APP.P(null,2,5,$APP.R,[u6,a],null)):h}],null),new $APP.P(null,3,5,$APP.R,[$APP.Xw,s6.Title,"string"===typeof b?new $APP.P(null,2,5,$APP.R,[v6,b],null):b],null),$APP.l(c)?new $APP.P(null,3,5,$APP.R,[$APP.Xw,s6.Description,c],null):c,function(){var h=$APP.x(f);return h?$APP.Hk.j(function(m){return $APP.qk.o(new $APP.P(null,3,5,$APP.R,[$APP.Xw,s6.Action,m],null))},f):h}(),function(){var h=$APP.Af(e);return h?new $APP.P(null,3,5,$APP.R,[$APP.Xw,s6.Close,"x"],null):h}()],null)},
y6=function(){var a=$APP.$u(new $APP.P(null,1,5,$APP.R,[x6],null));return $APP.Hk.j(function(b){var c=$APP.H(b,0,null);b=$APP.H(b,1,null);var d=$APP.N(b);b=$APP.K.j(d,$APP.sx);var e=$APP.K.j(d,$APP.mx),f=$APP.K.j(d,$APP.U),h=$APP.K.j(d,$APP.xW);d=$APP.K.j(d,$APP.nx);return $APP.gi(new $APP.P(null,7,5,$APP.R,[w6,c,b,e,f,h,d],null),new $APP.k(null,1,[$APP.Kq,c],null))},$APP.r(a))},B6=function(){return new $APP.P(null,3,5,$APP.R,[$APP.qk,$APP.gi(new $APP.P(null,3,5,$APP.R,[$APP.Xw,s6.Provider,new $APP.P(null,
4,5,$APP.R,[$APP.Xw,s6.Viewport,new $APP.k(null,1,[$APP.Zw,!0],null),new $APP.P(null,1,5,$APP.R,[z6],null)],null)],null),new $APP.k(null,1,[$APP.Kq,A6],null)),y6()],null)},C6=function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,$APP.uS],null))},E6=function(a){return new $APP.P(null,3,5,$APP.R,[D6,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.OT,"64vw"],null)],null),a],null)},H6=function(a,b){var c=$APP.N(a),d=$APP.K.j(c,$APP.V),e=$APP.K.j(c,$APP.zR);c=$APP.Nm($APP.l(d)?d:$APP.IV).startsWith("guild");
var f=$APP.Nm($APP.l(d)?d:$APP.IV).startsWith("merchant");d=$APP.Nm($APP.l(d)?d:$APP.IV).startsWith("the-map");return new $APP.P(null,5,5,$APP.R,[F6,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,2,[$APP.zO,"1fr auto 1fr",G6,"strech"],null)],null),new $APP.P(null,2,5,$APP.R,[$APP.l(d)?$APP.Zi:E6,new $APP.P(null,2,5,$APP.R,[$APP.l(e)?function(h){return new $APP.P(null,6,5,$APP.R,[L5,a,e,80,C6,h],null)}:$APP.Zi,new $APP.P(null,2,5,$APP.R,[$APP.l(c)?function(h){return new $APP.P(null,3,5,$APP.R,[q6,a,h],
null)}:$APP.l(f)?function(h){return new $APP.P(null,3,5,$APP.R,[r6,a,h],null)}:$APP.Zi,b],null)],null)],null),new $APP.P(null,1,5,$APP.R,[B6],null),new $APP.P(null,1,5,$APP.R,[q5],null)],null)},J6=function(a){return $APP.Sr(new $APP.k(null,2,[$APP.OR,function(){return $APP.l(a)?n5(new $APP.k(null,1,[$APP.BR,a],null)):a},$APP.ns,function(){var b=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[I6],null))),c=$APP.H(b,0,null),d=$APP.H(b,1,null),e=$APP.H(b,2,null);b=$APP.H(b,3,null);return $APP.Af(e)?new $APP.P(null,
3,5,$APP.R,[$APP.Ww,new $APP.k(null,4,[$APP.ws,"connect-btn",$APP.Rw,$APP.oW,$APP.V,d,$APP.$w,b],null),new $APP.P(null,2,5,$APP.R,[$APP.gx,c],null)],null):$APP.l(e)?new $APP.P(null,2,5,$APP.R,[$APP.gx,c],null):null}],null),$APP.LX)},M6=function(a){return new $APP.P(null,4,5,$APP.R,[$APP.Xw,K6.Root,new $APP.k(null,2,[$APP.xs,"bg-no-repeat",$APP.Hw,new $APP.k(null,4,[$APP.aO,'\nlinear-gradient(to right, rgba(0,0,0,.302),rgba(0,0,0,.302)),\nlinear-gradient(to right, rgba(0,0,0,.302),rgba(0,0,0,.302)),\nurl("/images/header-bg.svg")\n',
L6,"multiply",$APP.bW,"100% 37%, -8% -16%, 63% -33%",$APP.fW,"8.5% 44%, 100% 57%, 100% 77%"],null)],null),a],null)},V6=function(){$APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.LS],null));$APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.VM],null));$APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.yN],null));var a=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[N6],null))),b=$APP.H(a,0,null),c=$APP.H(a,1,null);a=$APP.H(a,2,null);return new $APP.P(null,2,5,$APP.R,[O6,new $APP.P(null,2,5,$APP.R,[M6,new $APP.P(null,8,5,$APP.R,[$APP.Xw,
K6.List,new $APP.k(null,1,[$APP.xs,"grid auto-cols-max auto-rows-max justify-items-stretch justify-between items-center content-center pt-2"],null),$APP.gi(new $APP.P(null,4,5,$APP.R,[$APP.Xw,K6.Item,new $APP.k(null,1,[$APP.xs,"cs1 ce3 rs1 re3"],null),new $APP.P(null,4,5,$APP.R,[$APP.Xw,K6.Link,new $APP.k(null,2,[$APP.xs,"cursor-pointer block p-2",$APP.$w,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,$APP.uS],null))}],null),new $APP.P(null,2,5,$APP.R,[P6,new $APP.k(null,1,[$APP.Hw,
new $APP.k(null,1,[$APP.OT,"8.8125rem"],null)],null)],null)],null)],null),new $APP.k(null,1,[$APP.Kq,Q6],null)),$APP.gi(new $APP.P(null,4,5,$APP.R,[$APP.Xw,K6.Item,new $APP.k(null,1,[$APP.xs,"cs7 ce9"],null),new $APP.P(null,2,5,$APP.R,[$APP.lZ,new $APP.P(null,3,5,$APP.R,[$APP.aP,new $APP.P(null,3,5,$APP.R,[$APP.iZ,"3rem",new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.zL,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.P(null,3,5,$APP.R,[$APP.gZ,c,new $APP.k(null,1,[$APP.xs,"fi mr-1"],
null)],null)],null)],null)],null),new $APP.k(null,1,[$APP.Kq,R6],null)),$APP.gi(new $APP.P(null,4,5,$APP.R,[$APP.Xw,K6.Item,new $APP.k(null,1,[$APP.xs,"cs9 ce11"],null),new $APP.P(null,2,5,$APP.R,[$APP.lZ,new $APP.P(null,3,5,$APP.R,[$APP.aP,new $APP.P(null,3,5,$APP.R,[$APP.uZ,"3rem",new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[$APP.zL,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.P(null,3,5,$APP.R,[$APP.gZ,b,new $APP.k(null,1,[$APP.xs,"fi mr-1"],null)],null)],null)],null)],null),new $APP.k(null,
1,[$APP.Kq,$APP.WM],null)),$APP.gi(new $APP.P(null,4,5,$APP.R,[$APP.Xw,K6.Item,new $APP.k(null,1,[$APP.xs,"cs11 ce13"],null),new $APP.P(null,2,5,$APP.R,[$APP.lZ,new $APP.P(null,6,5,$APP.R,[S6,new $APP.P(null,2,5,$APP.R,[$APP.uZ,"2rem"],null),new $APP.P(null,2,5,$APP.R,[$APP.PV,"1"],null),new $APP.P(null,3,5,$APP.R,[$APP.RU,new $APP.P(null,2,5,$APP.R,[$APP.dU,new $APP.k(null,1,[$APP.xL,"/images/ratio.svg"],null)],null),new $APP.P(null,2,5,$APP.R,[$APP.dU,new $APP.k(null,2,[$APP.Hw,new $APP.k(null,
1,[$APP.Lw,"rotate(180deg)"],null),$APP.xL,"/images/ratio.svg"],null)],null)],null),a,new $APP.P(null,3,5,$APP.R,[$APP.iZ,"2rem",new $APP.k(null,1,[$APP.xs,"mx-1"],null)],null)],null)],null)],null),new $APP.k(null,1,[$APP.Kq,T6],null)),$APP.gi(new $APP.P(null,4,5,$APP.R,[$APP.Xw,K6.Item,new $APP.k(null,1,[$APP.xs,"cs13 ce15"],null),new $APP.P(null,2,5,$APP.R,[J6,"0x4"],null)],null),new $APP.k(null,1,[$APP.Kq,U6],null))],null)],null)],null)},e6=function(){var a=$APP.$u(new $APP.P(null,1,5,$APP.R,[$APP.hO],
null)),b=$APP.$u(new $APP.P(null,1,5,$APP.R,[$APP.vS],null)),c=$APP.r($APP.$u(new $APP.P(null,1,5,$APP.R,[$APP.jO],null)));c=$APP.K.A(c,$APP.Xx,$APP.dk);c=$APP.N(c);var d=$APP.K.j(c,$APP.V),e=$APP.K.j(c,$APP.sQ);setTimeout(function(){return $APP.l(function(){var f=!$APP.D.j($APP.r(a),$APP.SP);return f?$APP.l(d)?!$APP.D.j(d,$APP.uS):d:f}())?($APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,$APP.uS],null)),$APP.Bw(),new $APP.P(null,1,5,$APP.R,[$APP.wN],null)):$APP.l(function(){var f=$APP.D.j($APP.r(a),$APP.SP);
return f?(f=$APP.r(b),$APP.l(f)?$APP.l(d)?!$APP.D.j(d,$APP.uS):d:f):f}())?($APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,$APP.uS],null)),$APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.RQ],null)),new $APP.P(null,1,5,$APP.R,[$APP.wN],null)):null},500);return new $APP.P(null,6,5,$APP.R,[W6,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,1,[X6,'"header" min-content "main"'],null)],null),new $APP.P(null,1,5,$APP.R,[V6],null),new $APP.P(null,1,5,$APP.R,[$APP.CL],null),new $APP.P(null,3,5,$APP.R,[H6,c,$APP.l(e)?new $APP.P(null,
2,5,$APP.R,[e,c],null):new $APP.P(null,1,5,$APP.R,[$APP.wN],null)],null),new $APP.P(null,2,5,$APP.R,[n6,new $APP.k(null,2,[$APP.Rx,"stylesheet",$APP.Qx,"/fonts/family.css"],null)],null)],null)};$APP.Vz.prototype.pc=S4(5,function(a,b){a=this.Qc.o?this.Qc.o(b):this.Qc.call(null,b);return $APP.l(a)?$APP.Bm.A($APP.Bm.A($APP.Xx.o(a),$APP.fz,$APP.Hx.o(a)),$APP.Dy,b):null});$APP.zZ.prototype.pc=S4(4,function(a,b){return $APP.Iz(this.data,b)});
$APP.AZ.prototype.pc=S4(3,function(a,b){a=this.Qc;a=$APP.l(a)?this.Qc.o?this.Qc.o(b):this.Qc.call(null,b):a;return $APP.l(a)?$APP.Bm.A($APP.Bm.A($APP.Xx.o(a),$APP.fz,$APP.Hx.o(a)),$APP.Dy,b):null});$APP.BZ.prototype.pc=S4(2,function(a,b){return $APP.D.j(this.p,b)?this.match:null});$APP.CZ.prototype.pc=S4(1,function(a,b){a=T4(this.ih,b);return $APP.l(a)?a:T4(this.ph,b)});$APP.DZ.prototype.pc=S4(0,function(a,b){a=T4(this.Tg,b);return $APP.l(a)?a:T4(this.kg,b)});
var p5=function p5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.uh(c.slice(0),0,null):null;return p5.B(c)};p5.B=function(a){return new $APP.P(null,3,5,$APP.R,[$APP.qk,new $APP.P(null,2,5,$APP.R,[$APP.Xw,$APP.Yw.Trigger],null),a],null)};p5.H=0;p5.T=function(a){return this.B($APP.x(a))};$APP.g=y5.prototype;$APP.g.Fa=function(a,b){return this.ga(null,b,null)};
$APP.g.ga=function(a,b,c){switch(b instanceof $APP.tj?b.qa:null){case "on-navigate":return this.za;case "router":return this.Ea;case "popstate-listener":return this.nc;case "hashchange-listener":return this.jc;case "last-fragment":return this.kc;default:return $APP.K.A(this.G,b,c)}};$APP.g.Rb=function(a,b,c){return $APP.Lf.A(function(d,e){var f=$APP.H(e,0,null);e=$APP.H(e,1,null);return b.A?b.A(d,f,e):b.call(null,d,f,e)},c,this)};
$APP.g.ha=function(a,b,c){return $APP.dn(b,function(d){return $APP.dn(b,$APP.jn,""," ","",c,d)},"#reitit.frontend.history.FragmentHistory{",", ","}",c,$APP.Ok.j(new $APP.P(null,5,5,$APP.R,[new $APP.P(null,2,5,$APP.R,[$APP.XW,this.za],null),new $APP.P(null,2,5,$APP.R,[$APP.zA,this.Ea],null),new $APP.P(null,2,5,$APP.R,[$APP.jU,this.nc],null),new $APP.P(null,2,5,$APP.R,[$APP.vQ,this.jc],null),new $APP.P(null,2,5,$APP.R,[$APP.UV,this.kc],null)],null),this.G))};
$APP.g.La=function(){return new $APP.Jl(this,5,new $APP.P(null,5,5,$APP.R,[$APP.XW,$APP.zA,$APP.jU,$APP.vQ,$APP.UV],null),$APP.l(this.G)?$APP.bh(this.G):$APP.ik())};$APP.g.O=function(){return this.Z};$APP.g.pa=function(){return 5+$APP.Th(this.G)};$APP.g.la=function(){var a=this.N;return null!=a?a:this.N=a=354327177^$APP.Eh(this)};
$APP.g.ka=function(a,b){return null!=b&&this.constructor===b.constructor&&$APP.D.j(this.za,b.za)&&$APP.D.j(this.Ea,b.Ea)&&$APP.D.j(this.nc,b.nc)&&$APP.D.j(this.jc,b.jc)&&$APP.D.j(this.kc,b.kc)&&$APP.D.j(this.G,b.G)};
$APP.g.yi=function(){function a(e){var f=x5(c);return $APP.D.j("popstate",e.type)||$APP.Em.j($APP.r(b),f)?$APP.xA(c,f):null}var b=$APP.zk(null),c=$APP.Bm.A(this,$APP.UV,b),d=$APP.Bm.B(c,$APP.jU,$APP.Bd(window,"popstate",a,!1),$APP.G([$APP.vQ,$APP.Bd(window,"hashchange",a,!1)]));$APP.xA(d,x5(d));return d};$APP.g.zi=function(){$APP.Md(this.nc);$APP.Md(this.jc);return null};$APP.g.sf=function(a,b){$APP.Ak(this.kc,b);a=u5(this.Ea,b,this);return this.za.j?this.za.j(a,this):this.za.call(null,a,this)};
$APP.g.dh=function(){var a=window.location.hash.substring(1);return $APP.D.j("",a)?"/":a};$APP.g.xi=function(a,b){return $APP.l(b)?["#",$APP.p.o(b)].join(""):null};$APP.g.fc=function(a,b){return $APP.Ki(new $APP.Hm(null,new $APP.k(null,5,[$APP.UV,null,$APP.zA,null,$APP.jU,null,$APP.XW,null,$APP.vQ,null],null),null),b)?$APP.zo.j($APP.vg($APP.qk.j($APP.dk,this),this.Z),b):new y5(this.za,this.Ea,this.nc,this.jc,this.kc,this.Z,$APP.ek($APP.zo.j(this.G,b)),null)};
$APP.g.Cb=function(a,b){switch(b instanceof $APP.tj?b.qa:null){case "on-navigate":case "router":case "popstate-listener":case "hashchange-listener":case "last-fragment":return!0;default:return $APP.Ki(this.G,b)}};
$APP.g.Ba=function(a,b,c){return $APP.l($APP.vj.j?$APP.vj.j($APP.XW,b):$APP.vj.call(null,$APP.XW,b))?new y5(c,this.Ea,this.nc,this.jc,this.kc,this.Z,this.G,null):$APP.l($APP.vj.j?$APP.vj.j($APP.zA,b):$APP.vj.call(null,$APP.zA,b))?new y5(this.za,c,this.nc,this.jc,this.kc,this.Z,this.G,null):$APP.l($APP.vj.j?$APP.vj.j($APP.jU,b):$APP.vj.call(null,$APP.jU,b))?new y5(this.za,this.Ea,c,this.jc,this.kc,this.Z,this.G,null):$APP.l($APP.vj.j?$APP.vj.j($APP.vQ,b):$APP.vj.call(null,$APP.vQ,b))?new y5(this.za,
this.Ea,this.nc,c,this.kc,this.Z,this.G,null):$APP.l($APP.vj.j?$APP.vj.j($APP.UV,b):$APP.vj.call(null,$APP.UV,b))?new y5(this.za,this.Ea,this.nc,this.jc,c,this.Z,this.G,null):new y5(this.za,this.Ea,this.nc,this.jc,this.kc,this.Z,$APP.Bm.A(this.G,b,c),null)};$APP.g.oa=function(){return $APP.x($APP.Ok.j(new $APP.P(null,5,5,$APP.R,[new $APP.Li($APP.XW,this.za),new $APP.Li($APP.zA,this.Ea),new $APP.Li($APP.jU,this.nc),new $APP.Li($APP.vQ,this.jc),new $APP.Li($APP.UV,this.kc)],null),this.G))};
$APP.g.P=function(a,b){return new y5(this.za,this.Ea,this.nc,this.jc,this.kc,b,this.G,this.N)};$APP.g.sa=function(a,b){return $APP.si(b)?this.Ba(null,$APP.ci(b,0),$APP.ci(b,1)):$APP.Lf.A($APP.Vf,this,b)};$APP.g=A5.prototype;$APP.g.Fa=function(a,b){return this.ga(null,b,null)};
$APP.g.ga=function(a,b,c){switch(b instanceof $APP.tj?b.qa:null){case "on-navigate":return this.za;case "router":return this.Ea;case "listen-key":return this.vc;case "click-listen-key":return this.sc;default:return $APP.K.A(this.G,b,c)}};$APP.g.Rb=function(a,b,c){return $APP.Lf.A(function(d,e){var f=$APP.H(e,0,null);e=$APP.H(e,1,null);return b.A?b.A(d,f,e):b.call(null,d,f,e)},c,this)};
$APP.g.ha=function(a,b,c){return $APP.dn(b,function(d){return $APP.dn(b,$APP.jn,""," ","",c,d)},"#reitit.frontend.history.Html5History{",", ","}",c,$APP.Ok.j(new $APP.P(null,4,5,$APP.R,[new $APP.P(null,2,5,$APP.R,[$APP.XW,this.za],null),new $APP.P(null,2,5,$APP.R,[$APP.zA,this.Ea],null),new $APP.P(null,2,5,$APP.R,[$APP.eS,this.vc],null),new $APP.P(null,2,5,$APP.R,[$APP.BW,this.sc],null)],null),this.G))};
$APP.g.La=function(){return new $APP.Jl(this,4,new $APP.P(null,4,5,$APP.R,[$APP.XW,$APP.zA,$APP.eS,$APP.BW],null),$APP.l(this.G)?$APP.bh(this.G):$APP.ik())};$APP.g.O=function(){return this.Z};$APP.g.pa=function(){return 4+$APP.Th(this.G)};$APP.g.la=function(){var a=this.N;return null!=a?a:this.N=a=-1654764186^$APP.Eh(this)};
$APP.g.ka=function(a,b){return null!=b&&this.constructor===b.constructor&&$APP.D.j(this.za,b.za)&&$APP.D.j(this.Ea,b.Ea)&&$APP.D.j(this.vc,b.vc)&&$APP.D.j(this.sc,b.sc)&&$APP.D.j(this.G,b.G)};
$APP.g.yi=function(){var a=this,b=this,c=function(){var e=$APP.yW.o(b);return $APP.l(e)?e:z5}(),d=$APP.Bm.B(b,$APP.eS,$APP.Bd(window,"popstate",function(){return b.sf(null,b.dh(null))},!1),$APP.G([$APP.BW,$APP.Bd(document,"click",function(e){var f=e.pe;a:for(f=null!=f.composedPath?f.composedPath()[0]:e.target;;)if($APP.l(f)){if($APP.D.j("A",f.nodeName))break a;f=f.parentNode}else{f=null;break a}if($APP.l(f)){var h=W4(f.href);if($APP.l(c.J?c.J(a.Ea,e,f,h):c.call(null,a.Ea,e,f,h)))return e.preventDefault(),
e=[$APP.p.o(h.mc),$APP.l(""!==h.oc.toString())?["?",$APP.p.o(h.getQuery())].join(""):null,$APP.l(!!h.cd)?["#",$APP.p.o(h.cd)].join(""):null].join(""),window.history.pushState(null,"",e),b.sf(null,e)}return null})]));$APP.xA(d,x5(d));return d};$APP.g.sf=function(a,b){a=u5(this.Ea,b,this);return this.za.j?this.za.j(a,this):this.za.call(null,a,this)};$APP.g.zi=function(){$APP.Md(this.vc);$APP.Md(this.sc);return null};$APP.g.dh=function(){return[$APP.p.o(window.location.pathname),$APP.p.o(window.location.search)].join("")};
$APP.g.xi=function(a,b){return b};$APP.g.fc=function(a,b){return $APP.Ki(new $APP.Hm(null,new $APP.k(null,4,[$APP.zA,null,$APP.eS,null,$APP.BW,null,$APP.XW,null],null),null),b)?$APP.zo.j($APP.vg($APP.qk.j($APP.dk,this),this.Z),b):new A5(this.za,this.Ea,this.vc,this.sc,this.Z,$APP.ek($APP.zo.j(this.G,b)),null)};$APP.g.Cb=function(a,b){switch(b instanceof $APP.tj?b.qa:null){case "on-navigate":case "router":case "listen-key":case "click-listen-key":return!0;default:return $APP.Ki(this.G,b)}};
$APP.g.Ba=function(a,b,c){return $APP.l($APP.vj.j?$APP.vj.j($APP.XW,b):$APP.vj.call(null,$APP.XW,b))?new A5(c,this.Ea,this.vc,this.sc,this.Z,this.G,null):$APP.l($APP.vj.j?$APP.vj.j($APP.zA,b):$APP.vj.call(null,$APP.zA,b))?new A5(this.za,c,this.vc,this.sc,this.Z,this.G,null):$APP.l($APP.vj.j?$APP.vj.j($APP.eS,b):$APP.vj.call(null,$APP.eS,b))?new A5(this.za,this.Ea,c,this.sc,this.Z,this.G,null):$APP.l($APP.vj.j?$APP.vj.j($APP.BW,b):$APP.vj.call(null,$APP.BW,b))?new A5(this.za,this.Ea,this.vc,c,this.Z,
this.G,null):new A5(this.za,this.Ea,this.vc,this.sc,this.Z,$APP.Bm.A(this.G,b,c),null)};$APP.g.oa=function(){return $APP.x($APP.Ok.j(new $APP.P(null,4,5,$APP.R,[new $APP.Li($APP.XW,this.za),new $APP.Li($APP.zA,this.Ea),new $APP.Li($APP.eS,this.vc),new $APP.Li($APP.BW,this.sc)],null),this.G))};$APP.g.P=function(a,b){return new A5(this.za,this.Ea,this.vc,this.sc,b,this.G,this.N)};$APP.g.sa=function(a,b){return $APP.si(b)?this.Ba(null,$APP.ci(b,0),$APP.ci(b,1)):$APP.Lf.A($APP.Vf,this,b)};
var K5=function K5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.uh(c.slice(1),0,null):null;return K5.B(arguments[0],c)};K5.B=function(a,b){return $APP.qk.j(new $APP.P(null,2,5,$APP.R,[$APP.wN,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,4,[$APP.aO,"url(/images/panel-bg-small.png)",$APP.fW,"100%",$APP.Mw,[$APP.p.o(a),"rem"].join(""),$APP.Jw,[$APP.p.o(a/2.08157647),"rem"].join("")],null)],null)],null),b)};K5.H=1;
K5.T=function(a){var b=$APP.z(a);a=$APP.A(a);return this.B(b,a)};
var Y5=$APP.S("white"),Y6=$APP.T("fgl.app.subs","re-pressed-example"),n6=$APP.S("link"),X6=$APP.S("gridTemplate"),O5=$APP.S("blue"),D6=$APP.S("div.cs2.ce3"),W6=$APP.S("div.grid.h-100vh.bg-cover.bg-no-repeat.bg-center"),R6=new $APP.v(null,"glory","glory",1732707291,null),I6=$APP.T("fgl.app.ui.connect-btn","text"),Z6=$APP.T("toast","failure"),F6=$APP.S("main.grid-area-main.grid.justify-strech.mt-30"),x6=$APP.T("toast","data"),l6=$APP.S("css"),$6=$APP.S("turqoise"),P5=$APP.S("green"),a7=$APP.S("sizes"),
T6=new $APP.v(null,"ratio","ratio",713971483,null),N6=$APP.T("fgl.app.ui.header","data"),M5=$APP.S("red"),Q6=new $APP.v(null,"logo","logo",-1416455506,null),b7=$APP.S("brown"),c7=$APP.S("black"),S6=$APP.S("div.flex.flex-row.justify-between.items-center.text-xl.fi"),o6=$APP.S("media"),d7=$APP.S("img.mr-8"),G6=$APP.S("justifyContent"),t6=$APP.S("onOpenChange"),m6=$APP.S("div.w-full.h-full.grid.grid-rows-1"),e7=$APP.S("success"),f7=$APP.T("lambdaisland.glogi.print","comma"),g7=$APP.S("gray1"),R5=$APP.S("gray3"),
T5=$APP.S("gray2"),h7=$APP.S("gray5"),S5=$APP.S("gray4"),i7=$APP.S("gray6"),f6=$APP.S("callback"),L6=$APP.S("backgroundBlendMode"),j7=$APP.S("re-pressed-example"),k7=$APP.S("failure"),z6=$APP.S("div.fixed.bottom-0.right-0.w-20.flex.flex-col.gap-10px.p-3.max-w-100vw.m-0.z-2147483647.list-none"),u6=$APP.T("toast","close"),l7=$APP.S("srcSet"),m7=$APP.S("purple"),U6=new $APP.v(null,"connect-btn","connect-btn",-1765022208,null),Q5=$APP.S("yellow"),j6=$APP.S("li\x3ebutton.relative.w-full.py-1_2rem"),n7=
$APP.S("ul.text-lg.text-center.fb.ml-2"),O6=$APP.S("header.w-100vw.grid-area-header.fixed.z-10"),o7=$APP.T("fgl.app.subs","name"),i6=$APP.T("fgl.app.ui.panel-route","hover"),A6=new $APP.v(null,"toast","toast",1709129656,null),p7=$APP.T("fgl.app.events","initialize-db"),v6=$APP.S("h1"),N5=$APP.S("orange"),q7=$APP.T("lambdaisland.glogi.print","space");$APP.kd("main");var W5=$APP.um([N5,g7,Y5,R5,S5,Q5,P5,$6,T5,M5,O5,m7,i7,h7,b7,c7],"#f5871f #e0e0e0 #ffffff #8e908c #969896 #eab700 #718c00 #3e999f #d6d6d6 #c82829 #4271ae #8959a8 #282a2e #4d4d4c #a3685a #1d1f21".split(" ")),r7=function r7(a,b){for(;;){if($APP.D.j(f7,b))return X5(a,", ",T5);if($APP.D.j(q7,b))return V5(a);if(b instanceof $APP.tj)return X5(a,b,O5);if(b instanceof $APP.v)return X5(a,b,P5);if("string"===typeof b)return X5(a,$APP.qn($APP.G([b])),$6);if($APP.ol(b)){var d=V5(function(){var f=a,h=$APP.jg(b);
return r7.j?r7.j(f,h):r7.call(null,f,h)}()),e=$APP.kg(b);return r7.j?r7.j(d,e):r7.call(null,d,e)}if(b instanceof $APP.k||b instanceof $APP.tm)return d=a,d=X5(d,"{",m7),d=$APP.Lf.A(r7,d,$APP.Nk(f7,b)),X5(d,"}",m7);if($APP.pi(b))return d=a,d=X5(d,["#",$APP.p.o(function(){var f=$APP.Hf(b),h=f.name;return $APP.ki(h)?$APP.qn($APP.G([f])):h}())," "].join(""),b7),d=X5(d,"{",m7),d=$APP.Lf.A(r7,d,$APP.Nk(f7,b)),X5(d,"}",m7);if($APP.mi(b))return d=a,d=X5(d,"#{",m7),d=$APP.Lf.A(r7,d,$APP.Nk(q7,b)),X5(d,"}",
m7);if($APP.si(b))return d=a,d=X5(d,"[",m7),d=$APP.Lf.A(r7,d,$APP.Nk(q7,b)),X5(d,"]",m7);if(b instanceof $APP.Fl)d=X5(a,"#queue ",b7),e=$APP.qk.j($APP.O,b),a=d,b=e;else{if($APP.yi(b))return d=a,d=X5(d,"(",b7),d=$APP.Lf.A(r7,d,$APP.Nk(q7,b)),X5(d,")",b7);if(null!=b?b.I&16384||$APP.t===b.vo||(b.I?0:$APP.Ff(Z4,b)):$APP.Ff(Z4,b))d=X5(a,"#atom ",b7),e=$APP.r(b),a=d,b=e;else if($APP.Zn(b))d=X5(a,"#uuid ",b7),e=$APP.p.o(b),a=d,b=e;else if(null!=b&&b.constructor===Object)d=X5(a,"#js ",b7),e=$APP.Lf.A(function(f,
h){return function(m,n){return $APP.Bm.A(m,$APP.kn.o(n),$APP.Ka(h,n))}}(a,b),$APP.dk,Object.keys(b)),a=d,b=e;else if($APP.yf(b))d=X5(a,"#js ",b7),e=$APP.qk.j($APP.O,b),a=d,b=e;else return X5(a,$APP.qn($APP.G([b])),h7)}}};var s7=a6(function(a){a=$APP.N(a);$APP.K.j(a,$APP.HM);var b=$APP.K.j(a,$APP.KR),c=$APP.K.j(a,$APP.IJ);$APP.K.j(a,$APP.Xt);return new $APP.P(null,2,5,$APP.R,[["[",$APP.p.o(b),"]"].join(""),c],null)}),t7=a6(function(a){var b=$APP.N(a),c=$APP.K.j(b,$APP.HM);a=$APP.K.j(b,$APP.KR);var d=$APP.K.j(b,$APP.IJ);$APP.K.j(b,$APP.Xt);b=U5(c);d=r7(V5(Z5(Z5(Z5(new $APP.P(null,2,5,$APP.R,["",$APP.O],null),"[",b),a,b),"]",b)),d);a=$APP.H(d,0,null);d=$APP.H(d,1,null);return $APP.rj(a,d)}),u7=a6(function(a){a=$APP.N(a);
$APP.K.j(a,$APP.HM);var b=$APP.K.j(a,$APP.KR),c=$APP.K.j(a,$APP.IJ);$APP.K.j(a,$APP.Xt);return new $APP.P(null,2,5,$APP.R,[["[",$APP.p.o(b),"]"].join(""),$APP.qn($APP.G([c]))],null)});var b6=$APP.zk($APP.dk);var v7=new $APP.k(null,1,[$APP.VO,null],null);$APP.xY.j(p7,function(){return v7});$APP.Yu(o7,$APP.G([function(a){return $APP.V.o(a)}]));$APP.Yu(Y6,$APP.G([function(a){return j7.o(a)}]));$APP.xY.j(i6,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);return $APP.Bm.A(a,i6,b)});$APP.Yu(i6,$APP.G([function(a){return $APP.K.A(a,i6,null)}]));var p6=function p6(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.uh(c.slice(0),0,null):null;return p6.B(c)};
p6.B=function(a){return new $APP.P(null,3,5,$APP.R,[$APP.qk,new $APP.P(null,3,5,$APP.R,[n7,new $APP.k(null,1,[$APP.Hw,new $APP.k(null,3,[$APP.vL,"linear-gradient(to right, transparent, rgb(80, 146, 158, 0.231))",$APP.TP,"rgb(158, 169, 172)",$APP.Uw,"1px 1px 1px rgba(0, 0, 0, 0.64)"],null)],null),new $APP.P(null,1,5,$APP.R,[h6],null)],null),$APP.Hk.j(function(b){var c=$APP.H(b,0,null);b=$APP.H(b,1,null);return new $APP.P(null,3,5,$APP.R,[k6,c,b],null)},a)],null)};p6.H=0;p6.T=function(a){return this.B($APP.x(a))};var s6=$APP.lo(424,{});var w7=$APP.zk(0);$APP.Yu(x6,$APP.G([function(a){return $APP.K.A(a,x6,$APP.O)}]));$APP.xY.j($APP.QT,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);return $APP.ct(a,new $APP.P(null,2,5,$APP.R,[x6,$APP.wn.j(w7,$APP.Hh)],null),$APP.Bm.A(b,$APP.U,e7))});$APP.xY.j(Z6,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);return $APP.ct(a,new $APP.P(null,2,5,$APP.R,[x6,$APP.wn.j(w7,$APP.Hh)],null),$APP.Bm.A(b,$APP.U,k7))});
$APP.xY.j(u6,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);return c5(a,new $APP.P(null,2,5,$APP.R,[x6,b],null))});n5($APP.dk);
$APP.Yu(I6,$APP.G([$APP.gV,new $APP.P(null,1,5,$APP.R,[$APP.hO],null),$APP.gV,new $APP.P(null,1,5,$APP.R,[$APP.vS],null),$APP.gV,new $APP.P(null,1,5,$APP.R,[$APP.YR],null),function(a){var b=$APP.H(a,0,null),c=$APP.H(a,1,null);a=$APP.H(a,2,null);return $APP.D.j(b,$APP.fU)?new $APP.P(null,4,5,$APP.R,["Wallet not detected","Wallet not detected",!1,function(){return open("https://metamask.io/")}],null):$APP.D.j(b,$APP.qU)?new $APP.P(null,4,5,$APP.R,["Connect Wallet","Connect Wallet",!1,$APP.Bw],null):
$APP.l(c)?new $APP.P(null,4,5,$APP.R,["Wrong Network","Wrong Network",!1,function(){return $APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.RQ],null))}],null):new $APP.P(null,4,5,$APP.R,[$APP.l(a)?$APP.Ew(a):"","Address",!1,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[$APP.XQ,$APP.VR],null))}],null)}]));var K6=$APP.lo(426,{});var P6=function P6(a){switch(arguments.length){case 0:return P6.C();case 1:return P6.o(arguments[0]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};P6.C=function(){return P6.o($APP.dk)};
P6.o=function(a){a=$APP.N(a);var b=$APP.K.j(a,$APP.Hw);return new $APP.P(null,2,5,$APP.R,[d7,$APP.$p.B($APP.G([new $APP.k(null,4,[$APP.Mw,"4.75rem",$APP.vJ,"link to home page",l7,"/images/logo-128.png 128w,\n                /images/logo-256.png 256w,\n                /images/logo-512.png 512w,\n                /images/logo-1024.png 1024w,",a7,"(max-width: 1024px) 128px\n                (max-width: 2048px) 256px\n                (max-width: 2880px) 512px\n                (min-width: 2880px) 1024px"],
null),a,new $APP.k(null,1,[$APP.Hw,$APP.$p.B($APP.G([new $APP.k(null,3,[$APP.Mw,"4.75rem",$APP.OT,"4.75rem",$APP.fX,"3.28375rem"],null),b]))],null)]))],null)};P6.H=1;$APP.Yu(N6,$APP.G([function(a){var b=$APP.N(a);b=$APP.K.j(b,$APP.YR);b=$APP.K.j(a,b);a=$APP.K.A(a,$APP.xS,0).toString();var c=$APP.mP.o(b);b=$APP.NV.o(b);return new $APP.P(null,3,5,$APP.R,[c,b,a],null)}]));$APP.l(null)&&null.setCapturing(!1);var x7,y7="undefined"!==typeof devtools&&"undefined"!==typeof devtools.core&&"undefined"!==typeof devtools.core.installed_QMARK_;x7=y7?devtools.core.installed_QMARK_():y7;
var z7=$APP.l(x7)?s7:"undefined"===typeof window||"undefined"!==typeof window&&"undefined"!==typeof window&&"undefined"!==typeof window.navigator&&"undefined"!==typeof window&&"undefined"!==typeof window.navigator&&"undefined"!==typeof window.navigator.userAgent&&(-1<window.navigator.userAgent.indexOf("MSIE")||-1<window.navigator.userAgent.indexOf("Trident"))?u7:t7;j5?j5(z7):k5.call(null,z7);$APP.Rs(new $APP.k(null,1,[$APP.Fs,$APP.l(!1)?$APP.PT:$APP.rU],null));$APP.lf();
try{$APP.Ps("fgl.app.home-core",new $APP.k(null,2,[$APP.mU,$APP.MW,$APP.To,30],null));l5(new $APP.P(null,1,5,$APP.R,[p7],null));for(var A7=$APP.x($APP.r($APP.pu)),B7=null,C7=0,D7=0;;)if(D7<C7){var E7=B7.ma(null,D7);$APP.H(E7,0,null);var F7=$APP.H(E7,1,null);$APP.lr(F7);D7+=1}else{var G7=$APP.x(A7);if(G7){var H7=G7;if($APP.ti(H7)){var I7=$APP.Vg(H7),J7=$APP.Wg(H7),K7=I7,L7=$APP.Th(I7);A7=J7;B7=K7;C7=L7}else{var M7=$APP.z(H7);$APP.H(M7,0,null);var N7=$APP.H(M7,1,null);$APP.lr(N7);A7=$APP.A(H7);B7=null;
C7=0}D7=0}else break}$APP.l($APP.ek($APP.r($APP.pu)))&&$APP.Xs.B($APP.ev,$APP.G(["re-frame: The subscription cache isn't empty after being cleared"]));var d6=document.getElementById("app"),O7=d6;$APP.wn.A(b6,$APP.zo,O7);$APP.ZY.unmountComponentAtNode(O7);g6();$APP.Ps("fgl.app.routes",new $APP.k(null,2,[$APP.mU,$APP.kz,$APP.To,235],null));E5()}catch(a){throw console.error("An error occurred when calling (fgl.app.home-core/init)"),a;};
}).call(this);