(function(){
shadow$provide[542]=function(L,u,W,l){function x(p,z){return Object.keys(z).forEach(function(w){"default"!==w&&"__esModule"!==w&&Object.defineProperty(p,w,{enumerable:!0,get:function(){return z[w]}})}),p}function C(p,z,w){const F=w.originalEvent.currentTarget;w=new CustomEvent(p,{bubbles:!0,cancelable:!0,detail:w});z&&F.addEventListener(p,z,{once:!0});F.dispatchEvent(w)}var q,t=u(422).VisuallyHidden,b=u(396).useLayoutEffect,r=u(414).useControllableState,h=u(408).useCallbackRef,g=u(395).Primitive,
e=u(397).Presence,f=u(407).UnstablePortal,k=x({},u(413));L=u(416).createContextScope;var y=u(354).useComposedRefs,B=u(412).composeEventHandlers,H=x({},u(406)),K=x({},u(3)),G=(q=u(355))&&q.__esModule?q.default:q;const [I,N]=L("Toast");l.createToastScope=N;const [Q,S]=I("ToastProvider");u=p=>{const {__scopeToast:z,label:w="Notification",duration:F=5E3,swipeDirection:A="right",swipeThreshold:O=50,children:R}=p,[T,U]=K.useState(null),[ba,ja]=K.useState(0);p=K.useRef(!1);const na=K.useRef(!1);return K.createElement(Q,
{scope:z,label:w,duration:F,swipeDirection:A,swipeThreshold:O,toastCount:ba,viewport:T,onViewportChange:U,onToastAdd:K.useCallback(()=>ja(fa=>fa+1),[]),onToastRemove:K.useCallback(()=>ja(fa=>fa-1),[]),isFocusedToastEscapeKeyDownRef:p,isClosePausedRef:na},R)};l.ToastProvider=u;const J=["F8"];q=K.forwardRef((p,z)=>{var w=Object.assign({},p),F=p.__scopeToast;const A=void 0===p.hotkey?J:p.hotkey;p=void 0===p.label?"Notifications ({hotkey})":p.label;w=(delete w.__scopeToast,delete w.hotkey,delete w.label,
w);const O=S("ToastViewport",F),R=K.useRef(null),T=K.useRef(null);z=y(z,T,O.onViewportChange);F=A.join("+").replace(/Key/g,"").replace(/Digit/g,"");return K.useEffect(()=>{const U=ba=>{var ja;A.every(na=>ba[na]||ba.code===na)&&(null===(ja=T.current)||void 0===ja||ja.focus())};return document.addEventListener("keydown",U),()=>document.removeEventListener("keydown",U)},[A]),K.useEffect(()=>{const U=R.current,ba=T.current;if(U&&ba){const ja=()=>{const fa=new Event("toast.viewportPause");ba.dispatchEvent(fa);
O.isClosePausedRef.current=!0},na=()=>{const fa=new Event("toast.viewportResume");ba.dispatchEvent(fa);O.isClosePausedRef.current=!1};return U.addEventListener("focusin",ja),U.addEventListener("focusout",na),U.addEventListener("pointerenter",ja),U.addEventListener("pointerleave",na),window.addEventListener("blur",ja),window.addEventListener("focus",na),()=>{U.removeEventListener("focusin",ja);U.removeEventListener("focusout",na);U.removeEventListener("pointerenter",ja);U.removeEventListener("pointerleave",
na);window.removeEventListener("blur",ja);window.removeEventListener("focus",na)}}},[O.isClosePausedRef]),K.useEffect(()=>{const U=T.current;if(U){let ba=[];const ja=new MutationObserver(na=>{[na]=na;na.addedNodes.forEach(fa=>{ba.includes(fa)||(U.prepend(fa),ba=[...ba,fa])})});return ja.observe(U,{childList:!0}),()=>ja.disconnect()}},[]),K.createElement(k.Branch,{ref:R,role:"region","aria-label":p.replace("{hotkey}",F),tabIndex:-1,style:{pointerEvents:0<O.toastCount?void 0:"none"}},K.createElement(g.ol,
G({tabIndex:-1},w,{ref:z})))});l.ToastViewport=q;L=K.forwardRef((p,z)=>{var w=Object.assign({},p);const F=p.forceMount,A=p.open,O=p.defaultOpen,R=p.onOpenChange;w=(delete w.forceMount,delete w.open,delete w.defaultOpen,delete w.onOpenChange,w);const [T=!0,U]=r({prop:A,defaultProp:O,onChange:R});return K.createElement(e,{present:F||T},K.createElement(m,G({open:T},w,{ref:z,onClose:()=>U(!1),onSwipeStart:B(p.onSwipeStart,ba=>{ba.currentTarget.setAttribute("data-swipe","start")}),onSwipeMove:B(p.onSwipeMove,
ba=>{const {x:ja,y:na}=ba.detail.delta;ba.currentTarget.setAttribute("data-swipe","move");ba.currentTarget.style.setProperty("--radix-toast-swipe-move-x",`${ja}px`);ba.currentTarget.style.setProperty("--radix-toast-swipe-move-y",`${na}px`)}),onSwipeCancel:B(p.onSwipeCancel,ba=>{ba.currentTarget.setAttribute("data-swipe","cancel");ba.currentTarget.style.removeProperty("--radix-toast-swipe-move-x");ba.currentTarget.style.removeProperty("--radix-toast-swipe-move-y");ba.currentTarget.style.removeProperty("--radix-toast-swipe-end-x");
ba.currentTarget.style.removeProperty("--radix-toast-swipe-end-y")}),onSwipeEnd:B(p.onSwipeEnd,ba=>{const {x:ja,y:na}=ba.detail.delta;ba.currentTarget.setAttribute("data-swipe","end");ba.currentTarget.style.removeProperty("--radix-toast-swipe-move-x");ba.currentTarget.style.removeProperty("--radix-toast-swipe-move-y");ba.currentTarget.style.setProperty("--radix-toast-swipe-end-x",`${ja}px`);ba.currentTarget.style.setProperty("--radix-toast-swipe-end-y",`${na}px`);U(!1)})})))});l.Toast=L;const [V,
P]=I("Toast",{isInteractive:!1,onClose(){}}),m=K.forwardRef((p,z)=>{var w=Object.assign({},p);const F=p.__scopeToast,A=void 0===p.type?"foreground":p.type,O=p.duration,R=p.open,T=p.onClose,U=p.onEscapeKeyDown,ba=p.onSwipeStart,ja=p.onSwipeMove,na=p.onSwipeCancel,fa=p.onSwipeEnd;w=(delete w.__scopeToast,delete w.type,delete w.duration,delete w.open,delete w.onClose,delete w.onEscapeKeyDown,delete w.onSwipeStart,delete w.onSwipeMove,delete w.onSwipeCancel,delete w.onSwipeEnd,w);const ea=S("Toast",F),
ia=K.useRef(null);z=y(z,ia);const oa=K.useRef(null),ra=K.useRef(null),sa=O||ea.duration,da=K.useRef(0),ka=K.useRef(sa),ha=K.useRef(0),{onToastAdd:la,onToastRemove:pa}=ea,qa=h(()=>{var wa,za;(null===(wa=ia.current)||void 0===wa?0:wa.contains(document.activeElement))&&(null===(za=ea.viewport)||void 0===za||za.focus());T()}),ta=K.useCallback(wa=>{wa&&wa!==1/0&&(window.clearTimeout(ha.current),da.current=(new Date).getTime(),ha.current=window.setTimeout(qa,wa))},[qa]);return K.useEffect(()=>{const wa=
ea.viewport;if(wa){const za=()=>{ta(ka.current)},ya=()=>{const Aa=(new Date).getTime()-da.current;ka.current-=Aa;window.clearTimeout(ha.current)};return wa.addEventListener("toast.viewportPause",ya),wa.addEventListener("toast.viewportResume",za),()=>{wa.removeEventListener("toast.viewportPause",ya);wa.removeEventListener("toast.viewportResume",za)}}},[ea.viewport,sa,ta]),K.useEffect(()=>{R&&!ea.isClosePausedRef.current&&ta(sa)},[R,sa,ea.isClosePausedRef,ta]),K.useEffect(()=>(la(),()=>pa()),[la,pa]),
ea.viewport?K.createElement(K.Fragment,null,K.createElement(E,{__scopeToast:F,role:"status","aria-live":"foreground"===A?"assertive":"polite","aria-atomic":!0},p.children),K.createElement(V,{scope:F,isInteractive:!0,onClose:qa},H.createPortal(K.createElement(k.Root,{asChild:!0,onEscapeKeyDown:B(U,()=>{ea.isFocusedToastEscapeKeyDownRef.current||qa();ea.isFocusedToastEscapeKeyDownRef.current=!1})},K.createElement(g.li,G({role:"status","aria-live":"off","aria-atomic":!0,tabIndex:0,"data-state":R?"open":
"closed","data-swipe-direction":ea.swipeDirection},w,{ref:z,style:Object.assign({},{userSelect:"none",touchAction:"none"},p.style),onKeyDown:B(p.onKeyDown,wa=>{"Escape"===wa.key&&(null==U||U(wa.nativeEvent),wa.nativeEvent.defaultPrevented||(ea.isFocusedToastEscapeKeyDownRef.current=!0,qa()))}),onPointerDown:B(p.onPointerDown,wa=>{0===wa.button&&(oa.current={x:wa.clientX,y:wa.clientY})}),onPointerMove:B(p.onPointerMove,wa=>{if(oa.current){var za=wa.clientX-oa.current.x,ya=wa.clientY-oa.current.y,Aa=
!!ra.current,Fa=["left","right"].includes(ea.swipeDirection),Da=["left","up"].includes(ea.swipeDirection)?Math.min:Math.max,Ca=Fa?Da(0,za):0;Da=Fa?0:Da(0,ya);Fa="touch"===wa.pointerType?10:2;Ca={x:Ca,y:Da};Da={originalEvent:wa,delta:Ca};Aa?(ra.current=Ca,C("toast.swipeMove",ja,Da)):n(Ca,ea.swipeDirection,Fa)?(ra.current=Ca,C("toast.swipeStart",ba,Da),wa.target.setPointerCapture(wa.pointerId)):(Math.abs(za)>Fa||Math.abs(ya)>Fa)&&(oa.current=null)}}),onPointerUp:B(p.onPointerUp,wa=>{const za=ra.current;
if(wa.target.releasePointerCapture(wa.pointerId),ra.current=null,oa.current=null,za){const ya=wa.currentTarget;wa={originalEvent:wa,delta:za};n(za,ea.swipeDirection,ea.swipeThreshold)?C("toast.swipeEnd",fa,wa):C("toast.swipeCancel",na,wa);ya.addEventListener("click",Aa=>Aa.preventDefault(),{once:!0})}})}))),ea.viewport))):null});m.propTypes={type(p){if(p.type&&!["foreground","background"].includes(p.type))throw Error("Invalid prop `type` supplied to `Toast`. Expected `foreground | background`.");
return null}};const E=p=>{var z=Object.assign({},p),w=p.__scopeToast;z=(delete z.__scopeToast,z);w=S("Toast",w);const [F,A]=K.useState(!1),[O,R]=K.useState(!1);return function(T){const U=h(void 0===T?()=>{}:T);b(()=>{let ba=0,ja=0;return ba=window.requestAnimationFrame(()=>ja=window.requestAnimationFrame(U)),()=>{window.cancelAnimationFrame(ba);window.cancelAnimationFrame(ja)}},[U])}(()=>A(!0)),K.useEffect(()=>{const T=window.setTimeout(()=>R(!0),1E3);return()=>window.clearTimeout(T)},[]),O?null:
K.createElement(f,{asChild:!0},K.createElement(t,{asChild:!0},K.createElement("div",z,F&&K.createElement(K.Fragment,null,w.label," ",p.children))))};W=K.forwardRef((p,z)=>{p=Object.assign({},p);p=(delete p.__scopeToast,p);return K.createElement(g.div,G({},p,{ref:z}))});l.ToastTitle=W;const a=K.forwardRef((p,z)=>{p=Object.assign({},p);p=(delete p.__scopeToast,p);return K.createElement(g.div,G({},p,{ref:z}))});l.ToastDescription=a;const c=K.forwardRef((p,z)=>{var w=Object.assign({},p);const F=p.altText;
w=(delete w.altText,w);p=P("ToastAction",p.__scopeToast);return F?p.isInteractive?K.createElement(d,G({},w,{ref:z})):K.createElement("span",null,F):null});l.ToastAction=c;c.propTypes={altText(p){if(!p.altText)throw Error("Missing prop `altText` expected on `ToastAction`");return null}};const d=K.forwardRef((p,z)=>{var w=Object.assign({},p),F=p.__scopeToast;w=(delete w.__scopeToast,w);F=P("ToastClose",F);return F.isInteractive?K.createElement(g.button,G({type:"button"},w,{ref:z,onClick:B(p.onClick,
F.onClose)})):null});l.ToastClose=d;const n=(p,z,w)=>{w=void 0===w?0:w;const F=Math.abs(p.x);p=Math.abs(p.y);const A=F>p;return"left"===z||"right"===z?A&&F>w:!A&&p>w};l.Provider=u;l.Viewport=q;l.Root=L;l.Title=W;l.Description=a;l.Action=c;l.Close=d};
shadow$provide[543]=function(L,u,W,l){var x,C,q=(x={},C=u(3),Object.keys(C).forEach(function(t){"default"!==t&&"__esModule"!==t&&Object.defineProperty(x,t,{enumerable:!0,get:function(){return C[t]}})}),x);l.useDirection=function(t,b){const [r,h]=q.useState("ltr"),[g,e]=q.useState(),f=q.useRef(0);return q.useEffect(()=>{if(void 0===b&&null!=t&&t.parentElement){const k=getComputedStyle(t.parentElement);e(k)}},[t,b]),q.useEffect(()=>(void 0===b&&function y(){f.current=requestAnimationFrame(()=>{const B=
null==g?void 0:g.direction;B&&h(B);y()})}(),()=>cancelAnimationFrame(f.current)),[g,b,h]),b||r}};
shadow$provide[544]=function(L,u,W,l){function x(la){return la&&la.__esModule?la.default:la}function C(la,pa){return Object.keys(pa).forEach(function(qa){"default"!==qa&&"__esModule"!==qa&&Object.defineProperty(la,qa,{enumerable:!0,get:function(){return pa[qa]}})}),la}function q(la){const pa=[];for(la=document.createTreeWalker(la,NodeFilter.SHOW_ELEMENT,{acceptNode:qa=>{const ta="INPUT"===qa.tagName&&"hidden"===qa.type;return qa.disabled||qa.hidden||ta?NodeFilter.FILTER_SKIP:0<=qa.tabIndex?NodeFilter.FILTER_ACCEPT:
NodeFilter.FILTER_SKIP}});la.nextNode();)pa.push(la.currentNode);return pa}function t(la){const pa=document.activeElement;return la.some(qa=>qa===pa||(qa.focus(),document.activeElement!==pa))}function b(la,pa){const qa=g(pa);e(()=>{let ta=0;if(la){const wa=new ResizeObserver(()=>{cancelAnimationFrame(ta);ta=window.requestAnimationFrame(qa)});return wa.observe(la),()=>{window.cancelAnimationFrame(ta);wa.unobserve(la)}}},[la,qa])}function r(la){return pa=>"mouse"===pa.pointerType?la(pa):void 0}var h=
C({},u(422)),g=u(408).useCallbackRef,e=u(396).useLayoutEffect,f=u(420).usePrevious,k=u(413).DismissableLayer;L=u(423).createCollection;var y=u(415).useId,B=u(397).Presence,H=u(543).useDirection;W=u(354);var K=W.composeRefs,G=W.useComposedRefs,I=u(414).useControllableState,N=u(395).Primitive,Q=u(412).composeEventHandlers;W=u(416).createContextScope;var S=x(u(406)),J=C({},u(3)),V=x(u(355));const [P,m,E]=L("NavigationMenu"),[a,c,d]=L("NavigationMenu"),[n,p]=W("NavigationMenu",[E,d]);l.createNavigationMenuScope=
p;const [z,w]=n("NavigationMenu"),[F,A]=n("NavigationMenu");u=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.__scopeNavigationMenu,wa=la.value,za=la.onValueChange,ya=la.defaultValue,Aa=void 0===la.orientation?"horizontal":la.orientation;qa=(delete qa.__scopeNavigationMenu,delete qa.value,delete qa.onValueChange,delete qa.defaultValue,delete qa.orientation,qa);const [Fa,Da]=J.useState(null);pa=G(pa,Ca=>Da(Ca));return J.createElement(O,{scope:ta,isRootMenu:!0,value:wa,onValueChange:za,
defaultValue:ya,dir:H(Fa,la.dir),orientation:Aa,rootNavigationMenu:Fa},J.createElement(N.nav,V({"aria-label":"Main","data-orientation":Aa},qa,{ref:pa})))});l.NavigationMenu=u;L=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.__scopeNavigationMenu,wa=la.value,za=la.onValueChange,ya=la.defaultValue;la=void 0===la.orientation?"horizontal":la.orientation;qa=(delete qa.__scopeNavigationMenu,delete qa.value,delete qa.onValueChange,delete qa.defaultValue,delete qa.orientation,qa);const Aa=
w("NavigationMenuSub",ta);return J.createElement(O,{scope:ta,isRootMenu:!1,value:wa,onValueChange:za,defaultValue:ya,dir:Aa.dir,orientation:la,rootNavigationMenu:Aa.rootNavigationMenu},J.createElement(N.div,V({"data-orientation":la},qa,{ref:pa})))});l.NavigationMenuSub=L;const O=la=>{const {scope:pa,isRootMenu:qa,rootNavigationMenu:ta,value:wa,onValueChange:za,defaultValue:ya,dir:Aa,orientation:Fa,children:Da}=la,[Ca,Ga]=J.useState(null),[Ka,La]=J.useState(new Map),[Oa,Ma]=J.useState(null),Ia=J.useRef(0),
[Z="",aa]=I({prop:wa,onChange:za,defaultProp:ya});return J.useEffect(()=>()=>window.clearTimeout(Ia.current),[Ia]),J.createElement(z,{scope:pa,isRootMenu:qa,rootNavigationMenu:ta,value:Z,previousValue:f(Z),baseId:y(),dir:Aa,orientation:Fa,viewport:Ca,onViewportChange:Ga,indicatorTrack:Oa,onIndicatorTrackChange:Ma,onItemOver:J.useCallback(va=>{qa&&window.clearTimeout(Ia.current);aa(va)},[aa,qa]),onItemLeave:J.useCallback(()=>{qa&&(window.clearTimeout(Ia.current),Ia.current=window.setTimeout(()=>aa(""),
150))},[aa,qa]),onItemSelect:J.useCallback(va=>{aa(Y=>qa&&Y===va?"":va)},[aa,qa]),onItemDismiss:J.useCallback(()=>aa(""),[aa]),onViewportContentChange:J.useCallback((va,Y)=>{La(Pa=>(Pa.set(va,Y),new Map(Pa)))},[]),onViewportContentRemove:J.useCallback(va=>{La(Y=>Y.has(va)?(Y.delete(va),new Map(Y)):Y)},[])},J.createElement(P.Provider,{scope:pa},J.createElement(F,{scope:pa,items:Ka},Da)))};W=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);la=la.__scopeNavigationMenu;const ta=(delete qa.__scopeNavigationMenu,
qa);qa=w("NavigationMenuList",la);pa=J.createElement(N.ul,V({"data-orientation":qa.orientation},ta,{ref:pa}));return J.createElement(N.div,{style:{position:"relative"},ref:qa.onIndicatorTrackChange},J.createElement(P.Slot,{scope:la},qa.isRootMenu?J.createElement(da,{asChild:!0},pa):pa))});l.NavigationMenuList=W;const [R,T]=n("NavigationMenuItem"),U=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.__scopeNavigationMenu;la=la.value;qa=(delete qa.__scopeNavigationMenu,delete qa.value,qa);
var wa=y();la=la||wa||"LEGACY_REACT_AUTO_VALUE";const za=J.useRef(null);wa=J.useRef(null);const ya=J.useRef(null),Aa=J.useRef(()=>{}),Fa=J.useCallback(Ca=>{Ca=void 0===Ca?"start":Ca;if(za.current){Aa.current();const Ga=q(za.current);Ga.length&&t("start"===Ca?Ga:Ga.reverse())}},[]),Da=J.useCallback(()=>{if(za.current){const Ca=q(za.current);Ca.length&&(Aa.current=function(Ga){return Ga.forEach(Ka=>{Ka.dataset.tabindex=Ka.getAttribute("tabindex")||"";Ka.setAttribute("tabindex","-1")}),()=>{Ga.forEach(Ka=>
{Ka.setAttribute("tabindex",Ka.dataset.tabindex)})}}(Ca))}},[]);return J.createElement(R,{scope:ta,value:la,triggerRef:wa,contentRef:za,focusProxyRef:ya,onEntryKeyDown:Fa,onFocusProxyEnter:Fa,onRootContentClose:Da,onContentFocusOutside:Da},J.createElement(N.li,V({},qa,{ref:pa})))});l.NavigationMenuItem=U;const ba=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.__scopeNavigationMenu,wa=la.disabled;qa=(delete qa.__scopeNavigationMenu,delete qa.disabled,qa);const za=w("NavigationMenuTrigger",
la.__scopeNavigationMenu),ya=T("NavigationMenuTrigger",la.__scopeNavigationMenu),Aa=J.useRef(null);pa=G(Aa,ya.triggerRef,pa);const Fa=`${za.baseId}-trigger-${ya.value}`,Da=`${za.baseId}-content-${ya.value}`,Ca=J.useRef(!1),Ga=ya.value===za.value;return J.createElement(J.Fragment,null,J.createElement(P.ItemSlot,{scope:ta,value:ya.value},J.createElement(ha,{asChild:!0},J.createElement(N.button,V({id:Fa,disabled:wa,"data-disabled":wa?"":void 0,"data-state":Ga?"open":"closed","aria-expanded":Ga,"aria-controls":Da},
qa,{ref:pa,onPointerEnter:Q(la.onPointerEnter,()=>{Ca.current=!1}),onPointerMove:Q(la.onPointerMove,r(()=>{wa||Ca.current||za.onItemOver(ya.value)})),onPointerLeave:Q(la.onPointerLeave,r(()=>{wa||za.onItemLeave()})),onClick:Q(la.onClick,()=>{za.onItemSelect(ya.value);Ca.current=Ga}),onKeyDown:Q(la.onKeyDown,Ka=>{const La={horizontal:"ArrowDown",vertical:"rtl"===za.dir?"ArrowLeft":"ArrowRight"}[za.orientation];Ga&&Ka.key===La&&(ya.onEntryKeyDown(),Ka.preventDefault())})})))),Ga&&J.createElement(J.Fragment,
null,J.createElement(h.Root,{"aria-hidden":!0,tabIndex:0,ref:ya.focusProxyRef,onFocus:Ka=>{var La=ya.contentRef.current;const Oa=Ka.relatedTarget;Ka=Oa===Aa.current;La=null==La?void 0:La.contains(Oa);!Ka&&La||ya.onFocusProxyEnter(Ka?"start":"end")}}),za.viewport&&J.createElement("span",{"aria-owns":Da})))});l.NavigationMenuTrigger=ba;const ja=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);la=la.active;qa=(delete qa.__scopeNavigationMenu,delete qa.active,qa);return J.createElement(ha,{asChild:!0},
J.createElement(N.a,V({"data-active":la?"":void 0,"aria-current":la?"page":void 0},qa,{ref:pa})))});l.NavigationMenuLink=ja;const na=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.forceMount;qa=(delete qa.forceMount,qa);la=w("NavigationMenuIndicator",la.__scopeNavigationMenu);const wa=!!la.value;return la.indicatorTrack?S.createPortal(J.createElement(B,{present:ta||wa},J.createElement(fa,V({},qa,{ref:pa}))),la.indicatorTrack):null});l.NavigationMenuIndicator=na;const fa=J.forwardRef((la,
pa)=>{var qa=Object.assign({},la);la=la.__scopeNavigationMenu;qa=(delete qa.__scopeNavigationMenu,qa);const ta=w("NavigationMenuIndicator",la),wa=m(la),[za,ya]=J.useState(null),[Aa,Fa]=J.useState(null),Da="horizontal"===ta.orientation;la=!!ta.value;J.useEffect(()=>{var Ga;const Ka=null===(Ga=wa().find(La=>La.value===ta.value))||void 0===Ga?void 0:Ga.ref.current;Ka&&ya(Ka)},[wa,ta.value]);const Ca=()=>{za&&Fa({size:Da?za.offsetWidth:za.offsetHeight,offset:Da?za.offsetLeft:za.offsetTop})};return b(za,
Ca),b(ta.indicatorTrack,Ca),Aa?J.createElement(N.div,V({"aria-hidden":!0,"data-state":la?"visible":"hidden","data-orientation":ta.orientation},qa,{ref:pa,style:Object.assign({},{position:"absolute"},Da?{left:0,width:Aa.size+"px",transform:`translateX(${Aa.offset}px)`}:{top:0,height:Aa.size+"px",transform:`translateY(${Aa.offset}px)`},qa.style)})):null}),ea=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.forceMount;qa=(delete qa.forceMount,qa);const wa=w("NavigationMenuContent",la.__scopeNavigationMenu),
za=T("NavigationMenuContent",la.__scopeNavigationMenu);pa=G(za.contentRef,pa);const ya=za.value===wa.value;qa=Object.assign({},{value:za.value,triggerRef:za.triggerRef,focusProxyRef:za.focusProxyRef,onContentFocusOutside:za.onContentFocusOutside,onRootContentClose:za.onRootContentClose},qa);return wa.viewport?J.createElement(ia,V({forceMount:ta},qa,{ref:pa})):J.createElement(B,{present:ta||ya},J.createElement(oa,V({"data-state":ya?"open":"closed"},qa,{ref:pa,onPointerEnter:Q(la.onPointerEnter,()=>
{wa.onItemOver(za.value)}),onPointerLeave:Q(la.onPointerLeave,r(wa.onItemLeave)),style:Object.assign({},{pointerEvents:!ya&&wa.isRootMenu?"none":void 0},qa.style)})))});l.NavigationMenuContent=ea;const ia=J.forwardRef((la,pa)=>{const qa=w("NavigationMenuContent",la.__scopeNavigationMenu),{onViewportContentChange:ta,onViewportContentRemove:wa}=qa;return e(()=>{ta(la.value,Object.assign({},{ref:pa},la))},[la,pa,ta]),e(()=>()=>wa(la.value),[la.value,wa]),null}),oa=J.forwardRef((la,pa)=>{var qa=Object.assign({},
la),ta=la.__scopeNavigationMenu;const wa=la.value,za=la.triggerRef,ya=la.focusProxyRef,Aa=la.onRootContentClose,Fa=la.onContentFocusOutside;qa=(delete qa.__scopeNavigationMenu,delete qa.value,delete qa.triggerRef,delete qa.focusProxyRef,delete qa.onRootContentClose,delete qa.onContentFocusOutside,qa);const Da=w("NavigationMenuContent",ta),Ca=J.useRef(null);pa=G(Ca,pa);const Ga=`${Da.baseId}-trigger-${wa}`,Ka=`${Da.baseId}-content-${wa}`,La=m(ta),Oa=J.useRef(null),{onItemDismiss:Ma}=Da;J.useEffect(()=>
{const Ia=Ca.current;if(Da.isRootMenu&&Ia){const Z=()=>{var aa;Ma();Aa();Ia.contains(document.activeElement)&&(null===(aa=za.current)||void 0===aa||aa.focus())};return Ia.addEventListener("navigationMenu.contentDismiss",Z),()=>Ia.removeEventListener("navigationMenu.contentDismiss",Z)}},[Da.isRootMenu,la.value,za,Ma,Aa]);ta=J.useMemo(()=>{var Ia=La().map(Pa=>Pa.value);"rtl"===Da.dir&&Ia.reverse();const Z=Ia.indexOf(Da.value),aa=Ia.indexOf(Da.previousValue),va=wa===Da.value,Y=aa===Ia.indexOf(wa);if(!va&&
!Y)return Oa.current;Ia=(()=>{if(Z!==aa){if(va&&-1!==aa)return Z>aa?"from-end":"from-start";if(Y&&-1!==Z)return Z>aa?"to-start":"to-end"}return null})();return Oa.current=Ia,Ia},[Da.previousValue,Da.value,Da.dir,La,wa]);return J.createElement(da,{asChild:!0},J.createElement(k,V({id:Ka,"aria-labelledby":Ga,"data-motion":ta,"data-orientation":Da.orientation},qa,{ref:pa,onDismiss:()=>{var Ia;const Z=new Event("navigationMenu.contentDismiss",{bubbles:!0,cancelable:!0});null===(Ia=Ca.current)||void 0===
Ia||Ia.dispatchEvent(Z)},onFocusOutside:Q(la.onFocusOutside,Ia=>{var Z;Fa();const aa=Ia.target;null!==(Z=Da.rootNavigationMenu)&&void 0!==Z&&Z.contains(aa)&&Ia.preventDefault()}),onPointerDownOutside:Q(la.onPointerDownOutside,Ia=>{var Z;const aa=Ia.target,va=La().some(Pa=>{var Ta;return null===(Ta=Pa.ref.current)||void 0===Ta?void 0:Ta.contains(aa)}),Y=Da.isRootMenu&&(null===(Z=Da.viewport)||void 0===Z?void 0:Z.contains(aa));(va||Y||!Da.isRootMenu)&&Ia.preventDefault()}),onKeyDown:Q(la.onKeyDown,
Ia=>{var Z=Ia.altKey||Ia.ctrlKey||Ia.metaKey;if("Tab"===Ia.key&&!Z){Z=q(Ia.currentTarget);const va=document.activeElement,Y=Z.findIndex(Pa=>Pa===va);var aa;t(Ia.shiftKey?Z.slice(0,Y).reverse():Z.slice(Y+1,Z.length))?Ia.preventDefault():null===(aa=ya.current)||void 0===aa||aa.focus()}})})))}),ra=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.forceMount;qa=(delete qa.forceMount,qa);la=!!w("NavigationMenuViewport",la.__scopeNavigationMenu).value;return J.createElement(B,{present:ta||
la},J.createElement(sa,V({},qa,{ref:pa})))});l.NavigationMenuViewport=ra;const sa=J.forwardRef((la,pa)=>{var qa=Object.assign({},la),ta=la.__scopeNavigationMenu;qa=(delete qa.__scopeNavigationMenu,delete qa.children,qa);const wa=w("NavigationMenuViewport",ta);pa=G(pa,wa.onViewportChange);ta=A("NavigationMenuContent",la.__scopeNavigationMenu);const [za,ya]=J.useState(null),[Aa,Fa]=J.useState(null),Da=za?(null==za?void 0:za.width)+"px":void 0,Ca=za?(null==za?void 0:za.height)+"px":void 0,Ga=!!wa.value,
Ka=Ga?wa.value:wa.previousValue;return b(Aa,()=>{Aa&&ya({width:Aa.offsetWidth,height:Aa.offsetHeight})}),J.createElement(N.div,V({"data-state":Ga?"open":"closed","data-orientation":wa.orientation},qa,{ref:pa,style:Object.assign({},{pointerEvents:!Ga&&wa.isRootMenu?"none":void 0,"--radix-navigation-menu-viewport-width":Da,"--radix-navigation-menu-viewport-height":Ca},qa.style),onPointerEnter:Q(la.onPointerEnter,()=>{wa.onItemOver(Ka)}),onPointerLeave:Q(la.onPointerLeave,r(wa.onItemLeave))}),Array.from(ta.items).map(La=>
{var Oa=$jscomp.makeIterator(La);La=Oa.next().value;var Ma=Oa.next().value,Ia=Object.assign({},Ma);Oa=Ma.ref;Ma=Ma.forceMount;Ia=(delete Ia.ref,delete Ia.forceMount,Ia);const Z=Ka===La;return J.createElement(B,{key:La,present:Ma||Z},J.createElement(oa,V({},Ia,{ref:K(Oa,aa=>{Z&&aa&&Fa(aa)})})))}))}),da=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);la=la.__scopeNavigationMenu;qa=(delete qa.__scopeNavigationMenu,qa);const ta=w("FocusGroup",la);return J.createElement(a.Provider,{scope:la},J.createElement(a.Slot,
{scope:la},J.createElement(N.div,V({dir:ta.dir},qa,{ref:pa}))))}),ka=["ArrowRight","ArrowLeft","ArrowUp","ArrowDown"],ha=J.forwardRef((la,pa)=>{var qa=Object.assign({},la);const ta=la.__scopeNavigationMenu;qa=(delete qa.__scopeNavigationMenu,qa);const wa=c(ta),za=w("FocusGroupItem",ta);return J.createElement(a.ItemSlot,{scope:ta},J.createElement(N.button,V({},qa,{ref:pa,onKeyDown:Q(la.onKeyDown,ya=>{if(["Home","End",...ka].includes(ya.key)){let Aa=wa().map(Fa=>Fa.ref.current);if(["rtl"===za.dir?"ArrowRight":
"ArrowLeft","ArrowUp","End"].includes(ya.key)&&Aa.reverse(),ka.includes(ya.key)){const Fa=Aa.indexOf(ya.currentTarget);Aa=Aa.slice(Fa+1)}setTimeout(()=>t(Aa));ya.preventDefault()}})})))});l.Root=u;l.Sub=L;l.List=W;l.Item=U;l.Trigger=ba;l.Link=ja;l.Indicator=na;l.Content=ea;l.Viewport=ra};
'use strict';var mW=function(a,b){a&&$APP.Ac($APP.Ec(),a.Oc()).Le.push(b)},nW=function(a,b){a&&(a=$APP.Ac($APP.Ec(),a.Oc()),b=a.Le.indexOf(b),-1!==b&&a.Le.splice(b,1))},oW=function(a){if(a.Fc&&"function"==typeof a.Fc)return a.Fc();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if($APP.ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return $APP.Ea(a)},pW=function(a){if(a.Ie&&
"function"==typeof a.Ie)return a.Ie();if(!a.Fc||"function"!=typeof a.Fc){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if($APP.ca(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return $APP.Fa(a)}}},qW=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if($APP.ca(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=pW(a),e=oW(a),k=e.length,
l=0;l<k;l++)b.call(c,e[l],d&&d[l],a)},rW=function(a,b){if(a){a=a.split("\x26");for(var c=0;c<a.length;c++){var d=a[c].indexOf("\x3d"),e=null;if(0<=d){var k=a[c].substring(0,d);e=a[c].substring(d+1)}else k=a[c];b(k,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}},sW=function(a,b){this.lb=this.Ga=null;this.sb=a||null;this.Eb=!!b},tW=function(a){a.Ga||(a.Ga=new Map,a.lb=0,a.sb&&rW(a.sb,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))},vW=function(a,b){tW(a);b=uW(a,b);return a.Ga.has(b)},
uW=function(a,b){b=String(b);a.Eb&&(b=b.toLowerCase());return b},wW=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},xW=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},yW=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,xW),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},zW=function(a){this.Db=this.Yc=this.vc="";this.ud=null;this.lc=this.wb="";this.Eb=this.vi=!1;if(a instanceof zW){this.Eb=a.Eb;AW(this,
a.vc);var b=a.Yc;BW(this);this.Yc=b;b=a.Db;BW(this);this.Db=b;CW(this,a.ud);b=a.wb;BW(this);this.wb=b;DW(this,a.yb.clone());a=a.lc;BW(this);this.lc=a}else a&&(b=String(a).match($APP.ee))?(this.Eb=!1,AW(this,b[1]||"",!0),a=b[2]||"",BW(this),this.Yc=wW(a),a=b[3]||"",BW(this),this.Db=wW(a,!0),CW(this,b[4]),a=b[5]||"",BW(this),this.wb=wW(a,!0),DW(this,b[6]||"",!0),a=b[7]||"",BW(this),this.lc=wW(a)):(this.Eb=!1,this.yb=new sW(null,this.Eb))},AW=function(a,b,c){BW(a);a.vc=c?wW(b,!0):b;a.vc&&(a.vc=a.vc.replace(/:$/,
""))},CW=function(a,b){BW(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.ud=b}else a.ud=null},DW=function(a,b,c){BW(a);b instanceof sW?(a.yb=b,a.yb.kg(a.Eb)):(c||(b=yW(b,EW)),a.yb=new sW(b,a.Eb))},BW=function(a){if(a.vi)throw Error("Tried to modify a read-only Uri");},FW=function(a){return a instanceof zW?a.clone():new zW(a)},GW=function(a){a=a.toString();":"==a.charAt(0)&&(a=a.substring(1));return a},HW=function(a){if(!$APP.Hz)throw Error("shadow.loader API was called before shadow.loader.init!\nYou are probably calling module loader too early before shadow-cljs got fully initialized.");
a=GW(a);return $APP.ad.load(a)},IW=function(){},JW=function(a,b){return"undefined"!==typeof $APP.Wd&&"undefined"!==typeof $APP.an&&"undefined"!==typeof mW?mW(a,b):a.Dj(b)},KW=function(a,b){"undefined"!==typeof $APP.Wd&&"undefined"!==typeof $APP.an&&"undefined"!==typeof nW?nW(a,b):a.Xj(b)},LW=function(a,b){if($APP.Fh(b)){var c=$APP.hh(b);b=0<c?new $APP.H(null,2,5,$APP.I,[1<c?$APP.yh(b):null,$APP.xh(b)],null):null;c=$APP.A(b,0,null);b=$APP.A(b,1,null);return a.j?a.j(c,b):a.call(null,c,b)}for(c=$APP.G;;){var d=
$APP.q(b);b=$APP.t(d);if(d=$APP.w(d))c=$APP.mi.j(c,b),b=d;else return a.j?a.j(c,b):a.call(null,c,b)}},MW=function(){for(var a=$APP.q($APP.p($APP.vq)),b=null,c=0,d=0;;)if(d<c){var e=b.fa(null,d);$APP.A(e,0,null);e=$APP.A(e,1,null);$APP.fo(e);d+=1}else if(a=$APP.q(a))$APP.Gh(a)?(c=$APP.ng(a),a=$APP.og(a),b=c,c=$APP.hh(c)):(b=$APP.t(a),$APP.A(b,0,null),b=$APP.A(b,1,null),$APP.fo(b),a=$APP.w(a),b=null,c=0),d=0;else break;$APP.h($APP.Wi($APP.p($APP.vq)))&&$APP.Fp.B($APP.Vu,$APP.y(["re-frame: The subscription cache isn't empty after being cleared"]))},
PW=function(a,b,c){if($APP.zh(b))return c.o?c.o(a):c.call(null,a);var d=$APP.Oj(a,b,null);c=c.o?c.o(d):c.call(null,d);return $APP.h($APP.si.j?$APP.si.j(c,$APP.CG):$APP.si.call(null,c,$APP.CG))?a:$APP.h($APP.si.j?$APP.si.j(c,$APP.fs):$APP.si.call(null,c,$APP.fs))?NW?NW(a,b):OW.call(null,a,b):$APP.Lp(a,b,c)},OW=function(a){switch(arguments.length){case 3:return QW(arguments[0],arguments[1],arguments[2]);case 2:return NW(arguments[0],arguments[1]);default:for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),
d+=1;else break;b=new $APP.Mg(b.slice(3),0,null);return RW(arguments[0],arguments[1],arguments[2],b)}},RW=function(a,b,c,d){return PW(a,b,function(e){return $APP.Oi($APP.Vn,e,c,d)})},QW=function(a,b,c){return PW(a,b,function(d){return $APP.Vn.j(d,c)})},NW=function(a,b){return $APP.q(b)?LW(function(c,d){return QW(a,c,d)},b):a},SW=function(a,b){b=$APP.Ni($APP.J,$APP.Ha(a,"__glogi_handlers__"),b);a.__glogi_handlers__=b},TW=function(a,b){function c(e){e=new $APP.g(null,6,[$APP.TF,e.jj,$APP.aJ,e.kj,$APP.jA,
$APP.Tl.o(e.Tf.name.toLowerCase()),$APP.mC,e.Vi,$APP.fF,e.zi,$APP.Qq,e.Fe],null);return b.o?b.o(e):b.call(null,e)}a=$APP.Fc($APP.$m(a));if($APP.h(a)){var d=$APP.D.j($APP.Ha(a,"__glogi_handlers__"),b);$APP.h(d)&&KW(a,d);SW(a,$APP.y([b,c]));return null==a?null:JW(a,c)}return null},UW=function(a){return TW("",a)},VW=function(a){switch(arguments.length){case 1:UW(arguments[0]);break;case 2:TW(arguments[0],arguments[1]);break;default:throw Error(["Invalid arity: ",$APP.n.o(arguments.length)].join(""));
}},WW=function(a){$APP.rq(a);$APP.Yq($APP.Zq,a);return null},XW=function(a){return $APP.D.j($APP.fn,a).value},YW=function(a,b){var c=$APP.E(a),d=$APP.D.j(c,$APP.WF),e=$APP.D.j(c,$APP.Us),k=$APP.D.j(c,$APP.Os),l=$APP.D.j(c,$APP.AD),m=$APP.D.j(c,$APP.Ps);return $APP.yp(new $APP.g(null,2,[$APP.jF,function(){return $APP.P(new $APP.H(null,11,5,$APP.I,[$APP.Cs,$APP.Ms,d,$APP.Us,e,$APP.Os,k,$APP.Ps,m,$APP.Ns,l],null))},$APP.ip,function(){function r(){return $APP.P(new $APP.H(null,3,5,$APP.I,[$APP.Cs,$APP.Ds,
!0],null))}var u=$APP.p($APP.Hr(new $APP.H(null,2,5,$APP.I,[$APP.lH,$APP.Ms],null))),v=$APP.E(u),z=$APP.D.j(v,$APP.Ms);u=$APP.D.j(v,$APP.Us);var B=$APP.D.j(v,$APP.Os),C=$APP.D.j(v,$APP.Ns);v=$APP.D.j(v,$APP.Ps);z=$APP.Vn.j($APP.Vn.j($APP.Vn.j($APP.J.A($APP.J.A(c,$APP.rp,"gglobal"),$APP.Ms,z),$APP.Ps),$APP.Us),$APP.Os);return new $APP.H(null,5,5,$APP.I,[$APP.ys,$APP.zs.Root,z,b,new $APP.H(null,4,5,$APP.I,[$APP.ys,$APP.zs.Portal,new $APP.H(null,3,5,$APP.I,[$APP.ys,$APP.zs.Overlay,new $APP.g(null,2,
[$APP.sp,"fixed inset-0 bg-black opacity-20",$APP.Bs,$APP.h(C)?r:$APP.$h],null)],null),new $APP.H(null,7,5,$APP.I,[$APP.ys,$APP.zs.Content,new $APP.g(null,2,[$APP.sp,"fixed top-50% left-50% transform -translate-x-50% -translate-y-50% bg-no-repeat p-4 fb",$APP.Q,new $APP.g(null,5,[$APP.Av,"url(/images/popup.png)",$APP.Fv,"100%",$APP.Bv,1E4,$APP.ns,"40rem",$APP.ls,"20.4775396rem"],null)],null),$APP.h(u)?new $APP.H(null,4,5,$APP.I,[$APP.ys,$APP.zs.Title,new $APP.g(null,1,[$APP.sp,"flexr text-center text-2xl"],
null),u],null):u,$APP.h(B)?new $APP.H(null,4,5,$APP.I,[$APP.ys,$APP.zs.Description,new $APP.g(null,2,[$APP.sp,"px-4 text-lg flex flex-col justify-center h-76% overflow-auto mb-4",$APP.As,!0],null),new $APP.H(null,2,5,$APP.I,[$APP.zv,B],null)],null):B,$APP.h(v)?new $APP.H(null,2,5,$APP.I,[$APP.rI,v],null):v,$APP.h(C)?new $APP.H(null,4,5,$APP.I,[$APP.ys,$APP.zs.Close,new $APP.g(null,2,[$APP.sp,"absolute top-4 right-4",$APP.Bs,r],null),new $APP.H(null,2,5,$APP.I,[$APP.rH,new $APP.g(null,2,[$APP.Q,new $APP.g(null,
2,[$APP.LD,"-0.2rem",$APP.Mr,"translateX(10%)"],null),$APP.R,"/images/panel-close.svg"],null)],null)],null):C],null)],null)],null)}],null))},$W=function(){return new $APP.H(null,3,5,$APP.I,[YW,new $APP.g(null,4,[$APP.rp,$APP.cI,$APP.Us,"TX Status",$APP.Os,new $APP.H(null,1,5,$APP.I,[$APP.zv],null),$APP.RA,!0],null),new $APP.H(null,2,5,$APP.I,[ZW,new $APP.g(null,1,[$APP.sp,"invisible"],null)],null)],null)},aX=function(a){a=$APP.E(a);a=$APP.D.j(a,$APP.XE);return WW(new $APP.H(null,2,5,$APP.I,[$APP.hA,
a],null))},bX=function(a,b){return $APP.Zh(function(c,d,e){e=e.o?e.o(b):e.call(null,b);return $APP.J.A(c,d,e)},$APP.Ui,a)},cX=function(a){var b=$APP.Wv.o(a);return $APP.h(b)?bX(b,a):null},dX=function(a){var b=a.yb;return $APP.fj.j($APP.Ui,$APP.vj.j($APP.Il($APP.Tl,function(c){c=b.Fc(c);return 2>c.length?c[0]:$APP.fk(c)}),b.Ie()))},eX=function(a,b,c){c=$APP.E(c);var d=$APP.D.j(c,$APP.DD);b=FW(b);var e=$APP.h(d)?function(m){try{return cX(m)}catch(u){if(u instanceof Error){var r=u;d.j?d.j(m,r):d.call(null,
m,r);throw r;}throw u;}}:cX;a=$APP.ty(a,b.wb);if($APP.h(a)){var k=dX(b),l=$APP.J.A(a,$APP.IH,k);a=function(){var m=e.o?e.o(l):e.call(null,l);return $APP.h(m)?m:new $APP.g(null,2,[$APP.iw,$APP.Jx.o(l),$APP.XJ,k],null)}();return $APP.J.A(l,$APP.Wy,a)}return null},fX=function(a){if(null!=a&&null!=a.fg)a=a.fg(a);else{var b=fX[$APP.ba(null==a?null:a)];if(null!=b)a=b.o?b.o(a):b.call(null,a);else if(b=fX._,null!=b)a=b.o?b.o(a):b.call(null,a);else throw $APP.$e("History.-init",a);}return a},gX=function(a){if(null!=
a&&null!=a.gg)a=a.gg(a);else{var b=gX[$APP.ba(null==a?null:a)];if(null!=b)a=b.o?b.o(a):b.call(null,a);else if(b=gX._,null!=b)a=b.o?b.o(a):b.call(null,a);else throw $APP.$e("History.-stop",a);}return a},hX=function(a){if(null!=a&&null!=a.af)a=a.af(a);else{var b=hX[$APP.ba(null==a?null:a)];if(null!=b)a=b.o?b.o(a):b.call(null,a);else if(b=hX._,null!=b)a=b.o?b.o(a):b.call(null,a);else throw $APP.$e("History.-get-path",a);}return a},iX=function(a,b,c,d,e,k,l,m){this.qa=a;this.ta=b;this.xb=c;this.tb=d;
this.ub=e;this.U=k;this.G=l;this.J=m;this.F=2230716170;this.P=139264},jX=function(a,b,c,d){var e="undefined"!==typeof location?FW(location).Db:null;return(e=$APP.We(!!d.vc)&&$APP.We(!!d.Db)||$APP.x.j(e,d.Db))?(e=$APP.We(b.altKey))?(e=$APP.We(b.ctrlKey))?(e=$APP.We(b.metaKey))?(e=$APP.We(b.shiftKey))?(e=$APP.We(c.hasAttribute("target"))||$APP.Nh(new $APP.ul(null,new $APP.g(null,2,["",null,"_self",null],null),null),c.getAttribute("target")))?(b=$APP.x.j(0,b.button))?(c=$APP.We(c.isContentEditable))?
$APP.ty(a,d.wb):c:b:e:e:e:e:e:e},kX=function(a,b,c,d,e,k,l){this.qa=a;this.ta=b;this.Fb=c;this.Bb=d;this.U=e;this.G=k;this.J=l;this.F=2230716170;this.P=139264},lX=function(a,b){b=$APP.E(b);var c=$APP.D.A(b,$APP.DE,!0);b=$APP.J.B($APP.Vn.j(b,$APP.DE),$APP.gz,$APP.eN,$APP.y([$APP.hK,a]));a=fX;$APP.h(c)?(c=$APP.Vn.B(b,$APP.hK,$APP.y([$APP.gz,$APP.yH,$APP.SD,$APP.kJ])),c=$APP.Eh(b)?$APP.fj.j($APP.Ui,c):c,b=new iX($APP.hK.o(b),$APP.gz.o(b),$APP.yH.o(b),$APP.SD.o(b),$APP.kJ.o(b),null,$APP.Wi(c),null)):
(c=$APP.Vn.B(b,$APP.hK,$APP.y([$APP.gz,$APP.wF,$APP.PJ])),c=$APP.Eh(b)?$APP.fj.j($APP.Ui,c):c,b=new kX($APP.hK.o(b),$APP.gz.o(b),$APP.wF.o(b),$APP.PJ.o(b),null,$APP.Wi(c),null));a(b)},mX=function(a){return $APP.h(a)?gX(a):null},oX=function(){var a=nX,b=new $APP.g(null,1,[$APP.DE,!0],null);$APP.em.j($APP.cN,mX);lX(function(c,d){null==$APP.p($APP.cN)&&$APP.pj($APP.cN,d);return a.j?a.j(c,d):a.call(null,c,d)},b)},pX=function(a,b,c){a=$APP.Al(a);return $APP.h(!!$APP.ad.Ja[GW($APP.h(b)?b:a)].qc)?c.D?c.D():
c.call(null):HW($APP.h(b)?b:a).then(c,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.iv,$APP.iD],null))})},nX=function(a){if($APP.h(a)){var b=$APP.Bw.o(a),c=$APP.E(b);b=$APP.D.j(c,$APP.O);var d=$APP.D.j(c,$APP.hJ);c=$APP.D.j(c,$APP.ED);$APP.jn("fgl.app.routes",new $APP.g(null,2,[$APP.EI,b,$APP.oA,274],null));return $APP.h(d)?pX(b,c,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.KJ,a],null))}):$APP.P(new $APP.H(null,2,5,$APP.I,[$APP.KJ,a],null))}return null},qX=function(){return new $APP.H(null,
2,5,$APP.I,[$APP.Q,".guild-outer-menu {\n        background-image: linear-gradient(\n            to bottom,\n            rgba(40, 84, 95),\n            rgba(40, 84, 95, 0.5) 60%,\n            transparent 80%\n          ),\n          linear-gradient(to bottom, #1a2a31, #1a2a31 60%, #1a2a3130);\n      }\n\n      .guild-outer-menu li\x3ebutton {\n        position: relative;\n        width: 100%;\n        margin-top: 2rem;\n        text-align: center;\n        display: flex;\n        justify-content: center;\n        align-items: center;\n      }\n\n      .guild-outer-menu .guild-icon {\n        position: relative;\n        display: inline-block;\n        width: 1.3rem;\n        height: 1.3rem;\n        background-position: center;\n        background-repeat: no-repeat;\n        background-size: contain;\n        cursor: pointer;\n        z-index: 1;\n      }\n\n      .guild-outer-menu .guild-bg-light {\n        visibility: hidden;\n        position: absolute;\n        display: inline-block;\n        width: 3rem;\n        height: 3rem;\n        top: 50%;\n        left: 50%;\n        transform: translate(-50%, -50%);\n        background-image: radial-gradient(\n          #55e6ff,\n          #55e6ff90 20%,\n          #55e6ff10 50%,\n          transparent 60%,\n          transparent\n        );\n        background-size: 100%;\n        z-index: 0;\n      }\n      .guild-outer-menu li\x3ebutton.active .guild-bg-light {\n        visibility: visible;\n      }"],
null)},rX=function(a,b){var c=$APP.x.j(a,$APP.p($APP.Hr(new $APP.H(null,1,5,$APP.I,[$APP.fB],null)))),d=$APP.p($APP.Hr(new $APP.H(null,1,5,$APP.I,[$APP.BB],null)));d=$APP.D.A(d,$APP.Bw,$APP.Ui);d=$APP.E(d);d=$APP.D.j(d,$APP.O);d=$APP.h(d)?$APP.Al(d).startsWith(b):d;return $APP.vh(new $APP.H(null,4,5,$APP.I,[$APP.xD,new $APP.g(null,4,[$APP.sp,$APP.h(d)?"active":"",$APP.GA,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.FJ,a],null))},$APP.JH,function(){return $APP.P(new $APP.H(null,1,5,$APP.I,
[$APP.FJ],null))},$APP.Bs,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.iv,a],null))}],null),new $APP.H(null,2,5,$APP.I,[$APP.ZD,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Av,$APP.h(c?c:d)?["url(/images/menu-tab-",$APP.n.o(b),"-active.svg)"].join(""):["url(/images/menu-tab-",$APP.n.o(b),".svg)"].join("")],null)],null)],null),new $APP.H(null,1,5,$APP.I,[$APP.bE],null)],null),new $APP.g(null,1,[$APP.zn,b],null))},sX=function(){return new $APP.H(null,3,5,$APP.I,[$APP.nG,new $APP.H(null,
1,5,$APP.I,[qX],null),new $APP.H(null,6,5,$APP.I,[$APP.BG,new $APP.H(null,3,5,$APP.I,[rX,$APP.SF,"guild"],null),new $APP.H(null,3,5,$APP.I,[rX,$APP.iH,"battlefield"],null),new $APP.H(null,3,5,$APP.I,[rX,$APP.xB,"council"],null),new $APP.H(null,3,5,$APP.I,[rX,$APP.GC,"merchant"],null),new $APP.H(null,3,5,$APP.I,[rX,$APP.vB,"rank"],null)],null)],null)},tX=function(a,b){return[$APP.n.o(a/b),"rem"].join("")},vX=function(a,b,c,d,e){a=$APP.Vr.j(tX,c);var k=a(54.87179487);return new $APP.H(null,3,5,$APP.I,
[$APP.wB,new $APP.H(null,1,5,$APP.I,[sX],null),new $APP.H(null,4,5,$APP.I,[uX,c,new $APP.H(null,4,5,$APP.I,[$APP.II,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.AI,"0.5%"],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.qK,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Jr,a(60)],null)],null),b],null),new $APP.H(null,3,5,$APP.I,[$APP.VC,new $APP.g(null,1,[$APP.Bs,d],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,2,[$APP.R,"/images/panel-close.svg",$APP.Q,new $APP.g(null,3,[$APP.ns,
k,$APP.ls,k,$APP.Gv,a(685.89743588)],null)],null)],null)],null)],null),e],null)],null)},wX=function(){return new $APP.H(null,2,5,$APP.I,[$APP.Q,'button.menu-active::after {\n        content: "";\n        position: absolute;\n        width: 0;\n        height: 0;\n        border: 0.5rem solid transparent;\n        border-left: 0.5rem solid #25606a;\n        left: 100%;\n        top: 50%;\n        transform: translateY(-50%);\n      }'],null)},zX=function(a,b){function c(){return $APP.P(new $APP.H(null,
2,5,$APP.I,[$APP.iv,b],null))}return function(){var d=$APP.p($APP.Hr(new $APP.H(null,1,5,$APP.I,[$APP.BB],null))),e=$APP.p($APP.Hr(new $APP.H(null,1,5,$APP.I,[xX],null)));d=$APP.D.A(d,$APP.Bw,$APP.Ui);d=$APP.E(d);d=$APP.D.j(d,$APP.O);d=$APP.Al(d).startsWith($APP.Al(b));e=$APP.x.j(e,b);return $APP.vh(new $APP.H(null,3,5,$APP.I,[yX,new $APP.g(null,5,[$APP.DH,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[xX,b],null))},$APP.jC,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[xX,null],null))},
$APP.Bs,c,$APP.sp,$APP.h(d)?"menu-active":"",$APP.Q,$APP.h(e?e:d)?new $APP.g(null,2,[$APP.Kr,"radial-gradient(farthest-corner ellipse at top center, #3c8895, #1f545d)",$APP.oD,"white"],null):$APP.Ui],null),a],null),new $APP.g(null,1,[$APP.zn,a],null))}},EX=function(a,b){a=$APP.E(a);a=$APP.D.j(a,AX);return new $APP.H(null,5,5,$APP.I,[BX,new $APP.g(null,1,[$APP.Q,new $APP.g(null,2,[$APP.UB,"12rem 1fr",$APP.ls,"90.8%"],null)],null),$APP.h(a)?new $APP.H(null,2,5,$APP.I,[$APP.kA,new $APP.g(null,4,[$APP.Ou,
"stylesheet",$APP.Nu,a,$APP.T,"text/css",CX,"screen"],null)],null):a,new $APP.H(null,6,5,$APP.I,[DX,new $APP.H(null,2,5,$APP.I,["Basic",$APP.SF],null),new $APP.H(null,2,5,$APP.I,["Alter",$APP.lI],null),new $APP.H(null,2,5,$APP.I,["Vote",$APP.lG],null),new $APP.H(null,2,5,$APP.I,["Management",$APP.vH],null),new $APP.H(null,2,5,$APP.I,["Allocation",$APP.wD],null)],null),b],null)},FX=function(a,b){a=$APP.E(a);a=$APP.D.j(a,AX);return new $APP.H(null,5,5,$APP.I,[BX,new $APP.g(null,1,[$APP.Q,new $APP.g(null,
2,[$APP.UB,"12rem 1fr",$APP.ls,"90.8%"],null)],null),$APP.h(a)?new $APP.H(null,2,5,$APP.I,[$APP.kA,new $APP.g(null,4,[$APP.Ou,"stylesheet",$APP.Nu,a,$APP.T,"text/css",CX,"screen"],null)],null):a,new $APP.H(null,5,5,$APP.I,[DX,new $APP.H(null,2,5,$APP.I,["Mint",$APP.GC],null),new $APP.H(null,2,5,$APP.I,["Land Deeds",$APP.OB],null),new $APP.H(null,2,5,$APP.I,["Burn Land Deeds",$APP.PA],null),new $APP.H(null,2,5,$APP.I,["$GLORY for $GOLD",$APP.zA],null)],null),b],null)},GX=function(a,b){a=$APP.E(a);
a=$APP.D.j(a,AX);return new $APP.H(null,5,5,$APP.I,[BX,new $APP.g(null,1,[$APP.Q,new $APP.g(null,2,[$APP.UB,"12rem 1fr",$APP.ls,"90.8%"],null)],null),$APP.h(a)?new $APP.H(null,2,5,$APP.I,[$APP.kA,new $APP.g(null,4,[$APP.Ou,"stylesheet",$APP.Nu,a,$APP.T,"text/css",CX,"screen"],null)],null):a,new $APP.H(null,3,5,$APP.I,[DX,new $APP.H(null,2,5,$APP.I,["Personal",$APP.vB],null),new $APP.H(null,2,5,$APP.I,["Kingdom",$APP.fE],null)],null),b],null)},LX=function(a,b,c,d,e,k){c="string"===typeof c?new $APP.H(null,
2,5,$APP.I,[$APP.Vs,c],null):c;return new $APP.H(null,7,5,$APP.I,[$APP.ys,HX.Root,new $APP.g(null,2,[$APP.zn,a,IX,function(l){return(l=$APP.We(l))?$APP.P(new $APP.H(null,2,5,$APP.I,[JX,a],null)):l}],null),new $APP.H(null,3,5,$APP.I,[$APP.ys,HX.Title,"string"===typeof b?new $APP.H(null,2,5,$APP.I,[KX,b],null):b],null),$APP.h(c)?new $APP.H(null,3,5,$APP.I,[$APP.ys,HX.Description,c],null):c,function(){var l=$APP.q(k);return l?$APP.vj.j(function(m){return $APP.fj.o(new $APP.H(null,3,5,$APP.I,[$APP.ys,
HX.Action,m],null))},k):l}(),function(){var l=$APP.We(e);return l?new $APP.H(null,3,5,$APP.I,[$APP.ys,HX.Close,"x"],null):l}()],null)},NX=function(){var a=$APP.Hr(new $APP.H(null,1,5,$APP.I,[MX],null));return $APP.vj.j(function(b){var c=$APP.A(b,0,null);b=$APP.A(b,1,null);var d=$APP.E(b);b=$APP.D.j(d,$APP.Us);var e=$APP.D.j(d,$APP.Os),k=$APP.D.j(d,$APP.T),l=$APP.D.j(d,$APP.LJ);d=$APP.D.j(d,$APP.Ps);return $APP.vh(new $APP.H(null,7,5,$APP.I,[LX,c,b,e,k,l,d],null),new $APP.g(null,1,[$APP.zn,c],null))},
$APP.p(a))},QX=function(){return new $APP.H(null,3,5,$APP.I,[$APP.fj,$APP.vh(new $APP.H(null,3,5,$APP.I,[$APP.ys,HX.Provider,new $APP.H(null,4,5,$APP.I,[$APP.ys,HX.Viewport,new $APP.g(null,1,[$APP.As,!0],null),new $APP.H(null,1,5,$APP.I,[OX],null)],null)],null),new $APP.g(null,1,[$APP.zn,PX],null)),NX()],null)},RX=function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.iv,$APP.JF],null))},TX=function(a){return new $APP.H(null,3,5,$APP.I,[SX,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.dH,"64vw"],
null)],null),a],null)},WX=function(a,b){var c=$APP.Bw.o(a),d=$APP.E(c);c=$APP.D.j(d,$APP.O);var e=$APP.D.j(d,$APP.UE);d=$APP.Al($APP.h(c)?c:$APP.XI).startsWith("the-map");d=$APP.h(d)?d:$APP.Al($APP.h(c)?c:$APP.XI).startsWith("start");var k=$APP.Al($APP.h(c)?c:$APP.XI).startsWith("guild"),l=$APP.Al($APP.h(c)?c:$APP.XI).startsWith("merchant");c=$APP.Al($APP.h(c)?c:$APP.XI).startsWith("rank");return new $APP.H(null,5,5,$APP.I,[UX,new $APP.g(null,1,[$APP.Q,new $APP.g(null,2,[$APP.UB,"1fr auto 1fr",VX,
"strech"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.h(d)?$APP.$h:TX,new $APP.H(null,2,5,$APP.I,[$APP.h(e)?function(m){return new $APP.H(null,6,5,$APP.I,[vX,a,e,80,RX,m],null)}:$APP.$h,new $APP.H(null,2,5,$APP.I,[$APP.h(k)?function(m){return new $APP.H(null,3,5,$APP.I,[EX,a,m],null)}:$APP.h(l)?function(m){return new $APP.H(null,3,5,$APP.I,[FX,a,m],null)}:$APP.h(c)?function(m){return new $APP.H(null,3,5,$APP.I,[GX,a,m],null)}:$APP.$h,b],null)],null)],null),new $APP.H(null,1,5,$APP.I,[QX],null),
new $APP.H(null,1,5,$APP.I,[$W],null)],null)},YX=function(a){return $APP.yp(new $APP.g(null,2,[$APP.jF,function(){return $APP.h(a)?aX(new $APP.g(null,1,[$APP.XE,a],null)):a},$APP.ip,function(){var b=$APP.p($APP.Hr(new $APP.H(null,1,5,$APP.I,[XX],null))),c=$APP.A(b,0,null),d=$APP.A(b,1,null),e=$APP.A(b,2,null);b=$APP.A(b,3,null);return $APP.We(e)?new $APP.H(null,3,5,$APP.I,[$APP.xs,new $APP.g(null,4,[$APP.rp,"connect-btn",$APP.ss,$APP.EJ,$APP.O,d,$APP.Bs,b],null),new $APP.H(null,2,5,$APP.I,[$APP.Is,
c],null)],null):$APP.h(e)?new $APP.H(null,2,5,$APP.I,[$APP.Is,c],null):null}],null))},aY=function(a){return new $APP.H(null,4,5,$APP.I,[$APP.ys,ZX.Root,new $APP.g(null,2,[$APP.sp,"bg-no-repeat",$APP.Q,new $APP.g(null,4,[$APP.Av,'\nurl("/images/header-bg.svg")\n',$X,"multiply",$APP.sJ,"\n-10px 0.625rem",$APP.Fv,"\n100% 100%"],null)],null),a],null)},pY=function(){$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.ZF],null));$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.yA],null));$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.YA],
null));var a=$APP.p($APP.Hr(new $APP.H(null,1,5,$APP.I,[bY],null))),b=$APP.A(a,0,null),c=$APP.A(a,1,null);a=$APP.A(a,2,null);return new $APP.H(null,2,5,$APP.I,[cY,new $APP.H(null,2,5,$APP.I,[aY,new $APP.H(null,9,5,$APP.I,[$APP.ys,ZX.List,new $APP.g(null,1,[$APP.sp,"grid justify-items-stretch justify-between items-center content-center"],null),$APP.vh(new $APP.H(null,4,5,$APP.I,[$APP.ys,ZX.Item,new $APP.g(null,1,[$APP.sp,"cs1 ce3"],null),new $APP.H(null,4,5,$APP.I,[$APP.ys,ZX.Link,new $APP.g(null,
2,[$APP.sp,"cursor-pointer block p-2",$APP.Bs,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.iv,$APP.JF],null))}],null),new $APP.H(null,2,5,$APP.I,[dY,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.dH,"8.8125rem"],null)],null)],null)],null)],null),new $APP.g(null,1,[$APP.zn,eY],null)),$APP.vh(new $APP.H(null,4,5,$APP.I,[$APP.ys,ZX.Item,new $APP.g(null,1,[$APP.sp,"cs6 ce8"],null),new $APP.H(null,2,5,$APP.I,[$APP.ML,new $APP.H(null,4,5,$APP.I,[fY,new $APP.g(null,1,[$APP.Bs,function(){return $APP.ou("wallet_watchAsset",
new $APP.g(null,2,[$APP.T,gY,hY,new $APP.g(null,4,[$APP.su,$APP.DM.address,$APP.WD,"GLORY",iY,18,$APP.tJ,"https://cdn.jsdelivr.net/gh/ForGloryGame/for-glory-frontend@dev/resources/app/public/images/glory-token.png"],null)],null),console.log)}],null),new $APP.H(null,3,5,$APP.I,[$APP.vM,"3rem",new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Or,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.LL,c,new $APP.g(null,1,[$APP.sp,"fi mr-1"],null)],null)],null)],null)],null),
new $APP.g(null,1,[$APP.zn,jY],null)),$APP.vh(new $APP.H(null,4,5,$APP.I,[$APP.ys,ZX.Item,new $APP.g(null,1,[$APP.sp,"cs8 ce10"],null),new $APP.H(null,2,5,$APP.I,[$APP.ML,new $APP.H(null,4,5,$APP.I,[fY,new $APP.g(null,1,[$APP.Bs,function(){return $APP.ou("wallet_watchAsset",new $APP.g(null,2,[$APP.T,gY,hY,new $APP.g(null,4,[$APP.su,$APP.EM.address,$APP.WD,"GOLD",iY,18,$APP.tJ,"https://cdn.jsdelivr.net/gh/ForGloryGame/for-glory-frontend@dev/resources/app/public/images/gold-token.png"],null)],null),
console.log)}],null),new $APP.H(null,3,5,$APP.I,[$APP.wM,"3rem",new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[$APP.Or,"-1.4rem 0 -1.4rem -1.4rem"],null)],null)],null),new $APP.H(null,3,5,$APP.I,[$APP.LL,b,new $APP.g(null,1,[$APP.sp,"fi mr-1"],null)],null)],null)],null)],null),new $APP.g(null,1,[$APP.zn,kY],null)),$APP.vh(new $APP.H(null,4,5,$APP.I,[$APP.ys,ZX.Item,new $APP.g(null,1,[$APP.sp,"cs10 ce12"],null),new $APP.H(null,2,5,$APP.I,[$APP.ML,new $APP.H(null,6,5,$APP.I,[lY,new $APP.H(null,2,5,$APP.I,
[$APP.wM,"2rem"],null),new $APP.H(null,2,5,$APP.I,[$APP.dJ,"1"],null),new $APP.H(null,3,5,$APP.I,[$APP.fI,new $APP.H(null,2,5,$APP.I,[$APP.qH,new $APP.g(null,1,[$APP.R,"/images/ratio.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.qH,new $APP.g(null,2,[$APP.Q,new $APP.g(null,1,[$APP.Mr,"rotate(180deg)"],null),$APP.R,"/images/ratio.svg"],null)],null)],null),a,new $APP.H(null,3,5,$APP.I,[$APP.vM,"2rem",new $APP.g(null,1,[$APP.sp,"mx-1"],null)],null)],null)],null)],null),new $APP.g(null,1,[$APP.zn,
mY],null)),$APP.vh(new $APP.H(null,4,5,$APP.I,[$APP.ys,ZX.Item,new $APP.g(null,1,[$APP.sp,"cs12 ce14"],null),new $APP.H(null,2,5,$APP.I,[YX,"0x4"],null)],null),new $APP.g(null,1,[$APP.zn,nY],null)),$APP.vh(new $APP.H(null,3,5,$APP.I,[$APP.ys,ZX.Item,new $APP.g(null,1,[$APP.sp,"cs14"],null)],null),new $APP.g(null,1,[$APP.zn,oY],null))],null)],null)],null)},sY=function(){var a=$APP.Hr(new $APP.H(null,1,5,$APP.I,[$APP.AB],null)),b=$APP.Hr(new $APP.H(null,1,5,$APP.I,[$APP.KF],null)),c=$APP.p($APP.Hr(new $APP.H(null,
1,5,$APP.I,[$APP.BB],null))),d=$APP.D.j(c,$APP.Bw);d=$APP.E(d);var e=$APP.D.j(d,$APP.O);d=$APP.D.j(d,$APP.QD);var k=function(){var l=e instanceof $APP.ri;return l?$APP.Al(e).startsWith("guild-"):l}();setTimeout(function(){return $APP.h(function(){var l=!$APP.x.j($APP.p(a),$APP.nD);return l?$APP.h(e)?!$APP.x.j(e,$APP.JF):e:l}())?($APP.P(new $APP.H(null,2,5,$APP.I,[$APP.iv,$APP.JF],null)),$APP.ru(),new $APP.H(null,1,5,$APP.I,[$APP.zv],null)):$APP.h(function(){var l=$APP.x.j($APP.p(a),$APP.nD);return l?
(l=$APP.p(b),$APP.h(l)?$APP.h(e)?!$APP.x.j(e,$APP.JF):e:l):l}())?($APP.P(new $APP.H(null,2,5,$APP.I,[$APP.iv,$APP.JF],null)),$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.nE],null)),new $APP.H(null,1,5,$APP.I,[$APP.zv],null)):null},500);return new $APP.H(null,7,5,$APP.I,[qY,new $APP.g(null,1,[$APP.Q,new $APP.g(null,1,[rY,'"header" min-content "main"'],null)],null),new $APP.H(null,1,5,$APP.I,[pY],null),$APP.h(k)?new $APP.H(null,1,5,$APP.I,[$APP.xL],null):k,function(){var l=$APP.We(k);return l?new $APP.H(null,
1,5,$APP.I,[$APP.wO],null):l}(),new $APP.H(null,3,5,$APP.I,[WX,c,$APP.h(d)?new $APP.H(null,2,5,$APP.I,[d,c],null):new $APP.H(null,1,5,$APP.I,[$APP.zv],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.kA,new $APP.g(null,2,[$APP.Ou,"stylesheet",$APP.Nu,"/fonts/family.css"],null)],null)],null)},CY=function(a){var b=XW(a);return $APP.h(function(){var c=XW($APP.QI);return tY.j?tY.j(c,b):tY.call(null,c,b)}())?uY:$APP.h(function(){var c=XW($APP.JD);return tY.j?tY.j(c,b):tY.call(null,c,b)}())?vY:$APP.h(function(){var c=
XW($APP.GH);return tY.j?tY.j(c,b):tY.call(null,c,b)}())?wY:$APP.h(function(){var c=XW($APP.FF);return tY.j?tY.j(c,b):tY.call(null,c,b)}())?xY:$APP.h(function(){var c=XW($APP.ZG);return tY.j?tY.j(c,b):tY.call(null,c,b)}())?yY:$APP.h(function(){var c=XW($APP.DG);return tY.j?tY.j(c,b):tY.call(null,c,b)}())?zY:$APP.h(function(){var c=XW($APP.dD);return tY.j?tY.j(c,b):tY.call(null,c,b)}())?AY:BY},DY=function(a){var b=$APP.A(a,0,null);a=$APP.A(a,1,null);return new $APP.H(null,2,5,$APP.I,[[$APP.n.o(b),$APP.n.o(" ")].join(""),
a],null)},FY=function(a,b,c){var d=$APP.A(a,0,null);a=$APP.A(a,1,null);return new $APP.H(null,2,5,$APP.I,[[$APP.n.o(d),"%c",$APP.n.o(b),"%c"].join(""),$APP.mi.B(a,["color:",$APP.n.o($APP.D.j(EY,c))].join(""),$APP.y(["color:black"]))],null)},HY=function(a,b,c){var d=$APP.A(a,0,null);a=$APP.A(a,1,null);return new $APP.H(null,2,5,$APP.I,[[$APP.n.o(d),"%c",$APP.n.o(b),"%c"].join(""),$APP.mi.B(a,["color:",$APP.n.o($APP.D.j(EY,GY)),";background-color:",$APP.n.o($APP.D.j(EY,c))].join(""),$APP.y(["color:black;background-color:inherit"]))],
null)},IY=function(a){function b(c,d){return d>=c}a=XW(a);if(b(XW($APP.QI),a))return"error";if(b(XW($APP.JD),a))return"warn";if(b(XW($APP.GH),a))return"info";b(XW($APP.FF),a);return"log"},JY=function(a){return function(b){b=$APP.E(b);var c=$APP.D.j(b,$APP.fF),d=$APP.D.j(b,$APP.jA),e=$APP.D.j(b,$APP.Qq);d=IY(d);d=$APP.Ha(console,d);d=$APP.h(d)?d:console.log;$APP.Mi(d,a.o?a.o(b):a.call(null,b));return $APP.h(e)?d(["[",$APP.n.o(c),"]"].join(""),$APP.n.o(e),"\n",e.stack):null}},LY=function(a){$APP.em.A(KY,
$APP.Vn,a);$APP.OL.unmountComponentAtNode(a)},MY=function(a,b,c){var d=$APP.uo;$APP.uo=!0;try{return $APP.OL.render(a.D?a.D():a.call(null),b,function(){var e=$APP.uo;$APP.uo=!1;try{return $APP.em.N(KY,$APP.J,b,a),$APP.In.flush_after_render(),null!=c?c.D?c.D():c.call(null):null}finally{$APP.uo=e}})}finally{$APP.uo=d}},OY=function(a,b){return NY(a,b)},NY=function(a,b){$APP.jo();var c=$APP.th($APP.xp)?new $APP.H(null,2,5,$APP.I,[$APP.xp,$APP.xp],null):new $APP.H(null,2,5,$APP.I,[$APP.xp,PY.o($APP.xp)],
null),d=$APP.A(c,0,null);c=$APP.A(c,1,null);return MY(function(){return $APP.Mn(d,$APP.th(a)?a.D?a.D():a.call(null):a)},b,c)},QY=function(){MW();var a=document.getElementById("app");LY(a);setTimeout(function(){return OY($APP.bk([$APP.zv,new $APP.g(null,1,[$APP.Q,new $APP.g(null,5,[$APP.zF,"hidden",$APP.aE,"fixed",$APP.Bv,-100,$APP.ks,0,$APP.ms,0],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-rank-4.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,
new $APP.g(null,1,[$APP.R,"/images/rank-3.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-woff.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-morningstar.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-merchant-active.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/panel-bg-small.png"],null)],null),
new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/logo-512.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/avatar-2.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-phoenix-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/twitter.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-phoenix-flag.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/eth-token.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-down-arrow.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-back-btn.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/open-sea.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-bg-mask-s.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/avatar-1.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-rank-3.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-rank-active.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/logo-256.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/discord.svg"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/staked-tag.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-basic.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/logo-128.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-guild.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-guild-active.svg"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-kingdom-active.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-lion-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/panel-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-astas.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/check.svg"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/for-glory-bg.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-battlefield.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/share.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/ratio.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/logo-800.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/rank-1.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/crown.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/k4.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-battlefield-active.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-bg-mask.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-council.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-griffin-flag.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/k3.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,
"/images/menu-tab-rank.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-woff-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-ruins-active.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-rank-2.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/logo-1024.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,
new $APP.g(null,1,[$APP.R,"/images/select-kingdom-dragon.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/gold-token.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-council-active.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/header-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-phoenix.png"],null)],null),
new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/lord-example.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-woff-flag.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-vote-hover.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/k1.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-merchant-active.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/logo-600.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/k5.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/triangle.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-basic-hover.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-allocation.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/glory-token.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/k2.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/start-sound-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/avatar-3.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-management.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/rank-2.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/orange-btn.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/discord-2.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/medium.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-bottom-mask.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-rank-5.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/copy.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/start-bg-lg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/start-nosound.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/blue-btn.svg"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/rank-line-bg.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/votes-no.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/start-sound.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/panel-close.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/menu-tab-merchant.svg"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-rank-1.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/mint.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-ruins.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-battlefield.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/square.svg"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-division-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-griffin.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-dragon-flag.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/knight-example.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,
1,[$APP.R,"/images/kingdom-flamingo.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/rank-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/weapon.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-lion.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,
1,[$APP.R,"/images/kingdom-management-hover.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/start-btn-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-battlefield-active.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-council-active.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-dragon-bg.png"],null)],null),
new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-allocation-hover.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/landeed-token.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-luclars.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-alter.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/avatar-knight.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-council.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/card-bg.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/scroll-bar.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-vote.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/logo.png"],null)],
null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/popup.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/header-bg.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/avatar-lord.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/guild-avatar.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-dawns.png"],null)],
null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/eject.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/start-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-lion-flag.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/header-bg@2x.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/rune-token.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/select-kingdom-griffin-bg.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/twitter-2.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/kingdom-alter-hover.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/medium-2.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-merchant.png"],
null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/open-sea-2.svg"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/map-kingdom.png"],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.Lr,new $APP.g(null,1,[$APP.R,"/images/mega.png"],null)],null)],!0),document.getElementById("extra"))},3E3);OY(new $APP.H(null,1,5,$APP.I,[sY],null),a);$APP.jn("fgl.app.routes",new $APP.g(null,2,[$APP.BH,$APP.Ox,$APP.oA,280],null));oX()};$APP.f=sW.prototype;
$APP.f.add=function(a,b){tW(this);this.sb=null;a=uW(this,a);var c=this.Ga.get(a);c||this.Ga.set(a,c=[]);c.push(b);this.lb+=1;return this};$APP.f.remove=function(a){tW(this);a=uW(this,a);return this.Ga.has(a)?(this.sb=null,this.lb-=this.Ga.get(a).length,this.Ga.delete(a)):!1};$APP.f.clear=function(){this.Ga=this.sb=null;this.lb=0};$APP.f.isEmpty=function(){tW(this);return 0==this.lb};
$APP.f.forEach=function(a,b){tW(this);this.Ga.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};$APP.f.Ie=function(){tW(this);const a=Array.from(this.Ga.values()),b=Array.from(this.Ga.keys()),c=[];for(let d=0;d<b.length;d++){const e=a[d];for(let k=0;k<e.length;k++)c.push(b[d])}return c};$APP.f.Fc=function(a){tW(this);let b=[];if("string"===typeof a)vW(this,a)&&(b=b.concat(this.Ga.get(uW(this,a))));else{a=Array.from(this.Ga.values());for(let c=0;c<a.length;c++)b=b.concat(a[c])}return b};
$APP.f.set=function(a,b){tW(this);this.sb=null;a=uW(this,a);vW(this,a)&&(this.lb-=this.Ga.get(a).length);this.Ga.set(a,[b]);this.lb+=1;return this};$APP.f.get=function(a,b){if(!a)return b;a=this.Fc(a);return 0<a.length?String(a[0]):b};
$APP.f.toString=function(){if(this.sb)return this.sb;if(!this.Ga)return"";const a=[],b=Array.from(this.Ga.keys());for(var c=0;c<b.length;c++){var d=b[c];const k=encodeURIComponent(String(d)),l=this.Fc(d);for(d=0;d<l.length;d++){var e=k;""!==l[d]&&(e+="\x3d"+encodeURIComponent(String(l[d])));a.push(e)}}return this.sb=a.join("\x26")};$APP.f.clone=function(){var a=new sW;a.sb=this.sb;this.Ga&&(a.Ga=new Map(this.Ga),a.lb=this.lb);return a};
$APP.f.kg=function(a){a&&!this.Eb&&(tW(this),this.sb=null,this.Ga.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.sb=null,this.Ga.set(uW(this,d),$APP.va(b)),this.lb+=b.length))},this));this.Eb=a};$APP.f.extend=function(a){for(var b=0;b<arguments.length;b++)qW(arguments[b],function(c,d){this.add(d,c)},this)};var RY=/[#\/\?@]/g,SY=/[#\?]/g,TY=/[#\?:]/g,UY=/#/g,EW=/[#\?@]/g;$APP.f=zW.prototype;
$APP.f.toString=function(){var a=[],b=this.vc;b&&a.push(yW(b,RY,!0),":");var c=this.Db;if(c||"file"==b)a.push("//"),(b=this.Yc)&&a.push(yW(b,RY,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.ud,null!=c&&a.push(":",String(c));if(c=this.wb)this.Db&&"/"!=c.charAt(0)&&a.push("/"),a.push(yW(c,"/"==c.charAt(0)?SY:TY,!0));(c=this.yb.toString())&&a.push("?",c);(c=this.lc)&&a.push("#",yW(c,UY));return a.join("")};
$APP.f.resolve=function(a){var b=this.clone(),c=!!a.vc;c?AW(b,a.vc):c=!!a.Yc;if(c){var d=a.Yc;BW(b);b.Yc=d}else c=!!a.Db;c?(d=a.Db,BW(b),b.Db=d):c=null!=a.ud;d=a.wb;if(c)CW(b,a.ud);else if(c=!!a.wb){if("/"!=d.charAt(0))if(this.Db&&!this.wb)d="/"+d;else{var e=b.wb.lastIndexOf("/");-1!=e&&(d=b.wb.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var k=[],l=0;l<e.length;){var m=e[l++];"."==m?d&&l==e.length&&k.push(""):
".."==m?((1<k.length||1==k.length&&""!=k[0])&&k.pop(),d&&l==e.length&&k.push("")):(k.push(m),d=!0)}d=k.join("/")}else d=e}c?(BW(b),b.wb=d):c=""!==a.yb.toString();c?DW(b,a.yb.clone()):c=!!a.lc;c&&(a=a.lc,BW(b),b.lc=a);return b};$APP.f.clone=function(){return new zW(this)};$APP.f.getQuery=function(){return this.yb.toString()};$APP.f.removeParameter=function(a){BW(this);this.yb.remove(a);return this};$APP.f.kg=function(a){this.Eb=a;this.yb&&this.yb.kg(a)};
var ZW=function ZW(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.Mg(c.slice(0),0,null):null;return ZW.B(c)};ZW.B=function(a){return new $APP.H(null,3,5,$APP.I,[$APP.fj,new $APP.H(null,2,5,$APP.I,[$APP.ys,$APP.zs.Trigger],null),a],null)};ZW.I=0;ZW.T=function(a){return this.B($APP.q(a))};
var tY=function tY(a){switch(arguments.length){case 1:return tY.o(arguments[0]);case 2:return tY.j(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=new $APP.Mg(c.slice(2),0,null);return tY.B(arguments[0],arguments[1],c)}};tY.o=function(){return!0};tY.j=function(a,b){return a<=b};tY.B=function(a,b,c){for(;;)if(a<=b)if($APP.w(c))a=b,b=$APP.t(c),c=$APP.w(c);else return b<=$APP.t(c);else return!1};
tY.T=function(a){var b=$APP.t(a),c=$APP.w(a);a=$APP.t(c);c=$APP.w(c);return this.B(b,a,c)};tY.I=2;var uX=function uX(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.Mg(c.slice(1),0,null):null;return uX.B(arguments[0],c)};
uX.B=function(a,b){return $APP.fj.j(new $APP.H(null,2,5,$APP.I,[$APP.zv,new $APP.g(null,1,[$APP.Q,new $APP.g(null,5,[$APP.Av,"url(/images/panel-bg-small.png)",$APP.Fv,"100%",$APP.dH,[$APP.n.o(a),"rem"].join(""),$APP.ns,[$APP.n.o(a),"rem"].join(""),$APP.ls,[$APP.n.o(a/2.08157647),"rem"].join("")],null)],null)],null),b)};uX.I=1;uX.T=function(a){var b=$APP.t(a);a=$APP.w(a);return this.B(b,a)};$APP.f=iX.prototype;$APP.f.va=function(a,b){return this.ca(null,b,null)};
$APP.f.ca=function(a,b,c){switch(b instanceof $APP.ri?b.ka:null){case "on-navigate":return this.qa;case "router":return this.ta;case "popstate-listener":return this.xb;case "hashchange-listener":return this.tb;case "last-fragment":return this.ub;default:return $APP.D.A(this.G,b,c)}};$APP.f.nb=function(a,b,c){return $APP.cf.A(function(d,e){var k=$APP.A(e,0,null);e=$APP.A(e,1,null);return b.A?b.A(d,k,e):b.call(null,d,k,e)},c,this)};
$APP.f.ba=function(a,b,c){return $APP.Nl(b,function(d){return $APP.Nl(b,$APP.Sl,""," ","",c,d)},"#reitit.frontend.history.FragmentHistory{",", ","}",c,$APP.Fj.j(new $APP.H(null,5,5,$APP.I,[new $APP.H(null,2,5,$APP.I,[$APP.hK,this.qa],null),new $APP.H(null,2,5,$APP.I,[$APP.gz,this.ta],null),new $APP.H(null,2,5,$APP.I,[$APP.yH,this.xb],null),new $APP.H(null,2,5,$APP.I,[$APP.SD,this.tb],null),new $APP.H(null,2,5,$APP.I,[$APP.kJ,this.ub],null)],null),this.G))};
$APP.f.Ca=function(){return new $APP.xk(this,5,new $APP.H(null,5,5,$APP.I,[$APP.hK,$APP.gz,$APP.yH,$APP.SD,$APP.kJ],null),$APP.h(this.G)?$APP.ug(this.G):$APP.$i())};$APP.f.$=function(){return this.U};$APP.f.ia=function(){return 5+$APP.hh(this.G)};$APP.f.ea=function(){var a=this.J;return null!=a?a:this.J=a=354327177^$APP.Wg(this)};
$APP.f.da=function(a,b){return null!=b&&this.constructor===b.constructor&&$APP.x.j(this.qa,b.qa)&&$APP.x.j(this.ta,b.ta)&&$APP.x.j(this.xb,b.xb)&&$APP.x.j(this.tb,b.tb)&&$APP.x.j(this.ub,b.ub)&&$APP.x.j(this.G,b.G)};
$APP.f.fg=function(){function a(e){var k=hX(c);return $APP.x.j("popstate",e.type)||$APP.Vi($APP.p(b),k)?$APP.ez(c,k):null}var b=$APP.oj(null),c=$APP.J.A(this,$APP.kJ,b),d=$APP.J.B(c,$APP.yH,$APP.sd(window,"popstate",a,!1),$APP.y([$APP.SD,$APP.sd(window,"hashchange",a,!1)]));$APP.ez(d,hX(d));return d};$APP.f.gg=function(){$APP.Dd(this.xb);$APP.Dd(this.tb);return null};$APP.f.ce=function(a,b){$APP.pj(this.ub,b);a=eX(this.ta,b,this);return this.qa.j?this.qa.j(a,this):this.qa.call(null,a,this)};
$APP.f.af=function(){var a=window.location.hash.substring(1);return $APP.x.j("",a)?"/":a};$APP.f.eg=function(a,b){return $APP.h(b)?["#",$APP.n.o(b)].join(""):null};$APP.f.Cb=function(a,b){return $APP.Nh(new $APP.ul(null,new $APP.g(null,5,[$APP.kJ,null,$APP.gz,null,$APP.yH,null,$APP.hK,null,$APP.SD,null],null),null),b)?$APP.Vn.j($APP.Of($APP.fj.j($APP.Ui,this),this.U),b):new iX(this.qa,this.ta,this.xb,this.tb,this.ub,this.U,$APP.Wi($APP.Vn.j(this.G,b)),null)};
$APP.f.hb=function(a,b){switch(b instanceof $APP.ri?b.ka:null){case "on-navigate":case "router":case "popstate-listener":case "hashchange-listener":case "last-fragment":return!0;default:return $APP.Nh(this.G,b)}};
$APP.f.ua=function(a,b,c){return $APP.h($APP.si.j?$APP.si.j($APP.hK,b):$APP.si.call(null,$APP.hK,b))?new iX(c,this.ta,this.xb,this.tb,this.ub,this.U,this.G,null):$APP.h($APP.si.j?$APP.si.j($APP.gz,b):$APP.si.call(null,$APP.gz,b))?new iX(this.qa,c,this.xb,this.tb,this.ub,this.U,this.G,null):$APP.h($APP.si.j?$APP.si.j($APP.yH,b):$APP.si.call(null,$APP.yH,b))?new iX(this.qa,this.ta,c,this.tb,this.ub,this.U,this.G,null):$APP.h($APP.si.j?$APP.si.j($APP.SD,b):$APP.si.call(null,$APP.SD,b))?new iX(this.qa,
this.ta,this.xb,c,this.ub,this.U,this.G,null):$APP.h($APP.si.j?$APP.si.j($APP.kJ,b):$APP.si.call(null,$APP.kJ,b))?new iX(this.qa,this.ta,this.xb,this.tb,c,this.U,this.G,null):new iX(this.qa,this.ta,this.xb,this.tb,this.ub,this.U,$APP.J.A(this.G,b,c),null)};$APP.f.ha=function(){return $APP.q($APP.Fj.j(new $APP.H(null,5,5,$APP.I,[new $APP.Bk($APP.hK,this.qa),new $APP.Bk($APP.gz,this.ta),new $APP.Bk($APP.yH,this.xb),new $APP.Bk($APP.SD,this.tb),new $APP.Bk($APP.kJ,this.ub)],null),this.G))};
$APP.f.aa=function(a,b){return new iX(this.qa,this.ta,this.xb,this.tb,this.ub,b,this.G,this.J)};$APP.f.ma=function(a,b){return $APP.Fh(b)?this.ua(null,$APP.rh(b,0),$APP.rh(b,1)):$APP.cf.A($APP.of,this,b)};$APP.f=kX.prototype;$APP.f.va=function(a,b){return this.ca(null,b,null)};
$APP.f.ca=function(a,b,c){switch(b instanceof $APP.ri?b.ka:null){case "on-navigate":return this.qa;case "router":return this.ta;case "listen-key":return this.Fb;case "click-listen-key":return this.Bb;default:return $APP.D.A(this.G,b,c)}};$APP.f.nb=function(a,b,c){return $APP.cf.A(function(d,e){var k=$APP.A(e,0,null);e=$APP.A(e,1,null);return b.A?b.A(d,k,e):b.call(null,d,k,e)},c,this)};
$APP.f.ba=function(a,b,c){return $APP.Nl(b,function(d){return $APP.Nl(b,$APP.Sl,""," ","",c,d)},"#reitit.frontend.history.Html5History{",", ","}",c,$APP.Fj.j(new $APP.H(null,4,5,$APP.I,[new $APP.H(null,2,5,$APP.I,[$APP.hK,this.qa],null),new $APP.H(null,2,5,$APP.I,[$APP.gz,this.ta],null),new $APP.H(null,2,5,$APP.I,[$APP.wF,this.Fb],null),new $APP.H(null,2,5,$APP.I,[$APP.PJ,this.Bb],null)],null),this.G))};
$APP.f.Ca=function(){return new $APP.xk(this,4,new $APP.H(null,4,5,$APP.I,[$APP.hK,$APP.gz,$APP.wF,$APP.PJ],null),$APP.h(this.G)?$APP.ug(this.G):$APP.$i())};$APP.f.$=function(){return this.U};$APP.f.ia=function(){return 4+$APP.hh(this.G)};$APP.f.ea=function(){var a=this.J;return null!=a?a:this.J=a=-1654764186^$APP.Wg(this)};
$APP.f.da=function(a,b){return null!=b&&this.constructor===b.constructor&&$APP.x.j(this.qa,b.qa)&&$APP.x.j(this.ta,b.ta)&&$APP.x.j(this.Fb,b.Fb)&&$APP.x.j(this.Bb,b.Bb)&&$APP.x.j(this.G,b.G)};
$APP.f.fg=function(){var a=this,b=this,c=function(){var e=$APP.MJ.o(b);return $APP.h(e)?e:jX}(),d=$APP.J.B(b,$APP.wF,$APP.sd(window,"popstate",function(){return b.ce(null,b.af(null))},!1),$APP.y([$APP.PJ,$APP.sd(document,"click",function(e){var k=e.pd;a:for(k=null!=k.composedPath?k.composedPath()[0]:e.target;;)if($APP.h(k)){if($APP.x.j("A",k.nodeName))break a;k=k.parentNode}else{k=null;break a}if($APP.h(k)){var l=FW(k.href);if($APP.h(c.N?c.N(a.ta,e,k,l):c.call(null,a.ta,e,k,l)))return e.preventDefault(),
e=[$APP.n.o(l.wb),$APP.h(""!==l.yb.toString())?["?",$APP.n.o(l.getQuery())].join(""):null,$APP.h(!!l.lc)?["#",$APP.n.o(l.lc)].join(""):null].join(""),window.history.pushState(null,"",e),b.ce(null,e)}return null})]));$APP.ez(d,hX(d));return d};$APP.f.ce=function(a,b){a=eX(this.ta,b,this);return this.qa.j?this.qa.j(a,this):this.qa.call(null,a,this)};$APP.f.gg=function(){$APP.Dd(this.Fb);$APP.Dd(this.Bb);return null};$APP.f.af=function(){return[$APP.n.o(window.location.pathname),$APP.n.o(window.location.search)].join("")};
$APP.f.eg=function(a,b){return b};$APP.f.Cb=function(a,b){return $APP.Nh(new $APP.ul(null,new $APP.g(null,4,[$APP.gz,null,$APP.wF,null,$APP.PJ,null,$APP.hK,null],null),null),b)?$APP.Vn.j($APP.Of($APP.fj.j($APP.Ui,this),this.U),b):new kX(this.qa,this.ta,this.Fb,this.Bb,this.U,$APP.Wi($APP.Vn.j(this.G,b)),null)};$APP.f.hb=function(a,b){switch(b instanceof $APP.ri?b.ka:null){case "on-navigate":case "router":case "listen-key":case "click-listen-key":return!0;default:return $APP.Nh(this.G,b)}};
$APP.f.ua=function(a,b,c){return $APP.h($APP.si.j?$APP.si.j($APP.hK,b):$APP.si.call(null,$APP.hK,b))?new kX(c,this.ta,this.Fb,this.Bb,this.U,this.G,null):$APP.h($APP.si.j?$APP.si.j($APP.gz,b):$APP.si.call(null,$APP.gz,b))?new kX(this.qa,c,this.Fb,this.Bb,this.U,this.G,null):$APP.h($APP.si.j?$APP.si.j($APP.wF,b):$APP.si.call(null,$APP.wF,b))?new kX(this.qa,this.ta,c,this.Bb,this.U,this.G,null):$APP.h($APP.si.j?$APP.si.j($APP.PJ,b):$APP.si.call(null,$APP.PJ,b))?new kX(this.qa,this.ta,this.Fb,c,this.U,
this.G,null):new kX(this.qa,this.ta,this.Fb,this.Bb,this.U,$APP.J.A(this.G,b,c),null)};$APP.f.ha=function(){return $APP.q($APP.Fj.j(new $APP.H(null,4,5,$APP.I,[new $APP.Bk($APP.hK,this.qa),new $APP.Bk($APP.gz,this.ta),new $APP.Bk($APP.wF,this.Fb),new $APP.Bk($APP.PJ,this.Bb)],null),this.G))};$APP.f.aa=function(a,b){return new kX(this.qa,this.ta,this.Fb,this.Bb,b,this.G,this.J)};$APP.f.ma=function(a,b){return $APP.Fh(b)?this.ua(null,$APP.rh(b,0),$APP.rh(b,1)):$APP.cf.A($APP.of,this,b)};
var GY=$APP.K("white"),VY=$APP.N("fgl.app.subs","re-pressed-example"),rY=$APP.K("gridTemplate"),kY=new $APP.Jg(null,"gold","gold",833705111,null),wY=$APP.K("blue"),SX=$APP.K("div.cs2.ce3"),qY=$APP.K("div.grid.h-100vh.bg-cover.bg-no-repeat.bg-center"),jY=new $APP.Jg(null,"glory","glory",1732707291,null),XX=$APP.N("fgl.app.ui.connect-btn","text"),WY=$APP.N("toast","failure"),UX=$APP.K("main.grid-area-main.grid.justify-strech.mt-30"),MX=$APP.N("toast","data"),AX=$APP.K("css"),XY=$APP.K("turqoise"),xY=
$APP.K("green"),YY=$APP.K("sizes"),mY=new $APP.Jg(null,"ratio","ratio",713971483,null),bY=$APP.N("fgl.app.ui.header","data"),uY=$APP.K("red"),eY=new $APP.Jg(null,"logo","logo",-1416455506,null),ZY=$APP.K("brown"),$Y=$APP.K("black"),lY=$APP.K("div.flex.flex-row.justify-between.items-center.text-xl.fi"),CX=$APP.K("media"),aZ=$APP.K("img.mr-8"),VX=$APP.K("justifyContent"),IX=$APP.K("onOpenChange"),BX=$APP.K("div.w-full.h-full.grid.grid-rows-1"),bZ=$APP.K("success"),cZ=$APP.N("lambdaisland.glogi.print",
"comma"),dZ=$APP.K("gray1"),zY=$APP.K("gray3"),BY=$APP.K("gray2"),eZ=$APP.K("gray5"),AY=$APP.K("gray4"),fZ=$APP.K("gray6"),PY=$APP.K("callback"),$X=$APP.K("backgroundBlendMode"),gZ=$APP.K("re-pressed-example"),hZ=$APP.K("failure"),iZ=$APP.K("alt"),gY=$APP.K("ERC20"),OX=$APP.K("div.fixed.bottom-0.right-0.w-20.flex.flex-col.gap-10px.p-3.max-w-100vw.m-0.z-2147483647.list-none"),JX=$APP.N("toast","close"),fY=$APP.K("div.flex.flex-row.justify-between.items-center.text-xl.cursor-pointer"),jZ=$APP.K("srcSet"),
iY=$APP.K("decimals"),kZ=$APP.K("purple"),nY=new $APP.Jg(null,"connect-btn","connect-btn",-1765022208,null),yY=$APP.K("yellow"),yX=$APP.K("li\x3ebutton.relative.w-full.py-1_2rem"),lZ=$APP.K("ul.text-lg.text-center.fb.ml-2"),cY=$APP.K("header.w-100vw.grid-area-header.fixed.z-10"),mZ=$APP.N("fgl.app.subs","name"),xX=$APP.N("fgl.app.ui.panel-route","hover"),hY=$APP.K("options"),PX=new $APP.Jg(null,"toast","toast",1709129656,null),nZ=$APP.N("fgl.app.events","initialize-db"),KX=$APP.K("h1"),oY=new $APP.Jg(null,
"placeholder","placeholder",1535658444,null),vY=$APP.K("orange"),oZ=$APP.N("lambdaisland.glogi.print","space");$APP.cd("main");var pZ=new $APP.g(null,1,[$APP.qC,null],null);$APP.uL.j(nZ,function(){return pZ});$APP.Fr(mZ,$APP.y([function(a){return $APP.O.o(a)}]));$APP.Fr(VY,$APP.y([function(a){return gZ.o(a)}]));$APP.uL.j(xX,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return $APP.J.A(a,xX,b)});$APP.Fr(xX,$APP.y([function(a){return $APP.D.A(a,xX,null)}]));var DX=function DX(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.Mg(c.slice(0),0,null):null;return DX.B(c)};
DX.B=function(a){return new $APP.H(null,3,5,$APP.I,[$APP.fj,new $APP.H(null,3,5,$APP.I,[lZ,new $APP.g(null,1,[$APP.Q,new $APP.g(null,3,[$APP.Kr,"linear-gradient(to right, transparent, rgb(80, 146, 158, 0.231))",$APP.oD,"rgb(158, 169, 172)",$APP.vs,"1px 1px 1px rgba(0, 0, 0, 0.64)"],null)],null),new $APP.H(null,1,5,$APP.I,[wX],null)],null),$APP.vj.j(function(b){var c=$APP.A(b,0,null);b=$APP.A(b,1,null);return new $APP.H(null,3,5,$APP.I,[zX,c,b],null)},a)],null)};DX.I=0;DX.T=function(a){return this.B($APP.q(a))};var HX=$APP.pn(542,{});var qZ=$APP.oj(0);$APP.Fr(MX,$APP.y([function(a){return $APP.D.A(a,MX,$APP.G)}]));$APP.uL.j($APP.gH,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return $APP.Lp(a,new $APP.H(null,2,5,$APP.I,[MX,$APP.em.j(qZ,$APP.Xg)],null),$APP.J.A(b,$APP.T,bZ))});$APP.uL.j(WY,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return $APP.Lp(a,new $APP.H(null,2,5,$APP.I,[MX,$APP.em.j(qZ,$APP.Xg)],null),$APP.J.A(b,$APP.T,hZ))});
$APP.uL.j(JX,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return NW(a,new $APP.H(null,2,5,$APP.I,[MX,b],null))});var ZX=$APP.pn(544,{});aX($APP.Ui);
$APP.Fr(XX,$APP.y([$APP.wI,new $APP.H(null,1,5,$APP.I,[$APP.AB],null),$APP.wI,new $APP.H(null,1,5,$APP.I,[$APP.KF],null),$APP.wI,new $APP.H(null,1,5,$APP.I,[$APP.Xu],null),function(a){var b=$APP.A(a,0,null),c=$APP.A(a,1,null);a=$APP.A(a,2,null);return $APP.x.j(b,$APP.sH)?new $APP.H(null,4,5,$APP.I,["Wallet not detected","Wallet not detected",!1,function(){return open("https://metamask.io/")}],null):$APP.x.j(b,$APP.FH)?new $APP.H(null,4,5,$APP.I,["Connect Wallet","Connect Wallet",!1,$APP.ru],null):
$APP.h(c)?new $APP.H(null,4,5,$APP.I,["Wrong Network","Wrong Network",!1,function(){return $APP.P(new $APP.H(null,1,5,$APP.I,[$APP.nE],null))}],null):new $APP.H(null,4,5,$APP.I,[$APP.h(a)?$APP.Sr(a):"","Address",!1,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.iv,$APP.nF],null))}],null)}]));var dY=function dY(a){switch(arguments.length){case 0:return dY.D();case 1:return dY.o(arguments[0]);default:throw Error(["Invalid arity: ",$APP.n.o(arguments.length)].join(""));}};dY.D=function(){return dY.o($APP.Ui)};
dY.o=function(a){a=$APP.E(a);var b=$APP.D.j(a,$APP.Q);return new $APP.H(null,2,5,$APP.I,[aZ,$APP.Fo.B($APP.y([new $APP.g(null,3,[iZ,"link to home page",jZ,"/images/logo-128.png 128w,\n                /images/logo-256.png 256w,\n                /images/logo-512.png 512w,\n                /images/logo-1024.png 1024w,",YY,"(max-width: 1024px) 128px\n                (max-width: 2048px) 256px\n                (max-width: 2880px) 512px\n                (min-width: 2880px) 1024px"],null),a,new $APP.g(null,
1,[$APP.Q,$APP.Fo.B($APP.y([new $APP.g(null,3,[$APP.ns,"4.75rem",$APP.dH,"4.75rem",$APP.pK,"3.28375rem"],null),b]))],null)]))],null)};dY.I=1;$APP.Fr(bY,$APP.y([function(a){var b=$APP.E(a);b=$APP.D.j(b,$APP.Xu);b=$APP.D.j(a,b);a=$APP.D.A(a,$APP.MF,0).toString();var c=$APP.HC.o(b);b=$APP.bJ.o(b);return new $APP.H(null,3,5,$APP.I,[c,b,a],null)}]));var EY=$APP.jl([vY,dZ,GY,zY,AY,yY,xY,XY,BY,uY,wY,kZ,fZ,eZ,ZY,$Y],"#f5871f #e0e0e0 #ffffff #8e908c #969896 #eab700 #718c00 #3e999f #d6d6d6 #c82829 #4271ae #8959a8 #282a2e #4d4d4c #a3685a #1d1f21".split(" ")),rZ=function rZ(a,b){for(;;){if($APP.x.j(cZ,b))return FY(a,", ",BY);if($APP.x.j(oZ,b))return DY(a);if(b instanceof $APP.ri)return FY(a,b,wY);if(b instanceof $APP.Jg)return FY(a,b,xY);if("string"===typeof b)return FY(a,$APP.Zl($APP.y([b])),XY);if($APP.ck(b)){var d=DY(function(){var k=a,l=$APP.Cf(b);
return rZ.j?rZ.j(k,l):rZ.call(null,k,l)}()),e=$APP.Df(b);return rZ.j?rZ.j(d,e):rZ.call(null,d,e)}if(b instanceof $APP.g||b instanceof $APP.il)return d=a,d=FY(d,"{",kZ),d=$APP.cf.A(rZ,d,$APP.Bj(cZ,b)),FY(d,"}",kZ);if($APP.Dh(b))return d=a,d=FY(d,["#",$APP.n.o(function(){var k=$APP.Ze(b),l=k.name;return $APP.zh(l)?$APP.Zl($APP.y([k])):l}())," "].join(""),ZY),d=FY(d,"{",kZ),d=$APP.cf.A(rZ,d,$APP.Bj(cZ,b)),FY(d,"}",kZ);if($APP.Bh(b))return d=a,d=FY(d,"#{",kZ),d=$APP.cf.A(rZ,d,$APP.Bj(oZ,b)),FY(d,"}",
kZ);if($APP.Fh(b))return d=a,d=FY(d,"[",kZ),d=$APP.cf.A(rZ,d,$APP.Bj(oZ,b)),FY(d,"]",kZ);if(b instanceof $APP.tk)d=FY(a,"#queue ",ZY),e=$APP.fj.j($APP.G,b),a=d,b=e;else{if($APP.Ih(b))return d=a,d=FY(d,"(",ZY),d=$APP.cf.A(rZ,d,$APP.Bj(oZ,b)),FY(d,")",ZY);if(null!=b?b.P&16384||$APP.Eg===b.Fj||(b.P?0:$APP.Ye(IW,b)):$APP.Ye(IW,b))d=FY(a,"#atom ",ZY),e=$APP.p(b),a=d,b=e;else if(null!=b&&$APP.Eg===b.ci)d=FY(a,"#uuid ",ZY),e=$APP.n.o(b),a=d,b=e;else if(null!=b&&b.constructor===Object)d=FY(a,"#js ",ZY),e=
$APP.cf.A(function(k,l){return function(m,r){return $APP.J.A(m,$APP.Tl.o(r),$APP.Ha(l,r))}}(a,b),$APP.Ui,Object.keys(b)),a=d,b=e;else if($APP.Ve(b))d=FY(a,"#js ",ZY),e=$APP.fj.j($APP.G,b),a=d,b=e;else return FY(a,$APP.Zl($APP.y([b])),eZ)}}};var sZ=JY(function(a){a=$APP.E(a);$APP.D.j(a,$APP.jA);var b=$APP.D.j(a,$APP.fF),c=$APP.D.j(a,$APP.mC);$APP.D.j(a,$APP.Qq);return new $APP.H(null,2,5,$APP.I,[["[",$APP.n.o(b),"]"].join(""),c],null)}),tZ=JY(function(a){var b=$APP.E(a),c=$APP.D.j(b,$APP.jA);a=$APP.D.j(b,$APP.fF);var d=$APP.D.j(b,$APP.mC);$APP.D.j(b,$APP.Qq);b=CY(c);d=rZ(DY(HY(HY(HY(new $APP.H(null,2,5,$APP.I,["",$APP.G],null),"[",b),a,b),"]",b)),d);a=$APP.A(d,0,null);d=$APP.A(d,1,null);return $APP.pi(a,d)}),uZ=JY(function(a){a=$APP.E(a);
$APP.D.j(a,$APP.jA);var b=$APP.D.j(a,$APP.fF),c=$APP.D.j(a,$APP.mC);$APP.D.j(a,$APP.Qq);return new $APP.H(null,2,5,$APP.I,[["[",$APP.n.o(b),"]"].join(""),$APP.Zl($APP.y([c]))],null)});var KY=$APP.oj($APP.Ui);$APP.h(null)&&null.setCapturing(!1);var vZ,wZ="undefined"!==typeof devtools&&"undefined"!==typeof devtools.core&&"undefined"!==typeof devtools.core.installed_QMARK_;vZ=wZ?devtools.core.installed_QMARK_():wZ;
var xZ=$APP.h(vZ)?sZ:"undefined"===typeof window||"undefined"!==typeof window&&"undefined"!==typeof window&&"undefined"!==typeof window.navigator&&"undefined"!==typeof window&&"undefined"!==typeof window.navigator&&"undefined"!==typeof window.navigator.userAgent&&(-1<window.navigator.userAgent.indexOf("MSIE")||-1<window.navigator.userAgent.indexOf("Trident"))?uZ:tZ;UW?UW(xZ):VW.call(null,xZ);$APP.ln(new $APP.g(null,1,[$APP.Zm,$APP.h(!1)?$APP.eH:$APP.GH],null));$APP.Je();try{$APP.jn("fgl.app.home-core",new $APP.g(null,2,[$APP.BH,$APP.ZJ,$APP.oA,33],null)),WW(new $APP.H(null,1,5,$APP.I,[nZ],null)),QY()}catch(a){throw console.error("An error occurred when calling (fgl.app.home-core/init)"),a;};
}).call(this);