(function(){
'use strict';var GV,IV,NV,QV,EV,RV,FV,KV,SV,LV,JV,DV,CV,HV,MV,PV,OV;$APP.zL=function(){return new $APP.I(null,1,5,$APP.J,[new $APP.g(null,2,[$APP.zq,function(){$APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.MD,$APP.aM.address],null));$APP.Q(new $APP.I(null,1,5,$APP.J,[$APP.qE],null));$APP.Q(new $APP.I(null,1,5,$APP.J,[$APP.oz],null));return $APP.Q(new $APP.I(null,1,5,$APP.J,[$APP.Nz],null))},$APP.mv,$APP.Zh],null)],null)};
GV=function(){var a=$APP.p($APP.ns(new $APP.I(null,1,5,$APP.J,[CV],null)));a=$APP.F(a);a=$APP.E.j(a,DV);return new $APP.I(null,3,5,$APP.J,[$APP.xs,new $APP.I(null,2,5,$APP.J,[$APP.cB,"Exchange Rate:"],null),new $APP.I(null,2,5,$APP.J,[EV,new $APP.I(null,6,5,$APP.J,[FV,new $APP.I(null,2,5,$APP.J,[$APP.hK,"2rem"],null),new $APP.I(null,2,5,$APP.J,[$APP.$G,"1"],null),new $APP.I(null,3,5,$APP.J,[$APP.iG,new $APP.I(null,2,5,$APP.J,[$APP.zF,new $APP.g(null,1,[$APP.R,"/images/ratio.svg"],null)],null),new $APP.I(null,
2,5,$APP.J,[$APP.zF,new $APP.g(null,2,[$APP.Nn,new $APP.g(null,1,[$APP.Rn,"rotate(180deg)"],null),$APP.R,"/images/ratio.svg"],null)],null)],null),new $APP.I(null,2,5,$APP.J,[$APP.$G,a],null),new $APP.I(null,3,5,$APP.J,[$APP.oK,"2rem",new $APP.g(null,1,[$APP.Yn,"ml-2"],null)],null)],null)],null)],null)};
IV=function(){var a=$APP.p($APP.ns(new $APP.I(null,1,5,$APP.J,[CV],null)));a=$APP.F(a);a=$APP.E.j(a,$APP.fB);return new $APP.I(null,3,5,$APP.J,[$APP.xs,new $APP.I(null,2,5,$APP.J,[$APP.cB,"Amount of $GLORY to exchange:"],null),new $APP.I(null,2,5,$APP.J,[$APP.HB,new $APP.g(null,3,[$APP.az,function(b){return $APP.Q(new $APP.I(null,2,5,$APP.J,[HV,b.target.value],null))},$APP.sw,a,$APP.Nn,new $APP.g(null,1,[$APP.$n,"inset 1px 1px #111, 1px 1px rgba(116, 191, 206, 0.2)"],null)],null)],null)],null)};
NV=function(){var a=$APP.p($APP.ns(new $APP.I(null,1,5,$APP.J,[CV],null))),b=$APP.F(a);a=$APP.E.j(b,JV);b=$APP.E.j(b,KV);return new $APP.I(null,3,5,$APP.J,[LV,new $APP.I(null,3,5,$APP.J,[$APP.Lz,new $APP.I(null,2,5,$APP.J,[MV,"You will receive:"],null),new $APP.I(null,3,5,$APP.J,[$APP.WH,new $APP.I(null,2,5,$APP.J,[$APP.oK,"2.5rem"],null),new $APP.I(null,3,5,$APP.J,[$APP.oJ,a,new $APP.g(null,2,[$APP.GG,4,$APP.Nn,new $APP.g(null,1,[$APP.PG,"20rem"],null)],null)],null)],null)],null),new $APP.I(null,
3,5,$APP.J,[$APP.Lz,new $APP.I(null,2,5,$APP.J,[MV,"You $GOLD Balance will be:"],null),new $APP.I(null,3,5,$APP.J,[$APP.WH,new $APP.I(null,2,5,$APP.J,[$APP.oK,"2.5rem"],null),new $APP.I(null,3,5,$APP.J,[$APP.oJ,b,new $APP.g(null,2,[$APP.GG,4,$APP.Nn,new $APP.g(null,1,[$APP.PG,"20rem"],null)],null)],null)],null)],null)],null)};
QV=function(){var a=$APP.p($APP.ns(new $APP.I(null,1,5,$APP.J,[CV],null)));a=$APP.F(a);var b=$APP.E.j(a,$APP.uB),c=$APP.E.j(a,JV),d=$APP.E.j(a,$APP.rG),e=$APP.E.j(a,$APP.YC);return new $APP.I(null,2,5,$APP.J,[OV,new $APP.I(null,3,5,$APP.J,[$APP.co,new $APP.g(null,2,[$APP.rs,function(){return $APP.Q($APP.h(e)?new $APP.I(null,2,5,$APP.J,[$APP.JD,new $APP.g(null,3,[$APP.tu,PV,$APP.uu,new $APP.I(null,3,5,$APP.J,[b,d,c],null),$APP.wu,function(){$APP.Hs();$APP.Q(new $APP.I(null,1,5,$APP.J,[$APP.DH],null));
$APP.Q(new $APP.I(null,1,5,$APP.J,[$APP.OA],null));$APP.Q(new $APP.I(null,1,5,$APP.J,[$APP.UF],null));$APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.MD,$APP.aM.address],null));return $APP.Q(new $APP.I(null,2,5,$APP.J,[HV,""],null))}],null)],null):new $APP.I(null,2,5,$APP.J,[$APP.uD,new $APP.g(null,3,[$APP.tu,$APP.gC,$APP.uu,new $APP.I(null,2,5,$APP.J,[$APP.aM.address,"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],null),$APP.wu,function(){$APP.Q(new $APP.I(null,2,5,$APP.J,[$APP.MD,
$APP.aM.address],null));return $APP.Hs()}],null)],null))},$APP.Xn,$APP.uI],null),$APP.h(e)?"CONFIRM":"APPROVE"],null)],null)};$APP.yL=function(){return new $APP.I(null,6,5,$APP.J,[RV,new $APP.I(null,1,5,$APP.J,[GV],null),new $APP.I(null,1,5,$APP.J,[IV],null),new $APP.I(null,2,5,$APP.J,[$APP.iK,new $APP.g(null,1,[$APP.Yn,"mt-14 mb-4"],null)],null),new $APP.I(null,1,5,$APP.J,[NV],null),new $APP.I(null,1,5,$APP.J,[QV],null)],null)};EV=$APP.M("div.w-full.text-xl.py-3.bg-C81c6dd1a.px-40");RV=$APP.M("div.relative.px-10.fb");
FV=$APP.M("div.grid.grid-cols-5.items-center.m-auto.w-30%.justify-items-center");KV=$APP.M("balance-rst");SV=$APP.O("fgl.app.views.merchant-swap","input-str");LV=$APP.M("div.grid.grid-cols-2.gap-4");JV=$APP.M("amount-out");DV=$APP.M("ratio");CV=$APP.O("fgl.app.views.merchant-swap","data");HV=$APP.O("fgl.app.views.merchant-swap","input");MV=$APP.M("div.text-base.mt-4.mb-3.ffd.flexrs.text-C6bc9db");PV=$APP.M("swap");OV=$APP.M("div.w-full.flexr.mt-20");$APP.cd("merchant-swap");$APP.xL={};
$APP.GJ.j(HV,function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);var c=$APP.F(a);c=$APP.E.j(c,$APP.Ou);c=$APP.Mj(a,new $APP.I(null,2,5,$APP.J,[c,$APP.YG],null));b=b.replace(/\.+/,".").replace(/-/,"");try{var d=module$node_modules$ethers$lib$index.utils.parseUnits(b)}catch(k){if(k instanceof Error)d=$APP.tC;else throw k;}if($APP.z.j(b,""))a=$APP.K.B(a,HV,module$node_modules$ethers$lib$index.BigNumber.from("0"),$APP.B([SV,""]));else if(!$APP.z.j(d,$APP.tC)||!$APP.La(b,".")||$APP.z.j($APP.Zm(b,"."),$APP.an(b)))if($APP.z.j(d,
$APP.tC)&&$APP.La(b,"."))a=$APP.K.A(a,SV,b);else if(!$APP.z.j(d,$APP.tC)){var e=d.gte(0);c=$APP.h(e)?d.lte(c):e;a=$APP.h(c)?$APP.K.B(a,HV,d,$APP.B([SV,b])):a}return a});
$APP.ls(CV,$APP.B([function(a){var b=$APP.F(a),c=$APP.E.j(b,HV),d=$APP.E.j(b,SV),e=$APP.E.j(b,$APP.Ou),k=$APP.E.j(b,$APP.fE),l=$APP.E.j(b,$APP.jE);b=$APP.E.j(b,$APP.gG);var m=$APP.E.j(a,e);m=$APP.F(m);m=$APP.E.j(m,$APP.lB);m=$APP.h(m)?m:module$node_modules$ethers$lib$index.BigNumber.from("0");k=$APP.h(k)?k:module$node_modules$ethers$lib$index.BigNumber.from("1");c=$APP.h(c)?c:module$node_modules$ethers$lib$index.BigNumber.from("0");l=c.mul(l).div(c.add(b)).mul(9).div(10);a=$APP.Nj(a,new $APP.I(null,
3,5,$APP.J,[e,$APP.MD,$APP.aM.address],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));return new $APP.g(null,7,[$APP.uB,e,JV,l,$APP.rG,c,$APP.YC,c.lte(a),DV,1/k,$APP.fB,d,KV,m.add(l)],null)}]));$APP.Je();
}).call(this);