(function(){
'use strict';var SW,UW,ZW,bX,QW,cX,RW,WW,dX,XW,VW,PW,OW,TW,YW,aX,$W;$APP.HL=function(){return new $APP.J(null,1,5,$APP.K,[new $APP.g(null,2,[$APP.Aq,function(){$APP.R(new $APP.J(null,2,5,$APP.K,[$APP.PD,$APP.iM.address],null));$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.uE],null));$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.pz],null));return $APP.R(new $APP.J(null,1,5,$APP.K,[$APP.Pz],null))},$APP.nv,$APP.$h],null)],null)};
SW=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[OW],null)));a=$APP.H(a);a=$APP.E.j(a,PW);return new $APP.J(null,3,5,$APP.K,[$APP.ys,new $APP.J(null,2,5,$APP.K,[$APP.dB,"Exchange Rate:"],null),new $APP.J(null,2,5,$APP.K,[QW,new $APP.J(null,6,5,$APP.K,[RW,new $APP.J(null,2,5,$APP.K,[$APP.oK,"2rem"],null),new $APP.J(null,2,5,$APP.K,[$APP.fH,"1"],null),new $APP.J(null,3,5,$APP.K,[$APP.oG,new $APP.J(null,2,5,$APP.K,[$APP.FF,new $APP.g(null,1,[$APP.T,"/images/ratio.svg"],null)],null),new $APP.J(null,
2,5,$APP.K,[$APP.FF,new $APP.g(null,2,[$APP.On,new $APP.g(null,1,[$APP.Sn,"rotate(180deg)"],null),$APP.T,"/images/ratio.svg"],null)],null)],null),new $APP.J(null,2,5,$APP.K,[$APP.fH,a],null),new $APP.J(null,3,5,$APP.K,[$APP.vK,"2rem",new $APP.g(null,1,[$APP.Zn,"ml-2"],null)],null)],null)],null)],null)};
UW=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[OW],null)));a=$APP.H(a);a=$APP.E.j(a,$APP.gB);return new $APP.J(null,3,5,$APP.K,[$APP.ys,new $APP.J(null,2,5,$APP.K,[$APP.dB,"Amount of $GLORY to exchange:"],null),new $APP.J(null,2,5,$APP.K,[$APP.IB,new $APP.g(null,3,[$APP.bz,function(b){return $APP.R(new $APP.J(null,2,5,$APP.K,[TW,b.target.value],null))},$APP.tw,a,$APP.On,new $APP.g(null,1,[$APP.ao,"inset 1px 1px #111, 1px 1px rgba(116, 191, 206, 0.2)"],null)],null)],null)],null)};
ZW=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[OW],null))),b=$APP.H(a);a=$APP.E.j(b,VW);b=$APP.E.j(b,WW);return new $APP.J(null,3,5,$APP.K,[XW,new $APP.J(null,3,5,$APP.K,[$APP.Nz,new $APP.J(null,2,5,$APP.K,[YW,"You will receive:"],null),new $APP.J(null,3,5,$APP.K,[$APP.cI,new $APP.J(null,2,5,$APP.K,[$APP.vK,"2.5rem"],null),new $APP.J(null,3,5,$APP.K,[$APP.vJ,a,new $APP.g(null,2,[$APP.MG,4,$APP.On,new $APP.g(null,1,[$APP.VG,"20rem"],null)],null)],null)],null)],null),new $APP.J(null,
3,5,$APP.K,[$APP.Nz,new $APP.J(null,2,5,$APP.K,[YW,"You $GOLD Balance will be:"],null),new $APP.J(null,3,5,$APP.K,[$APP.cI,new $APP.J(null,2,5,$APP.K,[$APP.vK,"2.5rem"],null),new $APP.J(null,3,5,$APP.K,[$APP.vJ,b,new $APP.g(null,2,[$APP.MG,4,$APP.On,new $APP.g(null,1,[$APP.VG,"20rem"],null)],null)],null)],null)],null)],null)};
bX=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[OW],null)));a=$APP.H(a);var b=$APP.E.j(a,$APP.vB),c=$APP.E.j(a,VW),d=$APP.E.j(a,$APP.xG),e=$APP.E.j(a,$APP.ZC);return new $APP.J(null,2,5,$APP.K,[$W,new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,2,[$APP.ss,function(){return $APP.R($APP.h(e)?new $APP.J(null,2,5,$APP.K,[$APP.MD,new $APP.g(null,3,[$APP.uu,aX,$APP.vu,new $APP.J(null,3,5,$APP.K,[b,d,c],null),$APP.xu,function(){$APP.Is();$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.KH],null));
$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.QA],null));$APP.R(new $APP.J(null,1,5,$APP.K,[$APP.$F],null));$APP.R(new $APP.J(null,2,5,$APP.K,[$APP.PD,$APP.iM.address],null));return $APP.R(new $APP.J(null,2,5,$APP.K,[TW,""],null))}],null)],null):new $APP.J(null,2,5,$APP.K,[$APP.wD,new $APP.g(null,3,[$APP.uu,$APP.gC,$APP.vu,new $APP.J(null,2,5,$APP.K,[$APP.iM.address,"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],null),$APP.xu,function(){$APP.R(new $APP.J(null,2,5,$APP.K,[$APP.PD,
$APP.iM.address],null));return $APP.Is()}],null)],null))},$APP.Yn,$APP.BI],null),$APP.h(e)?"CONFIRM":"APPROVE"],null)],null)};$APP.GL=function(){return new $APP.J(null,6,5,$APP.K,[cX,new $APP.J(null,1,5,$APP.K,[SW],null),new $APP.J(null,1,5,$APP.K,[UW],null),new $APP.J(null,2,5,$APP.K,[$APP.pK,new $APP.g(null,1,[$APP.Zn,"mt-14 mb-4"],null)],null),new $APP.J(null,1,5,$APP.K,[ZW],null),new $APP.J(null,1,5,$APP.K,[bX],null)],null)};QW=$APP.N("div.w-full.text-xl.py-3.bg-C81c6dd1a.px-40");cX=$APP.N("div.relative.px-10.fb");
RW=$APP.N("div.grid.grid-cols-5.items-center.m-auto.w-30%.justify-items-center");WW=$APP.N("balance-rst");dX=$APP.P("fgl.app.views.merchant-swap","input-str");XW=$APP.N("div.grid.grid-cols-2.gap-4");VW=$APP.N("amount-out");PW=$APP.N("ratio");OW=$APP.P("fgl.app.views.merchant-swap","data");TW=$APP.P("fgl.app.views.merchant-swap","input");YW=$APP.N("div.text-base.mt-4.mb-3.ffd.flexrs.text-C6bc9db");aX=$APP.N("swap");$W=$APP.N("div.w-full.flexr.mt-20");$APP.dd("merchant-swap");$APP.FL={};
$APP.NJ.j(TW,function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);var c=$APP.H(a);c=$APP.E.j(c,$APP.Ou);c=$APP.Mj(a,new $APP.J(null,2,5,$APP.K,[c,$APP.dH],null));b=b.replace(/\.+/,".").replace(/-/,"");try{var d=module$node_modules$ethers$lib$index.utils.parseUnits(b)}catch(k){if(k instanceof Error)d=$APP.uC;else throw k;}if($APP.z.j(b,""))a=$APP.M.B(a,TW,module$node_modules$ethers$lib$index.BigNumber.from("0"),$APP.B([dX,""]));else if(!$APP.z.j(d,$APP.uC)||!$APP.Ma(b,".")||$APP.z.j($APP.Zm(b,"."),$APP.an(b)))if($APP.z.j(d,
$APP.uC)&&$APP.Ma(b,"."))a=$APP.M.A(a,dX,b);else if(!$APP.z.j(d,$APP.uC)){var e=d.gte(0);c=$APP.h(e)?d.lte(c):e;a=$APP.h(c)?$APP.M.B(a,TW,d,$APP.B([dX,b])):a}return a});
$APP.ms(OW,$APP.B([function(a){var b=$APP.H(a),c=$APP.E.j(b,TW),d=$APP.E.j(b,dX),e=$APP.E.j(b,$APP.Ou),k=$APP.E.j(b,$APP.iE),l=$APP.E.j(b,$APP.mE);b=$APP.E.j(b,$APP.mG);var m=$APP.E.j(a,e);m=$APP.H(m);m=$APP.E.j(m,$APP.mB);m=$APP.h(m)?m:module$node_modules$ethers$lib$index.BigNumber.from("0");k=$APP.h(k)?k:module$node_modules$ethers$lib$index.BigNumber.from("1");c=$APP.h(c)?c:module$node_modules$ethers$lib$index.BigNumber.from("0");l=c.mul(l).div(c.add(b)).mul(9).div(10);a=$APP.Nj(a,new $APP.J(null,
3,5,$APP.K,[e,$APP.PD,$APP.iM.address],null),module$node_modules$ethers$lib$index.BigNumber.from("0"));return new $APP.g(null,7,[$APP.vB,e,VW,l,$APP.xG,c,$APP.ZC,c.lte(a),PW,1/k,$APP.gB,d,WW,m.add(l)],null)}]));$APP.Ke();
}).call(this);