(function(){
'use strict';var p2,u2,x2,D2,E2,z2,v2,G2,t2,H2,q2,I2,F2,C2,y2,A2,B2,w2,s2,r2;$APP.u0=function(){return new $APP.P(null,1,5,$APP.R,[new $APP.k(null,2,[$APP.kt,function(){return $APP.gu(new $APP.P(null,1,5,$APP.R,[$APP.pR],null))},$APP.MA,$APP.Zi],null)],null)};
p2=function(){return new $APP.P(null,2,5,$APP.R,[$APP.Jw,'\n      .guild-burn-land-deeds button\x3efigure {\n        transition: all 0.2s ease;\n      }\n\n      .guild-burn-land-deeds button:nth-child(n + 2) {\n        margin-left: 0.8rem;\n      }\n\n      .guild-burn-land-deeds button\x3efigure:hover {\n        transform: scale(1.05);\n      }\n\n      .guild-burn-land-deeds button\x3efigure .selected {\n        position: absolute;\n        top: 0;\n        left: 0;\n        width: 100%;\n        height: 100%;\n        border: 0.25rem solid #fff;\n        border-radius: 4px;\n      }\n      .guild-burn-land-deeds button\x3efigure .selected::after {\n        content: "";\n        position: absolute;\n        width: 0;\n        height: 0;\n        border: 1rem solid transparent;\n        border-right: 1rem solid #fff;\n        transform: translate(calc(-50% - 1px), calc(-50% - 1px)) rotate(45deg);\n      }\n\n      .guild-burn-land-deeds figcaption {\n        text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.4);\n      }'],null)};
u2=function(a){var b=$APP.r($APP.cv(new $APP.P(null,1,5,$APP.R,[q2],null)));b=$APP.N(b);var c=$APP.K.j(b,r2);return $APP.gi(new $APP.P(null,3,5,$APP.R,[$APP.zS,new $APP.k(null,1,[$APP.bx,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[s2,a],null))}],null),new $APP.P(null,3,5,$APP.R,[t2,new $APP.P(null,2,5,$APP.R,[$APP.yL,new $APP.k(null,1,[$APP.zL,"/images/mega.png"],null)],null),function(){var d=$APP.D.j(a,c);return d?new $APP.P(null,1,5,$APP.R,[$APP.mX],null):d}()],null)],null),new $APP.k(null,
1,[$APP.Kq,a],null))};x2=function(){var a=$APP.r($APP.cv(new $APP.P(null,1,5,$APP.R,[q2],null)));a=$APP.N(a);a=$APP.K.j(a,v2);return new $APP.P(null,3,5,$APP.R,[$APP.hx,new $APP.P(null,2,5,$APP.R,[$APP.ZV,"My Land Deeds"],null),$APP.qk.j(new $APP.P(null,1,5,$APP.R,[w2],null),$APP.Hk.j(function(b){return new $APP.P(null,2,5,$APP.R,[u2,b],null)},a))],null)};
D2=function(){var a=$APP.r($APP.cv(new $APP.P(null,1,5,$APP.R,[q2],null)));a=$APP.N(a);var b=$APP.K.j(a,y2);$APP.K.j(a,r2);$APP.K.j(a,v2);return new $APP.P(null,3,5,$APP.R,[$APP.hx,new $APP.P(null,2,5,$APP.R,[$APP.iT,"Your returned token will be"],null),new $APP.P(null,3,5,$APP.R,[z2,new $APP.P(null,3,5,$APP.R,[A2,new $APP.k(null,2,[$APP.xs,$APP.D.j(b,B2)?"bg-C71edf599":"",$APP.bx,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[C2,B2],null))}],null),new $APP.P(null,3,5,$APP.R,[$APP.wT,new $APP.P(null,
2,5,$APP.R,[$APP.T0,"2rem"],null),new $APP.P(null,2,5,$APP.R,[$APP.ix,"18"],null)],null)],null),new $APP.P(null,3,5,$APP.R,[A2,new $APP.k(null,2,[$APP.xs,$APP.D.j(b,$APP.aN)?"bg-C71edf599":"",$APP.bx,function(){return $APP.gu(new $APP.P(null,2,5,$APP.R,[C2,$APP.aN],null))}],null),new $APP.P(null,3,5,$APP.R,[$APP.wT,new $APP.P(null,2,5,$APP.R,[$APP.d_,"2rem"],null),new $APP.P(null,2,5,$APP.R,[$APP.ix,"2.33"],null)],null)],null)],null)],null)};
E2=function(){var a=$APP.r($APP.cv(new $APP.P(null,1,5,$APP.R,[q2],null)));a=$APP.N(a);$APP.K.j(a,r2);$APP.K.j(a,v2);return new $APP.P(null,2,5,$APP.R,[$APP.iQ,new $APP.P(null,3,5,$APP.R,[$APP.Yw,new $APP.k(null,1,[$APP.Tw,$APP.aY],null),"BURN"],null)],null)};
$APP.t0=function(){return new $APP.P(null,3,5,$APP.R,[$APP.hx,new $APP.P(null,1,5,$APP.R,[p2],null),new $APP.P(null,5,5,$APP.R,[F2,new $APP.P(null,1,5,$APP.R,[x2],null),new $APP.P(null,1,5,$APP.R,[D2],null),new $APP.P(null,2,5,$APP.R,[$APP.RZ,new $APP.k(null,1,[$APP.xs,"mt-24 mb-8"],null)],null),new $APP.P(null,1,5,$APP.R,[E2],null)],null)],null)};z2=$APP.S("div.grid.grid-cols-2.gap-x-6.text-3xl");v2=$APP.S("token-ids");G2=$APP.S("goldp");t2=$APP.S("figure.relative.w-11_2rem");H2=$APP.S("ethp");
q2=$APP.T("fgl.app.views.merchant-burn","data");I2=$APP.T("fgl.app.views.merchant-burn","type");F2=$APP.S("div.guild-burn-land-deeds.relative.px-10.py-4");C2=$APP.T("fgl.app.views.merchant-burn","payment");y2=$APP.S("payment");A2=$APP.S("button.bg-C81c6dd1a.leading-3rem.rounded-sm");B2=$APP.S("eth");w2=$APP.S("div.flex.bg-C81c6dd1a.py-3.pl-2.pr-6.rounded-sm.relative");s2=$APP.T("fgl.app.views.merchant-burn","token-id");r2=$APP.S("token-id");$APP.kd("merchant-burn");$APP.s0={};$APP.gZ.j(C2,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);return $APP.Bm.A(a,C2,b)});$APP.gZ.j(s2,function(a,b){$APP.H(b,0,null);b=$APP.H(b,1,null);return $APP.Bm.A(a,s2,b)});
$APP.av(q2,$APP.G([function(a){var b=$APP.N(a),c=$APP.K.j(b,$APP.kS),d=$APP.K.j(b,I2),e=$APP.K.j(b,s2),f=$APP.K.j(b,$APP.AS);b=$APP.K.j(b,$APP.sW);var h=$APP.$k(a,new $APP.P(null,2,5,$APP.R,[c,$APP.AO],null)),m=$APP.l(d)?d:3;a=function(){var n=$APP.BR.o($APP.K.j(f,m));return $APP.l(n)?n:module$node_modules$ethers$lib$index.BigNumber.from(0)}();c=($APP.l(b)?b:module$node_modules$ethers$lib$index.BigNumber.from(0)).mul(a);return new $APP.k(null,5,[$APP.U,m,v2,function(){var n=$APP.y(h);return n?n:$APP.Kp(1,
2,3,4,5)}(),H2,a,G2,c,r2,$APP.l(e)?e:s2],null)}]));$APP.lf();
}).call(this);