(function(){
'use strict';var WK,bL,eL,jL,lL,nL,cL,mL,aL,XK,oL,hL,iL,YK,fL,gL,dL,kL,$K,ZK;$APP.VK=function(){return new $APP.H(null,1,5,$APP.I,[new $APP.g(null,2,[$APP.Cp,function(){return $APP.P(new $APP.H(null,1,5,$APP.I,[$APP.Qz],null))},$APP.aB,$APP.Zh],null)],null)};
WK=function(){return new $APP.H(null,2,5,$APP.I,[$APP.Q,'\n      .guild-burn-land-deeds button\x3efigure {\n        transition: all 0.2s ease;\n      }\n\n      .guild-burn-land-deeds button:nth-child(n + 2) {\n        margin-left: 0.8rem;\n      }\n\n      .guild-burn-land-deeds button\x3efigure:hover {\n        transform: scale(1.05);\n      }\n\n      .guild-burn-land-deeds button\x3efigure .selected {\n        position: absolute;\n        top: 0;\n        left: 0;\n        width: 100%;\n        height: 100%;\n        border: 0.25rem solid #fff;\n        border-radius: 4px;\n      }\n      .guild-burn-land-deeds button\x3efigure .selected::after {\n        content: "";\n        position: absolute;\n        width: 0;\n        height: 0;\n        border: 1rem solid transparent;\n        border-right: 1rem solid #fff;\n        transform: translate(calc(-50% - 1px), calc(-50% - 1px)) rotate(45deg);\n      }\n\n      .guild-burn-land-deeds figcaption {\n        text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.4);\n      }\n      figure.dt2\x3eimg {\n        filter: hue-rotate(230deg) saturate(.6);\n      }\n      figure.dt1\x3eimg {\n        filter: hue-rotate(171deg) saturate(.6);\n      }\n      figure.dt0\x3eimg {\n        filter: hue-rotate(57deg) saturate(.6);\n      }'],null)};
bL=function(a){return $APP.hp(new $APP.g(null,2,[$APP.vA,function(){$APP.P(new $APP.H(null,2,5,$APP.I,[$APP.WC,a],null));return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.qD,a],null))},$APP.So,function(){var b=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[XK],null)));b=$APP.E(b);var c=$APP.D.j(b,YK),d=$APP.D.j(b,ZK);b=["dt",$APP.m.o($APP.h(c)?c:0)].join("");return $APP.uh(new $APP.H(null,3,5,$APP.I,[$APP.LA,new $APP.g(null,1,[$APP.ks,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$K,a],null))}],null),
new $APP.H(null,4,5,$APP.I,[aL,new $APP.g(null,1,[$APP.bp,b],null),new $APP.H(null,2,5,$APP.I,[$APP.ur,new $APP.g(null,1,[$APP.R,"/images/mega.png"],null)],null),function(){var e=$APP.x.j(a,d);return e?new $APP.H(null,1,5,$APP.I,[$APP.qE],null):e}()],null)],null),new $APP.g(null,1,[$APP.hn,a],null))}],null))};
eL=function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[XK],null)));a=$APP.E(a);a=$APP.D.j(a,cL);return new $APP.H(null,3,5,$APP.I,[$APP.tB,new $APP.H(null,2,5,$APP.I,[$APP.wD,"My Land Deeds"],null),$APP.cj.j(new $APP.H(null,1,5,$APP.I,[dL],null),$APP.nj.j(function(b){return new $APP.H(null,2,5,$APP.I,[bL,b],null)},a))],null)};
jL=function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[XK],null))),b=$APP.E(a);a=$APP.D.j(b,fL);b=$APP.D.j(b,$APP.Bw);return new $APP.H(null,3,5,$APP.I,[$APP.tB,new $APP.H(null,2,5,$APP.I,[$APP.pB,"Your returned token will be"],null),new $APP.H(null,3,5,$APP.I,[gL,new $APP.H(null,3,5,$APP.I,[hL,new $APP.g(null,1,[$APP.ks,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[iL,fL],null))}],null),new $APP.H(null,3,5,$APP.I,[$APP.BB,new $APP.H(null,2,5,$APP.I,[$APP.gH,"2rem"],null),new $APP.H(null,
3,5,$APP.I,[$APP.dG,a,new $APP.g(null,1,[$APP.uD,4],null)],null)],null)],null),new $APP.H(null,3,5,$APP.I,[hL,new $APP.g(null,1,[$APP.ks,function(){return $APP.P(new $APP.H(null,2,5,$APP.I,[iL,$APP.Bw],null))}],null),new $APP.H(null,3,5,$APP.I,[$APP.BB,new $APP.H(null,2,5,$APP.I,[$APP.PG,"2rem"],null),new $APP.H(null,3,5,$APP.I,[$APP.dG,b,new $APP.g(null,1,[$APP.uD,4],null)],null)],null)],null)],null)],null)};
lL=function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[kL],null)));return new $APP.H(null,3,5,$APP.I,[$APP.NG,new $APP.g(null,2,[$APP.Xr,"1.5rem",$APP.KC,new $APP.H(null,2,5,$APP.I,[$APP.iy,"Do not remind me next time"],null)],null),new $APP.g(null,3,[$APP.bp,"flex flex-row cs1 ce2 rs1 re2 justify-self-start items-center",$APP.mD,function(b){return $APP.P(new $APP.H(null,2,5,$APP.I,[kL,b],null))},$APP.lD,a],null)],null)};
nL=function(){function a(){return $APP.P(new $APP.H(null,2,5,$APP.I,[$APP.tD,new $APP.g(null,3,[$APP.mu,mL,$APP.nu,new $APP.H(null,3,5,$APP.I,[[d],e,k],null),$APP.pu,function(){$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.NC],null));$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.cE],null));return $APP.As()}],null)],null))}function b(){return $APP.h(l)?localStorage.setItem("burn-checked",1):localStorage.removeItem("burn-checked")}var c=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[XK],null)));c=$APP.E(c);var d=$APP.D.j(c,
ZK),e=$APP.D.j(c,fL),k=$APP.D.j(c,$APP.Bw),l=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[kL],null)));return new $APP.H(null,2,5,$APP.I,[$APP.Zy,new $APP.H(null,3,5,$APP.I,[$APP.gs,new $APP.g(null,2,[$APP.bs,$APP.XE,$APP.ks,function(){return $APP.h(localStorage.getItem("burn-checked"))?a():$APP.P(new $APP.H(null,9,5,$APP.I,[$APP.ls,$APP.vs,!0,$APP.Ds,"",$APP.xs,new $APP.H(null,4,5,$APP.I,[$APP.tB,new $APP.H(null,2,5,$APP.I,[$APP.UB,"Notice: If you choose to Burn your Land Deed, you will receive 95% of the\ntoken you used to mint the Land Deed. The rest 5% are being charged as\nhandling fee. Afterwards, you will lose corresponding utilities of this Land\nDeed."],
null),new $APP.H(null,1,5,$APP.I,[$APP.ss],null),new $APP.H(null,1,5,$APP.I,[lL],null)],null),$APP.ys,new $APP.H(null,3,5,$APP.I,[$APP.tB,new $APP.H(null,3,5,$APP.I,[$APP.gs,new $APP.g(null,3,[$APP.bs,$APP.XE,$APP.ks,$APP.uu.j(a,b),$APP.bp,"mr-8"],null),"Confirm"],null),new $APP.H(null,3,5,$APP.I,[$APP.gs,new $APP.g(null,2,[$APP.bs,$APP.zs,$APP.ks,function(){return $APP.P(new $APP.H(null,3,5,$APP.I,[$APP.ls,$APP.ms,!0],null))}],null),"Cancel"],null)],null)],null))}],null),"BURN"],null)],null)};
$APP.pL=function(){return new $APP.H(null,3,5,$APP.I,[$APP.tB,new $APP.H(null,1,5,$APP.I,[WK],null),new $APP.H(null,5,5,$APP.I,[oL,new $APP.H(null,1,5,$APP.I,[eL],null),new $APP.H(null,1,5,$APP.I,[jL],null),new $APP.H(null,2,5,$APP.I,[$APP.hH,new $APP.g(null,1,[$APP.bp,"mt-24 mb-8"],null)],null),new $APP.H(null,1,5,$APP.I,[nL],null)],null)],null)};cL=$APP.K("token-ids");mL=$APP.K("redeem");aL=$APP.K("figure.relative.w-11_2rem");XK=$APP.M("fgl.app.views.merchant-burn","data");oL=$APP.K("div.guild-burn-land-deeds.relative.px-10.py-4");
hL=$APP.K("li.bg-C81c6dd1a.leading-3rem.rounded-sm");iL=$APP.M("fgl.app.views.merchant-burn","payment");YK=$APP.K("ttype");fL=$APP.K("eth");gL=$APP.K("ul.grid.grid-cols-2.gap-x-6.text-3xl");dL=$APP.K("div.flex.bg-C81c6dd1a.py-3.pl-2.pr-6.rounded-sm.relative");kL=$APP.M("fgl.app.views.merchant-burn","burn-checked");$K=$APP.M("fgl.app.views.merchant-burn","token-id");ZK=$APP.K("token-id");$APP.cd("merchant-burn");$APP.qL={};$APP.PF.j(iL,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return $APP.J.A(a,iL,b)});$APP.PF.j($K,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return $APP.J.A(a,$K,b)});
$APP.or(XK,$APP.y([function(a){var b=$APP.E(a),c=$APP.D.j(b,$APP.Gu),d=$APP.D.j(b,$K),e=$APP.D.j(b,$APP.gx),k=$APP.D.j(b,$APP.kB);b=$APP.D.j(b,$APP.Uw);c=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[c,$APP.Ax],null));var l=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[$APP.WC,d],null));a=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[$APP.qD,d],null));k=$APP.Dr(a,0).mul($APP.Dr(k,0)).mul(9).div(10).div($APP.Dr(b,1));e=$APP.Dr(a,0).mul($APP.Dr(e,0)).mul(9).div(10).div($APP.Dr(b,1));return new $APP.g(null,5,[cL,c,ZK,$APP.h(d)?
d:$K,YK,l,fL,k,$APP.Bw,e],null)}]));$APP.PF.j(kL,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);return $APP.J.A(a,kL,b)});$APP.or(kL,$APP.y([function(a){return $APP.D.A(a,kL,!1)}]));$APP.Je();
}).call(this);