(function(){
'use strict';var P_,R_,W_,Z_,N_,$_,O_,T_,a0,U_,S_,M_,L_,Q_,V_,Y_,X_;$APP.UZ=function(){return new $APP.H(null,1,5,$APP.I,[new $APP.g(null,2,[$APP.Cp,function(){$APP.P(new $APP.H(null,2,5,$APP.I,[$APP.DA,$APP.nH.address],null));$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.jB],null));$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.xw],null));return $APP.P(new $APP.H(null,1,5,$APP.I,[$APP.Uw],null))},$APP.bB,$APP.Zh],null)],null)};
P_=function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[L_],null)));a=$APP.E(a);a=$APP.C.j(a,M_);return new $APP.H(null,3,5,$APP.I,[$APP.vB,new $APP.H(null,2,5,$APP.I,[$APP.dy,"Exchange Rate:"],null),new $APP.H(null,2,5,$APP.I,[N_,new $APP.H(null,6,5,$APP.I,[O_,new $APP.H(null,2,5,$APP.I,[$APP.SG,"2rem"],null),new $APP.H(null,2,5,$APP.I,[$APP.QD,"1"],null),new $APP.H(null,3,5,$APP.I,[$APP.WC,new $APP.H(null,2,5,$APP.I,[$APP.jC,new $APP.g(null,1,[$APP.R,"/images/ratio.svg"],null)],null),new $APP.H(null,
2,5,$APP.I,[$APP.jC,new $APP.g(null,2,[$APP.Q,new $APP.g(null,1,[$APP.vr,"rotate(180deg)"],null),$APP.R,"/images/ratio.svg"],null)],null)],null),new $APP.H(null,2,5,$APP.I,[$APP.QD,a],null),new $APP.H(null,3,5,$APP.I,[$APP.TG,"2rem",new $APP.g(null,1,[$APP.bp,"ml-2"],null)],null)],null)],null)],null)};
R_=function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[L_],null)));a=$APP.E(a);a=$APP.C.j(a,$APP.gy);return new $APP.H(null,3,5,$APP.I,[$APP.vB,new $APP.H(null,2,5,$APP.I,[$APP.dy,"Amount of $Virtue to exchange:"],null),new $APP.H(null,2,5,$APP.I,[$APP.Ky,new $APP.g(null,3,[$APP.kw,function(b){return $APP.P(new $APP.H(null,2,5,$APP.I,[Q_,b.target.value],null))},$APP.wz,a,$APP.Q,new $APP.g(null,1,[$APP.ds,"inset 1px 1px #111, 1px 1px rgba(116, 191, 206, 0.2)"],null)],null)],null)],null)};
W_=function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[L_],null))),b=$APP.E(a);a=$APP.C.j(b,S_);b=$APP.C.j(b,T_);return new $APP.H(null,3,5,$APP.I,[U_,new $APP.H(null,3,5,$APP.I,[$APP.Sw,new $APP.H(null,2,5,$APP.I,[V_,"You will receive:"],null),new $APP.H(null,3,5,$APP.I,[$APP.EE,new $APP.H(null,2,5,$APP.I,[$APP.TG,"2.5rem"],null),new $APP.H(null,3,5,$APP.I,[$APP.hG,a,new $APP.g(null,2,[$APP.xD,4,$APP.Q,new $APP.g(null,1,[$APP.FD,"20rem"],null)],null)],null)],null)],null),new $APP.H(null,
3,5,$APP.I,[$APP.Sw,new $APP.H(null,2,5,$APP.I,[V_,"You $Glory Balance will be:"],null),new $APP.H(null,3,5,$APP.I,[$APP.EE,new $APP.H(null,2,5,$APP.I,[$APP.TG,"2.5rem"],null),new $APP.H(null,3,5,$APP.I,[$APP.hG,b,new $APP.g(null,2,[$APP.xD,4,$APP.Q,new $APP.g(null,1,[$APP.FD,"20rem"],null)],null)],null)],null)],null)],null)};
Z_=function(){var a=$APP.p($APP.qr(new $APP.H(null,1,5,$APP.I,[L_],null)));a=$APP.E(a);var b=$APP.C.j(a,$APP.xy),c=$APP.C.j(a,S_),d=$APP.C.j(a,$APP.fD),e=$APP.C.j(a,$APP.Rz);return new $APP.H(null,2,5,$APP.I,[X_,new $APP.H(null,3,5,$APP.I,[$APP.gs,new $APP.g(null,2,[$APP.ks,function(){return $APP.P($APP.h(e)?new $APP.H(null,2,5,$APP.I,[$APP.BA,new $APP.g(null,3,[$APP.mu,Y_,$APP.nu,new $APP.H(null,3,5,$APP.I,[b,d,c],null),$APP.pu,function(){$APP.As();$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.nE],null));
$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.Qx],null));$APP.P(new $APP.H(null,1,5,$APP.I,[$APP.DC],null));$APP.P(new $APP.H(null,2,5,$APP.I,[$APP.DA,$APP.nH.address],null));return $APP.P(new $APP.H(null,2,5,$APP.I,[Q_,""],null))}],null)],null):new $APP.H(null,2,5,$APP.I,[$APP.mA,new $APP.g(null,3,[$APP.mu,$APP.fz,$APP.nu,new $APP.H(null,2,5,$APP.I,[$APP.nH.address,"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],null),$APP.pu,function(){$APP.P(new $APP.H(null,2,5,$APP.I,[$APP.DA,
$APP.nH.address],null));return $APP.As()}],null)],null))},$APP.bs,$APP.aF],null),$APP.h(e)?"CONFIRM":"APPROVE"],null)],null)};$APP.TZ=function(){return new $APP.H(null,6,5,$APP.I,[$_,new $APP.H(null,1,5,$APP.I,[P_],null),new $APP.H(null,1,5,$APP.I,[R_],null),new $APP.H(null,2,5,$APP.I,[$APP.lH,new $APP.g(null,1,[$APP.bp,"mt-14 mb-4"],null)],null),new $APP.H(null,1,5,$APP.I,[W_],null),new $APP.H(null,1,5,$APP.I,[Z_],null)],null)};N_=$APP.K("div.w-full.text-xl.py-3.bg-C81c6dd1a.px-40");$_=$APP.K("div.relative.px-10.fb");
O_=$APP.K("div.grid.grid-cols-5.items-center.m-auto.w-30%.justify-items-center");T_=$APP.K("balance-rst");a0=$APP.M("fgl.app.views.merchant-swap","input-str");U_=$APP.K("div.grid.grid-cols-2.gap-4");S_=$APP.K("amount-out");M_=$APP.K("ratio");L_=$APP.M("fgl.app.views.merchant-swap","data");Q_=$APP.M("fgl.app.views.merchant-swap","input");V_=$APP.K("div.text-base.mt-4.mb-3.ffd.flexrs.text-C6bc9db");Y_=$APP.K("swap");X_=$APP.K("div.w-full.flexr.mt-20");$APP.cd("merchant-swap");$APP.SZ={};
$APP.TF.j(Q_,function(a,b){$APP.A(b,0,null);b=$APP.A(b,1,null);var c=$APP.E(a);c=$APP.C.j(c,$APP.Gu);c=$APP.Ej(a,new $APP.H(null,2,5,$APP.I,[c,$APP.OD],null));b=b.replace(/\.+/,".").replace(/-/,"");try{var d=$APP.Cr.utils.parseUnits(b)}catch(k){if(k instanceof Error)d=$APP.sz;else throw k;}if($APP.x.j(b,""))a=$APP.J.B(a,Q_,$APP.Cr.BigNumber.from("0"),$APP.y([a0,""]));else if(!$APP.x.j(d,$APP.sz)||!$APP.La(b,".")||$APP.x.j($APP.Km(b,"."),$APP.Lm(b)))if($APP.x.j(d,$APP.sz)&&$APP.La(b,"."))a=$APP.J.A(a,
a0,b);else if(!$APP.x.j(d,$APP.sz)){var e=d.gte(0);c=$APP.h(e)?d.lte(c):e;a=$APP.h(c)?$APP.J.B(a,Q_,d,$APP.y([a0,b])):a}return a});
$APP.or(L_,$APP.y([function(a){var b=$APP.E(a),c=$APP.C.j(b,Q_),d=$APP.C.j(b,a0),e=$APP.C.j(b,$APP.Gu),k=$APP.C.j(b,$APP.VA),l=$APP.C.j(b,$APP.$A);b=$APP.C.j(b,$APP.TC);var n=$APP.C.j(a,e);n=$APP.E(n);n=$APP.C.j(n,$APP.oy);n=$APP.h(n)?n:$APP.Cr.BigNumber.from("0");k=$APP.h(k)?k:$APP.Cr.BigNumber.from("1");c=$APP.h(c)?c:$APP.Cr.BigNumber.from("0");l=c.mul(l).div(c.add(b)).mul(9).div(10);a=$APP.Fj(a,new $APP.H(null,3,5,$APP.I,[e,$APP.DA,$APP.nH.address],null),$APP.Cr.BigNumber.from("0"));return new $APP.g(null,
7,[$APP.xy,e,S_,l,$APP.fD,c,$APP.Rz,c.lte(a),M_,1/k,$APP.gy,d,T_,n.add(l)],null)}]));$APP.Je();
}).call(this);