(function(){
'use strict';var DO,JO,MO,RO,TO,KO,SO,IO,EO,UO,PO,QO,FO,NO,OO,LO,HO,GO;$APP.zL=function(){return new $APP.J(null,1,5,$APP.K,[new $APP.g(null,2,[$APP.Aq,function(){return $APP.S(new $APP.J(null,1,5,$APP.K,[$APP.WC],null))},$APP.nv,$APP.$h],null)],null)};
DO=function(){return new $APP.J(null,2,5,$APP.K,[$APP.On,'\n      .guild-burn-land-deeds button\x3efigure {\n        transition: all 0.2s ease;\n      }\n\n      .guild-burn-land-deeds button:nth-child(n + 2) {\n        margin-left: 0.8rem;\n      }\n\n      .guild-burn-land-deeds button\x3efigure:hover {\n        transform: scale(1.05);\n      }\n\n      .guild-burn-land-deeds button\x3efigure .selected {\n        position: absolute;\n        top: 0;\n        left: 0;\n        width: 100%;\n        height: 100%;\n        border: 0.25rem solid #fff;\n        border-radius: 4px;\n      }\n      .guild-burn-land-deeds button\x3efigure .selected::after {\n        content: "";\n        position: absolute;\n        width: 0;\n        height: 0;\n        border: 1rem solid transparent;\n        border-right: 1rem solid #fff;\n        transform: translate(calc(-50% - 1px), calc(-50% - 1px)) rotate(45deg);\n      }\n\n      .guild-burn-land-deeds figcaption {\n        text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.4);\n      }\n      figure.dt2\x3eimg {\n        filter: hue-rotate(230deg) saturate(.6);\n      }\n      figure.dt1\x3eimg {\n        filter: hue-rotate(171deg) saturate(.6);\n      }\n      figure.dt0\x3eimg {\n        filter: hue-rotate(57deg) saturate(.6);\n      }'],null)};
JO=function(a){return $APP.xp(new $APP.g(null,2,[$APP.HD,function(){$APP.S(new $APP.J(null,2,5,$APP.K,[$APP.mG,a],null));return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.EG,a],null))},$APP.Tp,function(){var b=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[EO],null)));b=$APP.H(b);var c=$APP.E.j(b,FO),d=$APP.E.j(b,GO);b=["dt",$APP.n.o($APP.h(c)?c:0)].join("");return $APP.vh(new $APP.J(null,3,5,$APP.K,[$APP.YD,new $APP.g(null,1,[$APP.ss,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[HO,a],null))}],null),
new $APP.J(null,4,5,$APP.K,[IO,new $APP.g(null,1,[$APP.Zn,b],null),new $APP.J(null,2,5,$APP.K,[$APP.jv,new $APP.g(null,1,[$APP.T,"/images/mega.png"],null)],null),function(){var e=$APP.z.j(a,d);return e?new $APP.J(null,1,5,$APP.K,[$APP.OH],null):e}()],null)],null),new $APP.g(null,1,[$APP.oo,a],null))}],null),$APP.CJ)};
MO=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[EO],null)));a=$APP.H(a);a=$APP.E.j(a,KO);return new $APP.J(null,3,5,$APP.K,[$APP.ys,new $APP.J(null,2,5,$APP.K,[$APP.LG,"My Land Deeds"],null),$APP.ej.j(new $APP.J(null,1,5,$APP.K,[LO],null),$APP.uj.j(function(b){return new $APP.J(null,2,5,$APP.K,[JO,b],null)},a))],null)};
RO=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[EO],null))),b=$APP.H(a);a=$APP.E.j(b,NO);b=$APP.E.j(b,$APP.tz);return new $APP.J(null,3,5,$APP.K,[$APP.ys,new $APP.J(null,2,5,$APP.K,[$APP.yE,"Your returned token will be"],null),new $APP.J(null,3,5,$APP.K,[OO,new $APP.J(null,3,5,$APP.K,[PO,new $APP.g(null,1,[$APP.ss,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[QO,NO],null))}],null),new $APP.J(null,3,5,$APP.K,[$APP.HE,new $APP.J(null,2,5,$APP.K,[$APP.EK,"2rem"],null),new $APP.J(null,
3,5,$APP.K,[$APP.rJ,a,new $APP.g(null,1,[$APP.IG,4],null)],null)],null)],null),new $APP.J(null,3,5,$APP.K,[PO,new $APP.g(null,1,[$APP.ss,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[QO,$APP.tz],null))}],null),new $APP.J(null,3,5,$APP.K,[$APP.HE,new $APP.J(null,2,5,$APP.K,[$APP.rK,"2rem"],null),new $APP.J(null,3,5,$APP.K,[$APP.rJ,b,new $APP.g(null,1,[$APP.IG,4],null)],null)],null)],null)],null)],null)};
TO=function(){var a=$APP.p($APP.os(new $APP.J(null,1,5,$APP.K,[EO],null)));a=$APP.H(a);var b=$APP.E.j(a,GO),c=$APP.E.j(a,NO),d=$APP.E.j(a,$APP.tz);return new $APP.J(null,2,5,$APP.K,[$APP.ZB,new $APP.J(null,3,5,$APP.K,[$APP.eo,new $APP.g(null,2,[$APP.Yn,$APP.xI,$APP.ss,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.HG,new $APP.g(null,3,[$APP.uu,SO,$APP.vu,new $APP.J(null,3,5,$APP.K,[[b],c,d],null),$APP.xu,function(){$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.fG],null));$APP.S(new $APP.J(null,
1,5,$APP.K,[$APP.vH],null));return $APP.Is()}],null)],null))}],null),"BURN"],null)],null)};$APP.yL=function(){return new $APP.J(null,3,5,$APP.K,[$APP.ys,new $APP.J(null,1,5,$APP.K,[DO],null),new $APP.J(null,5,5,$APP.K,[UO,new $APP.J(null,1,5,$APP.K,[MO],null),new $APP.J(null,1,5,$APP.K,[RO],null),new $APP.J(null,2,5,$APP.K,[$APP.lK,new $APP.g(null,1,[$APP.Zn,"mt-24 mb-8"],null)],null),new $APP.J(null,1,5,$APP.K,[TO],null)],null)],null)};KO=$APP.O("token-ids");SO=$APP.O("redeem");IO=$APP.O("figure.relative.w-11_2rem");
EO=$APP.P("fgl.app.views.merchant-burn","data");UO=$APP.O("div.guild-burn-land-deeds.relative.px-10.py-4");PO=$APP.O("li.bg-C81c6dd1a.leading-3rem.rounded-sm");QO=$APP.P("fgl.app.views.merchant-burn","payment");FO=$APP.O("ttype");NO=$APP.O("eth");OO=$APP.O("ul.grid.grid-cols-2.gap-x-6.text-3xl");LO=$APP.O("div.flex.bg-C81c6dd1a.py-3.pl-2.pr-6.rounded-sm.relative");HO=$APP.P("fgl.app.views.merchant-burn","token-id");GO=$APP.O("token-id");$APP.dd("merchant-burn");$APP.xL={};$APP.JJ.j(QO,function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);return $APP.M.A(a,QO,b)});$APP.JJ.j(HO,function(a,b){$APP.D(b,0,null);b=$APP.D(b,1,null);return $APP.M.A(a,HO,b)});
$APP.ms(EO,$APP.B([function(a){var b=$APP.H(a),c=$APP.E.j(b,$APP.Ou),d=$APP.E.j(b,HO),e=$APP.E.j(b,$APP.gA),k=$APP.E.j(b,$APP.uE);b=$APP.E.j(b,$APP.Qz);c=$APP.Mj(a,new $APP.J(null,2,5,$APP.K,[c,$APP.yA],null));var l=$APP.Mj(a,new $APP.J(null,2,5,$APP.K,[$APP.mG,d],null));a=$APP.Mj(a,new $APP.J(null,2,5,$APP.K,[$APP.EG,d],null));k=$APP.tn(a,0).mul($APP.tn(k,0)).mul(9).div(10).div($APP.tn(b,1));e=$APP.tn(a,0).mul($APP.tn(e,0)).mul(9).div(10).div($APP.tn(b,1));return new $APP.g(null,5,[KO,c,GO,$APP.h(d)?
d:HO,FO,l,NO,k,$APP.tz,e],null)}]));$APP.Ke();
}).call(this);