(function(){
'use strict';var yH,AH,CH,EH,BH,zH,DH;$APP.xH=function(){return new $APP.P(null,1,5,$APP.R,[new $APP.l(null,2,[$APP.bq,function(){return $APP.Yq(new $APP.P(null,1,5,$APP.R,[$APP.by],null))},$APP.QA,$APP.ki],null)],null)};
yH=function(a){$APP.Yq(new $APP.P(null,2,5,$APP.R,[$APP.Vy,new $APP.l(null,5,[$APP.xu,$APP.cw,$APP.yu,new $APP.P(null,1,5,$APP.R,[a],null),$APP.zu,function(){return $APP.Yq(new $APP.P(null,3,5,$APP.R,[$APP.Tt,$APP.eu,new $APP.P(null,1,5,$APP.R,[$APP.au],null)],null))},$APP.Au,function(){return $APP.Yq(new $APP.P(null,7,5,$APP.R,[$APP.Tt,$APP.du,!0,$APP.eu,new $APP.P(null,1,5,$APP.R,[$APP.bu],null),$APP.fu,new $APP.P(null,3,5,$APP.R,[$APP.Vt,new $APP.l(null,1,[$APP.Jt,$APP.gu],null),"OK"],null)],null))},
$APP.Cu,$APP.mu],null)],null));return $APP.Yq(new $APP.P(null,5,5,$APP.R,[$APP.Tt,$APP.eu,new $APP.P(null,1,5,$APP.R,[$APP.ju],null),$APP.fu,null],null))};
AH=function(){var a=$APP.Uf($APP.Sr(new $APP.P(null,1,5,$APP.R,[zH],null))),b=$APP.N(a);a=$APP.H.j(b,$APP.ky);b=$APP.H.j(b,$APP.zE);$APP.m(b)&&$APP.Yq(new $APP.P(null,9,5,$APP.R,[$APP.Tt,$APP.cu,!0,$APP.ku,"Reveal Mint Commits",$APP.eu,new $APP.P(null,4,5,$APP.R,[$APP.Yt,new $APP.P(null,2,5,$APP.R,[$APP.lu,"Found pending commit"],null),new $APP.P(null,1,5,$APP.R,[$APP.$t],null),new $APP.P(null,2,5,$APP.R,[$APP.lu,"Click the REVEAL button below to reveal them"],null)],null),$APP.fu,new $APP.P(null,
3,5,$APP.R,[$APP.Ot,new $APP.l(null,2,[$APP.Jt,$APP.gu,$APP.St,$APP.hn.j(yH,a)],null),"REVEAL"],null)],null))};
$APP.FH=function(){AH();return new $APP.P(null,3,5,$APP.R,[BH,new $APP.P(null,4,5,$APP.R,[$APP.py,new $APP.l(null,2,[$APP.tp,"w-45% relative block",$APP.St,function(){$APP.Yq(new $APP.P(null,2,5,$APP.R,[$APP.Vy,new $APP.l(null,5,[$APP.xu,$APP.gy,$APP.yu,new $APP.P(null,2,5,$APP.R,[1,!1],null),$APP.zu,function(){return $APP.Yq(new $APP.P(null,3,5,$APP.R,[$APP.Tt,$APP.eu,new $APP.P(null,1,5,$APP.R,[$APP.au],null)],null))},$APP.Au,function(){$APP.hu();return $APP.Yq(new $APP.P(null,1,5,$APP.R,[CH],null))},
$APP.Cu,$APP.mu],null)],null));return $APP.Yq(new $APP.P(null,3,5,$APP.R,[$APP.Tt,$APP.cu,!0],null))}],null),new $APP.P(null,2,5,$APP.R,[$APP.Cy,new $APP.l(null,1,[$APP.XD,"/images/mint.png"],null)],null),new $APP.P(null,3,5,$APP.R,[DH,new $APP.P(null,2,5,$APP.R,[$APP.rG,"3rem"],null),new $APP.P(null,3,5,$APP.R,[$APP.pG,"40000000000000000000",new $APP.l(null,1,[$APP.tp,"text-2xl"],null)],null)],null)],null),new $APP.P(null,2,5,$APP.R,[EH,new $APP.l(null,1,[$APP.XD,"/images/weapon.png"],null)],null)],
null)};CH=$APP.T("fgl.contracts.gameminter","init-raw");EH=$APP.S("img.w-45%");BH=$APP.S("div.flexb.px-24.w-full");zH=$APP.T("fgl.app.views.merchant-mint","data");DH=$APP.S("div.absolute.bottom-10%.right-13%.flexr");$APP.hd("merchant-mint");$APP.GH={};$APP.Qr(zH,$APP.D([function(a){var b=$APP.N(a);b=$APP.H.j(b,$APP.pA);a=$APP.Sj(a,new $APP.P(null,2,5,$APP.R,[b,$APP.WB],null));return new $APP.l(null,2,[$APP.ky,b,$APP.zE,a],null)}]));$APP.Re();
}).call(this);