(function(){
'use strict';var MM,TM,UM,HM,EM,VM,JM,WM,BM,XM,RM,YM,zM,GM,NM,PM,QM,AM,KM,SM,DM,ZM,CM,OM,$M,xM,aN,bN,IM,LM,FM,yM;$APP.eL=function(){return new $APP.J(null,1,5,$APP.K,[new $APP.h(null,2,[$APP.hr,$APP.ai,$APP.$u,$APP.ai],null)],null)};
$APP.dL=function(){$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.OC],null));$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.wB],null));$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.vG],null));$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.FB],null));$APP.S(new $APP.J(null,1,5,$APP.K,[$APP.BC],null));var a=module$node_modules$ethers$lib$index.utils.keccak256(module$node_modules$ethers$lib$index.utils.toUtf8Bytes("MINTER_ROLE")),b=$APP.Ws(new $APP.J(null,1,5,$APP.K,[xM],null));b=$APP.p(b);var c=$APP.H(b);b=$APP.E.j(c,$APP.eH);
var d=$APP.E.j(c,yM),e=$APP.E.j(c,zM),f=$APP.E.j(c,AM),l=$APP.E.j(c,BM),m=$APP.E.j(c,CM),r=$APP.E.j(c,DM),t=$APP.E.j(c,EM),v=$APP.E.j(c,FM),y=$APP.E.j(c,GM),A=$APP.E.j(c,$APP.hB),D=$APP.E.j(c,HM),G=$APP.E.j(c,$APP.oD);c=$APP.E.j(c,IM);var N=$APP.p($APP.Ws(new $APP.J(null,1,5,$APP.K,[$APP.tD],null)));return new $APP.J(null,13,5,$APP.K,[$APP.vz,new $APP.J(null,2,5,$APP.K,[JM,"Mint"],null),new $APP.J(null,10,5,$APP.K,[KM,"Admin",new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,
2,5,$APP.K,[$APP.sF,new $APP.h(null,2,[$APP.Bu,MM,$APP.Cu,new $APP.J(null,2,5,$APP.K,[a,"0x0F2b4329fb3a37E78931aABf1C39BCa73818744d"],null)],null)],null))}],null),"Grant Minter to mint Glory NFT"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.RA,new $APP.h(null,2,[$APP.Bu,NM,$APP.Cu,new $APP.J(null,1,5,$APP.K,["0x4e0A4d2d76825DA44363d8ccb5E6bcc26a3BF671"],null)],null)],null))}],null),"Set sgold kingdoms contract addr"],null),
new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.EA,new $APP.h(null,2,[$APP.Bu,MM,$APP.Cu,new $APP.J(null,2,5,$APP.K,[module$node_modules$ethers$lib$index.utils.keccak256(module$node_modules$ethers$lib$index.utils.toUtf8Bytes("GAME_PROXY_ROLE")),"0xEE0472DEf27c658D6EE01006e80b11e9F64fe597"],null)],null)],null))}],null),"Grant Battlefield Proxy GAME_PROXY_ROLE role"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,
2,5,$APP.K,[$APP.EA,new $APP.h(null,2,[$APP.Bu,MM,$APP.Cu,new $APP.J(null,2,5,$APP.K,[module$node_modules$ethers$lib$index.utils.keccak256(module$node_modules$ethers$lib$index.utils.toUtf8Bytes("GAME_PROXY_ROLE")),"0x0F2b4329fb3a37E78931aABf1C39BCa73818744d"],null)],null)],null))}],null),"Grant minter Proxy GAME_PROXY_ROLE role"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.cD,new $APP.h(null,2,[$APP.Bu,MM,$APP.Cu,new $APP.J(null,
2,5,$APP.K,[a,"0xC2Be9Bf78B2119A995DB49109daA790283399f85"],null)],null)],null))}],null),"Grant Battlefield To Mint Glory"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.tH,new $APP.h(null,2,[$APP.Bu,MM,$APP.Cu,new $APP.J(null,2,5,$APP.K,[a,"0xC2Be9Bf78B2119A995DB49109daA790283399f85"],null)],null)],null))}],null),"Grant Battlefield To Mint Gold"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,
2,5,$APP.K,[$APP.tH,new $APP.h(null,2,[$APP.Bu,OM,$APP.Cu,new $APP.J(null,2,5,$APP.K,[N,module$node_modules$ethers$lib$index.BigNumber.from("1000").mul(module$node_modules$ethers$lib$index.BigNumber.from("1000000000000000000"))],null)],null)],null))}],null),"Mint Gold"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.cD,new $APP.h(null,2,[$APP.Bu,OM,$APP.Cu,new $APP.J(null,2,5,$APP.K,[N,module$node_modules$ethers$lib$index.BigNumber.from("200").mul(module$node_modules$ethers$lib$index.BigNumber.from("1000000000000000000"))],
null)],null)],null))}],null),"Mint Glory"],null)],null),new $APP.J(null,3,5,$APP.K,[KM,"Gold Token",new $APP.J(null,3,5,$APP.K,[PM,"balance: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,G],null)],null)],null),new $APP.J(null,3,5,$APP.K,[KM,"Glory Token",new $APP.J(null,3,5,$APP.K,[PM,"balance: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,D],null)],null)],null),new $APP.J(null,3,5,$APP.K,[KM,"Game Pass Token",new $APP.J(null,3,5,$APP.K,[PM,"balance: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,e],null)],null)],null),new $APP.J(null,
5,5,$APP.K,[KM,"Minter",new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.ZB,new $APP.h(null,2,[$APP.Bu,$APP.bB,$APP.Cu,new $APP.J(null,2,5,$APP.K,[1,!1],null)],null)],null))}],null),"Mint Glory NFT"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.ZB,new $APP.h(null,2,[$APP.Bu,$APP.bB,$APP.Cu,new $APP.J(null,2,5,$APP.K,[1,!0],null)],null)],null))}],null),"Mint Glory NFT and Stake"],
null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.ZB,new $APP.h(null,2,[$APP.Bu,$APP.Ny,$APP.Cu,new $APP.J(null,1,5,$APP.K,[N],null)],null)],null))}],null),"revealMint"],null)],null),new $APP.J(null,4,5,$APP.K,[KM,"Glory NFT",new $APP.J(null,3,5,$APP.K,[PM,"glory nft balance: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,v],null)],null),new $APP.J(null,2,5,$APP.K,[PM,["glory nft token ids: ",$APP.n.o(r)].join("")],null)],null),new $APP.J(null,
4,5,$APP.K,[KM,"Landeed NFT",new $APP.J(null,3,5,$APP.K,[PM,"Landeed nft balance: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,t],null)],null),new $APP.J(null,2,5,$APP.K,[PM,["Landeed nft token ids: ",$APP.n.o(y)].join("")],null)],null),new $APP.J(null,6,5,$APP.K,[KM,"Kingdom",new $APP.J(null,2,5,$APP.K,[QM,["Kingdoms: ",$APP.n.o(b)].join("")],null),new $APP.J(null,2,5,$APP.K,[QM,["Which: ",$APP.n.o(m)].join("")],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,
2,5,$APP.K,[$APP.DH,new $APP.h(null,2,[$APP.Bu,$APP.TA,$APP.Cu,new $APP.J(null,1,5,$APP.K,[2],null)],null)],null))}],null),"Join kingdom 2"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.DH,new $APP.h(null,1,[$APP.Bu,RM],null)],null))}],null),"Leave current kingdom"],null)],null),new $APP.J(null,8,5,$APP.K,[KM,"sGold",new $APP.J(null,3,5,$APP.K,[QM,"User balance: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,l],null)],null),new $APP.J(null,
3,5,$APP.K,[QM,"User locked: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,d],null)],null),new $APP.J(null,3,5,$APP.K,[QM,"User unlocked: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,c],null)],null),new $APP.J(null,3,5,$APP.K,[$APP.fj,new $APP.J(null,2,5,$APP.K,[QM,"User UnlockInfo Info: "],null),$APP.vj.j(function(Q){var Y=$APP.H(Q);Q=$APP.E.j(Y,$APP.Pu);Y=$APP.E.j(Y,$APP.Qu);return new $APP.J(null,3,5,$APP.K,[SM,new $APP.J(null,3,5,$APP.K,[QM,"Amount: ",new $APP.J(null,2,5,$APP.K,[$APP.BJ,Q],null)],null),new $APP.J(null,
2,5,$APP.K,[QM,["Date: ",$APP.n.o(Y)].join("")],null)],null)},A)],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.RA,new $APP.h(null,2,[$APP.Bu,$APP.MF,$APP.Cu,new $APP.J(null,2,5,$APP.K,[1,2],null)],null)],null))}],null),"Lock 1 sgold for 2 weeks"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.RA,new $APP.h(null,1,[$APP.Bu,TM],null)],null))}],null),
"Withdraw all unlocked sgold"],null)],null),new $APP.J(null,5,5,$APP.K,[KM,"Battlefield",new $APP.J(null,2,5,$APP.K,[QM,["User staked NFT token ids: ",$APP.n.o(f)].join("")],null),new $APP.J(null,2,5,$APP.K,[QM,["User pending reward gold: ",$APP.n.o($APP.p($APP.Ws(new $APP.J(null,4,5,$APP.K,[$APP.hz,N,$APP.u(f),$APP.cz],null))))].join("")],null),new $APP.J(null,2,5,$APP.K,[QM,["User pending reward glory: ",$APP.n.o($APP.p($APP.Ws(new $APP.J(null,4,5,$APP.K,[$APP.hz,N,$APP.u(f),$APP.zA],null))))].join("")],
null)],null),new $APP.J(null,6,5,$APP.K,[KM,"Battlefield Proxy",new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.sF,new $APP.h(null,2,[$APP.Bu,$APP.RB,$APP.Cu,new $APP.J(null,2,5,$APP.K,["0xC2Be9Bf78B2119A995DB49109daA790283399f85",$APP.u(r)],null)],null)],null))}],null),"Approve Battlefield spend glory nft"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.HC,
new $APP.h(null,2,[$APP.Bu,$APP.TA,$APP.Cu,new $APP.J(null,1,5,$APP.K,[[$APP.u(r)]],null)],null)],null))}],null),"Stake"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.HC,new $APP.h(null,1,[$APP.Bu,$APP.KH],null)],null))}],null),"Claim"],null),new $APP.J(null,3,5,$APP.K,[LM,new $APP.h(null,1,[$APP.Ut,function(){return $APP.S(new $APP.J(null,2,5,$APP.K,[$APP.HC,new $APP.h(null,1,[$APP.Bu,$APP.kz],null)],null))}],null),"Unstake"],
null)],null)],null)};MM=$APP.O("grantRole");TM=$APP.O("withdraw");UM=$APP.P("fgl.contracts.gamepass","balance");HM=$APP.O("glory-balance");EM=$APP.O("landeed-balance");VM=$APP.P("fgl.contracts.gamepass","init");JM=$APP.O("h1.text-4xl");WM=$APP.P("fgl.contracts.gamepass","token-ids");BM=$APP.O("sgold-balance");XM=$APP.P("fgl.contracts.gamepass","init-raw");RM=$APP.O("leave");YM=$APP.P("fgl.contracts.gamepass","set");zM=$APP.O("gamepass-balance");GM=$APP.O("landeed-token-ids");NM=$APP.O("updateKindoms");
PM=$APP.O("li\x3espan");QM=$APP.O("li");AM=$APP.O("battlefield-token-ids");KM=$APP.O("ul.list-disc.mt-10");SM=$APP.O("ul");DM=$APP.O("nft-token-ids");ZM=$APP.P("fgl.contracts.kingdoms","kingom-id");CM=$APP.O("kingdom-id");OM=$APP.O("mint");$M=$APP.P("fgl.contracts.gamepass","send");xM=$APP.P("fgl.app.views.mint","data");aN=$APP.P("fgl.contracts.kingdoms","kingoms");bN=$APP.O("gamepass");IM=$APP.O("sgold-unlocked");LM=$APP.O("li\x3ebutton.border");FM=$APP.O("nft-balance");yM=$APP.O("sgold-locked");$APP.ed("mint");var cN=$APP.vu($APP.B([$APP.ho,bN,$APP.qu,"0xC06212b90705000693080258baA294b831F8aF91",$APP.ru,new $APP.J(null,29,5,$APP.K,[new $APP.h(null,4,[$APP.Bz,!1,$APP.V,new $APP.J(null,3,5,$APP.K,[new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"account",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"operator",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!1,$APP.W,"bool",$APP.R,"approved",$APP.T,"bool"],null)],null),$APP.R,"ApprovalForAll",$APP.T,"event"],null),new $APP.h(null,
4,[$APP.Bz,!1,$APP.V,new $APP.J(null,3,5,$APP.K,[new $APP.h(null,4,[$APP.Z,!0,$APP.W,"bytes32",$APP.R,"role",$APP.T,"bytes32"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"bytes32",$APP.R,"previousAdminRole",$APP.T,"bytes32"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"bytes32",$APP.R,"newAdminRole",$APP.T,"bytes32"],null)],null),$APP.R,"RoleAdminChanged",$APP.T,"event"],null),new $APP.h(null,4,[$APP.Bz,!1,$APP.V,new $APP.J(null,3,5,$APP.K,[new $APP.h(null,4,[$APP.Z,!0,$APP.W,"bytes32",$APP.R,"role",
$APP.T,"bytes32"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"account",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"sender",$APP.T,"address"],null)],null),$APP.R,"RoleGranted",$APP.T,"event"],null),new $APP.h(null,4,[$APP.Bz,!1,$APP.V,new $APP.J(null,3,5,$APP.K,[new $APP.h(null,4,[$APP.Z,!0,$APP.W,"bytes32",$APP.R,"role",$APP.T,"bytes32"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"account",$APP.T,"address"],null),new $APP.h(null,4,
[$APP.Z,!0,$APP.W,"address",$APP.R,"sender",$APP.T,"address"],null)],null),$APP.R,"RoleRevoked",$APP.T,"event"],null),new $APP.h(null,4,[$APP.Bz,!1,$APP.V,new $APP.J(null,5,5,$APP.K,[new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"operator",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"from",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"to",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!1,$APP.W,"uint256[]",$APP.R,"ids",$APP.T,
"uint256[]"],null),new $APP.h(null,4,[$APP.Z,!1,$APP.W,"uint256[]",$APP.R,"values",$APP.T,"uint256[]"],null)],null),$APP.R,"TransferBatch",$APP.T,"event"],null),new $APP.h(null,4,[$APP.Bz,!1,$APP.V,new $APP.J(null,5,5,$APP.K,[new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"operator",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"from",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"address",$APP.R,"to",$APP.T,"address"],null),new $APP.h(null,4,[$APP.Z,
!1,$APP.W,"uint256",$APP.R,"id",$APP.T,"uint256"],null),new $APP.h(null,4,[$APP.Z,!1,$APP.W,"uint256",$APP.R,"value",$APP.T,"uint256"],null)],null),$APP.R,"TransferSingle",$APP.T,"event"],null),new $APP.h(null,4,[$APP.Bz,!1,$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,4,[$APP.Z,!1,$APP.W,"string",$APP.R,"value",$APP.T,"string"],null),new $APP.h(null,4,[$APP.Z,!0,$APP.W,"uint256",$APP.R,"id",$APP.T,"uint256"],null)],null),$APP.R,"URI",$APP.T,"event"],null),new $APP.h(null,5,[$APP.V,$APP.I,$APP.R,
"DEFAULT_ADMIN_ROLE",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"",$APP.T,"bytes32"],null)],null),$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,$APP.I,$APP.R,"MINTER_ROLE",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"",$APP.T,"bytes32"],null)],null),$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,$APP.I,$APP.R,"WEAPON_PASS_TOKEN_ID",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,
"uint8",$APP.R,"",$APP.T,"uint8"],null)],null),$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"uint256",$APP.R,"id",$APP.T,"uint256"],null)],null),$APP.R,"balanceOf",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"uint256",$APP.R,"",$APP.T,"uint256"],null)],null),$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,
2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address[]",$APP.R,"accounts",$APP.T,"address[]"],null),new $APP.h(null,3,[$APP.W,"uint256[]",$APP.R,"ids",$APP.T,"uint256[]"],null)],null),$APP.R,"balanceOfBatch",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"uint256[]",$APP.R,"",$APP.T,"uint256[]"],null)],null),$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,3,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,"address"],null),new $APP.h(null,
3,[$APP.W,"uint256",$APP.R,"id",$APP.T,"uint256"],null),new $APP.h(null,3,[$APP.W,"uint256",$APP.R,"value",$APP.T,"uint256"],null)],null),$APP.R,"burn",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,3,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"uint256[]",$APP.R,"ids",$APP.T,"uint256[]"],null),new $APP.h(null,3,[$APP.W,"uint256[]",$APP.R,"values",$APP.T,"uint256[]"],null)],null),
$APP.R,"burnBatch",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"role",$APP.T,"bytes32"],null)],null),$APP.R,"getRoleAdmin",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"",$APP.T,"bytes32"],null)],null),$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"role",$APP.T,"bytes32"],
null),new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,"address"],null)],null),$APP.R,"grantRole",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"role",$APP.T,"bytes32"],null),new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,"address"],null)],null),$APP.R,"hasRole",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bool",$APP.R,"",$APP.T,"bool"],null)],null),
$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,$APP.I,$APP.R,"initialize",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"address",$APP.R,"operator",$APP.T,"address"],null)],null),$APP.R,"isApprovedForAll",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bool",$APP.R,"",$APP.T,"bool"],null)],null),$APP.X,
"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"_recipient",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"uint256",$APP.R,"_amount",$APP.T,"uint256"],null)],null),$APP.R,"mintWeaponPass",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,$APP.I,$APP.R,"name",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"string",$APP.R,"",$APP.T,"string"],null)],null),$APP.X,"pure",
$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"role",$APP.T,"bytes32"],null),new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,"address"],null)],null),$APP.R,"renounceRole",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bytes32",$APP.R,"role",$APP.T,"bytes32"],null),new $APP.h(null,3,[$APP.W,"address",$APP.R,"account",$APP.T,
"address"],null)],null),$APP.R,"revokeRole",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,5,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"from",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"address",$APP.R,"to",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"uint256[]",$APP.R,"ids",$APP.T,"uint256[]"],null),new $APP.h(null,3,[$APP.W,"uint256[]",$APP.R,"amounts",$APP.T,"uint256[]"],null),new $APP.h(null,3,[$APP.W,"bytes",$APP.R,
"data",$APP.T,"bytes"],null)],null),$APP.R,"safeBatchTransferFrom",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,5,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"from",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"address",$APP.R,"to",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"uint256",$APP.R,"id",$APP.T,"uint256"],null),new $APP.h(null,3,[$APP.W,"uint256",$APP.R,"amount",$APP.T,"uint256"],null),new $APP.h(null,3,[$APP.W,"bytes",
$APP.R,"data",$APP.T,"bytes"],null)],null),$APP.R,"safeTransferFrom",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,2,5,$APP.K,[new $APP.h(null,3,[$APP.W,"address",$APP.R,"operator",$APP.T,"address"],null),new $APP.h(null,3,[$APP.W,"bool",$APP.R,"approved",$APP.T,"bool"],null)],null),$APP.R,"setApprovalForAll",$APP.U,$APP.I,$APP.X,"nonpayable",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,
"bytes4",$APP.R,"interfaceId",$APP.T,"bytes4"],null)],null),$APP.R,"supportsInterface",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"bool",$APP.R,"",$APP.T,"bool"],null)],null),$APP.X,"view",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,$APP.I,$APP.R,"symbol",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"string",$APP.R,"",$APP.T,"string"],null)],null),$APP.X,"pure",$APP.T,"function"],null),new $APP.h(null,5,[$APP.V,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,
[$APP.W,"uint256",$APP.R,"",$APP.T,"uint256"],null)],null),$APP.R,"uri",$APP.U,new $APP.J(null,1,5,$APP.K,[new $APP.h(null,3,[$APP.W,"string",$APP.R,"",$APP.T,"string"],null)],null),$APP.X,"view",$APP.T,"function"],null)],null)]));$APP.Us(UM,$APP.B([function(a,b){$APP.C(b,0,null);b=$APP.C(b,1,null);return $APP.Oj(a,new $APP.J(null,2,5,$APP.K,[b,UM],null),0).toString()}]));$APP.Us(WM,$APP.B([function(a,b){$APP.C(b,0,null);b=$APP.C(b,1,null);return $APP.Nj(a,new $APP.J(null,2,5,$APP.K,[b,WM],null))}]));
$APP.It(VM,new $APP.J(null,1,5,$APP.K,[$APP.lJ],null),function(a){a=$APP.H(a);a=$APP.E.j(a,$APP.Is);a=$APP.H(a);var b=$APP.E.j(a,$APP.Iu),c=$APP.E.j(a,$APP.tD);if($APP.k(c)&&$APP.k(b)){a=$APP.wu(cN,b);var d=$APP.yu(a);$APP.xu($APP.Ko(null),function(){return $APP.xu($APP.Ko(d($APP.oE,c)),function(e){return $APP.xu($APP.Ko(null),function(){return $APP.Ko($APP.S(new $APP.J(null,4,5,$APP.K,[YM,e,c,WM],null)))})})})}return new $APP.h(null,1,[$APP.bG,XM],null)});$APP.Ou(cN,$M);$APP.cL={};
$APP.Us(xM,$APP.B([function(a){var b=$APP.H(a);b=$APP.E.j(b,$APP.tD);a=$APP.E.j(a,b);var c=$APP.H(a);a=$APP.E.j(c,aN);var d=$APP.E.j(c,$APP.xC),e=$APP.E.j(c,UM),f=$APP.E.j(c,$APP.lD),l=$APP.E.j(c,$APP.Iy),m=$APP.E.j(c,ZM),r=$APP.E.j(c,$APP.Kz),t=$APP.E.j(c,$APP.pC),v=$APP.E.j(c,$APP.ND),y=$APP.E.j(c,$APP.gA),A=$APP.E.j(c,$APP.oH),D=$APP.E.j(c,$APP.IG),G=$APP.E.j(c,$APP.WA);c=$APP.E.j(c,$APP.NH);A=$APP.Ru(A);return $APP.jl([CM,FM,DM,EM,GM,$APP.hB,HM,$APP.eB,$APP.oD,IM,zM,$APP.eH,yM,AM,BM],[m,v,r,t,
y,A,D,b,G,c,e,a,d,f,l])}]));$APP.Le();
}).call(this);